/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAGeomCompareServices_h
#define CATIAGeomCompareServices_h

#ifndef ExportedByCATHASPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATHASPubIDL
#define ExportedByCATHASPubIDL __declspec(dllexport)
#else
#define ExportedByCATHASPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATHASPubIDL
#endif
#endif

#include "CATIABase.h"

class CATIAPart;

extern ExportedByCATHASPubIDL IID IID_CATIAGeomCompareServices;

class ExportedByCATHASPubIDL CATIAGeomCompareServices : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GenerateComparisonReport(CATIAPart * iInputPart)=0;


};

CATDeclareHandler(CATIAGeomCompareServices, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
