BUILT_OBJECT_TYPE = SHARED LIBRARY
ENCODING_KEY = System

MKMK_USEPRECOMPIL=
COMMON_LINK_WITH =  LCCArch  DSLSArch SSLArch 
COMMON_CCFLAGS = -DUKU_SUPPORT -DMULTI_USE_DISPLAY -DHTTPARCH -D__OPENSSL -D__JS0DSLOCK -DUKU_LICENSE_2
SRC_LINK_WITH = JS0LSR LCCSDK JS0DSLUTILS

OS = AIX
LOCAL_CCFLAGS = $(COMMON_CCFLAGS) -D_AIX_SOURCE -qNORO
LOCAL_CFLAGS = $(LOCAL_CCFLAGS)
LINK_WITH = $(COMMON_LINK_WITH)
SYS_LIBS = -lodm -lcfg -lpthreads 



OS = SunOS
LOCAL_CCFLAGS = $(COMMON_CCFLAGS) 
LOCAL_CFLAGS = $(LOCAL_CCFLAGS)
LINK_WITH = $(COMMON_LINK_WITH)
SYS_LIBS = -lpthread -lsocket  
FORTRAN_LIBS=
SUNMATH_LIBS=


OS = Windows_NT
LOCAL_CCFLAGS = $(COMMON_CCFLAGS) -D_X86_SOURCE -DWINNT\
                -URESTORE_TZ
LOCAL_CFLAGS = $(LOCAL_CCFLAGS)
LINK_WITH = $(COMMON_LINK_WITH)
#MKMFC_DEPENDENCY=Yes 
LOCAL_LDFLAGS = /NODEFAULTLIB:libcmt.lib 
SYS_LIBS = netapi32.lib wsock32.lib comsuppw.lib oleaut32.lib ole32.lib Wbemuuid.lib wininet.lib dnsapi.lib   Ws2_32.lib

