/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAPartDocument_h
#define CATIAPartDocument_h

#ifndef ExportedByMecModPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __MecModPubIDL
#define ExportedByMecModPubIDL __declspec(dllexport)
#else
#define ExportedByMecModPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByMecModPubIDL
#endif
#endif

#include "CATIADocument.h"

class CATIAPart;
class CATIAProduct;

extern ExportedByMecModPubIDL IID IID_CATIAPartDocument;

class ExportedByMecModPubIDL CATIAPartDocument : public CATIADocument
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Part(CATIAPart *& oPart)=0;

    virtual HRESULT __stdcall get_Product(CATIAProduct *& oProduct)=0;


};

CATDeclareHandler(CATIAPartDocument, CATIADocument);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
