/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridBodies_h
#define CATIAHybridBodies_h

#ifndef ExportedByMecModPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __MecModPubIDL
#define ExportedByMecModPubIDL __declspec(dllexport)
#else
#define ExportedByMecModPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByMecModPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATVariant.h"

class CATIAHybridBody;

extern ExportedByMecModPubIDL IID IID_CATIAHybridBodies;

class ExportedByMecModPubIDL CATIAHybridBodies : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Add(CATIAHybridBody *& oHybridBody)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAHybridBody *& oHybridBody)=0;


};

CATDeclareHandler(CATIAHybridBodies, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
