
#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID =  \
PSNInteroperabilityUUID
#else
LINK_WITH_FOR_IID =
#endif

BUILT_OBJECT_TYPE = SHARED LIBRARY
INCLUDED_MODULES = XCOservices
#
OS = COMMON
#
LINK_WITH= JS0XXC0 JS0SCBAK CATCinBBMessage 
