#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
#LINK_WITH = ... $(WIZARD_LINK_MODULES) ...
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP CATInfInterfaces NavigatorPubIDL NavigatorInterfacesUUID 
#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATIAApplicationFrameUUID \
Navigator4DUIUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID)  AD0XXBAS Collections\
            DI0PANV2 JS0FM JS0GROUP NS0S3STR \
			CK0UNIT CATLifRelations CATLiteralFeatures\
            ObjectModeler OM0EDPRO CD0WIN CATVisualization \
			CATNavigatorItf CATNavigator2Itf CATDlgStandard \
      KnowledgeItf CATViz

#


OS = COMMON

