# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module CATFecLayersAndFilters.m
#======================================================================
#
#  Oct 2001  Creation: Code generated by the CAA wizard  CLE
#======================================================================
#
# NONE 
#
BUILT_OBJECT_TYPE=NONE 
