#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
#
LINK_WITH=$(LINK_WITH_FOR_IID)  CO0LSTPV CO0HTAB \
	JS0CORBA  AD0XXBAS NS0S3STR\
	AC0SPBAS CO0RCINT CO0LSTPV AC0XXLNK YI00IMPL\
	CD0FRAME JS0FM\
	CO0LSTST VE0BASE AS0STARTUP\
	CXMODEL CK0FEAT\
	SketcherItf MF0STARTUP CK0FEAT CD0WIN MecModItfCPP PartItf \
	PCBModeler  YI00IMPL DI0PANV2\
        CATMathematics CATGeometricObjects ProductStructurePubIDL \
	CATAssCouMdl AS0SEL AC0XXLNK\
	CATCclInterfaces InfProIDL  YN000FUN  MF0CST CO0RCDBL\
	CATProductStructureInterfaces  NS0S1MSG \ 
	PCBServices AC0XXLNK CATAssemblyInterfaces \
	CATInteractiveInterfaces Y30UIUTI CATGitInterfaces BOHYBOPELight



LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ 



OS = Windows_NT
LOCAL_CCFLAGS = -D_CATNoWarningPromotion_
LOCAL_CFLAGS = -D_CATNoWarningPromotion_
#
OS = wnt40a
BUILD = NO



