/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAProcessDocument_h
#define CATIAProcessDocument_h

#ifndef ExportedByProcessPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __ProcessPubIDL
#define ExportedByProcessPubIDL __declspec(dllexport)
#else
#define ExportedByProcessPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByProcessPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIADocument.h"

class CATBaseDispatch;

extern ExportedByProcessPubIDL IID IID_CATIAProcessDocument;

class ExportedByProcessPubIDL CATIAProcessDocument : public CATIADocument
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_PPRDocument(CATBaseDispatch *& oPPRDoc)=0;

    virtual HRESULT __stdcall AddLibrary(const CATBSTR & iFileName)=0;

    virtual HRESULT __stdcall get_DNB3DStatePositionManagement(CATBaseDispatch *& oPositionMgt)=0;


};

CATDeclareHandler(CATIAProcessDocument, CATIADocument);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
