/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef DNBItemAssignmentType_h
#define DNBItemAssignmentType_h

enum ItemAssignmentType {
        ProcessProcesses,
        ProcessFirstProcesses,
        ProcessRemoves,
        ProcessImplementsRequirementPartial,
        ProcessImplementsRequirementComplete,
        productviewpoint,
        productvisualization
};

#endif
