#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ObjectModelerBaseUUID \
ObjectModelerSDMUUID
#else
LINK_WITH_FOR_IID =
#endif
#
#
# LOAD MODULE
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = CP0SCHEM

LOCAL_CCFLAGS= -DSDAI_CPP_LATE_BINDING -DSDAI_IMPLEMENTATION_CKM

LINK_WITH=$(LINK_WITH_FOR_IID)  CP0CLIP \
	    AC0XXLNK AD0XXBAS AD0SDBAS \
	    KS0BINA KS0ROLL \
	    KS0SIMPL KS0LATE \
	    NS0S3STR  \
	    JS0CORBA JS0ERROR JS0SCBAK JS03TRA \
	    CO0LSTPV CO0LSTST


# ckmBT
LOCAL_CKMFLAGS= -gEarly

#
OS = AIX
#INSTANCIATION_MODE = -qnotempinc

#
OS = IRIX

#
OS = HP-UX
INSTANCIATION_MODE = -pta -ptv

#
OS = SunOS

#
OS = Windows_NT
