#
BUILT_OBJECT_TYPE=LOAD MODULE
#
#OS = COMMON
PROGRAM_NAME = SetupHFXB
#
LINK_WITH = WFTOCTools JS0GROUP CXINSTUTIL 
SH_SYS_LIBS = 
SH_SYS_LIBPATH = 

OS = SunOS
FORTRAN_LIBS =

OS = Windows_NT
LINK_WITH = WFTOCTools JS0GROUP CXINSTUTIL 
SH_SYS_LIBS = 
SH_SYS_LIBPATH = 
