#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=EL LIBRARY

LINK_WITH = CATVizBase VE0PIX JS0CORBA JS0MRSHL JS03TRA JS0SCBAK CO0LSTPV CO0HTAB JS0STR JS0FM

OS = AIX

OS = HP-UX

OS = IRIX
LOCAL_CCFLAGS  = -float
LOCAL_CFLAGS   = -float

OS = SunOs

OS = intel_a 
LOCAL_CCFLAGS = -D_WNT40I_SOURCE
LOCAL_CFLAGS  = -D_WNT40I_SOURCE 

OS = win_b 
LOCAL_CCFLAGS = -D_WNT40I_SOURCE
LOCAL_CFLAGS  = -D_WNT40I_SOURCE 

OS = win_b64 
LOCAL_CCFLAGS = -D_WNT40I_SOURCE
LOCAL_CFLAGS  = -D_WNT40I_SOURCE 

OS = intel_a64
LOCAL_CCFLAGS = -D_WNT40I_SOURCE
LOCAL_CFLAGS  = -D_WNT40I_SOURCE

OS = alpha_a
LOCAL_CCFLAGS = -D_WNT40A_SOURCE
LOCAL_CFLAGS  = -D_WNT40A_SOURCE
