#BUILT_OBJECT_TYPE=ARCHIVE / XEN - A REMETTRE EN ARCHIVE SI LIVRAISON D'UNE INTERFACE CAR VIDE POUR L'INSTANT
BUILT_OBJECT_TYPE=NONE
BUILD=NO

LINK_WITH_V5_ONLY=
LINK_WITH_V6_ONLY=

LINK_WITH=\
    $(LINK_WITH_V5_ONLY)           \
    $(LINK_WITH_V6_ONLY)           \
#

OS = COMMON
#if defined(CATIAR201)
LINK_WITH_V6_ONLY= \
#
#else
#if defined(CATIAV5R21)
LINK_WITH_V5_ONLY= \
#
#endif
#endif
