#
# SHARED LIBRARY
#
#BUILT_OBJECT_TYPE=SHARED LIBRARY
BUILT_OBJECT_TYPE=NONE

#LOCAL_CCFLAGS = -DPRODSTRU_PROTO

LINK_WITH = PRDWorkshop AC0SPBAS AD0XXBAS AS0STARTUP CD0FRAME CD0WIN Collections\
            VE0GRPH2 DI0PANV2 DI0STATE 	JS0FM JS0GROUP JS0FILE NS0S3STR\
            ObjectModeler OM0EDPRO VE0MDL YN000MAT YP00IMPL VE0BASE YN000MFL\
            PRDExport JS0XXC0 CATPrsRep \
            CATIAEntity InfPubIDL \
            ProductStructureItf JS0CATLM\
	    AS0STNAV CATProductStructure1 CATPrsNumbering CATPrsScene AC0XXLNK AS0AUTO\
      CATPDMBaseItfCPP
#
