#
# Included in CATVisualization.m

BUILT_OBJECT_TYPE=NONE
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION

OS = SunOS
LOCAL_CFLAGS = -DCATVIZ_SPECIFICATION -DMOTIF12_HEADERS
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION -DMOTIF12_HEADERS
