
BUILT_OBJECT_TYPE=LOAD MODULE
DELIVERABLE=NO

#if os Windows
CXX_WARNINGPROMOTE=CATOstWarningPromote.h
#endif

LINK_WITH_COMMON=JS0GROUP

#ifdef (CATIAR203)
LINK_WITH=$(LINK_WITH_COMMON)
#else
LINK_WITH=$(LINK_WITH_COMMON)
#endif
