#
# SHARED LIBRARY          
#
BUILT_OBJECT_TYPE= SHARED LIBRARY

LINK_WITH =	JS0GROUP JS0CORBA \
			CATDialogEngine JS0FM CD0FRAME \
			DI0PANV2 \
			KnowledgeItf \
			CATLifRelations \
			CK0PARAM CK0FEAT AC0SPBAS
#




#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
#LINK_WITH = ... $(WIZARD_LINK_MODULES) ...
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP  \
CK0PARAM 
# END WIZARD EDITION ZONE
