BUILT_OBJECT_TYPE = LOAD MODULE


BUILD=NO

OS = Windows_NT
BUILD=YES
LINK_WITH = JS0CATREG NS0SI18N
SYS_LIBS = Netapi32.lib opengl32.lib version.lib Ws2_32.lib 
SH_SYS_LIBPATH = $(SYS_LIBPATH)
LOCAL_CCFLAGS =
LOCAL_CFLAGS = /SUBSYSTEM:WINDOWS
