BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH = VE0BASE  AC0SPBAS AD0XXBAS CD0FRAME CD0WIN DI0PANV2 DI0STATE JS0GROUP JS0FM \
			ON0PROP YN000MFL \
			CATProductStructure1 AS0STARTUP CATEsuProductServices CATEsuUtil \
            CATPspUIUtils CATPspUtilities CATPspSelect CATPspUUID CATPspItfCPP CATDraftingInfrastructureUI CATSktAssistant

SH_LINK_WITH= $(LINK_WITH)

