#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# PG0GCGM : CGM driver
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
LINK_WITH=$(LINK_WITH_FOR_IID) CATPrt CATPrtBase JS0GROUP JS0FM DI0PANV2 Mathematics VE0PIX CATMMediaImageFile YN000FUN CATLightXml XMLParserItf

OS = AIX
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = HP-UX
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = IRIX
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = SunOS
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = intel_a
BUILD=YES
