# COPYRIGHT DASSAULT SYSTEMES 2002

BUILT_OBJECT_TYPE=SHARED LIBRARY

INCLUDED_MODULES=Plug3D

LINK_WITH= \
  CATMathematics \
  CATMathStream \
  JS0GROUP \
  CATCDS \
  CATCosSolverImplementation
#
OS = Windows_NT
#
OPTIMIZATION_CPP=/O2
