#@ autoformat 08:01:24
# COPYRIGHT DASSAULT SYSTEMES 2007
#======================================================================
# Imakefile for module CATOperatorModeler.m
#======================================================================
#  Sep 2007  Creation: Code generated by the CAA wizard				MMQ
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE = SHARED LIBRARY

LINK_WITH = \
    JS0GROUP                       \ # System                         JS0GROUP
    CATMathematics                 \ # Mathematics                    CATMathematics
    CATGMModelInterfaces           \ # GMModelInterfaces              CATGMModelInterfaces
    YP00IMPL                       \ # GeometricObjects               CATGeometricObjects
    OprInterfaces                  \ # OperatorModelerInterfaces      OprInterfaces
#
