# COPYRIGHT DASSAULT SYSTEMES 2000
#======================================================================
# Imakefile for module CATMoldInterfaces.m
#======================================================================
#
#  Mar 2000  Creation: Code generated by the CAA wizard  cqo
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
# pem probleme de link sur aix WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

INCLUDED_MODULES = CATMoldItf  CATMoldItfCPP CATMoldPubIDL CATMoldProIDL
 
LINK_WITH=	JS0GROUP 


# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
