#ifndef CATArrangementItemResVisuMode_IDL
#define CATArrangementItemResVisuMode_IDL
// COPYRIGHT DASSAULT SYSTEMES 2000

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

/**
 * Visualization mode for Item Reservation.
 * @param CatArrangementItemReservationVisuModeVisuAxis
 *   The Item Reservation is visualized as an axis (no extents are shown).
 * @param CatArrangementItemReservationVisuModeVisuFlat
 *   The Item Reservation is visualized as a flattened box.
 * @param CatArrangementItemReservationVisuModeItem Reservation
 *   The Item Reservation is visualized as solid box.
 */
enum CATArrangementItemResVisuMode 
{ 
  CatArrangementItemReservationVisuModeAxis,
  CatArrangementItemReservationVisuModeFlat,
  CatArrangementItemReservationVisuModeSolid
};

#endif
