#ifndef CATArrangementAreaVisuMode_IDL
#define CATArrangementAreaVisuMode_IDL
// COPYRIGHT Dassault Systemes 2000
/*IDLREP*/
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

/**  
 * ArrangementAreaVisuMode Styles.  
 * <b> Role: </b>
 * The styles defined here can be used to provide the 
 * appropriate Visual Mode to the ArrangementArea.
 * @param CatArrangementAreaVisuModeFlat
 *   The Area is flattened on its base plane (the height is not shown).
 * @param CatArrangementAreaVisuModeSolid
 *   The Area is shown as a Solid with its height shown.
 */
enum CATArrangementAreaVisuMode 
{
   CatArrangementAreaVisuModeFlat ,
   CatArrangementAreaVisuModeSolid
};


#endif
