#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
PCBoardBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# Makefile for the .idl files
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID) JS0GROUP InfItf AD0XXBAS
 
INCLUDED_MODULES=PCBItf PCBItfCPP PCBProIDL

