# COPYRIGHT DASSAULT SYSTEMES 2004
#======================================================================
# Imakefile for module CATGkwPattern.m
#======================================================================
#
#  Jul 2004  Creation: Code generated by the CAA wizard  tvq
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0GROUP JS0FM CATLifDriver CATLifSpecs KnowledgeInterfacesUUID  \
DI0PANV2 CATApplicationFrame 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATLiteralFeatures CATKnowledgeModeler CATObjectSpecsModeler CATVisualization CATObjectModelerBase CATProductStructure1 MecModItfCPP CATInteractiveInterfaces CATViz CATUdfInterfaces CATAfrInterfaces ON0FRAME CATLiteralsEditor DI0PANV2 CATAssemblyInterfaces  CATUdfInterfaces CATMcoModel CATCclInterfaces ProductStructureItf CATConstraintModelerItf

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
