/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef ENOIACD5ID_h
#define ENOIACD5ID_h

#ifndef ExportedByENOCD5IntegPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __ENOCD5IntegPubIDL
#define ExportedByENOCD5IntegPubIDL __declspec(dllexport)
#else
#define ExportedByENOCD5IntegPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByENOCD5IntegPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"

class CATIADocument;

extern ExportedByENOCD5IntegPubIDL IID IID_ENOIACD5ID;

class ExportedByENOCD5IntegPubIDL ENOIACD5ID : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetID(CATBSTR & oID)=0;


};

CATDeclareHandler(ENOIACD5ID, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
