#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

INCLUDED_MODULES=ON0GRAPH

LINK_WITH = JS0STR DI0PANV2 JS0CORBA JS0FM JS0SCBAK VE0BASE YN000MFL YN000M2D JS0LIB0 NS0S3STR VE0PIX JS0ERROR JS03TRA \
	    AD0XXBAS \
	    ON0GRBAS ON0GREXT \
	    CO0LSTPV CO0LSTST CO0RCINT \
	    ON0MAIN JS0CATLM

OS = aix_a
SYS_LIBS = -lXt -lXi -lX11

OS = aix_a64
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = HP-UX
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = IRIX
SYS_LIBS = -lXm -lXt -lXi -lX11
LOCAL_CCFLAGS  = -float
LOCAL_CFLAGS   = -float 

OS = SunOS
SYS_LIBS = -lXm -lXt -lXi -lX11
#LOCAL_CFLAGS = -DMOTIF12_HEADERS
#LOCAL_CCFLAGS = -DMOTIF12_HEADERS

