BUILT_OBJECT_TYPE=LOAD MODULE
BUILD = NO

OS = Windows_NT
BUILD = YES
LINK_WITH = NS0S3STR strmbasd strmiids 
LOCAL_LDFLAGS = /NODEFAULTLIB:LIBCMTD setargv.obj
SYS_LIBS = winmm.lib

OS = win_b64
LOCAL_LDFLAGS = /NODEFAULTLIB:LIBCMTD /NODEFAULTLIB:LIBC setargv.obj
