#
BUILT_OBJECT_TYPE= SHARED LIBRARY
#

IMPACT_ON_IMPORT = YES

OS = aix_a
OPTIMIZATION_FORTRAN = -O3 -qstrict
LOCAL_CCFLAGS=-D_ELF_AIX
LOCAL_CFLAGS=-D_ELF_AIX -D_ELF_AIX32
LOCAL_FFLAGS=-qnosave -qsmp=noauto -qtune=pwr3 
SYS_LIBS = -lxlsmp -lxlf -lxlf90 -lxlfpad -lblas -lodm -lcfg
BLASLIB =

OS = aix_a64
OPTIMIZATION_FORTRAN = -O3 -qstrict
LOCAL_CCFLAGS=-D_ELF_AIX -D_ELF64
LOCAL_CFLAGS=-D_ELF_AIX -D_ELF64
LOCAL_FFLAGS=-qnosave -qsmp=noauto -qtune=pwr3 
SYS_LIBS = -lxlsmp -lxlf -lxlf90 -lxlfpad -lblas -lodm -lcfg
BLASLIB =

OS = SunOS
OPTIMIZATION_FORTRAN = -O4
LOCAL_FFLAGS=-stackvar
LOCAL_CCFLAGS=-D_ELF_SUN
LOCAL_CFLAGS=-D_ELF_SUN
SYS_LIBS = -lM77 -lF77
BLASLIB =

OS = intel_a
LOCAL_CCFLAGS=-D_ELF_WINDOWS 
LOCAL_CFLAGS=-D_ELF_WINDOWS
LOCAL_FFLAGS=/Qopenmp
LOCAL_POST_FFLAGS=/Qauto
OPTIMIZATION_FORTRAN = /O3 /arch:SSE2
OPTIMIZATION_C =  /Oxt /Gy /GF /GR-
BLASLIB = CATMathematics 

OS = win_b
OPTIMIZATION_FORTRAN = /OPTIMIZE:4
LOCAL_FFLAGS=/Qunroll:8
LOCAL_CCFLAGS=-D_ELF_WINDOWS 
LOCAL_CFLAGS=-D_ELF_WINDOWS
SYS_LIBS = DFORDLL.LIB
BLASLIB = 

OS = intel_a64
OPTIMIZATION_FORTRAN = /O4
LOCAL_FFLAGS=/Qunroll:8
LOCAL_CCFLAGS=-D_ELF_WINDOWS -D_ELF64 /Wp64
LOCAL_CFLAGS=-D_ELF_WINDOWS /Wp64
SYS_LIBS = 
BLASLIB = 

OS = win_b64
LOCAL_FFLAGS=/Qopenmp
LOCAL_POST_FFLAGS=/Qauto
LOCAL_CCFLAGS=-D_ELF_WINDOWS -D_ELF64 
LOCAL_CFLAGS=-D_ELF_WINDOWS
BLASLIB = CATMathematics 

OS = win_a
LOCAL_CCFLAGS=-D_ELF_WINDOWS
LOCAL_CFLAGS=-D_ELF_WINDOWS
SYS_LIBS = DFORDLL.LIB
BLASLIB = 

OS = COMMON
LINK_WITH = JS0CORBA $(BLASLIB)
