#
# SHARED LIBRARY

#
BUILT_OBJECT_TYPE=NONE

LINK_WITH = JS0CORBA JS0MRSHL JS0STR JS0ERROR JS03TRA JS0CTYP JS0ERROR JS0DSPA \
NS0S3STR JS0INF

#
OS = AIX
LOCAL_CCFLAGS=-DCATMAINWIN
#
OS = HP-UX
LOCAL_CCFLAGS=-DCATMAINWIN
#LOCAL_CCFLAGS=-Wp,-H50000
#BUILD = NO

#
OS = IRIX
LOCAL_CCFLAGS=-DCATMAINWIN
#
OS = SunOS
LOCAL_CCFLAGS=-DCATMAINWIN
#
## @linux mcf 2004-04-16.14:09:07 [Add OS = Linux]##
OS = Linux
LOCAL_CCFLAGS=-DCATMAINWIN

#
OS = Windows_NT
