#
BUILT_OBJECT_TYPE = LOAD MODULE
#

LINK_WITH = CORBAServerInfraUUID  CATCsbCORBA orbix JS0GROUP GW0EXIT  CATSysMultiThreading GW0Utils GW0COMUN
CATCsbCORBA = SERVER

OS = AIX
LOCAL_CCFLAGS = -D_AIX_SOURCE  -D_LARGE_FDS 
LOCAL_LDFLAGS =-F:$(LD) -brtl -bnortllib
CXX_EXCEPTION = 
SYS_INCPATH =
SYS_LIBPATH =
SYS_LIBS = -lc_r -blibpath:/usr/lib/threads:/lib:/usr/lib -lpthreads_compat -ls

OS = HP-UX
LOCAL_CCFLAGS = -D_HPUX_SOURCE -D_REENTRANT -D_CMA_NOWRAPPERS_
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
#SYS_LIBS =  -lcma -Wl,-a,archive -Wl,-a,shared 


OS = IRIX
LOCAL_CCFLAGS = -D_IRIX_SOURCE 
LOCAL_LDFLAGS =
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
SYS_LIBS = -lCsup

OS = SunOS
LOCAL_CCFLAGS = -D_SUNOS_SOURCE
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
SYS_LIBS = -Bstatic  -Bdynamic -lnsl -lsocket

OS = alpha_a
BUILD = NO


OS = win_a
BUILD=NO
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -DIT_EX_MACROS -MD /GX /Od /Zi -DORBIX_DLL /D_CATNoWarningPromotion_
LOCAL_CFLAGS= /D_CATNoWarningPromotion_
LINK_WITH = ITMi CATCsbCORBA
CATCsbCORBA = SERVER 
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib rpcrt4.lib netapi32.lib

OS = intel_a
#BUILD=NO
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -D_WIN32_WINNT=0x0500\
                -DIT_EX_MACROS -MD /GX /Od /Zi -DORBIX_DLL /D_CATNoWarningPromotion_
LOCAL_CFLAGS= /D_CATNoWarningPromotion_
LINK_WITH = ITMi JS0MT CATCsbCORBA JS0GROUP GW0EXIT  CORBAServerInfraUUID GW0COMUN GW0Utils
CATCsbCORBA = SERVER
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib rpcrt4.lib netapi32.lib userenv.lib

OS = win_b
#BUILD=NO
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0500\
                -DIT_EX_MACROS -MD /GX /Od /Zi -DORBIX_DLL /D_CATNoWarningPromotion_
LOCAL_CFLAGS= /D_CATNoWarningPromotion_
LINK_WITH = ITMi JS0MT CATCsbCORBA JS0GROUP GW0EXIT  CORBAServerInfraUUID GW0COMUN GW0Utils
CATCsbCORBA = SERVER
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib rpcrt4.lib netapi32.lib

OS = win_b64
#BUILD=NO
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DIT_EX_MACROS -DORBIX_DLL /D_CATNoWarningPromotion_ -D_WIN32_WINNT=0x0500
LOCAL_CFLAGS= /D_CATNoWarningPromotion_
LINK_WITH = ITMi JS0MT CATCsbCORBA JS0GROUP GW0EXIT  CORBAServerInfraUUID GW0COMUN GW0Utils
CATCsbCORBA = SERVER
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib rpcrt4.lib netapi32.lib userenv.lib


