# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CATAECMigrationItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Feb 2002  Creation: Code generated by the CAA wizard  s223254
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE
