#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=EL LIBRARY

LINK_WITH =  CATMathStream CATVizBase CATVisShader VE0PIX VE0FONT JS0FM JS0SCBAK JS0CORBA JS0STR YN000MFL CATSysMultiThreading

LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -DCATVIZ_SPECIFICATION


OS = AIX
SYS_LIBS = -lXt -lX11 -lGL -lGLU -lXext -I/usr/lib/rcm.exp
LOCAL_CCFLAGS = -qfloat=hsflt -DCATVIZ_SPECIFICATION

OS = HP-UX
LOCAL_POST_CCFLAGS=-Wc,-call_limit,2000
LOCAL_CCFLAGS = -I/opt/graphics/OpenGL/include -DCATVIZ_SPECIFICATION
LOCAL_LDFLAGS = -L/opt/graphics/OpenGL/lib -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXt -lX11 -lGL -lGLU 

OS = hpux_b64
LOCAL_POST_CCFLAGS=-Wc,-call_limit,2000
LOCAL_CCFLAGS = -I/opt/graphics/OpenGL/include -DCATVIZ_SPECIFICATION
LOCAL_LDFLAGS = -L/opt/graphics/OpenGL/lib/pa20_64 -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXt -lX11 -lGL -lGLU 

OS = SunOS
SYS_LIBS = -lXt -lX11 -lGL -lGLU -lXext
#ifdef CATIAV5R8
OPTIMIZATION_CPP = -xO4
#else
OPTIMIZATION = -xO5
#endif
LOCAL_CCFLAGS = -xprefetch=explicit -xlibmil -DCATVIZ_SPECIFICATION

OS = intel_a 
LINK_WITH = CATVizBase VE0PIX VE0FONT JS0FM JS0SCBAK JS0CORBA JS0STR YN000MFL CATSysMultiThreading CATVisShader
SYS_LIBS = opengl32.lib glu32.lib cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGl.dll
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION

OS = win_b
LINK_WITH = CATVizBase VE0PIX VE0FONT JS0FM JS0SCBAK JS0CORBA JS0STR YN000MFL CATSysMultiThreading CATVisShader
SYS_LIBS = opengl32.lib glu32.lib cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGl.dll
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION

OS = win_b64
LINK_WITH = CATVizBase VE0PIX VE0FONT JS0FM JS0SCBAK JS0CORBA JS0STR YN000MFL CATSysMultiThreading CATVisShader
SYS_LIBS = opengl32.lib glu32.lib cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGl.dll
LOCAL_CCFLAGS = -D_WNT40I_SOURCE
LOCAL_CFLAGS  = -D_WNT40I_SOURCE

OS = alpha_a
LINK_WITH = CATVizBase VE0PIX VE0FONT JS0FM JS0SCBAK JS0CORBA JS0STR YN000MFL CATSysMultiThreading CATVisShader
SYS_LIBS = opengl32.lib glu32.lib cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGl.dll
LOCAL_CCFLAGS = -D_WNT40A_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40A_SOURCE -DCATVIZ_SPECIFICATION

OS = win_a 
LINK_WITH = CATVizBase VE0PIX VE0FONT JS0FM JS0SCBAK JS0CORBA JS0STR YN000MFL CATSysMultiThreading CATVisShader
SYS_LIBS = opengl32.lib glu32.lib cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGl.dll
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION

OS = IRIX
LINK_WITH = CATVizBase VE0PIX VE0FONT JS0FM JS0SCBAK JS0CORBA JS0STR YN000MFL CATSysMultiThreading CATVisShader
SYS_LIBS = -lXt -lX11 -lGLcore -lGL -lGLU -lXext
LOCAL_CCFLAGS = -float -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -float -DCATVIZ_SPECIFICATION
LOCAL_LDFLAGS = 
