#
# CATArrangementUI Plane.m 
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=   \
CO0LSTPV CO0LSTST CO0RCINT \
AD0XXBAS AC0XXLNK \
CD0FRAME CD0WIN \
DI0PANV2 \
JS03TRA JS0STR JS0CORBA JS0FM JS0LIB0 JS0SCBAK \
NS0S3STR  ON0MAIN ON0GREXT \
YN000MFL SELECT \
AS0STARTUP \
ArrUtility ArrUIInterfaces ArrArrangementInterfaces ArrSelect \
CATArrangementItf CATVisualization CATDialogEngine CATArrProductServices

#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_IID=CATArrangementUUID CATArrangementUIUUID
#else
LINK_WITH_IID=
#endif

#------------
OS = COMMON
