#ifndef CATScmPDMObject_H
#define CATScmPDMObject_H
// Reconciliator
// Version 1 Release 0
// COPYRIGHT DASSAULT SYSTEMES 2004-2013
/**
  * @CAA2Level L1
  * @CAA2Usage U1
  */
// *****************************************************************
//
//   Identification :
//   ---------------
//
//      RESPONSIBLE : Jean-Luc MEDIONI
//      FUNCTION    : Reconciliator
//      USE         : CATIA & ENOVIA
//
// *****************************************************************
//
//   Description :
//   ------------
//
// Header definition of CATScmPDMObject
//
// *****************************************************************
//
//   Remarks :
//   ---------
//
//
// ****************************************************************
//
//   Story :
//   -------
//
//   Revision 1.0  Jan 2004     Creation: Code generated by the CAA wizard.
//   Revision 2.1  Jan 2004     Update:   V5R14 migration.
//   Revision 2.1  Dec 2004     Update:   File extension management.
//   Revision 2.2  Dec 2008     Update:   Add management of maturity freezed, site ownership and lock management.
//   Revision 2.2  Nov 2010     Update:   Add GetCATIDocId method 
//   Revision 2.3  Sep 2012     Update:   Add Set/GetCATUuid + datamember
//   Revision 2.4  Nov 2013     Update:   Add unary GetValue method
//
// ****************************************************************
//
// INSIDE class:
// -------------
//
//
// ****************************************************************
// Abstract class    : No
// Template code     : No
// Ilined   Function : No
// ****************************************************************

#include "CATPDMReconcileModel.h"

class CATPPRHubObjectDescriptor ;

// --- Include used classes

#include "CATUnicodeString.h"
#include "CATUuid.h"
#include "CATListOfCATUnicodeString.h"
#include "CATBaseUnknown.h"  
#include "CATTime.h"  
#include "sequence_octet.h"

class CATIDocId;

// --- * Mask to current PDM object property

#define CATScmPDMObject_Init                     0x00000000
#define CATScmPDMObject_MaturityStatusDefined    0x00000001
#define CATScmPDMObject_MaturityStatusFreezed    0x00000002
#define CATScmPDMObject_SiteOwnershipDefined     0x00000004
#define CATScmPDMObject_SiteOwnershipLocal       0x00000008
#define CATScmPDMObject_LockStatusDefined        0x00000010
#define CATScmPDMObject_LockByMe                 0x00000020
#define CATScmPDMObject_LockByOther              0x00000040
#define CATScmPDMObject_PublicationExposed       0x00000080
#define CATScmPDMObject_StructureExposed         0x00000100
#define CATScmPDMObject_HasACATUuid              0x00000200

//-----------------------------------------------------------------------

/**
  * Information on a Object stored on VPDM Repository.
  *
  * <b>Role</b>: Information on a Object stored on VPDM Repository in context of
  * reconciliation operation. This class must be used in conjonction with 
  * @href CATScmObject.
  */
class ExportedByCATPDMReconcileModel CATScmPDMObject
{
   // -------------------------------------------
   // --- Standard constructors and destructors
   // -------------------------------------------

   public :
   /** @nodoc
     * Constructs a PDM object.
     * 
     * <br><b>Role</b>: Constructs a PDM object.
     * Used in context of a <b><i>Criterion</i></b> as result of queries.
     * 
     * @param iHubDesc
     * VPDM Object descriptor (VPDM identification).
     * 
     * @param iAttrValues
     * List of attribute values as string (@href CATIPDMCriterionScm ).
     * 
     */
      CATScmPDMObject( CATPPRHubObjectDescriptor  & iHubDesc
                     , CATListValCATUnicodeString & iAttrValues ) ;

   /** 
     * Constructs a Reconciliation object.
     * 
     * <br><b>Role</b>: Constructs a Reconciliation object from one CATIA object.
     * 
     * @param iRecObj
     * CATIA Object.
     */
      CATScmPDMObject ( const CATScmPDMObject & ) ;

   /** 
     */
      CATScmPDMObject& operator =(const CATScmPDMObject &);

   /** 
     */
      virtual ~CATScmPDMObject();

   /** 
     */
       int operator == (const CATScmPDMObject & ) const ;

   /**
     * Gets list of Attribute values of a VPDM object.
     *
     * <b>Role:</b> Gets list of Attribute values of a VPDM object. 
     * <br>Those information are filled by the execution of a <b><i>Criterion</i></b>
     * on a @href CATScmObject. The name of Attributes are found on <b><i>CATScmObject</i></b>.
     * 
     * <br><b>Pre-condition</b>: Assumes that the address of an already
     *  built <b><i>CATLISTP(CATIPDMCriterionScm )</i></b> is passed.
     *
     * @return
     * Method return code 
     * <br><b>Legal values</b>: Returns <b><i>S_OK</i></b> if operation runs well. 
     * 
     * @param oAttrValues
     * List of values  (@href CATIPDMCriterionScm ).
     */
      HRESULT GetValues( CATListValCATUnicodeString & oAttrValues ) const ;

     
      /**
      *
      * <br><b>Role</b>: Gets Attribute value of a VPDM object, for the iposition-th attribute.
      * @param iposition [in]
      *        position in the internal list, so must be in [1..n], n the number of attributes for this PDM object
      * 
      * @return the attribute value as a const unicode string reference
      *         if iposition out of bound, return an empty string
      * 
      */
      const CATUnicodeString & GetValue ( int iposition ) const;


   /**
     * Sets list of Attribute values of a VPDM object.
     *
     * <b>Role:</b> Sets list of Attribute values of a VPDM object. 
     *
     * @return
     * Method return code 
     * <br><b>Legal values</b>: Returns <b><i>S_OK</i></b> if operation runs well. 
     * 
     * @param iAttrValues
     *   List of values.
     */
      HRESULT SetValues( const CATListValCATUnicodeString & iAttrValues ) ;

      /** 
      * Return the underlying environement of the PDMObject.
      *
      * <br><b>Role</b>: retunr the environment (LateType)
      *
      *
      * @return
      *   The string containing the environment
      *
      */
      CATUnicodeString GetEnvironment () const;

   /** @nodoc
     * Gets access to the PDM object.
     *
     * <b>Role:</b> Gets access to the PDM object in VPDM repository. 
     *
     * <br><b>Post-condition</b>: Result must not to be deleted by the caller
     *
     * @return
     * Method return code 
     * <br><b>Legal values</b>: Returns <b><i>S_OK</i></b> if operation runs well. 
     * 
     * @param ixDesc
     *   PDM descriptor (@href CATPPRHubObjectDescriptor ).
     */
      HRESULT GetDescriptor( CATPPRHubObjectDescriptor ** ixDesc ) const ;

   /** @nodoc
     * Sets access to the PDM object.
     *
     * <b>Role:</b> Sets access to the PDM object in VPDM repository.
     *
     * <br><b>Post-condition</b>: Input descriptor is dupplicated by this method, 
     * so it must be deleted by the caller.
     *
     * @return
     * Method return code 
     * <br><b>Legal values</b>: Returns <b><i>S_OK</i></b> if operation runs well. 
     * 
     * @param oxDesc
     *   PDM descriptor (@href CATPPRHubObjectDescriptor ).
     */
      HRESULT SetDescriptor( CATPPRHubObjectDescriptor * oxDesc ) ;

   /**  
     * Sets VPDM object Timestamp.
     *
     * <br><b>Role</b>: Sets VPDM object Timestamp.
     *
     * @return
     * Returns error code
     *
     * @param itTimeStamp
     * VPMD timestamp.
     */
      HRESULT SetPdmTimeStamp( const CATTime & itTimeStamp ) ;

   /** 
     * Gets VPDM object Timestamp.
     *
     * <br><b>Role</b>: Gets VPDM object Timestamp.
     *
     * @return
     * Returns VPDM time stamp of this object
     */
      CATTime GetPdmTimeStamp() const ;

   /**  
     * Sets File extension.
     *
     * <br><b>Role</b>: Sets File extension such as CATPart, model and so on.
     *
     * @return
     * Returns error code
     *
     * @param icFileExtension
     * File extension.
     */
      HRESULT SetFileExtension( const CATUnicodeString & icFileExtension ) ;

   /** 
     * Gets File extension.
     *
     * <br><b>Role</b>: Gets File extension such as CATPart, model and so on.
     *
     * @return
     * Returns file extension for a document (blank otherwise).
     */
      CATUnicodeString GetFileExtension() const ;

   /**
     * Gets PDM Type.
     *
     * <br><b>Role</b>: Gets PDM type used in CATIA Log.
     *
     * @return
     * Returns error code
     *
     * @param ocPdmType
     * PDM Type.
     */
      HRESULT GetPdmType( CATUnicodeString & ocPdmType ) const ;

   /**
     * Gets PDM alias Type name.
     *
     * <br><b>Role</b>: Gets PDM alias Type name.
     *
     * @return
     * Returns error code
     *
     * @param ocPdmAliasType
     *  PDM Alias Type name.
     */
      HRESULT GetPdmTypeAlias( CATUnicodeString & ocPdmAliasType ) const ;

   /**
     * Gets PDM Id.
     *
     * <br><b>Role</b>: Gets PDM Id.
     *
     * @return
     * Returns error code
     *
     * @param ocPdmId
     * PDM Type.
     */
      HRESULT GetPdmName(CATUnicodeString & ocPdmId ) const ;

	   HRESULT GetSequencePdmId( SEQUENCE(octet) & osId ) const;

   /**  
     * Sets lock information.
     *
     * <br><b>Role</b>: Sets if object is locked and by whom it is locked.
     *
     * @return
     * Returns error code
     *
     * @param inLockStatus
     *   Identify lock status.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>-1</dt>    <dd>Lock status not set.</dd>
     *     <dt> 0</dt>    <dd>Object not lock by anybody.</dd>
     *     <dt> 1</dt>    <dd>Object lock by current connected user.</dd>
     *     <dt> 2</dt>    <dd>Object lock by another user.</dd>
     *     </dl>
     *
     * @param icLockOwner
     *   User that has locked the object.
     */
      HRESULT SetLockOwner( int inLockStatus , const CATUnicodeString & icLockOwner ) ;

   /** 
     * Gets lock information.
     *
     * <br><b>Role</b>: Gets if object is locked and by whom it is locked.
     *
     * @param onLockStatus
     *   Identify lock status.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>-1</dt>    <dd>Lock status not set.</dd>
     *     <dt> 0</dt>    <dd>Object not lock by anybody.</dd>
     *     <dt> 1</dt>    <dd>Object lock by current connected user.</dd>
     *     <dt> 2</dt>    <dd>Object lock by another user.</dd>
     *     </dl>
     *
     * @return
     *   User that has locked the object.
     */
      CATUnicodeString GetLockOwner( int & onLockStatus ) const ;

   /**  
     * Sets site ownership information.
     *
     * <br><b>Role</b>: Sets site ownership information to identify if an object has been shared with another location (replication).
     *  It enables also to know if object is editable or not on local sites.
     *
     * @return
     * Returns error code
     *
     * @param inSiteOwnerStatus
     *   Identify if object has been shared.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>-1</dt>    <dd>No information about Site Ownership.</dd>
     *     <dt> 0</dt>    <dd>Object owned locally (could be edit on this site).</dd>
     *     <dt> 1</dt>    <dd>Object owned by another site, thus could not be modified on this site.</dd>
     *     </dl>
     *
     * @param icSiteOwnership
     *   Site owning this object (empty is owned locallly).
     */
      HRESULT SetSiteOwnership( int inSiteOwnerStatus , const CATUnicodeString & icSiteOwnership ) ;

   /**  
     * Gets site ownership information.
     *
     * <br><b>Role</b>: Gets site ownership information to identify if an object has been shared with another location (replication).
     *  It enables also to know if object is editable or not on local sites.
     *
     * @param onSiteOwnerStatus
     *   Identify if object has been shared.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>-1</dt>    <dd>No information about Site Ownership.</dd>
     *     <dt> 0</dt>    <dd>Object owned locally (could be edit on this site).</dd>
     *     <dt> 1</dt>    <dd>Object owned by another site, thus could not be modified on this site.</dd>
     *     </dl>
     *
     * @return
     *   Site owning this object (empty is owned locallly).
     */
      CATUnicodeString GetSiteOwnership( int & onSiteOwnerStatus ) const ;

   /**  
     * Sets maturity freezed status.
     *
     * <br><b>Role</b>: Sets maturity freezed status.
     *  It enables to know if maturity has reached a level that forbid modification of it.
     *
     * @return
     * Returns error code
     *
     * @param inMaturityStatus
     *   Identify if object has been frozen.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>-1</dt>    <dd>No information about maturity status.</dd>
     *     <dt> 0</dt>    <dd>Object maturity authorizes modification.</dd>
     *     <dt> 1</dt>    <dd>Object maturity forbid object modification.</dd>
     *     </dl>
     */
      HRESULT SetMaturityFreezeStatus( int inMaturityStatus ) ;

   /**  
     * Gets maturity freezed status.
     *
     * <br><b>Role</b>: Gets maturity freezed status.
     *  It enables to know if maturity has reached a level that forbid modification of it.
     *
     * @return
     *   Identify if object has been frozen.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>-1</dt>    <dd>No information about maturity status.</dd>
     *     <dt> 0</dt>    <dd>Object maturity authorizes modification.</dd>
     *     <dt> 1</dt>    <dd>Object maturity forbid object modification.</dd>
     *     </dl>
     */
      int GetMaturityFreezeStatus() const ;

   /**  
     * Sets object exposition mode.
     *
     * <br><b>Role</b>: Sets object exposition mode.
     *  It enables to know if an object is Structure exposed (managed by <b>ENOVIA</b>) or Publication exposed (managed by <b>CATIA</b>).
     *
     * @return
     * Returns error code
     *
     * @param inExpositionMode
     *   Identify object exposition mode.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>0</dt>    <dd>No information about exposition mode.</dd>
     *     <dt>1</dt>    <dd>Object in Publication exposed (managed by <b>CATIA</b>).</dd>
     *     <dt>2</dt>    <dd>Object Structure exposed (managed by <b>ENOVIA</b>).</dd>
     *     </dl>
     */
      HRESULT SetExpositionMode( int inExpositionMode ) ;

   /**  
     * Gets object exposition mode.
     *
     * <br><b>Role</b>: Gets object exposition mode.
     *  It enables to know if an object is Structure exposed (managed by <b>ENOVIA</b>) or Publication exposed (managed by <b>CATIA</b>).
     *
     * @return
     *   Identify object exposition mode.
     *   <br><b>Legal values</b>: 
     *     <dl>
     *     <dt>0</dt>    <dd>No information about exposition mode.</dd>
     *     <dt>1</dt>    <dd>Object in Publication exposed (managed by <b>CATIA</b>).</dd>
     *     <dt>2</dt>    <dd>Object Structure exposed (managed by <b>ENOVIA</b>).</dd>
     *     </dl>
     */
      int GetExpositionMode() const ;


      /** 
      * Short role of the method.
      *
      * <br><b>Role</b>: returned the CATIDocId of current PDMObject (if a doc...)
      *
      * @param oDocId [out, CATBaseUnknown#Release]
      *   The CATIDocId corresponding ot this, if this is mapping a document (NULL elsewhere)
      *   Pointer must be intialized to NULL prior to call the method
      *
      * @return
      *   <code>E_INVALIDARG</code> if oDocId was not intially set to NULL
      *   <code>E_UNEXPECTED</code> if this is not a PDMDocument
      *   <code>E_FAIL</code> if cannot collect all needed data to build CATIDocID
      *   <code>S_OK</code> if everything ran ok, otherwise...
      *
      */
      HRESULT GetDocId (CATIDocId * & oDocId ) const;

      
      /**
      *
      * <br><b>Role</b>: Setter to store an uuid complient with  System/PublicInterfaces/CATUuid.h
      * No allocation done, size of input string is not checked
      * @param iCATUuid [in] the CATUuid to store in current CATScmPDMObject
      * 
      */
      void SetCATUuid ( const CATUuid  & iCATUuid ) ;

      /**
      *
      * <br><b>Role</b>: Getter to store an uuid complient with  System/PublicInterfaces/CATUuid.h
      * No allocation done, size of input string is not checked
      * @param oCATUuid [out] the returned CATUuid (copy of the stored one in current CATScmPDMObject)
      * 
      */
      void GetCATUuid (  CATUuid  & oCATUuid ) const ;

   private :
      /** 
        * VPDM identification.
        */
      CATPPRHubObjectDescriptor  * _HubDesc        ;

      /** 
        * List of attribute values.
        */
      CATListValCATUnicodeString   _AttrValues     ;

      /** 
        * Database timestamp.
        */
      CATTime                      _tTS            ;

      /**  
        * File extension such as CATPart, model and so on.
        */
      CATUnicodeString             _cFileExtension ;

      /**  
        * Site ownership name.
        */
      CATUnicodeString             _cSiteOwnership ;

      /**  
        * Site Lock owner management.
        */
      CATUnicodeString             _cLockOwner    ;

      /**  
        * Object status (see mask status to decode this mask of bits).
        */
      int                          _nPdmObjectStatus ;

      /**  
        * To store the CATIA uuid (eg the one of RootContainer for a CATDocument).
        */
      CATUuid                 _catUuid ;

} ;

//-----------------------------------------------------------------------

#endif
