# 
#      LIB : IDV4STD
# 
BUILT_OBJECT_TYPE = SHARED LIBRARY
INCLUDED_MODULES = IDV4STD
#
COMDYN_MODULE = V4SysCOMD
#
DUMMY_LINK_WITH = V4SysUTIL V4SysB V4SysMEM CATCdbEntity CATIAPrjEntity IDV4BA1
#
#INCLUDED_MODULES = IDV4STD

#
IMPACT_ON_IMPORT=YES
#
OS = COMMON
LINK_WITH = $(DUMMY_LINK_WITH)
#
OS = AIX
SYS_LIBS = -lxlf -lxlf90 -lxlfpad
#
OS = IRIX
LOCAL_LDFLAGS = -no_unresolved 
SYS_LIBS = -lftn
#
OS = Windows_NT
#OPTIMIZATION_FORTRAN = /optimize:1
#
OS = HP-UX
#
OS = SunOS
#

