/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAMfgResourceFactory_h
#define CATIAMfgResourceFactory_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByManufacturingPubIdl
#ifdef _WINDOWS_SOURCE
#ifdef __ManufacturingPubIdl
#define ExportedByManufacturingPubIdl __declspec(dllexport)
#else
#define ExportedByManufacturingPubIdl __declspec(dllimport)
#endif
#else
#define ExportedByManufacturingPubIdl
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"

extern ExportedByManufacturingPubIdl IID IID_CATIAMfgResourceFactory;

class ExportedByManufacturingPubIdl CATIAMfgResourceFactory : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall CreateResource(const CATBSTR & iType, CAT_VARIANT_BOOL iAddList, CATIABase *& oResource)=0;


};

CATDeclareHandler(CATIAMfgResourceFactory, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
