/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAMfgManufacturingFactories2_h
#define CATIAMfgManufacturingFactories2_h

#ifndef ExportedByManufacturingPubIdl
#ifdef _WINDOWS_SOURCE
#ifdef __ManufacturingPubIdl
#define ExportedByManufacturingPubIdl __declspec(dllexport)
#else
#define ExportedByManufacturingPubIdl __declspec(dllimport)
#endif
#else
#define ExportedByManufacturingPubIdl
#endif
#endif

#include "CATIABase.h"

extern ExportedByManufacturingPubIdl IID IID_CATIAMfgManufacturingFactories2;

class ExportedByManufacturingPubIdl CATIAMfgManufacturingFactories2 : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetManufacturingFeatureFactory(CATIABase *& oFeatureFactory)=0;


};

CATDeclareHandler(CATIAMfgManufacturingFactories2, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
