/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAManufacturingActivityToolPath_h
#define CATIAManufacturingActivityToolPath_h

#ifndef ExportedByManufacturingPubIdl
#ifdef _WINDOWS_SOURCE
#ifdef __ManufacturingPubIdl
#define ExportedByManufacturingPubIdl __declspec(dllexport)
#else
#define ExportedByManufacturingPubIdl __declspec(dllimport)
#endif
#else
#define ExportedByManufacturingPubIdl
#endif
#endif

#include "CATIABase.h"

extern ExportedByManufacturingPubIdl IID IID_CATIAManufacturingActivityToolPath;

class ExportedByManufacturingPubIdl CATIAManufacturingActivityToolPath : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall ComputeAndSetToolPath()=0;


};

CATDeclareHandler(CATIAManufacturingActivityToolPath, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
