/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAManufacturingMachiningAxis_h
#define CATIAManufacturingMachiningAxis_h

#ifndef ExportedByManufacturingPubIdl
#ifdef _WINDOWS_SOURCE
#ifdef __ManufacturingPubIdl
#define ExportedByManufacturingPubIdl __declspec(dllexport)
#else
#define ExportedByManufacturingPubIdl __declspec(dllimport)
#endif
#else
#define ExportedByManufacturingPubIdl
#endif
#endif

#include "CATIAManufacturingFeature.h"

class CATIABase;

extern ExportedByManufacturingPubIdl IID IID_CATIAManufacturingMachiningAxis;

class ExportedByManufacturingPubIdl CATIAManufacturingMachiningAxis : public CATIAManufacturingFeature
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Origin(short & Origin)=0;

    virtual HRESULT __stdcall put_Origin(short Origin)=0;

    virtual HRESULT __stdcall get_OriginNumber(short & OriginNumber)=0;

    virtual HRESULT __stdcall put_OriginNumber(short OriginNumber)=0;

    virtual HRESULT __stdcall get_OriginGroup(short & OriginGroup)=0;

    virtual HRESULT __stdcall put_OriginGroup(short OriginGroup)=0;

    virtual HRESULT __stdcall SetPartAxisSystem(CATIABase * iPAS, CATIABase * iProduct)=0;

    virtual HRESULT __stdcall SetOriginPoint(CATIABase * iPoint, CATIABase * iProduct)=0;

    virtual HRESULT __stdcall GetOriginPoint(double & x, double & y, double & z)=0;

    virtual HRESULT __stdcall SetOriginXDirection(double x, double y, double z)=0;

    virtual HRESULT __stdcall SetOriginZDirection(double x, double y, double z)=0;

    virtual HRESULT __stdcall GetOriginXDirection(double & x, double & y, double & z)=0;

    virtual HRESULT __stdcall GetOriginYDirection(double & x, double & y, double & z)=0;

    virtual HRESULT __stdcall GetOriginZDirection(double & x, double & y, double & z)=0;

    virtual HRESULT __stdcall SetOriginPointByCoordinates(double x, double y, double z)=0;


};

CATDeclareHandler(CATIAManufacturingMachiningAxis, CATIAManufacturingFeature);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIAParameter.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
