// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// CATICAAABFJointBody.h
// Define the CATICAAABFJointBody interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Feb 2012  Creation: Code generated by the CAA wizard  bs5
//===================================================================
#ifndef CATICAAABFJointBody_H
#define CATICAAABFJointBody_H

/**
* @CAA2Level L0
* @CAA2Usage U3
*/

#include "CATBaseUnknown.h"
#include "CATIUnknownList.h"
#include "CATListOfCATUnicodeString.h"
#include "CATUnicodeString.h"
#include "CATICAAABFJoint.h"


#ifdef  _WINDOWS_SOURCE
#ifdef  __CATGbfModelItfCPP
#define ExportedByCATGbfModelItfCAA     __declspec(dllexport)
#else
#define ExportedByCATGbfModelItfCAA     __declspec(dllimport)
#endif
#else
#define ExportedByCATGbfModelItfCAA
#endif

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATGbfModelItfCAA IID IID_CATICAAABFJointBody;
#else
extern "C" const IID IID_CATICAAABFJointBody ;
#endif

/**	
* Interface representing ABF Joint Body.
* <b>Role:</b> this interface concerns joint body.
*
*/
class ExportedByCATGbfModelItfCAA CATICAAABFJointBody: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

	/**
	*       
	*   GetJointBodyName returns the Joint Body Name.
	*   @param strJointBodyName
	*      Joint body name string.
	* 
	*/
	virtual HRESULT GetJointBodyName(CATUnicodeString &ostrJointBodyName) = 0 ;

	/**
	*       
	*   GetJointElements returns the Joint element list of the joint body.
	*   @param oJointElmts
	*      List of the joint elements of the joint body.
	* 
	*/
	virtual HRESULT GetJointElements (CATIUnknownList **oJointElmts) = 0 ;

	/*
	* Gets the list of Contact Zones Names on the input Joined component 
   *
   *   @param oZoneNames : List of  Zone Names, each name can be:
   *                           - the Publication Name of a specific geometrical feature
   *                           - either a NULL_string for the first created UNSPEC zone
   *                           - a character string  <<Additional_%UNSPEC_Zone_i%>> for each additional zone
   *
   *   @param iComp            : Input Joined Product component joined by the Father Assembly Joint
   */
	virtual HRESULT GetJoinedZonesFromComponent (CATListOfCATUnicodeString & oZonesNames,  const IUnknown* const iComp ) = 0; 

	/**
	*       
	*   GetFatherJoint returns the parent joint for this joint body.
	*   @param oFatherJoint
	*      Pointer to the parent joint of this joint body.
	* 
	*/
	virtual HRESULT GetFatherJoint(CATICAAABFJoint **oFatherJoint) = 0 ;

	/**
	*       
	*   IsHem returns Hem rule status of the component.
	*   @param oHemRole
	*      Hem rule status.
	*   @param iZoneName
	*      Input zone name for the Hem rule.
	*   @param iComp
	*      Input component for the Hem rule.
	* 
	*/
	virtual HRESULT IsHem (CATBoolean  * oHemRole, const CATUnicodeString & iZoneName, const IUnknown* const iComp ) = 0; 

	/**
	*       
	*   GetJointZoneThickness returns the joint zone thickness values.
	*   @param oThickness1
	*      Thickness one value.
	*   @param oThickness2
	*      Thickness two value.
	*   @param oThickness1Orient
	*      Thickness orientation.
	*   @param iZoneName
	*      Input zone name for joint zone thickness.
	*   @param iComp
	*      Input component for joint zone thickness.
	* 
	*/
	virtual HRESULT GetJointZoneThickness (double * oThickness1, double * oThickness2, int * oThickness1Orient, const CATUnicodeString & iZoneName, const IUnknown* const iComp )  = 0;

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
