// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// CATICAAABFManager.h
// Define the CATICAAABFManager interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Mar 2012  Creation: Code generated by the CAA wizard  bs5
//===================================================================
#ifndef CATICAAABFManager_H
#define CATICAAABFManager_H

/**
* @CAA2Level L0
* @CAA2Usage U3
*/

#include "CATBaseUnknown.h"
class CATIUnknownList;


#ifdef  _WINDOWS_SOURCE
#ifdef  __CATGbfModelItfCPP
#define ExportedByCATGbfModelItfCAA     __declspec(dllexport)
#else
#define ExportedByCATGbfModelItfCAA     __declspec(dllimport)
#endif
#else
#define ExportedByCATGbfModelItfCAA
#endif



#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATGbfModelItfCAA IID IID_CATICAAABFManager;
#else
extern "C" const IID IID_CATICAAABFManager ;
#endif


/**	
* Interface representing ABF Manager.
* <b>Role:</b> this interface concerns ABF joint manager.
*
*/
class ExportedByCATGbfModelItfCAA CATICAAABFManager: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

	/**
	*   Get the list of joints of this ABFManager
	*   @param oABFJoints
	*      The list of the joints of the ABFManager.
	* 
	*/
	virtual HRESULT GetJoints (CATIUnknownList ** oABFJoints) = 0;
  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
