#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ObjectModelerCATIAUUID
#else
LINK_WITH_FOR_IID =
#endif
# 
IMPACT_ON_IMPORT = YES
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
COMDYN_MODULE = V4SysCOMD
#
DUMMY_LINK_WITH = CATV4DataAdmin CATCdbEntity CATIADataFormat AC0CATPL JS0GROUP
#
#
OS = COMMON
LINK_WITH=$(LINK_WITH_FOR_IID)  $(DUMMY_LINK_WITH)
SYS_LIBPATH = 
