// COPYRIGHT DASSAULT SYSTEMES PROVENCE 2000

/**
  * @CAA2Level L0
  * @CAA2Usage U3
  */

//===================================================================
//
// CATIMldPlate.h
// Define the CATIMldPlate interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Aug 2000  Creation: Code generated by the CAA wizard  jcb
//  07/11/2001 : pic; Add Plates Geometric attributes management.
//  06/11/2003 : fdm; Passage L0.
//===================================================================
#ifndef CATIMldPlate_H
#define CATIMldPlate_H

#include "CATMoldItfCPP.h"
#include "CATIMldMoldBaseElement.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATMoldItfCPP IID IID_CATIMldPlate ;
#else
extern "C" const IID IID_CATIMldPlate ;
#endif

//------------------------------------------------------------------

/**
 * Describe the functionality of your interface here
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class ExportedByCATMoldItfCPP CATIMldPlate: public CATIMldMoldBaseElement
{
  CATDeclareInterface;

  public:

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
	 /**
	 *		Set ZOriented of the MoldBaseElement.
	 * @param iZOriented
     */
		virtual HRESULT SetZOriented(CATBoolean iZOriented) = 0;

	 /**
	 *		Get ZOriented of the MoldBase.
	 * @param oZOriented
     */
		virtual HRESULT GetZOriented(CATBoolean *oZOriented) = 0;
	/**
	 *		Set ZValue of the MoldBaseElement.
	 * @param iZValue
     */
		virtual HRESULT SetZValue(CATISpecObject_var iZValue) = 0;

	 /**
	 *		Get ZValue of the MoldBase.
	 * @param oZValue
     */
		virtual HRESULT GetZValue(CATISpecObject_var oZValue) = 0;

};

//------------------------------------------------------------------

CATDeclareHandler( CATIMldPlate, CATIMldMoldBaseElement );

#endif
