//===================================================================
// COPYRIGHT Dassault Systemes 2018
//===================================================================

#ifndef CATIAManufacturingActivityToolPath_IDL
#define CATIAManufacturingActivityToolPath_IDL

/*IDLREP*/

/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "CATIABase.idl"

/**
* Interface to compute the tool path of an activity.
*/
interface CATIAManufacturingActivityToolPath : CATIABase
{
	/**
	* Compute and set Tool Path for this operation
	*/
	HRESULT ComputeAndSetToolPath();

};

// Interface name : CATIAManufacturingActivityToolPath
#pragma ID CATIAManufacturingActivityToolPath "DCE:944342cd-c930-48e4-a99171091a118432"
#pragma DUAL CATIAManufacturingActivityToolPath

// VB object name : CATIAManufacturingActivityToolPathVB (Id used in Visual Basic)
#pragma ID ManufacturingActivityToolPath "DCE:e1de4846-d5e9-4dc9-97a6048b02e210a4"
#pragma ALIAS CATIAManufacturingActivityToolPath ManufacturingActivityToolPath

#endif
