// COPYRIGHT Dassault Systemes 2014
//===================================================================
//
// CATIAManufacturingToolAssembly2.idl
// Automation interface for the ManufacturingToolAssembly element 
//
//===================================================================
//  Jan 2014  Creation: ZPP
//===================================================================

#ifndef CATIAManufacturingToolAssembly2_IDL
#define CATIAManufacturingToolAssembly2_IDL

/*IDLREP*/
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "CATIABase.idl"
#include "CATIAManufacturingTool.idl"
#include "CATIAManufacturingInsert.idl"


/**  
* Represents the tool assembly.   
*/
interface CATIAManufacturingToolAssembly2 : CATIABase 
{

	/**
	* Set the tool of an assembly.
	* @param iMfgTool
	*		The tool to set to tool assembly
	*/
#pragma PROPERTY Tool
	HRESULT put_Tool (in CATIAManufacturingTool iMfgTool);

	/**
	* Set the insert of an assembly.
	* @param iMfgInsert
	*		The insert to set to tool assembly
	*/
#pragma PROPERTY Insert
	HRESULT put_Insert (in CATIAManufacturingInsert iMfgInsert);

};

// Interface name : CATIAManufacturingToolAssembly2
#pragma ID CATIAManufacturingToolAssembly2 "DCE:40E10691-2E2D-49FC-BD8E628E35D11026"
#pragma DUAL CATIAManufacturingToolAssembly2

// VB object name : ManufacturingToolAssembly (Id used in Visual Basic)
#pragma ID ManufacturingToolAssembly2 "DCE:C68A603B-BF03-402F-8DF405E2E36AE9B4"
#pragma ALIAS CATIAManufacturingToolAssembly2 ManufacturingToolAssembly2

#endif


