// COPYRIGHT Dassault Systemes 2014
//===================================================================

#ifndef CATIAMfgManufacturingFactories_IDL
#define CATIAMfgManufacturingFactories_IDL
/*IDLREP*/

/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "CATIABase.idl"

/**
* Interface to manage manufacturing factories.
* <br><b>Role</b>: CATIAMfgManufacturingFactories has methods to 
* manage manufacturing factories.
*/
interface CATIAMfgManufacturingFactories : CATIABase
{	
	/**
	* Retrieves the manufacturing resource factory from the given object.
	* @param oResourceFactory
	* The manufacturing resource factory. 
	*/
	HRESULT GetManufacturingResourceFactory(out /*IDLRETVAL*/ CATIABase oResourceFactory);

};

// Interface name : CATIAMfgManufacturingFactories
#pragma ID CATIAMfgManufacturingFactories "DCE:22b41242-5045-462e-bddecc468fbf729d"
#pragma DUAL CATIAMfgManufacturingFactories

// VB object name : CATIAMfgManufacturingFactoriesVB (Id used in Visual Basic)
#pragma ID ManufacturingFactories "DCE:141a4906-c90b-4404-a4d870813dc1fb02"
#pragma ALIAS CATIAMfgManufacturingFactories ManufacturingFactories

#endif
