#ifndef CATIAManufacturingProcess_IDL
#define CATIAManufacturingProcess_IDL
/*IDLREP*/

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1999
//=================================================================
//								   
// CATIAManufacturingProcess:						   
// Exposed interface for ManufacturingProcess
//								   
//=================================================================
// Usage notes:
//
//=================================================================
// Oct99 Creation				       Thomas DELIE
// 24/02/03 Tag CAA removed                                     DCN  
//=================================================================
/**
* @CAA2Level L1
* @CAA2Usage U3
*/
#include "CATIABase.idl"
#include "CATBSTR.idl"
#include "CATIAMfgActivities.idl"


/**
 * A ManufacturingProcess for a Manufacturing Document.
 */
interface CATIAManufacturingProcess : CATIABase
{
#pragma PROPERTY Setups

  /**
  * Give the List of Setups linked to a Manufacturing Process.<br>
  * <dl>
  * <dt><b>Example:</b>
  * <dd>The following example returns the list of Setups <tt>SetupsList</tt> linked to the manufacturing Process <tt>CurrentProcess</tt>
  * <pre>
  * Set SetupsList = CurrentProcess.Setups
  *</pre>
  * </dl>
  */
HRESULT get_Setups(out /*IDLRETVAL*/ CATIAMfgActivities oSetupsList);  


};

// Interface name : CATIAManufacturingProcess
#pragma ID CATIAManufacturingProcess "DCE:3cdaae40-8144-11d3-b8130008c74fe567"
#pragma DUAL CATIAManufacturingProcess

// VB object name : ManufacturingProcess (Id used in Visual Basic)
#pragma ID ManufacturingProcess "DCE:3e74c2b8-8144-11d3-b8130008c74fe567"
#pragma ALIAS CATIAManufacturingProcess ManufacturingProcess

#endif // CATIAManufacturingProcess_IDL











