//===================================================================
// COPYRIGHT Dassault Systemes 2019
//===================================================================

#ifndef CATIAMfgMachinableAreaMngt_IDL
#define CATIAMfgMachinableAreaMngt_IDL
/*IDLREP*/

/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "CATIABase.idl"
#include "CATSafeArray.idl"


/**
* Interface dedicated to machinable area feature managment.
* <b>Role</b>: This interface delivers services on machinable area features <br>
*/
interface CATIAMfgMachinableAreaMngt : CATIABase
{

	/**
	* Gets all the data in the Manufacturing Machinable Feature.
	* @param oDatas The list of data
	*/
	HRESULT GetAllDatas(out /*IDLRETVAL*/ CATSafeArrayVariant oDatas);

};

// Interface name : CATIAMfgMachinableAreaMngt
#pragma ID CATIAMfgMachinableAreaMngt "DCE:3feae21b-f41c-442b-8934677468bea12c"
#pragma DUAL CATIAMfgMachinableAreaMngt

// VB object name : CATIAMfgMachinableAreaMngtVB (Id used in Visual Basic)
#pragma ID ManufacturingMachinableAreaMngt "DCE:446d61f7-dfe2-42dd-9122e94a06498ace"
#pragma ALIAS CATIAMfgMachinableAreaMngt ManufacturingMachinableAreaMngt

#endif
