#ifndef CATIAManufacturingActivitySyntax2_IDL
#define CATIAManufacturingActivitySyntax2_IDL
/*IDLREP*/

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 2013
//=================================================================
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "CATIABase.idl"
#include "CATBSTR.idl"


/**
* This interface offers services to manage PP words of activity.
*/
interface CATIAManufacturingActivitySyntax2 : CATIABase
{
	/**
	* Retrieves the PP words syntax.
	* @return
	*   the PPWORDS 
	*/
	HRESULT GetPPWORDSyntax (inout /*IDLRETVAL*/ CATBSTR oPPWORDs);	

};

// Interface name : CATIAManufacturingActivitySyntax
#pragma ID CATIAManufacturingActivitySyntax2 "DCE:B2FF32B3-C7EB-4D69-91BD4E92C3DB918F"
#pragma DUAL CATIAManufacturingActivitySyntax2

// VB object name : ManufacturingActivitySyntax (Id used in Visual Basic)
#pragma ID ManufacturingActivitySyntax2 "DCE:7D2600BC-3A8F-49AE-83A161A01ADFF0B0"
#pragma ALIAS CATIAManufacturingActivitySyntax2 ManufacturingActivitySyntax2

#endif // CATIAManufacturingActivitySyntax_IDL
