// COPYRIGHT Dassault Systemes 2001
//===================================================================
//
// CATIMfgLineAndCircleDiscretizeCurve.h
// Define the CATIMfgLineAndCircleDiscretizeCurve interface
//
//===================================================================
//
// Usage notes:
// Interface dedicated to lines and circles discretization from a CATCurve.
//
//
//  CATIMfgLineAndCircleDiscretizeCurve *piLACDC=NULL;
//
//  CATString ClassName("CATMfgLineAndCircleDiscretizeCurve");
//  CATIInstanciateComponent (ClassName,
//                            CATIMfgLineAndCircleDiscretizeCurve::ClassId(),
//                            piLACDC);
//   .....................
//
//   HRESULT Res = piLACDC->Discretize (iCurve,iSag,iPlane,oXY, oIsACircle);
//   .....................
//   if (piLACDC) pi->Release();
//   .....................
//
//   int NbEntite=oIsACircle.Size();
//   int ilig=1;
//   int ientite ;
//   for (ientite=1 ;ientite<=NbEntite ;ientite++)
//	 {
//	    if (IsACircle[ientite])
//		{
//		   // Lecture des 6 coordonnees de l'arc
//		   double XDebut=oXY[ilig] ;
//		   double YDebut=oXY[ilig+1] ;
//  	   double XMilieu=oXY[ilig+2] ;
//		   double YMilieu=oXY[ilig+3] ;
//		   double XFin=oXY[ilig+4] ;
//		   double XFin=oXY[ilig+5] ;
//		   ilig=ilig+6 ;
//		}
//	    else
//		{
//		   double XDebut=oXY[ilig] ;
//		   double YDebut=oXY[ilig+1] ;
//		   double XFin=oXY[ilig+2] ;
//		   double XFin=oXY[ilig+3] ;
//		   ilig=ilig+4 ;
//		}
//   }
//
//===================================================================
//  Mar 2001  Creation: Code generated by the CAA wizard  TBL
//===================================================================
#ifndef CATIMfgLineAndCircleDiscretizeCurve_H
#define CATIMfgLineAndCircleDiscretizeCurve_H

/**
* @CAA2Level L0
* @CAA2Usage U0
*/

// module
#include "MfgItfEnv.h"

// inheritance
#include "CATBaseUnknown.h"

// forwards
#include "CATListOfInt.h"
#include "CATListOfDouble.h"
class CATCurve;
class CATMathPlane;

#ifndef LOCAL_DEFINITION_FOR_IID
extern IID ExportedByMfgItfEnv IID_CATIMfgLineAndCircleDiscretizeCurve;
#else
extern "C" const IID IID_CATIMfgLineAndCircleDiscretizeCurve;
#endif

//------------------------------------------------------------------

/**
 * Interface dedicated to lines and circles discretization from a CATCurve.
 */
class ExportedByMfgItfEnv CATIMfgLineAndCircleDiscretizeCurve: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
     * This method is used to discretize, according to a tolerance, a CATCurve projected into a plane
     * into lines and circles.
     * <dl>
     * <pre>
     *  @param iCurve    : Pointer on CATCurve object (only one)
     *  @param iSag      : Discretization tolerance
     *  @param iPlane    : Projection plane
     *  @param oXY       : Table of coordinates for lines and circles (defined in 'iPlane' plane)
     *  @see CATListOfDouble
     *  @param oIsACircle: Table of integer indicating if each element is a line or a circleCoordinates for lines and circles (defined in 'iPlane' plane)
     *  Notes: the number of elements is given by oIsActive size (oIsActive.Size())
     *  @see CATListOfInt
     * </pre>
     * </dl>
     */
     virtual HRESULT Discretize (CATCurve     *iCurve,	
                                 const double        iSag,
                                 const CATMathPlane &iPlane,
                                 CATListOfDouble    &oXY,
                                 CATListOfInt       &oIsACircle)=0;

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};
CATDeclareHandler(CATIMfgLineAndCircleDiscretizeCurve, CATBaseUnknown);

//------------------------------------------------------------------

#endif
