#ifndef CatManufacturingPrecedenceType_IDL
#define CatManufacturingPrecedenceType_IDL
/*IDLREP*/

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1997
//=================================================================
//								   
// CatManufacturingPrecedenceType:						   
// enumeration for all types of possible manufacturing predence   
//								   
//=================================================================
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

/**
 * Possible types of precedence.
 *   @param catPrecedenceTypeJustBefore
 *     The precedence type is JustBefore. No other element can be inserted between the 2 elements.
 *
 *   @param catPrecedenceTypeBefore
 *     The precedence type is Before. Other elements can be inserted between the 2 elements.
 *
 */

enum CatManufacturingPrecedenceType
{
	catPrecedenceTypeJustBefore,
	catPrecedenceTypeBefore
};

#endif // CatManufacturingPrecedenceType_IDL









