#ifndef CATIATolerancePerUnitBasisRestrictiveValue_IDL
#define CATIATolerancePerUnitBasisRestrictiveValue_IDL

// COPYRIGHT Dassault Systemes 2002

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIABase.idl"

/**
 * Interface for accessing tolerance per unit basis restrictive value on a TPS.
 * (ASME norm only)
 */
interface CATIATolerancePerUnitBasisRestrictiveValue : CATIABase 
{
    /**
     * Retrieves value (in millimeters).
     *  @param oValue
     *    Positive or equal to -1 which means not valuated.
     */
  #pragma PROPERTY Value
   HRESULT get_Value (out /*IDLRETVAL*/ double oValue);
   HRESULT put_Value (in double iValue);
};

// Interface name : CATIATolerancePerUnitBasisRestrictiveValue
#pragma ID CATIATolerancePerUnitBasisRestrictiveValue "DCE:a33f6be8-260d-11d6-be890002b341dd3a"
#pragma DUAL CATIATolerancePerUnitBasisRestrictiveValue

// VB object name : TolerancePerUnitBasisRestrictiveValue (Id used in Visual Basic)
#pragma ID TolerancePerUnitBasisRestrictiveValue "DCE:a33f6be9-260d-11d6-be890002b341dd3a"
#pragma ALIAS CATIATolerancePerUnitBasisRestrictiveValue TolerancePerUnitBasisRestrictiveValue

#endif
