#ifndef CATIAEnvelopCondition_IDL
#define CATIAEnvelopCondition_IDL

// COPYRIGHT Dassault Systemes 2002

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIABase.idl"

/**
 * Interface for accessing Envelop Condition modifier on a TPS.
 */
interface CATIAEnvelopCondition : CATIABase 
{
    /**
     * Retrieves Envelop Condition modifier.
     */
  #pragma PROPERTY Modifier
   HRESULT get_Modifier (inout /*IDLRETVAL*/ CATBSTR oModifier);
};

// Interface name : CATIAEnvelopCondition
#pragma ID CATIAEnvelopCondition "DCE:cf8b8c68-2f89-11d6-be8a0002b341dd3a"
#pragma DUAL CATIAEnvelopCondition

// VB object name : EnvelopCondition (Id used in Visual Basic)
#pragma ID EnvelopCondition "DCE:cf8b8c69-2f89-11d6-be8a0002b341dd3a"
#pragma ALIAS CATIAEnvelopCondition EnvelopCondition

#endif
