#ifndef CATIADimensionPattern_IDL
#define CATIADimensionPattern_IDL

// COPYRIGHT Dassault Systemes 2002

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIABase.idl"

/**
 * Interface to dimension pattern.
 */
interface CATIADimensionPattern : CATIABase
{
  #pragma PROPERTY InstanceCount
    /**
     * Get count of instances.
     */
    HRESULT get_InstanceCount (out /*IDLRETVAL*/ double oInstanceCount);
};

// Interface name : CATIADimensionPattern
#pragma ID CATIADimensionPattern "DCE:538cec24-2f7e-11d6-be890002b341dd3a"
#pragma DUAL CATIADimensionPattern

// VB object name : DimensionPattern (Id used in Visual Basic)
#pragma ID DimensionPattern "DCE:538cec25-2f7e-11d6-be890002b341dd3a"
#pragma ALIAS CATIADimensionPattern DimensionPattern

#endif
