#ifndef CATIATPSViews_IDL
#define CATIATPSViews_IDL

// COPYRIGHT Dassault Systemes 2003

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIACollection.idl"
#include "CATVariant.idl"
#include "CATIABase.idl"

/**  
 * Interface for collection of TPS Views CATIATPSView.
 */
interface CATIATPSViews : CATIACollection 
{
  /**
    * Retrieve a TPS View.
    */
  HRESULT Item (in CATVariant iIndex,
                out /*IDLRETVAL*/ CATIABase oAnnot);
};

// Interface name : CATIATPSViews
#pragma ID CATIATPSViews "DCE:06fec6cd-5169-44a6-a836ddd9cc5b9493"
#pragma DUAL CATIATPSViews

// VB object name : TPSViews (Id used in Visual Basic)
#pragma ID TPSViews "DCE:58a8de9d-8de4-4586-88af22c40bd6ff5a"
#pragma ALIAS CATIATPSViews TPSViews

#endif
