#ifndef CATIAParticularTolElem_IDL
#define CATIAParticularTolElem_IDL

// COPYRIGHT Dassault Systemes 2002

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIABase.idl"

/**
 * Interface for accessing particular geometry of the toleranced element.
 */
interface CATIAParticularTolElem : CATIABase 
{
  #pragma PROPERTY ParticularGeometry
    /**
     * Retrieves particular geometry of the toleranced element.
     *  @param oPartGeom : Not Defined
     *                     CenterElement
     *                     Surface
     *                     Unsupported
     */
    HRESULT get_ParticularGeometry (inout /*IDLRETVAL*/ CATBSTR oPartGeom);
};

// Interface name : CATIAParticularTolElem
#pragma ID CATIAParticularTolElem "DCE:dab40c8e-2f76-11d6-be890002b341dd3a"
#pragma DUAL CATIAParticularTolElem

// VB object name : ParticularTolElem (Id used in Visual Basic)
#pragma ID ParticularTolElem "DCE:dab40c8f-2f76-11d6-be890002b341dd3a"
#pragma ALIAS CATIAParticularTolElem ParticularTolElem

#endif
