#ifndef CATIANonSemanticGDT_IDL
#define CATIANonSemanticGDT_IDL

// COPYRIGHT Dassault Systemes 2002

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIABase.idl"

interface CATIADrawingGDT;
interface CATIATPSParallelOnScreen;

interface CATIANonSemanticGDT : CATIABase
{
  /**
  * Retrieves Drafting GDT.
  */
    HRESULT  Get2dAnnot(out /*IDLRETVAL*/ CATIADrawingGDT oGDT);

  /**
    * Gets the annotation on TPSParallelOnScreen interface.
    */
    HRESULT  TPSParallelOnScreen (out /*IDLRETVAL*/ CATIATPSParallelOnScreen  oTPSParallelOnScreen);
};

// Interface name : CATIANonSemanticGDT
#pragma ID CATIANonSemanticGDT "DCE:d55ebb76-a0ce-11d3-9c940008c725d79e"
#pragma DUAL CATIANonSemanticGDT

// VB object name : NonSemanticGDT
#pragma ID NonSemanticGDT "DCE:d55ebb76-a0ce-11d3-9c940008c725d79f"
#pragma ALIAS CATIANonSemanticGDT NonSemanticGDT

#endif
