
#ifndef CATIAFTASettingAtt_IDL
#define CATIAFTASettingAtt_IDL
/*IDLREP*/

// COPYRIGHT Dassault Systemes 2003

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIASettingController.idl"
#include "CATVariant.idl"
#include "CATSafeArray.idl"
#include "CATBSTR.idl"

enum CATFTADimConfigureSnapping
{
  CATFTADimSnappingUndefined, 
  CATFTADimSnappingOnGrid, 
  CATFTADimSnappingValue, 
  CATFTADimSnappingBoth
};

enum CATFTADimCreateOn
{
  CATFTADimCreateOnUndefined, 
  CATFTADimCreateOnCenter, 
  CATFTADimCreateOnEdge
};

// Putting your explanations in the following "JavaDoc"-like comment will enable mkdcidl to document your class.
/**  
 * The interface to access a CATIAFTASettingAtt.
 */
interface CATIAFTASettingAtt : CATIASettingController 
{
    /**
     * Returns or sets the Non SemanticAllways Upgrade parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY NonSemanticAllwaysUpgrade
   HRESULT get_NonSemanticAllwaysUpgrade(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_NonSemanticAllwaysUpgrade( in boolean iValue );

    /**
     * Locks or unlocks the Non Semantic Allways Upgrade parameter.
     */
     HRESULT SetNonSemanticAllwaysUpgradeLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Non Semantic Allways Upgrade setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetNonSemanticAllwaysUpgradeInfo ( inout CATBSTR AdminLevel,
                                               inout CATBSTR oLocked,
                                               out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Non Semantic Tol Allowed parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY NonSemanticTolAllowed
    HRESULT get_NonSemanticTolAllowed(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_NonSemanticTolAllowed( in boolean iValue );

    /**
     * Locks or unlocks the Non Semantic Tol Allowed parameter.
     */
     HRESULT SetNonSemanticTolAllowedLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Non Semantic Tol Allowed setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetNonSemanticTolAllowedInfo ( inout CATBSTR AdminLevel,
                                           inout CATBSTR oLocked,
                                           out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Non Semantic Dim Allowed parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY NonSemanticDimAllowed
    HRESULT get_NonSemanticDimAllowed(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_NonSemanticDimAllowed( in boolean iValue );

    /**
     * Locks or unlocks the Non Semantic Dim Allowed parameter.
     */
     HRESULT SetNonSemanticDimAllowedLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Non Semantic Dim Allowed setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetNonSemanticDimAllowedInfo ( inout CATBSTR AdminLevel,
                                           inout CATBSTR oLocked,
                                           out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Noa Creation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY NoaCreation
    HRESULT get_NoaCreation(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_NoaCreation( in boolean iValue );

    /**
     * Locks or unlocks the Noa Creation parameter.
     */
     HRESULT SetNoaCreationLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Noa Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetNoaCreationInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Non Semantic Marked parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY NonSemanticMarked
    HRESULT get_NonSemanticMarked(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_NonSemanticMarked( in boolean iValue );

    /**
     * Locks or unlocks the Non Semantic Marked parameter.
     */
     HRESULT SetNonSemanticMarkedLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Non Semantic Marked setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetNonSemanticMarkedInfo ( inout CATBSTR AdminLevel,
                                       inout CATBSTR oLocked,
                                       out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Rotation Snap Angle parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY RotationSnapAngle
    HRESULT get_RotationSnapAngle(out /*IDLRETVAL*/ double oValue);
     HRESULT put_RotationSnapAngle( in double iValue );

    /**
     * Locks or unlocks the Rotation Snap Angle parameter.
     */
     HRESULT SetRotationSnapAngleLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Rotation Snap Angle setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetRotationSnapAngleInfo ( inout CATBSTR AdminLevel,
                                       inout CATBSTR oLocked,
                                       out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Rotation Snap Auto parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY RotationSnapAuto
    HRESULT get_RotationSnapAuto(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_RotationSnapAuto( in boolean iValue );

    /**
     * Locks or unlocks the Rotation Snap Auto parameter.
     */
     HRESULT SetRotationSnapAutoLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Rotation Snap Auto setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetRotationSnapAutoInfo ( inout CATBSTR AdminLevel,
                                      inout CATBSTR oLocked,
                                      out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Parameters in tree parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY ParametersInTree
    HRESULT get_ParametersInTree(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_ParametersInTree( in boolean iValue );

    /**
     * Locks or unlocks the Parameters in tree parameter.
     */
     HRESULT SetParametersInTreeLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Parameters in tree setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetParametersInTreeInfo ( inout CATBSTR AdminLevel,
                                      inout CATBSTR oLocked,
                                      out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Shifted Profile parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY ShiftedProfile
    HRESULT get_ShiftedProfile(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_ShiftedProfile( in boolean iValue );

    /**
     * Locks or unlocks the Shifted Profile parameter.
     */
     HRESULT SetShiftedProfileLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Shifted Profile setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetShiftedProfileInfo ( inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Highlight Def Annot parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY HighlightDefAnnot
    HRESULT get_HighlightDefAnnot(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_HighlightDefAnnot( in boolean iValue );

    /**
     * Locks or unlocks the Highlight Def Annot parameter.
     */
     HRESULT SetHighlightDefAnnotLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Highlight Def Annot setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetHighlightDefAnnotInfo ( inout CATBSTR AdminLevel,
                                       inout CATBSTR oLocked,
                                       out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Over Run Creation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimORunCre
    HRESULT get_DimORunCre(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimORunCre( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Over Run Creation parameter.
     */
     HRESULT SetDimORunCreLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Over Run Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimORunCreInfo ( inout CATBSTR AdminLevel,
                                inout CATBSTR oLocked,
                                out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Over Run Modification parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimORunMod
    HRESULT get_DimORunMod(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimORunMod( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Over Run Modification parameter.
     */
     HRESULT SetDimORunModLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Over Run Modification setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimORunModInfo ( inout CATBSTR AdminLevel,
                                inout CATBSTR oLocked,
                                out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Blanking Creation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimBlankingCre
    HRESULT get_DimBlankingCre(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimBlankingCre( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Blanking Creation parameter.
     */
     HRESULT SetDimBlankingCreLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Blanking Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimBlankingCreInfo ( inout CATBSTR AdminLevel,
                                inout CATBSTR oLocked,
                                out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Blanking Modification parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimBlankingMod
    HRESULT get_DimBlankingMod(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimBlankingMod( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Blanking Modification parameter.
     */
     HRESULT SetDimBlankingModLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Blanking Modification setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimBlankingModInfo ( inout CATBSTR AdminLevel,
                                inout CATBSTR oLocked,
                                out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Before Creation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimBeforeCre
    HRESULT get_DimBeforeCre(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimBeforeCre( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Before Creation parameter.
     */
     HRESULT SetDimBeforeCreLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Before Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimBeforeCreInfo ( inout CATBSTR AdminLevel,
                                  inout CATBSTR oLocked,
                                  out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Before Modification parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimBeforeMod
    HRESULT get_DimBeforeMod(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimBeforeMod( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Before Modification parameter.
     */
     HRESULT SetDimBeforeModLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Before Modification setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimBeforeModInfo ( inout CATBSTR AdminLevel,
                                  inout CATBSTR oLocked,
                                  out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension After Creaation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimAfterCre
    HRESULT get_DimAfterCre(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimAfterCre( in boolean iValue );

    /**
     * Locks or unlocks the Dimension After Creaation parameter.
     */
     HRESULT SetDimAfterCreLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension After Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimAfterCreInfo ( inout CATBSTR AdminLevel,
                                  inout CATBSTR oLocked,
                                  out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension After Modification parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimAfterMod
    HRESULT get_DimAfterMod(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimAfterMod( in boolean iValue );

    /**
     * Locks or unlocks the Dimension After Modification parameter.
     */
     HRESULT SetDimAfterModLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension After Modification setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimAfterModInfo ( inout CATBSTR AdminLevel,
                                  inout CATBSTR oLocked,
                                  out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Move Value Creation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimMoveValueCre
    HRESULT get_DimMoveValueCre(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimMoveValueCre( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Move Value Creation parameter.
     */
     HRESULT SetDimMoveValueCreLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Move Value Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimMoveValueCreInfo ( inout CATBSTR AdminLevel,
                                     inout CATBSTR oLocked,
                                     out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Move Value Modification parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimMoveValueMod
    HRESULT get_DimMoveValueMod(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimMoveValueMod( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Move Value Modification parameter.
     */
     HRESULT SetDimMoveValueModLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Move Value Modification setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimMoveValueModInfo ( inout CATBSTR AdminLevel,
                                     inout CATBSTR oLocked,
                                     out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Move Dimension Line Creation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimMoveDimLineCre
    HRESULT get_DimMoveDimLineCre(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimMoveDimLineCre( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Move Dimension Line Creation parameter.
     */
     HRESULT SetDimMoveDimLineCreLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Move Dimension Line Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimMoveDimLineCreInfo ( inout CATBSTR AdminLevel,
                                       inout CATBSTR oLocked,
                                       out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Move Dimension Line Modification parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimMoveDimLineMod
    HRESULT get_DimMoveDimLineMod(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimMoveDimLineMod( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Move Dimension Line Modification parameter.
     */
     HRESULT SetDimMoveDimLineModLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Move Dimension Line Modification setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimMoveDimLineModInfo ( inout CATBSTR AdminLevel,
                                       inout CATBSTR oLocked,
                                       out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Move 2D Creation parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimMove2dPartCre
    HRESULT get_DimMove2dPartCre(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimMove2dPartCre( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Move 2D Creation parameter.
     */
     HRESULT SetDimMove2dPartCreLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Move 2D Creation setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimMove2dPartCreInfo ( inout CATBSTR AdminLevel,
                                      inout CATBSTR oLocked,
                                      out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Move 2D Modification parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimMove2dPartMod
    HRESULT get_DimMove2dPartMod(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimMove2dPartMod( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Move 2D Modification parameter.
     */
     HRESULT SetDimMove2dPartModLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Move 2D Modification setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimMove2dPartModInfo ( inout CATBSTR AdminLevel,
                                      inout CATBSTR oLocked,
                                      out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Orientation Default Symbol parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimOriDefaultSymb
    HRESULT get_DimOriDefaultSymb(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimOriDefaultSymb( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Orientation Default Symbol parameter.
     */
     HRESULT SetDimOriDefaultSymbLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Orientation Default Symbol setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimOriDefaultSymbInfo ( inout CATBSTR AdminLevel,
                                      inout CATBSTR oLocked,
                                      out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Line Up Base Length parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimLineUpBaseLength
    HRESULT get_DimLineUpBaseLength(out /*IDLRETVAL*/ double oValue);
     HRESULT put_DimLineUpBaseLength( in double iValue );

    /**
     * Locks or unlocks the Dimension Line Up Base Length parameter.
     */
     HRESULT SetDimLineUpBaseLengthLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Line Up Base Length setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimLineUpBaseLengthInfo ( inout CATBSTR AdminLevel,
                                         inout CATBSTR oLocked,
                                         out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Line Up Base Angle parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimLineUpBaseAngle
    HRESULT get_DimLineUpBaseAngle(out /*IDLRETVAL*/ double oValue);
     HRESULT put_DimLineUpBaseAngle( in double iValue );

    /**
     * Locks or unlocks the Dimension Line Up Base Angle parameter.
     */
     HRESULT SetDimLineUpBaseAngleLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Line Up Base Angle setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimLineUpBaseAngleInfo ( inout CATBSTR AdminLevel,
                                        inout CATBSTR oLocked,
                                        out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Line Up Stack parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimLineUpStack
    HRESULT get_DimLineUpStack(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimLineUpStack( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Line Up Stack parameter.
     */
     HRESULT SetDimLineUpStackLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Line Up Stack setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimLineUpStackInfo ( inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Line Up Cululated parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimLineUpCumul
    HRESULT get_DimLineUpCumul(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimLineUpCumul( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Line Up Cululated parameter.
     */
     HRESULT SetDimLineUpCumulLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Line Up Cululated setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimLineUpCumulInfo ( inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Line Up Funnel parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimLineUpFunnel
    HRESULT get_DimLineUpFunnel(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimLineUpFunnel( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Line Up Funnel parameter.
     */
     HRESULT SetDimLineUpFunnelLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Line Up Funnel setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimLineUpFunnelInfo ( inout CATBSTR AdminLevel,
                                     inout CATBSTR oLocked,
                                     out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Manual Positionning parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimManualPositionning
    HRESULT get_DimManualPositionning(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimManualPositionning( in boolean iValue );

    /**
     * Locks or unlocks the Manual Positionning parameter.
     */
     HRESULT SetDimManualPositionningLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Manual Positionning setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimManualPositionningInfo ( inout CATBSTR AdminLevel,
                                           inout CATBSTR oLocked,
                                           out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Constant Offset parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimConstantOffset
    HRESULT get_DimConstantOffset(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimConstantOffset( in boolean iValue );

    /**
     * Locks or unlocks the Constant Offset parameter.
     */
     HRESULT SetDimConstantOffsetLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Constant Offset setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimConstantOffsetInfo ( inout CATBSTR AdminLevel,
                                       inout CATBSTR oLocked,
                                       out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Line Position Value parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimLinePosValue
    HRESULT get_DimLinePosValue(out /*IDLRETVAL*/ double oValue);
     HRESULT put_DimLinePosValue( in double iValue );

    /**
     * Locks or unlocks the Dimension Line Position Value parameter.
     */
     HRESULT SetDimLinePosValueLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Line Position Value setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimLinePosValueInfo ( inout CATBSTR AdminLevel,
                                     inout CATBSTR oLocked,
                                     out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension Snapping parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimSnapping
    HRESULT get_DimSnapping(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimSnapping( in boolean iValue );

    /**
     * Locks or unlocks the Dimension Snapping parameter.
     */
     HRESULT SetDimSnappingLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension Snapping setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimSnappingInfo ( inout CATBSTR AdminLevel,
                                     inout CATBSTR oLocked,
                                     out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the DimMoveSubPart parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimMoveSubPart
    HRESULT get_DimMoveSubPart(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_DimMoveSubPart( in boolean iValue );

    /**
     * Locks or unlocks the DimMoveSubPart parameter.
     */
     HRESULT SetDimMoveSubPartLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the DimMoveSubPart setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimMoveSubPartInfo ( inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the DimConfigureSnapping parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimConfigureSnapping
    HRESULT get_DimConfigureSnapping(out /*IDLRETVAL*/ CATFTADimConfigureSnapping oValue);
     HRESULT put_DimConfigureSnapping( in CATFTADimConfigureSnapping iValue );

    /**
     * Locks or unlocks the DimConfigureSnapping parameter.
     */
     HRESULT SetDimConfigureSnappingLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the DimMoveSubPart setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimConfigureSnappingInfo ( inout CATBSTR AdminLevel,
                                          inout CATBSTR oLocked,
                                          out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the DimCreateOn parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY DimCreateOn
    HRESULT get_DimCreateOn(out /*IDLRETVAL*/ CATFTADimCreateOn oValue);
     HRESULT put_DimCreateOn( in CATFTADimCreateOn iValue );

    /**
     * Locks or unlocks the DimCreateOn parameter.
     */
     HRESULT SetDimCreateOnLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the DimCreateOn setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetDimCreateOnInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Non SemanticAllways Upgrade general tolerance parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY NonSemanticAllwaysUpgradeGeneralTol
    HRESULT get_NonSemanticAllwaysUpgradeGeneralTol(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_NonSemanticAllwaysUpgradeGeneralTol( in boolean iValue );

    /**
     * Locks or unlocks the Non Semantic Allways Upgrade general tolerance parameter.
     */
     HRESULT SetNonSemanticAllwaysUpgradeGeneralTolLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Non Semantic Allways Upgrade general tolerance setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetNonSemanticAllwaysUpgradeGeneralTolInfo ( inout CATBSTR AdminLevel,
                                                      inout CATBSTR oLocked,
                                                      out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension general class parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY GeneralTolClass
    HRESULT get_GeneralTolClass(out /*IDLRETVAL*/ long oValue);
     HRESULT put_GeneralTolClass( in long iValue );

    /**
     * Locks or unlocks the Dimension general class parameter.
     */
     HRESULT SetGeneralTolClassLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension general class tolerance setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetGeneralTolClassInfo ( inout CATBSTR AdminLevel,
                                     inout CATBSTR oLocked,
                                     out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Dimension general class parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY AngulaireGeneralTolClass
    HRESULT get_AngulaireGeneralTolClass(out /*IDLRETVAL*/ long oValue);
     HRESULT put_AngulaireGeneralTolClass( in long iValue );

    /**
     * Locks or unlocks the Dimension general class parameter.
     */
     HRESULT SetAngulaireGeneralTolClassLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Dimension general class tolerance setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetAngulaireGeneralTolClassInfo ( inout CATBSTR AdminLevel,
                                              inout CATBSTR oLocked,
                                              out  /*IDLRETVAL*/boolean oModified);


    /**
     * Returns or sets the Visibility of Part instances, bodies and geometrical sets in Capture.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY BodyHideInCapture
    HRESULT get_BodyHideInCapture(out /*IDLRETVAL*/ long oValue);
     HRESULT put_BodyHideInCapture( in long iValue );

    /**
     * Locks or unlocks the Dimension general class parameter.
     */
     HRESULT SetBodyHideInCaptureLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Visibility of Part instances, bodies and geometrical sets in Capture.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetBodyHideInCaptureInfo ( inout CATBSTR AdminLevel,
                                              inout CATBSTR oLocked,
                                              out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Slect Published Geometry parameter.
     * <p>
     * Ensure consistency with the C++ interface to which the work is delegated.
     */
#pragma PROPERTY SelectPublishedGeometry
    HRESULT get_SelectPublishedGeometry(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_SelectPublishedGeometry( in boolean iValue );

    /**
     * Locks or unlocks the Select Published Geometry parameter.
     */
     HRESULT SetSelectPublishedGeometryLock( in  boolean iLocked );

    /** 
    * Retrieves informations about the Select Published Geometry setting parameter value.
    * <br>Refer to @href CATIASettingController for a detailled description.
    */ 
    HRESULT GetSelectPublishedGeometryInfo (inout CATBSTR AdminLevel,
                                            inout CATBSTR oLocked,
                                            out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the Pattern of Visu setting parameter value.
     * <br><b>True</b> if the Pattern of Visu setting parameter is checked.
     * <br><b>Role</b>: When set to True, the FTA 3D Annotation representations are saved in CGR.
     * Otherwise, they are not saved.
     */
#pragma PROPERTY SectPattern
    HRESULT get_SectPattern(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_SectPattern(in boolean iValue);

  /** 
   * Locks or unlocks the Pattern of Visu setting parameter value.
   * <br>Refer to @href CATIASettingController for a detailed description.
   */
     HRESULT SetSectPatternLock( in  boolean iLocked );

  /** 
   * Retrieves informations about the Pattern of Visu setting parameter value.
   * <br>Refer to @href CATIASettingController for a detailled description.
  */ 
    HRESULT GetSectPatternInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);

    /**
     * Returns or sets the AlphabeticOrder setting parameter value.
     * <br><b>True</b> if the AlphabeticOrder setting parameter is checked.
     * <br><b>Role</b>: When set to True, the FTA 3D Annotation representations
     *  are saved in CGR. Otherwise, they are not saved.
     */
#pragma PROPERTY AlphabeticOrder
    HRESULT get_AlphabeticOrder(out /*IDLRETVAL*/ boolean oValue);
     HRESULT put_AlphabeticOrder(in boolean iValue);

  /** 
   * Locks or unlocks the AlphabeticOrder setting parameter value.
   * <br>Refer to @href CATIASettingController for a detailed description.
   */
     HRESULT SetAlphabeticOrderLock( in  boolean iLocked );

  /** 
   * Retrieves informations about the AlphabeticOrder setting parameter value.
   * <br>Refer to @href CATIASettingController for a detailled description.
  */ 
    HRESULT GetAlphabeticOrderInfo ( inout CATBSTR AdminLevel,
                                     inout CATBSTR oLocked,
                                     out  /*IDLRETVAL*/boolean oModified);

  /**
  * Get the Dimension leader Creation parameter.
  * @param oValue
  *   Output value of the Dimension Leader creation check box status.
  * If return code E_FAIL oValue is not obtained.
  * If return code S_OK oValue is obtained.
  * 
  */
 #pragma PROPERTY DimMoveLeaderCre
    HRESULT get_DimMoveLeaderCre(out /*IDLRETVAL*/ boolean oValue);

  /**
  * Returns sets the Dimension leader Creation parameter.
  * @param iValue
  *   Input value of the Dimension Leader creation check box status. 
  * If return code E_FAIL iValue is not set.
  * If return code S_OK iValue is set.
  *
  */
  HRESULT put_DimMoveLeaderCre( in boolean iValue );

  /**
  * Locks or unlocks the Dimension leader Creation parameter.
  * @param iLocked
  *   Input value of the Dimension leader creation check box lock/unlock status.
  * If return code E_FAIL iLocked is not set.
  * If return code S_OK iLocked is set.
  *
  */
  HRESULT SetDimMoveLeaderCreLock( in boolean iLocked );

  /** 
  * Retrieves informations about the Dimension leader Creation setting 
  * parameter value.
  * @param AdminLevel
  *   Input/Output parameter, is the administration level.
  * @param oLocked
  *   Input/Output parameter, is the lock status of the check button.
  * @param oModified
  *   Output paramter which gives the status as boolean if the status is modified.
  * If return code E_FAIL the values are not obtained.
  * If return code S_OK the values are obtained.
  * <br>Refer to @href CATIASettingController for a detailled description.
  *
  */ 
  HRESULT GetDimMoveLeaderCreInfo ( inout CATBSTR AdminLevel,
  inout CATBSTR oLocked,
  out /*IDLRETVAL*/boolean oModified);


  /**
  * Returns gets the Dimension leader modification parameter.
  * @param oValue
  *   Output value of the Dimension Leader modification check box status.
  * If return code E_FAIL oValue is not obtained.
  * If return code S_OK oValue is obtained.
  *
  */
  #pragma PROPERTY DimMoveLeaderMod
  HRESULT get_DimMoveLeaderMod(out /*IDLRETVAL*/ boolean oValue);

  /**
  * Returns sets the Dimension leader modification parameter.
  * @param iValue
  *   Input value of the Dimension Leader modification check box status.
  * If return code E_FAIL iValue is not set.
  * If return code S_OK iValue is set.
  *
  */
  HRESULT put_DimMoveLeaderMod( in boolean iValue );

  /**
  * Locks or unlocks the Dimension leader modification parameter.
  * @param iLocked
  *   Input value of the Dimension leader modification check box (lock/unlock).
  * If return code E_FAIL iLocked is not set.
  * If return code S_OK iLocked is set.
  */
  HRESULT SetDimMoveLeaderModLock( in boolean iLocked );

  /** 
  * Retrieves informations about the Dimension leader modification setting 
  * parameter value.
  * @param AdminLevel
  *   Input/Output parameter, is the administration level.
  * @param oLocked
  *   Input/Output parameter, is the lock status of the check button.
  * @param oModified
  *   Output paramter which gives the status as boolean if the status is modified.
  * If return code E_FAIL the values are not obtained.
  * If return code S_OK the values are obtained.
  * <br>Refer to @href CATIASettingController for a detailled description.
  */ 
  HRESULT GetDimMoveLeaderModInfo ( inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out /*IDLRETVAL*/boolean oModified);


  #pragma PROPERTY DimLineUpOffsetToRefLength
  /**
  * Returns gets the DimLineUpOffsetToRefLength parameter.
  * @param oValue
  *   Output value of the DimLineUpOffsetToRefLength.
  * If return code E_FAIL oValue is not obtained.
  * If return code S_OK oValue is obtained.
  *
  */
  HRESULT get_DimLineUpOffsetToRefLength(out /*IDLRETVAL*/ double oValue);

  /**
  * Returns sets the DimLineUpOffsetToRefLength modification parameter.
  * @param iValue
  *   Input value of the DimLineUpOffsetToRefLength.
  * If return code E_FAIL iValue is not set.
  * If return code S_OK iValue is set.
  *
  */
  HRESULT put_DimLineUpOffsetToRefLength(in double iValue);

  /**
  * Locks or unlocks the DimLineUpOffsetToRefLength parameter.
  * @param iLocked
  *   Input value of the DimLineUpOffsetToRefLength (lock/unlock).
  * If return code E_FAIL iLocked is not set.
  * If return code S_OK iLocked is set.
  */
  HRESULT SetDimLineUpOffsetToRefLengthLock(in boolean iLocked);

  /** 
  * Retrieves informations about the DimLineUpOffsetToRefLength setting 
  * parameter value.
  * @param AdminLevel
  *   Input/Output parameter, is the administration level.
  * @param oLocked
  *   Input/Output parameter, is the lock status of the check button.
  * @param oModified
  *   Output paramter which gives the status as boolean if the status is modified.
  * If return code E_FAIL the values are not obtained.
  * If return code S_OK the values are obtained.
  * <br>Refer to @href CATIASettingController for a detailled description.
  */ 
  HRESULT GetDimLineUpOffsetToRefLengthInfo(inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out /*IDLRETVAL*/boolean oModified);

#pragma PROPERTY DimLineUpOffsetToRefAngle
  /**
  * Returns gets the DimLineUpOffsetToRefAngle parameter.
  * @param oValue
  *   Output value of the DimLineUpOffsetToRefAngle.
  * If return code E_FAIL oValue is not obtained.
  * If return code S_OK oValue is obtained.
  *
  */
  HRESULT get_DimLineUpOffsetToRefAngle(out /*IDLRETVAL*/ double oValue);

  /**
  * Returns sets the DimLineUpOffsetToRefAngle modification parameter.
  * @param iValue
  *   Input value of the DimLineUpOffsetToRefAngle.
  * If return code E_FAIL iValue is not set.
  * If return code S_OK iValue is set.
  *
  */
  HRESULT put_DimLineUpOffsetToRefAngle(in double iValue);

  /**
  * Locks or unlocks the DimLineUpOffsetToRefAngle parameter.
  * @param iLocked
  *   Input value of the DimLineUpOffsetToRefAngle (lock/unlock).
  * If return code E_FAIL iLocked is not set.
  * If return code S_OK iLocked is set.
  */
  HRESULT SetDimLineUpOffsetToRefAngleLock(in boolean iLocked);

  /** 
  * Retrieves informations about the DimLineUpOffsetToRefAngle setting 
  * parameter value.
  * @param AdminLevel
  *   Input/Output parameter, is the administration level.
  * @param oLocked
  *   Input/Output parameter, is the lock status of the check button.
  * @param oModified
  *   Output paramter which gives the status as boolean if the status is modified.
  * If return code E_FAIL the values are not obtained.
  * If return code S_OK the values are obtained.
  * <br>Refer to @href CATIASettingController for a detailled description.
  */ 
  HRESULT GetDimLineUpOffsetToRefAngleInfo(inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out /*IDLRETVAL*/boolean oModified);

  #pragma PROPERTY DimLineUpOffsetBetDimLength
  /**
  * Returns gets the DimLineUpOffsetBetDimLength parameter.
  * @param oValue
  *   Output value of the DimLineUpOffsetBetDimLength.
  * If return code E_FAIL oValue is not obtained.
  * If return code S_OK oValue is obtained.
  *
  */
  HRESULT get_DimLineUpOffsetBetDimLength(out /*IDLRETVAL*/ double oValue);

  /**
  * Returns sets the DimLineUpOffsetBetDimLength modification parameter.
  * @param iValue
  *   Input value of the DimLineUpOffsetBetDimLength.
  * If return code E_FAIL iValue is not set.
  * If return code S_OK iValue is set.
  *
  */
  HRESULT put_DimLineUpOffsetBetDimLength(in double iValue);

  /**
  * Locks or unlocks the DimLineUpOffsetBetDimLength parameter.
  * @param iLocked
  *   Input value of the DimLineUpOffsetBetDimLength (lock/unlock).
  * If return code E_FAIL iLocked is not set.
  * If return code S_OK iLocked is set.
  */
  HRESULT SetDimLineUpOffsetBetDimLengthLock(in boolean iLocked);

  /** 
  * Retrieves informations about the DimLineUpOffsetBetDimLength setting 
  * parameter value.
  * @param AdminLevel
  *   Input/Output parameter, is the administration level.
  * @param oLocked
  *   Input/Output parameter, is the lock status of the check button.
  * @param oModified
  *   Output paramter which gives the status as boolean if the status is modified.
  * If return code E_FAIL the values are not obtained.
  * If return code S_OK the values are obtained.
  * <br>Refer to @href CATIASettingController for a detailled description.
  */ 
  HRESULT GetDimLineUpOffsetBetDimLengthInfo(inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out /*IDLRETVAL*/boolean oModified);

  #pragma PROPERTY DimLineUpOffsetBetDimAngle
  /**
  * Returns gets the DimLineUpOffsetBetDimAngle parameter.
  * @param oValue
  *   Output value of the DimLineUpOffsetBetDimAngle.
  * If return code E_FAIL oValue is not obtained.
  * If return code S_OK oValue is obtained.
  *
  */
  HRESULT get_DimLineUpOffsetBetDimAngle(out /*IDLRETVAL*/ double oValue);

  /**
  * Returns sets the DimLineUpOffsetBetDimAngle modification parameter.
  * @param iValue
  *   Input value of the DimLineUpOffsetBetDimAngle.
  * If return code E_FAIL iValue is not set.
  * If return code S_OK iValue is set.
  *
  */
  HRESULT put_DimLineUpOffsetBetDimAngle(in double iValue);

  /**
  * Locks or unlocks the DimLineUpOffsetBetDimAngle parameter.
  * @param iLocked
  *   Input value of the DimLineUpOffsetBetDimAngle (lock/unlock).
  * If return code E_FAIL iLocked is not set.
  * If return code S_OK iLocked is set.
  */
  HRESULT SetDimLineUpOffsetBetDimAngleLock(in boolean iLocked);

  /** 
  * Retrieves informations about the DimLineUpOffsetBetDimAngle setting 
  * parameter value.
  * @param AdminLevel
  *   Input/Output parameter, is the administration level.
  * @param oLocked
  *   Input/Output parameter, is the lock status of the check button.
  * @param oModified
  *   Output paramter which gives the status as boolean if the status is modified.
  * If return code E_FAIL the values are not obtained.
  * If return code S_OK the values are obtained.
  * <br>Refer to @href CATIASettingController for a detailled description.
  */ 
  HRESULT GetDimLineUpOffsetBetDimAngleInfo(inout CATBSTR AdminLevel,
                                    inout CATBSTR oLocked,
                                    out /*IDLRETVAL*/boolean oModified);

#pragma PROPERTY AnalysisDisplayMode 
    /** Returns the AnalysisDisplayMode parameter. */
    HRESULT get_AnalysisDisplayMode(out /*IDLRETVAL*/ boolean oValue);
    /** Sets the AnalysisDisplayMode parameter. */
    HRESULT put_AnalysisDisplayMode( in boolean iValue );
    /**
    * Locks or unlocks the AnalysisDisplayMode parameter.
    * <br><b>Role</b>:Locks or unlocks the AnalysisDisplayMode parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
    HRESULT SetAnalysisDisplayModeLock( in  boolean iLocked );

    /** 
    * Retrieves environment informations for the AnalysisDisplayMode parameter.
    * <br><b>Role</b>:Retrieves the state of the AnalysisDisplayMode parameter 
    * in the current environment. 
    * @param ioAdminLevel
    *       <br>If the parameter is locked, AdminLevel gives the administration
    *       level that imposes the value of the parameter.
    *	 <br>If the parameter is not locked, AdminLevel gives the administration
    *       level that will give the value of the parameter after a reset.
    * @param ioLocked
    *      Indicates if the parameter has been locked.
    * @return 
    *      Indicates if the parameter has been explicitly modified or remain
    *      to the administrated value.
    */
    HRESULT GetAnalysisDisplayModeInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);

#pragma PROPERTY AnnotDimOnDeletedGeom  
     /** Returns the AnnotDimOnDeletedGeom parameter. */
    HRESULT get_AnnotDimOnDeletedGeom (out /*IDLRETVAL*/ boolean oValue);
     /** Sets the AnnotDimOnDeletedGeom parameter. */
    HRESULT put_AnnotDimOnDeletedGeom ( in boolean iValue );
    /**
    * Locks or unlocks the AnnotDimOnDeletedGeom parameter.
    * <br><b>Role</b>:Locks or unlocks the AnnotDimOnDeletedGeom parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
     HRESULT SetAnnotDimOnDeletedGeomLock( in  boolean iLocked );

    /** 
    * Retrieves environment informations for the AnnotDimOnDeletedGeom parameter.
    * <br><b>Role</b>:Retrieves the state of the AnnotDimOnDeletedGeom parameter 
    * in the current environment. 
    * @param ioAdminLevel
    *       <br>If the parameter is locked, AdminLevel gives the administration
    *       level that imposes the value of the parameter.
    *	 <br>If the parameter is not locked, AdminLevel gives the administration
    *       level that will give the value of the parameter after a reset.
    * @param ioLocked
    *      Indicates if the parameter has been locked.
    * @return 
    *      Indicates if the parameter has been explicitly modified or remain
    *      to the administrated value.
    */
    HRESULT GetAnnotDimOnDeletedGeomInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);

  /** Returns the AnnotDimOnDeletedGeomColor parameter. */
  HRESULT GetAnnotDimOnDeletedGeomColor(out long oValueR, out long oValueG, out long oValueB);
  /** Sets the AnnotDimOnDeletedGeomColor parameter. */
  HRESULT SetAnnotDimOnDeletedGeomColor(in long	iValueR, in long	iValueG, in long	iValueB);
  /** 
	 * Retrieves environment informations for the AnnotDimOnDeletedGeomColor parameter.
	 * <br><b>Role</b>:Retrieves the state of the AnnotDimOnDeletedGeomColor parameter 
	 * in the current environment. 
	 * @param ioAdminLevel
	 *       <br>If the parameter is locked, AdminLevel gives the administration
	 *       level that imposes the value of the parameter.
	 *	 <br>If the parameter is not locked, AdminLevel gives the administration
	 *       level that will give the value of the parameter after a reset.
	 * @param ioLocked
	 *      Indicates if the parameter has been locked.
	 * @return 
	 *      Indicates if the parameter has been explicitly modified or remain
	 *      to the administrated value.
   */
  HRESULT GetAnnotDimOnDeletedGeomColorInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked,	out boolean	oModified);
  /**
   * Locks or unlocks the AnnotDimOnDeletedGeomColor parameter.
	 * <br><b>Role</b>:Locks or unlocks the AnnotDimOnDeletedGeomColor parameter if it is possible
	 * in the current administrative context. In user mode this method will always
	 * return E_FAIL.
	 * @param iLocked
	 *	the locking operation to be performed
	 *	<b>Legal values</b>:
	 *	<br><tt>TRUE :</tt>   to lock the parameter.
	 * 	<br><tt>FALSE:</tt>   to unlock the parameter.
   */
  HRESULT SetAnnotDimOnDeletedGeomColorLock(in boolean iLocked);

#pragma PROPERTY AnnotDimOnUnloadedGeom  
   /** Returns the AnnotDimOnUnloadedGeom parameter. */
    HRESULT get_AnnotDimOnUnloadedGeom (out /*IDLRETVAL*/ boolean oValue);
   /** Sets the AnnotDimOnUnloadedGeom parameter. */
    HRESULT put_AnnotDimOnUnloadedGeom ( in boolean iValue );

    /**
    * Locks or unlocks the AnnotDimOnUnloadedGeom parameter.
    * <br><b>Role</b>:Locks or unlocks the AnnotDimOnUnloadedGeom parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
     HRESULT SetAnnotDimOnUnloadedGeomLock( in  boolean iLocked );

     /** 
     * Retrieves environment informations for the AnnotDimOnUnloadedGeom parameter.
     * <br><b>Role</b>:Retrieves the state of the AnnotDimOnUnloadedGeom parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetAnnotDimOnUnloadedGeomInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);
    /** Returns the AnnotDimOnUnloadedGeomColor parameter. */
    HRESULT GetAnnotDimOnUnloadedGeomColor(out long oValueR, out long oValueG, out long oValueB);
    /** Sets the AnnotDimOnUnloadedGeomColor parameter. */
    HRESULT SetAnnotDimOnUnloadedGeomColor(in long	iValueR, in long	iValueG, in long	iValueB);
  /** 
	 * Retrieves environment informations for the AnnotDimOnUnloadedGeomColor parameter.
	 * <br><b>Role</b>:Retrieves the state of the AnnotDimOnUnloadedGeomColor parameter 
	 * in the current environment. 
	 * @param ioAdminLevel
	 *       <br>If the parameter is locked, AdminLevel gives the administration
	 *       level that imposes the value of the parameter.
	 *	 <br>If the parameter is not locked, AdminLevel gives the administration
	 *       level that will give the value of the parameter after a reset.
	 * @param ioLocked
	 *      Indicates if the parameter has been locked.
	 * @return 
	 *      Indicates if the parameter has been explicitly modified or remain
	 *      to the administrated value.
   */
  HRESULT GetAnnotDimOnUnloadedGeomColorInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked,	out boolean	oModified);
  /**
   * Locks or unlocks the AnnotDimOnUnloadedGeomColor parameter.
	 * <br><b>Role</b>:Locks or unlocks the AnnotDimOnUnloadedGeomColor parameter if it is possible
	 * in the current administrative context. In user mode this method will always
	 * return E_FAIL.
	 * @param iLocked
	 *	the locking operation to be performed
	 *	<b>Legal values</b>:
	 *	<br><tt>TRUE :</tt>   to lock the parameter.
	 * 	<br><tt>FALSE:</tt>   to unlock the parameter.
   */
  HRESULT SetAnnotDimOnUnloadedGeomColorLock(in boolean iLocked);

#pragma PROPERTY AnnotDimInvalid 
    /** Returns the AnnotDimInvalid parameter. */
    HRESULT get_AnnotDimInvalid (out /*IDLRETVAL*/ boolean oValue);
    /** Sets the AnnotDimInvalid parameter. */
    HRESULT put_AnnotDimInvalid ( in boolean iValue );

    /** 
    * Retrieves environment informations for the AnnotDimInvalid parameter.
    * <br><b>Role</b>:Retrieves the state of the AnnotDimInvalid parameter 
    * in the current environment. 
    * @param ioAdminLevel
    *       <br>If the parameter is locked, AdminLevel gives the administration
    *       level that imposes the value of the parameter.
    *	 <br>If the parameter is not locked, AdminLevel gives the administration
    *       level that will give the value of the parameter after a reset.
    * @param ioLocked
    *      Indicates if the parameter has been locked.
    * @return 
    *      Indicates if the parameter has been explicitly modified or remain
    *      to the administrated value.
   */
     HRESULT SetAnnotDimInvalidLock( in  boolean iLocked );

     /**
     * Locks or unlocks the AnnotDimInvalid parameter.
     * <br><b>Role</b>:Locks or unlocks the AnnotDimInvalid parameter if it is possible
     * in the current administrative context. In user mode this method will always
     * return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>TRUE :</tt>   to lock the parameter.
     * 	<br><tt>FALSE:</tt>   to unlock the parameter.
     */
    HRESULT GetAnnotDimInvalidInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);
    /** Returns the AnnotDimInvalidColor parameter. */
    HRESULT GetAnnotDimInvalidColor(out long oValueR, out long oValueG, out long oValueB);
    /** Sets the AnnotDimInvalidColor parameter. */
    HRESULT SetAnnotDimInvalidColor(in long	iValueR, in long	iValueG, in long	iValueB);
  /** 
	 * Retrieves environment informations for the AnnotDimInvalidColor parameter.
	 * <br><b>Role</b>:Retrieves the state of the AnnotDimInvalidColor parameter 
	 * in the current environment. 
	 * @param ioAdminLevel
	 *       <br>If the parameter is locked, AdminLevel gives the administration
	 *       level that imposes the value of the parameter.
	 *	 <br>If the parameter is not locked, AdminLevel gives the administration
	 *       level that will give the value of the parameter after a reset.
	 * @param ioLocked
	 *      Indicates if the parameter has been locked.
	 * @return 
	 *      Indicates if the parameter has been explicitly modified or remain
	 *      to the administrated value.
   */
  HRESULT GetAnnotDimInvalidColorInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked,	out boolean	oModified);
  /**
   * Locks or unlocks the AnnotDimInvalidColor parameter.
	 * <br><b>Role</b>:Locks or unlocks the AnnotDimInvalidColor parameter if it is possible
	 * in the current administrative context. In user mode this method will always
	 * return E_FAIL.
	 * @param iLocked
	 *	the locking operation to be performed
	 *	<b>Legal values</b>:
	 *	<br><tt>TRUE :</tt>   to lock the parameter.
	 * 	<br><tt>FALSE:</tt>   to unlock the parameter.
   */
  HRESULT SetAnnotDimInvalidColorLock(in boolean iLocked);

#pragma PROPERTY TrueDimension
    /** Returns the TrueDimension parameter. */
    HRESULT get_TrueDimension (out /*IDLRETVAL*/ boolean oValue);
   /** Sets the TrueDimension parameter. */
    HRESULT put_TrueDimension ( in boolean iValue );
    /**
    * Locks or unlocks the TrueDimension parameter.
    * <br><b>Role</b>:Locks or unlocks the TrueDimension parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
     HRESULT SetTrueDimensionLock( in  boolean iLocked );

     /** 
     * Retrieves environment informations for the TrueDimension parameter.
     * <br><b>Role</b>:Retrieves the state of the TrueDimension parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetTrueDimensionInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);
    /** Returns the TrueDimensionColor parameter. */
    HRESULT GetTrueDimensionColor(out long oValueR, out long oValueG, out long oValueB);
    /** Sets the TrueDimensionColor parameter. */
    HRESULT SetTrueDimensionColor(in long	iValueR, in long	iValueG, in long	iValueB);
  /** 
	 * Retrieves environment informations for the TrueDimensionColor parameter.
	 * <br><b>Role</b>:Retrieves the state of the TrueDimensionColor parameter 
	 * in the current environment. 
	 * @param ioAdminLevel
	 *       <br>If the parameter is locked, AdminLevel gives the administration
	 *       level that imposes the value of the parameter.
	 *	 <br>If the parameter is not locked, AdminLevel gives the administration
	 *       level that will give the value of the parameter after a reset.
	 * @param ioLocked
	 *      Indicates if the parameter has been locked.
	 * @return 
	 *      Indicates if the parameter has been explicitly modified or remain
	 *      to the administrated value.
   */
  HRESULT GetTrueDimensionColorInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked,	out boolean	oModified);
  /**
   * Locks or unlocks the TrueDimensionColor parameter.
	 * <br><b>Role</b>:Locks or unlocks the TrueDimensionColor parameter if it is possible
	 * in the current administrative context. In user mode this method will always
	 * return E_FAIL.
	 * @param iLocked
	 *	the locking operation to be performed
	 *	<b>Legal values</b>:
	 *	<br><tt>TRUE :</tt>   to lock the parameter.
	 * 	<br><tt>FALSE:</tt>   to unlock the parameter.
   */
  HRESULT SetTrueDimensionColorLock(in boolean iLocked);

#pragma PROPERTY AnnotOnZeroZSetting 
   /** Returns the AnnotOnZeroZSetting parameter. */
    HRESULT get_AnnotOnZeroZSetting (out /*IDLRETVAL*/ boolean oValue);
     /** Sets the AnnotOnZeroZSetting parameter. */
    HRESULT put_AnnotOnZeroZSetting ( in boolean iValue );
  /**
   * Locks or unlocks the AnnotOnZeroZSetting parameter.
	 * <br><b>Role</b>:Locks or unlocks the AnnotOnZeroZSetting parameter if it is possible
	 * in the current administrative context. In user mode this method will always
	 * return E_FAIL.
	 * @param iLocked
	 *	the locking operation to be performed
	 *	<b>Legal values</b>:
	 *	<br><tt>TRUE :</tt>   to lock the parameter.
	 * 	<br><tt>FALSE:</tt>   to unlock the parameter.
   */
     HRESULT SetAnnotOnZeroZSettingLock( in  boolean iLocked );

     /** 
     * Retrieves environment informations for the AnnotOnZeroZSetting parameter.
     * <br><b>Role</b>:Retrieves the state of the AnnotOnZeroZSetting parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetAnnotOnZeroZSettingInfo ( inout CATBSTR AdminLevel,
                                 inout CATBSTR oLocked,
                                 out  /*IDLRETVAL*/boolean oModified);

#pragma PROPERTY CATFTAChamferGeneralTolClass
    /** Returns the CATFTAChamferGeneralTolClass parameter. */
    HRESULT get_CATFTAChamferGeneralTolClass(out /*IDLRETVAL*/ long oValue);
    /** Sets the CATFTAChamferGeneralTolClass parameter. */
    HRESULT put_CATFTAChamferGeneralTolClass( in long iValue );
    /**
    * Locks or unlocks the CATFTAChamferGeneralTolClass parameter.
    * <br><b>Role</b>:Locks or unlocks the CATFTAChamferGeneralTolClass parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
     HRESULT SetCATFTAChamferGeneralTolClassLock( in  boolean iLocked );
     /** 
     * Retrieves environment informations for the CATFTAChamferGeneralTolClass parameter.
     * <br><b>Role</b>:Retrieves the state of the CATFTAChamferGeneralTolClass parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetCATFTAChamferGeneralTolClassInfo ( inout CATBSTR AdminLevel,
                                              inout CATBSTR oLocked,
                                              out  /*IDLRETVAL*/boolean oModified);

#pragma PROPERTY CATFTAUseLastTolerances
    /** Returns the CATFTAUseLastTolerances parameter. */
    HRESULT get_CATFTAUseLastTolerances(out /*IDLRETVAL*/ boolean oValue);
    /** Sets the CATFTAUseLastTolerances parameter. */
    HRESULT put_CATFTAUseLastTolerances( in boolean iValue );
    /**
    * Locks or unlocks the CATFTAUseLastTolerances parameter.
    * <br><b>Role</b>:Locks or unlocks the CATFTAUseLastTolerances parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
    HRESULT SetCATFTAUseLastTolerancesLock( in boolean iLocked );
     /** 
     * Retrieves environment informations for the CATFTAUseLastTolerances parameter.
     * <br><b>Role</b>:Retrieves the state of the CATFTAUseLastTolerances parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetCATFTAUseLastTolerancesInfo ( inout CATBSTR AdminLevel,
                                      inout CATBSTR oLocked,
                                      out /*IDLRETVAL*/boolean oModified);

    /** Returns the GetCATFTAEdgesColor parameter. */
    HRESULT GetCATFTAEdgesColor(out long oValueR, out long oValueG, out long oValueB);
    /** Sets the GetCATFTAEdgesColor parameter. */
    HRESULT SetCATFTAEdgesColor(in long	iValueR, in long	iValueG, in long	iValueB);
    /**
    * Locks or unlocks the GetCATFTAEdgesColor parameter.
    * <br><b>Role</b>:Locks or unlocks the GetCATFTAEdgesColor parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
    HRESULT SetCATFTAEdgesColorLock(in boolean iLocked);
     /** 
     * Retrieves environment informations for the GetCATFTAEdgesColor parameter.
     * <br><b>Role</b>:Retrieves the state of the GetCATFTAEdgesColor parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetCATFTAEdgesColorInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked,	out boolean	oModified);

#pragma PROPERTY CATFTAEdgesLineType
    /** Returns the CATFTAEdgesLineType parameter. */
    HRESULT get_CATFTAEdgesLineType(out /*IDLRETVAL*/long oValue);
    /** Sets the CATFTAEdgesLineType parameter. */
    HRESULT put_CATFTAEdgesLineType(in long iValue);
    /**
    * Locks or unlocks the CATFTAEdgesLineType parameter.
    * <br><b>Role</b>:Locks or unlocks the CATFTAEdgesLineType parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
  HRESULT SetCATFTAEdgesLineTypeLock(in boolean iLocked);
     /** 
     * Retrieves environment informations for the CATFTAEdgesLineType parameter.
     * <br><b>Role</b>:Retrieves the state of the CATFTAEdgesLineType parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetCATFTAEdgesLineTypeInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked,	out boolean	oModified);


#pragma PROPERTY CATFTAEdgesThickness
     /** Returns the CATFTAEdgesThickness parameter. */
    HRESULT get_CATFTAEdgesThickness(out /*IDLRETVAL*/long oValue);
     /** Sets the CATFTAEdgesThickness parameter. */
    HRESULT put_CATFTAEdgesThickness(in long iValue);
    /**
    * Locks or unlocks the CATFTAEdgesThickness parameter.
    * <br><b>Role</b>:Locks or unlocks the CATFTAEdgesThickness parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
    HRESULT SetCATFTAEdgesThicknessLock(in boolean iLocked);
     /** 
     * Retrieves environment informations for the CATFTAEdgesThickness parameter.
     * <br><b>Role</b>:Retrieves the state of the CATFTAEdgesThickness parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetCATFTAEdgesThicknessInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked,	out boolean	oModified);

#pragma PROPERTY CATFTAUFAutoTolerancing
    /** Returns the CATFTAUFAutoTolerancing parameter. */
    HRESULT get_CATFTAUFAutoTolerancing(inout /*IDLRETVAL*/CATBSTR oValue);
     /** Sets the CATFTAUFAutoTolerancing parameter. */
    HRESULT put_CATFTAUFAutoTolerancing(in CATBSTR iValue);
    /**
    * Locks or unlocks the CATFTAUFAutoTolerancing parameter.
    * <br><b>Role</b>:Locks or unlocks the CATFTAUFAutoTolerancing parameter if it is possible
    * in the current administrative context. In user mode this method will always
    * return E_FAIL.
    * @param iLocked
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>TRUE :</tt>   to lock the parameter.
    * 	<br><tt>FALSE:</tt>   to unlock the parameter.
    */
    HRESULT SetCATFTAUFAutoTolerancingLock(in boolean iLocked);
     /** 
     * Retrieves environment informations for the CATFTAUFAutoTolerancing parameter.
     * <br><b>Role</b>:Retrieves the state of the CATFTAUFAutoTolerancing parameter 
     * in the current environment. 
     * @param ioAdminLevel
     *       <br>If the parameter is locked, AdminLevel gives the administration
     *       level that imposes the value of the parameter.
     *	 <br>If the parameter is not locked, AdminLevel gives the administration
     *       level that will give the value of the parameter after a reset.
     * @param ioLocked
     *      Indicates if the parameter has been locked.
     * @return 
     *      Indicates if the parameter has been explicitly modified or remain
     *      to the administrated value.
     */
    HRESULT GetCATFTAUFAutoTolerancingInfo(inout CATBSTR ioAdminLevel, inout CATBSTR ioLocked, out boolean oModified);

};

// Interface name : CATIAFTASettingAtt
#pragma ID CATIAFTASettingAtt "DCE:eb742a1c-829a-4a7f-88541886cb04d0d5"
#pragma DUAL CATIAFTASettingAtt

// VB object name : FTASettingAtt (Id used in Visual Basic)
#pragma ID FTASettingAtt "DCE:7dcd166a-7449-471a-b757cd8498babf49"
#pragma ALIAS CATIAFTASettingAtt FTASettingAtt

#endif
