#ifndef CATIANonSemanticDatum_IDL
#define CATIANonSemanticDatum_IDL

// COPYRIGHT Dassault Systemes 2002

/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "CATIABase.idl"

/**
* Interface Managing Non Semantic Datum.
*/

interface CATIANonSemanticDatum : CATIABase
{
  /**
  * Retrieves or sets Label.
  */
#pragma PROPERTY Label
  HRESULT get_Label (inout /*IDLRETVAL*/ CATBSTR oLabel);
  HRESULT put_Label (in CATBSTR iLabel);

};

// Interface name : CATIANonSemanticDatum
#pragma ID CATIANonSemanticDatum "DCE:da80e0b6-a0ce-11d3-9c940008c725d79e"
#pragma DUAL CATIANonSemanticDatum

// VB object name : NonSemanticDatum
#pragma ID NonSemanticDatum "DCE:da80e0b6-a0ce-11d3-9c940008c725d79f"
#pragma ALIAS CATIANonSemanticDatum NonSemanticDatum

#endif
