// COPYRIGHT Dassault Systemes 2007
//===================================================================
//
// CATIEhfBundleSegmentLink.h
// Define the CATIEhfBundleSegmentLink interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  January 2007  Creation: Code generated by the CAA wizard  VEI
//===================================================================

/**
  * @CAA2Level L1
  * @CAA2Usage U3
  */

#ifndef CATIEhfBundleSegmentLink_h
#define CATIEhfBundleSegmentLink_h

#include "ExportedByCATEhfInterfaces.h"
#include "CATBaseUnknown.h"

// --- System Framework
#include "CATListOfCATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATEhfInterfaces IID IID_CATIEhfBundleSegmentLink;
#else
extern "C" const IID IID_CATIEhfBundleSegmentLink ;
#endif

//------------------------------------------------------------------

/**
 * This Interface allows user to retrieve the information of the Support and/or the Mechanical Part
 * through the Dashed Green Line.
 */

class ExportedByCATEhfInterfaces CATIEhfBundleSegmentLink: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

/**
 * Lists the Linked Mechanical Part through the Dashed Green Line.
 * @param opListMechanicalParts
 *     List of MechanicalParts retrieved through the Dashed Green Line.
 * @return
 *   An HRESULT value
 *   <br><b>Legal values</b>:
 *   <dl>
 *     <dt>S_OK</dt>
 *     <dd>List of MechanicalParts retrieved successfully</dd>
 *     <dt>E_FAIL </dt>
 *     <dd>An error occurred while retrieving List of MechanicalParts</dd>
 *   </dl>
 */

  virtual HRESULT ListLinkedMechanicalParts(CATListValCATBaseUnknown_var *& opListMechanicalParts) = 0 ;


/**
 * Lists the Linked Supports through the Dashed Green Line.
 * @param opListSupports
 *     List of Supports retrieved through the Dashed Green Line.
 * @return
 *   An HRESULT value
 *   <br><b>Legal values</b>:
 *   <dl>
 *     <dt>S_OK</dt>
 *     <dd>List of Supports retrieved successfully</dd>
 *     <dt>E_FAIL </dt>
 *     <dd>An error occurred while retrieving List of Supports</dd>
 *   </dl>
 */

  virtual HRESULT ListLinkedSupports(CATListValCATBaseUnknown_var *& opListSupports) = 0 ;

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif


