#
BUILT_OBJECT_TYPE=LOAD MODULE
#
#OS = COMMON
PROGRAM_NAME = CATVersion
#
LINK_WITH = JS0LIB0 NS0SI18N CXINSTDATA
OS = AIX
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"'
OS = HP-UX
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"'
OS = IRIX
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"'
OS = SunOS
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"'
OS = Windows_NT
RD=\"$(RELEASE_STARTDATE)\"
LOCAL_CCFLAGS= /D RELEASE_STARTDATE=$(RD)

