// COPYRIGHT DASSAULT SYSTEMES 2000
/**
* @CAA2Level L1
* @CAA2Usage U1
*/
//===================================================================
//
// CATIEhiBundleSegmentDef.h
// 
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2001  Creation: Code generated by the CAA wizard  TDS
//===================================================================
#ifndef CATEhiBundleSegmentDef_H
#define CATEhiBundleSegmentDef_H

/**
* Insertion mode.
* @param catEhiInsertBefore
*   Insertion before the given point.
* @param catEhiInsertAfter
*   Insertion after the given point.
*/
enum CatEhiInsertMode  { catEhiInsertBefore, catEhiInsertAfter };


/**
* Direction of entrance ofthe Branchable or Bundle Segment in the support.
* @param catEhiDirectMode
*   Entrance in direct mode.  
* @param catEhiInvertMode
*   Entrance in inverse mode.
*/

enum CatEhiSupportMode { catEhiDirectMode, catEhiInvertMode };

/**
* @nodoc
*/
enum CatEhiDeleteMode  { catEhiKeep, catEhiNoKeep };

/**
* @nodoc
*/
enum CatEhiLinkMode    { catEhiKeepLink, catEhiBreakLink, catEhiUsePrtSetting };

#endif

