#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=NONE
INCLUDED_MODULES=CATVisShader

LINK_WITH = JS0MRSHL JS0CORBA JS0SCBAK JS0FM JS0ERROR JS0STR JS03TRA \
CO0LSTPV CO0HTAB VE0FONT VE0PIX NS0S3STR YN000MFL \
YN000MAT YN000M2D VE0HLR VE0LOD CATVizIterators CATLightXml

OS = aix_a
LOCAL_CCFLAGS = -qfloat=hsflt  -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXt -lXi -lX11

OS = aix_a64
LOCAL_CCFLAGS = -qfloat=hsflt -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = HP-UX
LOCAL_CCFLAGS = -I/opt/graphics/OpenGL/include -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = IRIX
SYS_LIBS = -lXm -lXt -lX11 -lXext
LOCAL_CCFLAGS  = -float -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS   = -float

OS = SunOS
OPTIMIZATION_CPP = -xO4
SYS_LIBS = -lXm -lXt -lXi -lX11
LOCAL_CFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS -xlibmil

## @linux mcf 2004-05-13.11:14:31 [Linux support] ##
OS = Linux
SYS_LIBS = -lXm -lXt -lXi -lX11
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION

OS = Windows_NT
SYS_LIBS = vfw32.lib wsock32.lib winmm.lib
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION

OS = intel_a
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE

OS = win_b
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE

OS = win_b64
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE

OS = intel_a64
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE

OS = alpha_a
LOCAL_CCFLAGS = -D_WNT40A_SOURCE
LOCAL_CFLAGS  = -D_WNT40A_SOURCE
