/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchAppCntrFlow_h
#define CATIASchAppCntrFlow_h

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATIABase.h"
#include "CatSchIDLCntrFlowCapability.h"
#include "CatSchIDLCntrFlowReality.h"

extern ExportedByCATSchematicPubIDL IID IID_CATIASchAppCntrFlow;

class ExportedByCATSchematicPubIDL CATIASchAppCntrFlow : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AppGetFlowCapability(CatSchIDLCntrFlowCapability & oEFlowCapability)=0;

    virtual HRESULT __stdcall AppSetFlowCapability(CatSchIDLCntrFlowCapability iEFlowCapability)=0;

    virtual HRESULT __stdcall AppGetFlowReality(CatSchIDLCntrFlowReality & oEFlowReality)=0;

    virtual HRESULT __stdcall AppSetFlowReality(CatSchIDLCntrFlowReality iEFlowReality)=0;


};

CATDeclareHandler(CATIASchAppCntrFlow, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
