/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchAppCompatible_h
#define CATIASchAppCompatible_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"

class CATIASchListOfObjects;

extern ExportedByCATSchematicPubIDL IID IID_CATIASchAppCompatible;

class ExportedByCATSchematicPubIDL CATIASchAppCompatible : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AppIsTargetOKForRoute(const CATBSTR & iRouteCntrClassType, CATIASchListOfObjects *& oLOKCntrs, CAT_VARIANT_BOOL & oBYes)=0;

    virtual HRESULT __stdcall AppIsTargetOKForPlace(CATIASchListOfObjects * iLCompSourceCntrs, CATIASchListOfObjects *& oLTargetCntrs, CAT_VARIANT_BOOL & oBYes)=0;

    virtual HRESULT __stdcall AppIsTargetOKForInsert(CATIASchListOfObjects * iLCompSourceCntrs, CATIASchListOfObjects *& oLSourceCntrs, CAT_VARIANT_BOOL & oBYes)=0;


};

CATDeclareHandler(CATIASchAppCompatible, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
