/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchGRRComp_h
#define CATIASchGRRComp_h

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATIABase.h"
#include "CATSafeArray.h"

class CATIASchListOfDoubles;

extern ExportedByCATSchematicPubIDL IID IID_CATIASchGRRComp;

class ExportedByCATSchematicPubIDL CATIASchGRRComp : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetTransformation2D(CATIASchListOfDoubles *& oDb6TransMatrix)=0;

    virtual HRESULT __stdcall SetTransformation2D(const CATSafeArrayVariant & iDb6TransMatrix)=0;

    virtual HRESULT __stdcall GetScale(double & oDb1ScaleFactor)=0;

    virtual HRESULT __stdcall SetScale(double iDb1ScaleFactor)=0;

    virtual HRESULT __stdcall GetPosition(CATIASchListOfDoubles *& oDb2Position)=0;

    virtual HRESULT __stdcall SetPosition(const CATSafeArrayVariant & oDb2Position)=0;

    virtual HRESULT __stdcall GetRotationAngle(double & oDb1RotationAngleInRad)=0;

    virtual HRESULT __stdcall SetRotationAngle(double iDb1RotationAngleInRad)=0;


};

CATDeclareHandler(CATIASchGRRComp, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
