/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchCntrGraphic_h
#define CATIASchCntrGraphic_h

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATIABase.h"

class CATIASchGRR;
class CATIASchListOfObjects;

extern ExportedByCATSchematicPubIDL IID IID_CATIASchCntrGraphic;

class ExportedByCATSchematicPubIDL CATIASchCntrGraphic : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddGraphicalPrimitive(CATIASchGRR * iGRRToAdd, CATIASchGRR * iGRR)=0;

    virtual HRESULT __stdcall RemoveGraphicalPrimitive(CATIASchGRR * iGRRToRemove)=0;

    virtual HRESULT __stdcall ListGraphicalPrimitives(CATIASchListOfObjects *& oLGRR)=0;


};

CATDeclareHandler(CATIASchCntrGraphic, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
