/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchComponent2_h
#define CATIASchComponent2_h

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATIABase.h"
#include "CATSafeArray.h"

class CATIADocument;
class CATIASchAppConnectable;
class CATIASchComponent;
class CATIASchGRRComp;

extern ExportedByCATSchematicPubIDL IID IID_CATIASchComponent2;

class ExportedByCATSchematicPubIDL CATIASchComponent2 : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall PlaceInSpace(CATIASchGRRComp * iGRR, const CATSafeArrayVariant & iDb6Axis, CATIADocument * iDoc, CATIASchComponent *& oNewComponent)=0;

    virtual HRESULT __stdcall PlaceOnObject(CATIASchGRRComp * iGRR, const CATSafeArrayVariant & iDb6Axis, CATIASchAppConnectable * iObjectToConnect, CATIADocument * iDoc, CATIASchComponent *& oNewComponent)=0;


};

CATDeclareHandler(CATIASchComponent2, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
