/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchAppGroup_h
#define CATIASchAppGroup_h

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"

class CATIASchListOfObjects;

extern ExportedByCATSchematicPubIDL IID IID_CATIASchAppGroup;

class ExportedByCATSchematicPubIDL CATIASchAppGroup : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall ListZones(const CATBSTR & iClassType, CATIASchListOfObjects *& oLZones)=0;


};

CATDeclareHandler(CATIASchAppGroup, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
