/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchInternalFlow_h
#define CATIASchInternalFlow_h

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATIABase.h"
#include "CatSchIDLInternalFlowStatus.h"
#include "CatSchIDLInternalFlowType.h"

class CATIASchListOfObjects;

extern ExportedByCATSchematicPubIDL IID IID_CATIASchInternalFlow;

class ExportedByCATSchematicPubIDL CATIASchInternalFlow : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetInsertionType(CatSchIDLInternalFlowType & oEInternalFlowType)=0;

    virtual HRESULT __stdcall GetStatus(CatSchIDLInternalFlowStatus & oEInternalFlowStatus)=0;

    virtual HRESULT __stdcall SetStatus(CatSchIDLInternalFlowStatus iEInternalFlowStatus)=0;

    virtual HRESULT __stdcall ListSchConnectors(CATIASchListOfObjects *& oLSchCntrs)=0;


};

CATDeclareHandler(CATIASchInternalFlow, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
