/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASchZoneGraphic_h
#define CATIASchZoneGraphic_h

#ifndef ExportedByCATSchematicPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATSchematicPubIDL
#define ExportedByCATSchematicPubIDL __declspec(dllexport)
#else
#define ExportedByCATSchematicPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATSchematicPubIDL
#endif
#endif

#include "CATIABase.h"

class CATIASchGRRZone;
class CATIASchListOfObjects;

extern ExportedByCATSchematicPubIDL IID IID_CATIASchZoneGraphic;

class ExportedByCATSchematicPubIDL CATIASchZoneGraphic : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddGraphicalRepresentation(CATIASchGRRZone * iGRRToAdd)=0;

    virtual HRESULT __stdcall RemoveGraphicalRepresentation(CATIASchGRRZone * iGRRToRemove)=0;

    virtual HRESULT __stdcall ListGraphicalRepresentations(CATIASchListOfObjects *& oLGRR)=0;


};

CATDeclareHandler(CATIASchZoneGraphic, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
