/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatSchIDLDisplayMode_h
#define CatSchIDLDisplayMode_h

enum CatSchIDLDisplayMode {
        catSchIDLDisplayMode_Default,
        catSchIDLDisplayMode_Alternate
};

#endif
