/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatSchIDLRouteMode_h
#define CatSchIDLRouteMode_h

enum CatSchIDLRouteMode {
        catSchIDLRouteMode_Undefined,
        catSchIDLRouteMode_HorizontalVertical,
        catSchIDLRouteMode_HorizontalVertical45,
        catSchIDLRouteMode_PointToPoint,
        catSchIDLRouteMode_AroundObject
};

#endif
