#
# Imakefile to build FMSELECT.m
#

BUILT_OBJECT_TYPE=NONE

LINK_WITH= CO0LSTST ON0GRAPH ON0MAIN ON0FRAME CD0EDIT JS0CORBA JS0FM JS0SCBAK JS03TRA JS0STR CO0LSTPV DI0PANV2 \
	VE0MDL VE0BASE VE0GRPH2 CD0FRAME CD0WIN DI0APPLI DI0STATE NS0S3STR AD0XXBAS YP00IMPL

OS = IRIX

LOCAL_CCFLAGS = -G0
LOCAL_LDFLAGS =  -G0

