OS = COMMON
BUILT_OBJECT_TYPE = SHARED LIBRARY
LINK_WITH = GUIDVPMServices\
            AD0XXBAS ObjectModeler \
            JS0SETT JS0CORBA JS0SCBAK JS03TRA JS0LIB0 JS0ERROR JS0STR \
            CO0LSTPV CO0LSTST CO0HTAB CATXMLParserItf \ 
            NS0S3STR NS0S1MSG GUIDVPMInterfaces
