#
BUILT_OBJECT_TYPE = SHARED LIBRARY
INCLUDED_MODULES = CDMAServer
#
OS = COMMON

LINK_WITH=	JS0FM AD0XXBAS CATObjectSpecsModeler \
			PR0BASE CO0LSTPV \
			CD0FRAME DI0PANV2 \
			CDMAMapping CDMA_PS_MAPPING\
			CATCinDispatcher CATPDMBase CATVPMBase CDMAdoc \
			CATPDMBaseItf CATPDMItfOld CATPDMBaseUI CDMAInteroperabilityUUID CATCinProdStructInterop VE0MDL \
			 
