#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ElecRoutingItfUUID
#else
LINK_WITH_FOR_IID =
#endif

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0CORBA JS0LOGRP CD0VWTLB


