# 
IMPACT_ON_IMPORT = YES
#
BUILT_OBJECT_TYPE = NONE
#
COMDYN_MODULE = V4SysCOMD
#
DUMMY_LINK_WITH = CATAIXTools CATIAEntity CATIAMAO  CATIAUDB2 \
        CATAIXEngine CATUNITools CATUNITEngine CATV4DataAdmin \
        V4SysLMCALL V4SysANL V4SysENV V4SysMEM V4SysUTIL V4SysFILE V4SysB \
        AC0CATPL JS0CORBA
#
#
OS = COMMON
LINK_WITH = $(DUMMY_LINK_WITH)
SYS_LIBPATH = 

OS = AIX
SYS_LIBS = -lxlf -lxlf90 -lxlfpad

OS = IRIX
LINK_WITH = $(COMDYN_MODULE) $(DUMMY_LINK_WITH)
SYS_LIBS = -lftn

OS = Windows_NT
#if (defined MK_MSCVER) && (MK_MSCVER < 1400)
SYS_LIBS = DFORDLL.LIB
#endif

OS = HP-UX
SYS_LIBS = -lf

OS = SunOS
SYS_LIBS = -lF77
SYS_LIBPATH =
