# COPYRIGHT DASSAULT SYSTEMES 2003
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=JS0GROUP

BUILD=NO

OS = Windows_NT
BUILD=YES
LOCAL_CCFLAGS = /D_WIN32_WINNT=0x500 -I"$(MkmkADDON_INCLUDE)" -I"$(MkmkMSVCSHARPDIR)"
SYS_LIBS = mscoree.lib

