#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
#BUILD=NO
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = \
          JS0GROUP CATApplicationFrame CATObjectModelerBase \
JS0FM AD0XXBAS KnowledgeInterfacesUUID 
# END WIZARD EDITION ZONE

LINK_WITH=$(LINK_WITH_FOR_IID)  $(WIZARD_LINK_MODULES) \
    KnowledgeItf
