//===================================================================
// COPYRIGHT Dassault Systemes 2018
//===================================================================
// CATCciFiberMeshGeometryParameterAdapter.cpp
// Header definition of class CATCciFiberMeshGeometryParameterAdapter
//===================================================================
//
// Usage notes:
//	Adapter for CATICciFiberMeshGeometryParameter interface
//
//===================================================================
//  2018/05/24 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CATCciFiberMeshGeometryParameterAdapter_H
#define CATCciFiberMeshGeometryParameterAdapter_H

/**
* @CAA2Level L0
* @CAA2Usage U2
*/

#include "CATICciFiberMeshGeometryParameter.h"

#include "CAACompositesItf.h"
#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------
class ExportedByCAACompositesItf CATCciFiberMeshGeometryParameterAdapter : public CATICciFiberMeshGeometryParameter
{
public:
	// Standard constructors and destructors
	// -------------------------------------
	CATCciFiberMeshGeometryParameterAdapter();
	virtual ~CATCciFiberMeshGeometryParameterAdapter();


	// CATICciFiberMeshGeometryParameter methods
public:
	virtual short GetGeometricalCheckToSkip(const CATUnicodeString & iusPropagationType);


private:
	// Copy constructor and equal operator
	// -----------------------------------
	CATCciFiberMeshGeometryParameterAdapter(CATCciFiberMeshGeometryParameterAdapter &);
	CATCciFiberMeshGeometryParameterAdapter& operator=(CATCciFiberMeshGeometryParameterAdapter&);

	//-----------------------------------------------------------------------
};
#endif
