#ifndef CATICciNumAnalysisOper_H
#define CATICciNumAnalysisOper_H

// COPYRIGHT Dassault Systemes 2008
//===================================================================
//
//
//  
// CATICciNumAnalysisOper.h
// Define the CATICciNumAnalysisOper interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jul 2008  Creation: Code generated by the CAA wizard  NAU
//===================================================================

/**
  * @CAA2Level L0
  * @CAA2Usage U3
*/ 
#include "CAACompositesItf.h"
#include "CATBaseUnknown.h"
#include "CATLISTV_CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCAACompositesItf IID IID_CATICciNumAnalysisOper;
#else
extern "C" const IID IID_CATICciNumAnalysisOper ;
#endif

//------------------------------------------------------------------

/**
* Interface representing Numerical analysis operator.
* <b>Role</b>: This interface allows you to do analysis on Plies.
* <p>Note</p>
* <br>the following data type is created to store the results of the numerical analysis. check GetResult() method.
* the user needs to take care of creating & deleting this data type.
*/
struct CATCciNumericalAnalData
{
	double area;
	double volume;
	double volumicMass;
	double aerialMass;
	double cogX;
	double cogY;
	double cogZ;
	double cost;
};

/**
* Interface representing Numerical analysis operator.
* <b>Role</b>: This interface allows you to do analysis on Plies.
* <p>Note</p>
* <br>the following data type is created to store the results of the numerical analysis. check GetResult() method.
* the user needs to take care of creating & deleting this data type.
*/
class ExportedByCAACompositesItf CATICciNumAnalysisOper: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

     /**
	 * sets the plies for analysis
	 * @param iListOfPlies
	 *    The list of plies on which analysis calculation will be carried out.
	 */
	  virtual HRESULT SetPlies( CATLISTV(CATBaseUnknown_var)& iListOfPlies ) = 0;

	  /**
	 * sets the boolean which decides whether cutpieces(if any) of the plies needs to be consider or not.
	 * @param iTakeCutPieceIntoAccount
	 *    if this boolean is TRUE, cutpieces(if any) present in the plies(set by SetPlies) will be taken in to account
     *	     for calculation. Its corresponding ply will be neglected.
	 *    but if the boolean is FALSE, only plies(set by SetPlies) will be considered for calculation and never mind about
	 *        the cutpieces.
	 */
	  virtual HRESULT CutPieceOption( CATBoolean iTakeCutPieceIntoAccount ) = 0;

	  /**
	 * gets the results of the numerical calculation.
	 * @param oNumAnalData
	 *    an output data which contains summed up values of area,volume,volumic Mass,aerial mass & cost of all the plies
	 *    Also the same data contains the resultant values of X,Y,Z co-ordinate of the centre of gravity of the plies.
	 *    It is user's responsibility to create data(oNumAnalData) pointer by using new operator.Also the user needs to delete the pointer.
	 */
	  virtual HRESULT GetResult( CATCciNumericalAnalData* oNumAnalData ) = 0;
};

CATDeclareHandler(CATICciNumAnalysisOper, CATBaseUnknown);
//------------------------------------------------------------------

#endif
