// COPYRIGHT Dassault Systemes 2008
//===================================================================
//
// CATICciFiberAdvOperator.h
// Define the CATICciFiberAdvOperator interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Apr 2008  Creation: Code generated by the CAA wizard  PEY
//===================================================================
#ifndef CATICciFiberAdvOperator_H
#define CATICciFiberAdvOperator_H
/**
* @CAA2Level L0
* @CAA2Usage U5
*/
#include "CAACompositesItf.h"
#include "CATBaseUnknown.h"
#include "CATListOfCATUnicodeString.h"
#include "CATListOfInt.h"


#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCAACompositesItf IID IID_CATICciFiberAdvOperator;
#else
extern "C" const IID IID_CATICciFiberAdvOperator ;
#endif

class CATISpecObject_var;
//------------------------------------------------------------------

/**
 * AnalysisMode .
 */ 
enum CompAnalysisMode {Deviation=1, Deformation=2, Other=3 };
/**
 * Interface representing fiber init. 
 * <br><b>Role</b>: This is enhancement of CATICciFiberAdvOperator  
 * @href CATICciFiberMeshOperator 
 */
class ExportedByCAACompositesItf CATICciFiberAdvOperator: public CATBaseUnknown
{
  CATDeclareInterface;


   public:    
	

    // GET CONFIGURATION DATA 

	/**
	* Gets the list of Fiberinit types handled by the operator.
	* <br> WARNING: The name is stored in the producibility parameters feature. 
	*		          Once released the name should NEVER change!
	* @param oListOfFiberTypes
	*	List of Fiber types handled by operator
	* @param oListOfNLSFiberTypes
	*	List of  NLS Fiber types handled by operator - Use to  interactive dialog box 
	*/
	virtual void GetListOfFiberinitTypes(CATListOfCATUnicodeString & oListOfFiberTypes,
        CATListOfCATUnicodeString & oListOfNLSFiberTypes) = 0;



    // GET ANALYSIS DEFORMATION  AND OTHER Types 

    /**
    * Gets the list of available Analysis Deformation Types handled by the operator.
    * <br> WARNING: The name is stored in the producibility parameters feature. 
    *		          Once released the name should NEVER change!
    * @param oListOfAnalysisDefTypes
    *	List of analysis deformation  types handled by operator
    * @param oListOfNLSAnalysisDefTypes
    *	List of  NLS analysis deformation handled by operator - Use to  interactive dialog box 
    */
    virtual void GetListOfAnalysisDeformationTypes (CATListOfCATUnicodeString & oListOfAnalysisDefTypes,
        CATListOfCATUnicodeString & oListOfNLSAnalysisDefTypes) = 0;

    /**
    * Gets the list of available Analysis Other Types handled by the operator.
    * <br> WARNING: The name is stored in the producibility parameters feature. 
    *		          Once released the name should NEVER change!
    * @param oListOfAnalysisOtherTypes
    *	List of analysis Other  types handled by operator
    * @param oListOfNLSAnalysisOtherTypes
    *	List of  NLS analysis Other handled by operator - Use to  interactive dialog box 
    */
    virtual void GetListOfAnalysisOtherTypes (CATListOfCATUnicodeString & oListOfAnalyseOtherTypes,
        CATListOfCATUnicodeString & oListOfNLSAnalysisOtherTypes) = 0;


    // SET Sector Activation State 
  
    /** 		
	* Sets Sector Activation State. 
    * @param  iListOfSectorActivationState 
	*		List (which the size is equal to the number of sectors) of the activation state value of the sectors
    */
    virtual HRESULT    SetSectorActivationState   (CATListOfInt & iListOfSectorActivationState)  = 0 ;


    // SET PRODUCIBILITY BASE FEATURE 
  
    /** 		
	* Sets Producibility feature. 
    * @param  spProducibility 
	*		Producibility Feature associated to Mesh Operator 
    */
    virtual HRESULT    SetFiberProducibilityFeature   (const CATISpecObject_var spProducibility)  = 0 ;
        
    
    // SET ANALYSIS PARAMETERS 
    
    /** 		
	* Sets Fiber Analysis Mode. 
    * @param iMode 
	*		Type of requested analysis Deformatiomn/Deviation/Other 
    */
	virtual HRESULT  SetFiberAnalysisMode (const CompAnalysisMode  iAnaType) = 0;


   // GET  RESULT 
    
    /** 		
	* Gets Analysis colorized info result 
    * @param oTypeOfAnalysis 
	*		Retruns type of colorized data infos 
    * @param oNbColorInfos 
	*		Number of Color array info = Nb points for Fibetr Mesh 
     * @param oListOfColorU
	*		Array of Int for Color information in U ( from PointIndex to Point PlusU)
     * @param oListOfColorV
     *		Array of Int for Color information in V ( from PointIndex to Point PlusV)
    */
	virtual HRESULT  GetsFiberMeshColorResult (CATUnicodeString &oTypeOfAnalysis,
        int &oNbColorInfos,  CATListOfInt  & oListOfColorU,CATListOfInt  & oListOfColorV) = 0;


  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};
CATDeclareHandler(CATICciFiberAdvOperator, CATBaseUnknown);
//------------------------------------------------------------------

#endif
