//===================================================================
// COPYRIGHT DASSAULT SYSTEMES 2012/07/31
//===================================================================
// CATICciGridCellProperties.cpp
// Header definition of class CATICciGridCellProperties
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2012/07/31 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef CATICciGridCellProperties_H
#define CATICciGridCellProperties_H
/**
* @CAA2Level L0
* @CAA2Usage U5
*/
#include "CAACompositesItf.h"
#include "CATBaseUnknown.h"


extern ExportedByCAACompositesItf  IID IID_CATICciGridCellProperties ;

/**
* Interface representing  Gird cell properties 
* <b>Role</b>: Allows to identify properties associated to the grid cells 
*/
class ExportedByCAACompositesItf CATICciGridCellProperties: public CATBaseUnknown
{
    CATDeclareInterface;

public:

    /**
    * Sets a color property associated to the cell.
    * @param iRed 
    *    Red (0-255)
    * @param iGreen 
    *    Red (0-255)
    * @param iBlue 
    *    Red (0-255)
    */
    virtual HRESULT SetColor (unsigned int iRed, unsigned int iGreen, unsigned int iBlue) = 0;

    /**
    * Gets a color property associated to the cell.
    * @param oRed 
    *    Red (0-255)
    * @param oGreen 
    *    Red (0-255)
    * @param oBlue 
    *    Red (0-255)
    */
    virtual HRESULT GetColor (unsigned int & oRed, unsigned int & iGreen, unsigned int & iBlue) = 0;

};

//-----------------------------------------------------------------------
CATDeclareHandler( CATICciGridCellProperties, CATBaseUnknown );

#endif
