//===================================================================
// COPYRIGHT Dassault Systemes 2020
//===================================================================
// CATICciCompositesParametersMSS.cpp
// Header definition of class CATICciCompositesParametersMSS
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/07/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef CATICciCompositesParametersMSS_H
#define CATICciCompositesParametersMSS_H


/**
* @CAA2Level L0
* @CAA2Usage U3
*/


#include "CAACompositesItf.h"
#include "CATBaseUnknown.h"



extern ExportedByCAACompositesItf  IID IID_CATICciCompositesParametersMSS ;


/**
 * Interface Master Stacking Sequence.
 * <b>Role</b>: Allows operation on the Master Stacking Sequence.
 * <br>- The Master Stacking Sequence is recovered thanks CATIDescendants::GetAllChildren
 *  <pre>
 *  #include "CATICciCompositesParametersMSS.h"
 *  #include "CATIDescendants.h"
 *  ...
 *  CATICciCompositesParametersMSSImportExport_var spCompositesParametersMSS; //The interface for Import/Export
 *  CATIDescendants_var spDescendants = spPart; //spPart is the current Part
 *  if(NULL_var != spDescendants)
 *  {
 *      CATListValCATISpecObject_var spListCompositesParametersMSS;
 *		spDescendants->GetAllChildren (CATICciCompositesParametersMSS::ClassName(),spListCompositesParametersMSS);
 *      if(spListCompositesParametersMSS.Size() >0)
 *		   spCompositesParametersMSS = spListCompositesParametersMSS[1];
 *		...
 *	}
 *  </pre>
 */
class ExportedByCAACompositesItf CATICciCompositesParametersMSS: public CATBaseUnknown
{
CATDeclareInterface;

public:

	/**
	* Removes the Master Stacking Sequence.
	*/
	virtual HRESULT RemovesMasterStackingSequence() = 0;

};

//-----------------------------------------------------------------------
CATDeclareHandler( CATICciCompositesParametersMSS, CATBaseUnknown );

#endif
