# 
IMPACT_ON_IMPORT = YES
BUILT_OBJECT_TYPE =  NONE
DUMMY_LINK_WITH = V4SysB 
#DUMMY_LINK_WITH = V4SysB
#
OS = COMMON
COMDYN_MODULE = V4SysCOMD
LINK_WITH = $(DUMMY_LINK_WITH)

OS = AIX
SYS_LIBS = -lxlf -lxlf90 -lxlfpad
SYS_LIBPATH = 

OS = IRIX
LINK_WITH = $(DUMMY_LINK_WITH)
SYS_LIBS = -lftn

OS = HP-UX
SYS_INCPATH =
SYS_LIBS = -lf

OS = SunOS
SYS_INCPATH = 
SYS_LIBS = -lF77
SYS_LIBPATH =

OS = Windows_NT
LOCAL_CCFLAGS = /D_CATNoWarningPromotion_  
LOCAL_CFLAGS = /D_CATNoWarningPromotion_ 

