#
BUILT_OBJECT_TYPE = SHARED LIBRARY

#

#
OS = AIX
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -DNONDEFER=false -D_oracle_XA -D_ORACLE_8_1_6_
SYS_LIBS	= -blibpath:/usr/lib: -lpthreads
#
OS = HP-UX
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
#if os hpux_a
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_oracle_XA
#else
LOCAL_CCFLAGS=  +p -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_oracle_XA -D_ORACLE_8_1_6_
#endif
OS = IRIX
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_oracle_XA -D_ORACLE_8_1_6_
#
OS = SunOS
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_oracle_XA -D_ORACLE_8_1_6_

OS = alpha_a
BUILD=NO

OS = intel_a
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_ORACLE_8_1_6_ ######### -D_oracle_XA ######

OS = intel_a64
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_ORACLE_8_1_6_ ######### -D_oracle_XA ######
  
OS = win_a
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_ORACLE_8_1_6_ ######### -D_oracle_XA ######

OS = win_b64
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  OracleGLUE
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY -D_ORACLE_8_1_6_ ######### -D_oracle_XA ######







