# COPYRIGHT DASSAULT SYSTEMES 1999
#======================================================================
# Imakefile for module CATFunctSystemItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Aug 1999  Creation: Code generated by the CAA wizard  PHB
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE
