BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH =  NS0S3STR WFTOCTools JS0LIB0 JS0ZLIB DSYAdmInf
#
OS = SunOS
SYS_LIBS =-lsocket 

OS=Windows_NT
LINK_WITH = NS0S3STR WFTOCTools JS0LIB0 JS0INITENV DSYAdmInf
SYS_LIBS = wsock32.lib version.lib cabinet.lib psapi.lib 
