# COPYRIGHT DASSAULT SYSTEMES 2004
#======================================================================
# Imakefile for module PLMSecSSOLogContentProvider.m
#======================================================================
#
#  Jan 2005  Creation: Code generated by the CAA wizard  smq
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 

LINK_WITH = JS0GROUP PLMSecSSOBaseCpp 

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
