#ifndef CATVRDispatcher_H
#define CATVRDispatcher_H

// COPYRIGHT DASSAULT SYSTEMES 2001

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */


#include "CATBaseUnknown.h"
#include "CATListOfInt.h"
#include "list.h"
#include "CATListOfCATVRDeviceEvent.h"
#include "CATCallbackManager.h"
#include "CATConstantsForThreads.h"

class CATDeviceManager;
class CATDeviceBoxDispatcher;
class CATVRClientIterator;
class CATCleanManager;
class CATRessourceDispenser;

/**
* Base class for creating device event dispatchers.
* <p><tt>CATVRDispatcher</tt> supplies the methods to set/unset callbacks 
* on specified device events. You should not directly instantiate this object.
*/
class ExportedByCATVisVR CATVRDispatcher : public CATBaseUnknown
{
  CATDeclareClass;

protected:

  /**
  * Construct a CATVRDispatcher.
  */
  CATVRDispatcher();

public:

  /**
  * Destruct the object.
  * Deleting this object will remove all remaining callbacks.
  */
  virtual ~CATVRDispatcher();

   /**
  * Puts a Callback on given events.
  * When the @ref Dispatch method is called and at least one of the events specified
  * in iDeviceEventList was generated by the device drivers since the last Dispatch call,
  * the iMethod is called back with a @href CATVRNotification as argument.
  * The @href CATVRNotification offers methods to iterate on all those generated
  * events that had arrived between the current Dispatch and the previous one.
  * @param iClient
  *   The object interested in the event
  * @param iDeviceEventList
  *   The event types the @href CATVRNotification will iterate on.
  * @param iMethod
  *   The method to be called back.
  * @param iData
  *   The data to sent with the @href CATVRNotification.
  *   Default value is NULL
  * @return 
  *   The callback ID you may use to remove the callback. @see RemoveDeviceCallback.
  */
  CATCallback AddDeviceCallback(CATBaseUnknown* iClient, 
                                CATListOfCATVRDeviceEvent& iDeviceEventList, 
                                CATSubscriberMethod iMethod, 
                                CATSubscriberData iData=NULL);
  
  /**
  * Removes a callback.
  * @param iID
  *   The callback ID. @see AddDeviceCallback.
  */
  void RemoveDeviceCallback(CATCallback iID);

  /** @nodoc */
  void AddAccessConstraint(CATCallback iID1, CATCallback iID2);
  
  /** @nodoc */
  void RemoveAccessConstraints(CATCallback iID1, CATCallback iID2);

  /** @nodoc */
  CATCallback AddFocusCallback(CATCallback iID,
    CATSubscriberMethod iMethod, 
    CATSubscriberData iData=NULL);

  /** @nodoc */
  void RemoveFocusCallback(CATCallback iID);

protected:

  /**
  * Dispatch the @href CATVRNotification to the subscribed client objects.
  */
  void Dispatch();

  /** @nodoc */
  CATDeviceManager*               _deviceManager;

private:

  void ManageFocusEvent(CATCallbackEvent   iAlarmEvent,
            void             * iAlarm,
            CATNotification  * iAlarmNotification,
            CATSubscriberData  iBurglarData,
            CATCallback        iCallbackId);

  CATCleanManager*                _cleanManager;

  int                             _cleanID;

  CATListOfInt                    _cbIDList;
  CATListOfInt                    _cbFocusIDList;
  list<CATBaseUnknown>            _clientList;
  list<CATDeviceBoxDispatcher>    _dispatcherList;
  list<CATVRClientIterator>       _iteratorList;

  CATThreadsId                    _threadId;
  CATRessourceDispenser*          _ressourceDispenser;
  CATListOfInt                    _clientAccessState;
  CATListOfInt                    _clientIdAccessState;

};

#endif
