#
# SHARED LIBRARY          
#
BUILT_OBJECT_TYPE=NONE

LINK_WITH =	CK0FEAT \
		JS0GROUP  JS0FM\
		AC0SPBAS \
		ObjectModeler  \
		NS0SI18N  \
		Collections CD0FRAME \
		DI0PANV2 DI0STATE \
		ON0GREXT ON0MAIN ON0PROP  \
		VE0MDL JS0LOGRP JS0CORBA\
		CK0PARAM VE0PIX\
		AC0WINLNK VE0GRPH2 KnowledgeItf\
		DI0BUILD ON0FRAME
#



