/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatSIMLoopMode_h
#define CatSIMLoopMode_h

enum CatSIMLoopMode {
        catSIMLoopModeSingle,
        catSIMLoopModeResume,
        catSIMLoopModeReverse
};

#endif
