#======================================================================
# Imakefile for module CATMMediaPixelImage
#======================================================================
#  2017/05/11 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

COMMON_LINK_WITH = JS0GROUP CATSysTSObjectModeler 

LINK_WITH = $(COMMON_LINK_WITH) JS0MT CATSysTS CATViz 

