# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CATMmFunctionalTypeLib.m
# Module for compilation of the typelib
#======================================================================
#
#  Nov 2002  Creation: Code generated by the CAA wizard  jpi
#======================================================================
#
# TYPELIB          
#

BUILT_OBJECT_TYPE=TYPELIB
# no more BUILD_PRIORITY=4

LINK_WITH = InfTypeLib 
