#
# COPYRIGHT DASSAULT SYSTEMES 2003
#
# creation jfi 8-10-03
#
# module : CATMmrBackUpStartUpTool

BUILT_OBJECT_TYPE=LOAD MODULE

LINK_WITH = CATObjectModelerBase JS0GROUP AC0SPBAS AC0SPCAA CATPartArchi
