#ifndef CATIARemove_IDL
#define CATIARemove_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1997
//=================================================================
//								   
// CATIARemove:						   
// Exposed interface for remove Feature
//								   
//=================================================================
// Usage notes:
//
//=================================================================
// Oct97 Creation                                       Ph Baucher
//=================================================================
#include "CATIABooleanShape.idl"

/**
 * Represents the remove, or substract boolean operation.
 * It is performed between a body and the current shape.
 */

interface CATIARemove : CATIABooleanShape
{
	//		================
	//		== PROPERTIES ==
	//		================



	//		=============
	//		== METHODS ==
	//		=============
	//
};

// Interface name : CATIARemove
#pragma ID CATIARemove "DCE:80ebcad7-85b6-0000-0280030ba6000000"
#pragma DUAL CATIARemove

// VB object name : Remove (Id used in Visual Basic)
#pragma ID Remove "DCE:80ebcade-0fef-0000-0280030ba6000000"
#pragma ALIAS CATIARemove Remove


#endif
// CATIARemove_IDL

