// COPYRIGHT DASSAULT SYSTEMES 2013/07/03
//===================================================================
// CATIPdgUseTechResTool.cpp
// Header definition of class CATIPdgUseTechResTool
//===================================================================
//
// Usage notes: API TO GET ALL TECHNOLOGICAL RESULT UNDER MechanicalTool OR HYBRID Body
//
//===================================================================
//  2013/07/03 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef CATIPdgUseTechResTool_H
#define CATIPdgUseTechResTool_H

// COPYRIGHT DASSAULT SYSTEMES 2013
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "PartItf.h"
#include "CATBaseUnknown.h"
#include "CATListOfCATIPdgUseTechnoRes.h"


#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByPartItf IID IID_CATIPdgUseTechResTool;
#else
extern "C" const IID IID_CATIPdgUseTechResTool;
#endif

/*
 * Interface to Get Technological Results from tool.
 * Theses CAA APIs are licensed with the Technical Product PD1.prd
 * <dl>
 * <dt><b>Example:</b>
 * <pre>
 *       
 *   #include " CATListPCATIPdgUseTechnoRes.h"
 *   #include " CATIPdgUseTechResTool.h"
 *   //   pMechanicalTool is kind of CATIPdgUseTechResTool
 *      CATListOfCATIPdgUseTechnoRes TRList;
 * 	TRList = pMechanicalTool-> GetAllTechResFromTool (TRList); 
 * </pre>
 * </dl>
 *
 * 
 */
class ExportedByPartItf CATIPdgUseTechResTool: public CATBaseUnknown
{
 CATDeclareInterface;
public:

  /** 
  * Gets all Technological Results under tool if exist.
  *   @param oTechResList 
                 List of CATIPdgUseTechnoRes
				 Pointers contained in the list must be released
  */
  virtual HRESULT GetAllTechResFromTool(CATListOfCATIPdgUseTechnoRes &oTechResList)=0;

};

//-----------------------------------------------------------------------

#endif
