#ifndef CATIASlot_IDL
#define CATIASlot_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1997
//=================================================================
//								   
// CATIASlot:						   
// Exposed interface for Mechanical slot
//								   
//=================================================================
// Usage notes:
//
//=================================================================
// Oct97 Creation					Ph Baucher
// Dec97 Modification				  	 L Lalere	
//=================================================================
#include "CATIASweep.idl"

/**
 * Represents the slot shape.
 * The slot shape is made up of a profile represented by a sketch
 * swept along a center curve represented by another sketch.
 * This is a "negative" shape: it removes material from the body it
 * belongs to.
 * The profile sketch is usually drawn on another shape face.
 */
//-----------------------------------------------------------------
interface CATIASlot : CATIASweep
{
	//		================
	//		== PROPERTIES ==
	//		================



	//		=============
	//		== METHODS ==
	//		=============
};

// Interface name : CATIASlot
#pragma ID CATIASlot "DCE:54d29251-5c11-11d1-a2750000f87546fd"
#pragma DUAL CATIASlot

// VB object name : Slot (Id used in Visual Basic)
#pragma ID Slot "DCE:55037286-5c11-11d1-a2750000f87546fd"
#pragma ALIAS CATIASlot Slot


#endif
// CATIASlot_IDL

