#ifndef CATIAAdd_IDL
#define CATIAAdd_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1997
//=================================================================
//								   
// CATIAAdd:						   
// Exposed interface for Add Feature
//								   
//=================================================================
// Usage notes:
//
//=================================================================
// Oct97 Creation                                       Ph Baucher
//=================================================================
#include "CATIABooleanShape.idl"

/**
 * Represents the add, or union boolean operation.
 * It is performed between a body and the current shape.
 */

interface CATIAAdd : CATIABooleanShape
{
	//		================
	//		== PROPERTIES ==
	//		================



	//		=============
	//		== METHODS ==
	//		=============
	//
};

// Interface name : CATIAAdd
#pragma ID CATIAAdd "DCE:80ebca5f-b839-0000-0280030ba6000000"
#pragma DUAL CATIAAdd

// VB object name : Add (Id used in Visual Basic)
#pragma ID Add "DCE:80ebca68-aaec-0000-0280030ba6000000"
#pragma ALIAS CATIAAdd Add


#endif
// CATIAAdd_IDL

