#ifndef CATPatternDefs_IDL
#define CATPatternDefs_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 2002
//=================================================================
//                                   
// CATPatternDefs:                           
// enumerations for Mechanical Pattern
//                                   
//=================================================================
// Usage notes:
//    considered in Patterns
//=================================================================

/**
 * Circular Pattern Parameters.
 * The Circular Pattern can apply parameters to the angular repartition.
 * @param catInstancesandAngularSpacing
 *    The number of instances and the angular spacing are used to define the Pattern.  
 * @param catCompleteCrown
 *    Only the number of instances is used to define the Pattern, the total angle is set to 360 degrees.  
 */
enum CatCircularPatternParameters    
{
    catInstancesandAngularSpacing,
    catCompleteCrown,
	catUnequalAngularSpacing
};

/**
 * Rectangular Pattern Parameters.
 * The Rectangular Pattern can apply parameters to the repartition.
 * @param catInstancesandSpacing
 *    The number of instances and the length spacing are used to define the Pattern.  
 * @param catUnequalSpacing
 *    Only the number of instances is used to define the Pattern.
 */

enum CatRectangularPatternParameters    
{
    catInstancesandSpacing,
    catUnequalSpacing
};

#endif
// CATPatternDefs_IDL
