#
BUILT_OBJECT_TYPE=LOAD MODULE
LINK_WITH = WFTOCTools DI0PANV2 JS0SCBAK JS0CORBA JS0FM JS0STR JS0ERROR NS0S3STR NS0S1MSG CXINSTUTIL JS0ZLIB CATDlgStandard 
#
OS = SunOS
SYS_LIBS =-lXm -lsocket 

OS = Windows_NT
LOCAL_LDFLAGS=$(SUB_WIN)
MKMFC_DEPENDENCY=Yes 
SYS_LIBS = wsock32.lib 


