#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

LINK_WITH = JS0CORBA JS0SCBAK JS0STR JS0FM JS03TRA NS0S3STR\
            CO0RCINT CO0LSTST CO0LSTPV VE0BASE YN000MFL\
            AC0XXLNK AD0XXBAS AC0SPBAS MK0BASE ON0GREXT\
            CD0WIN CD0FRAME DI0PANV2 DI0STATE DI0GRAF DI0APPLI\
			CD0AUTOSTART CATInfInterfaces 
