# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module CATKWEPointer.m
#======================================================================
#
#  Aug 2001  Creation: Code generated by the CAA wizard  JPI
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP AD0XXBAS ObjectModelerBaseUUID 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
JS0GROUP CATLiteralFeatures CATObjectSpecsModeler CATObjectModelerBase CATKnowledgeModeler \
KnowledgeItf

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
