#
BUILT_OBJECT_TYPE = LOAD MODULE
#
OS = COMMON

LINK_WITH= PR0BASE PR0WCMD JS0CORBA  JS0STR JS03TRA JS0ERROR NS0S3STR CO0LSTPV CO0HDICO CO0LSTPV CO0SETST DI0PANV2 JS0SCBAK JS0SETT JS0FM CATSysDbSettings
MKMFC_DEPENDENCY=Yes
OS = AIX
LOCAL_LDFLAGS =-F:$(LD)

#
OS = HP-UX
#LOCAL_LDFLAGS = -Wl,-aarchive -Wl,-L/lib -lhppa -Wl,-E -Wl,-uallow_unaligned_data_access -Wl,-ashared 

#
OS = IRIX

#
OS = SunOS
SYS_LIBS=-lXm

#
OS = Windows_NT
#LOCAL_LDFLAGS= $(SUB_CONS)
LOCAL_LDFLAGS=$(SUB_WIN)
