BUILT_OBJECT_TYPE = CORBA

LINK_WITH = CATCsbCORBA ECB0CORBA

CORBA_BUILD_TYPE = SHAREDLIBRARY

CORBA_CPP_CS = SERVER CLIENT

#CORBA_CPP_OPTS = -A -B -S
#CORBA_CPP_OPTS = -A -B
CORBA_CPP_OPTS = -S

SYS_LIBS = -lorbix


OS = AIX
#if os aix_a64
LOCAL_CCFLAGS=-DSIXTY_FOUR_BIT_LONGS
#endif
LOCAL_LDFLAGS = -brtl

OS = intel_a
SYS_LIBS = ITMI.lib
LOCAL_CCFLAGS = -DORBIX_DLL -DWIN32_LEAN_AND_MEAN -DWIN32 -DIT_EX_MACROS

OS = win_b64
SYS_LIBS = ITMI.lib
LOCAL_CCFLAGS = -DORBIX_DLL -DIT_EX_MACROS

