#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = SI0REPOR
#
OS = COMMON

LINK_WITH = SI0REPER SI0TOPAC GN0GRAPH\
            SI0BREPA\
            Collections JS0CORBA JS0ERROR\
            JS0SCBAK JS0STR AD0XXBAS YP00IMPL CATMathematics CATMathStream YI00IMPL GN0NAME
