#
# Makefile for the shared libray of an interfaces Framework
#
 
BUILT_OBJECT_TYPE=NONE
 
LINK_WITH= JS0GROUP JS0DSPA JS0LOGRP JS0CTYP NS0SI18N \
           JS0CORBA JS03TRA JS0ERROR JS0INF
# AD0XXBAS 

INCLUDED_MODULES = SMTInterfacesPubIDL SMTInterfacesProIDL SMTInterfacesItfCPP 

 
#    INCLUDED_MODULES = SMTInterfacesPubIDL SMTInterfacesItfCPP 
#INCLUDED_MODULES = SMTInterfacesPubIDL 
