/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIATlgWebFactory_h
#define CATIATlgWebFactory_h

#ifndef ExportedByCATToolingPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATToolingPubIDL
#define ExportedByCATToolingPubIDL __declspec(dllexport)
#else
#define ExportedByCATToolingPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATToolingPubIDL
#endif
#endif

#include "CATIAFactory.h"

class CATIATlgWebAccess;

extern ExportedByCATToolingPubIDL IID IID_CATIATlgWebFactory;

class ExportedByCATToolingPubIDL CATIATlgWebFactory : public CATIAFactory
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddNewAccess(CATIATlgWebAccess *& opiAccess)=0;


};

CATDeclareHandler(CATIATlgWebFactory, CATIAFactory);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIAReference.h"
#include "CATIATlgWebAccess.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
