#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
MultimediaUUID
#else
LINK_WITH_FOR_IID =
#endif
#
#  Multimedia Interfaces
#

# BUILT_OBJECT_TYPE=NONE
BUILT_OBJECT_TYPE=SHARED LIBRARY
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0INF


