#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH = JS0FM JS0GROUP JS0CRYPTEXIT SystemUUID BatchInfrastructureUUID InfItf CATXMLParserItf CATSysCommunication

#
OS = AIX
LOCAL_CCFLAGS = -DNATIVE_EXCEPTION

#
OS = HP-UX
LOCAL_CCFLAGS = -DNATIVE_EXCEPTION
CXX_EXCEPTION=

#
OS = IRIX
LOCAL_CCFLAGS  = -float -DNATIVE_EXCEPTION
LOCAL_CFLAGS   = -float 
CXX_EXCEPTION= 

#
OS = SunOS
SH_LINK_WITH = $(LINK_WITH)
LOCAL_CCFLAGS = -mt -DNATIVE_EXCEPTION
SYS_LIBS =  -lsocket -lnsl


OS = Windows_NT
LOCAL_CCFLAGS = -DNATIVE_EXCEPTION
CXX_EXCEPTION=
SYS_LIBS = netapi32.lib wsock32.lib
