/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAFactory2D_h
#define CATIAFactory2D_h

#ifndef ExportedBySketcherPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __SketcherPubIDL
#define ExportedBySketcherPubIDL __declspec(dllexport)
#else
#define ExportedBySketcherPubIDL __declspec(dllimport)
#endif
#else
#define ExportedBySketcherPubIDL
#endif
#endif

#include "CATIABase.h"
#include "CATSafeArray.h"

class CATIAAngle;
class CATIACircle2D;
class CATIAControlPoint2D;
class CATIAEllipse2D;
class CATIAGeometricElements;
class CATIAGeometry2D;
class CATIAHyperbola2D;
class CATIALength;
class CATIALine2D;
class CATIAParabola2D;
class CATIAPoint2D;
class CATIAReference;
class CATIASpline2D;

extern ExportedBySketcherPubIDL IID IID_CATIAFactory2D;

class ExportedBySketcherPubIDL CATIAFactory2D : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall CreatePoint(double iX, double iY, CATIAPoint2D *& oNewPoint)=0;

    virtual HRESULT __stdcall CreateControlPoint(double iX, double iY, CATIAControlPoint2D *& oNewPoint)=0;

    virtual HRESULT __stdcall CreateLine(double iX1, double iY1, double iX2, double iY2, CATIALine2D *& oNewLine)=0;

    virtual HRESULT __stdcall CreateLineFromVector(double iX1, double iY1, double iUX, double iUY, CATIALine2D *& oNewLine)=0;

    virtual HRESULT __stdcall CreateClosedCircle(double iCenterX, double iCenterY, double iRadius, CATIACircle2D *& oNewCircle)=0;

    virtual HRESULT __stdcall CreateCircle(double iCenterX, double iCenterY, double iRadius, double iStartParam, double iEndParam, CATIACircle2D *& oNewCircle)=0;

    virtual HRESULT __stdcall CreateClosedEllipse(double iCenterX, double iCenterY, double iMajorX, double iMajorY, double iMajorRadius, double iMinorRadius, CATIAEllipse2D *& oNewEllipse)=0;

    virtual HRESULT __stdcall CreateEllipse(double iCenterX, double iCenterY, double iMajorX, double iMajorY, double iMajorRadius, double iMinorRadius, double iStartParam, double iEndParam, CATIAEllipse2D *& oNewEllipse)=0;

    virtual HRESULT __stdcall CreateSpline(const CATSafeArrayVariant & iPoles, CATIASpline2D *& oNewSpline)=0;

    virtual HRESULT __stdcall CreateProjections(CATIAReference * iGeometry, CATIAGeometricElements *& oSolutions)=0;

    virtual HRESULT __stdcall CreateIntersections(CATIAReference * iGeometry, CATIAGeometricElements *& oSolutions)=0;

    virtual HRESULT __stdcall CreateProjection(CATIAReference * iGeometry, CATIAGeometry2D *& oFirstSolution)=0;

    virtual HRESULT __stdcall CreateIntersection(CATIAReference * iGeometry, CATIAGeometry2D *& oFirstSolution)=0;

    virtual HRESULT __stdcall CreateParabola(double iCenterX, double iCenterY, double iAxisX, double iAxisY, double iFocalDistance, CATIAParabola2D *& oParabola)=0;

    virtual HRESULT __stdcall CreateHyperbola(double iCenterX, double iCenterY, double iAxisX, double iAxisY, double iMajorRadius, double iMinorRadius, CATIAHyperbola2D *& oHyperbola)=0;


};

CATDeclareHandler(CATIAFactory2D, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
