/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAGeometricElement_h
#define CATIAGeometricElement_h

#ifndef ExportedBySketcherPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __SketcherPubIDL
#define ExportedBySketcherPubIDL __declspec(dllexport)
#else
#define ExportedBySketcherPubIDL __declspec(dllimport)
#endif
#else
#define ExportedBySketcherPubIDL
#endif
#endif

#include "CATGeometricType.h"
#include "CATIABase.h"

extern ExportedBySketcherPubIDL IID IID_CATIAGeometricElement;

class ExportedBySketcherPubIDL CATIAGeometricElement : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_GeometricType(CatGeometricType & oType)=0;


};

CATDeclareHandler(CATIAGeometricElement, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
