BUILT_OBJECT_TYPE=SHARED LIBRARY
LINK_WITH=

OS = AIX
LOCAL_CCFLAGS = -D_AIX_SOURCE
LOCAL_LDFLAGS = -brtl
CXX_EXCEPTION =
SYS_INCPATH =
SYS_LIBPATH =

OS = HP-UX
LOCAL_CCFLAGS = -D_HPUX_SOURCE
SYS_INCPATH =
SYS_LIBPATH =
CXX_EXCEPTION =

OS = IRIX
LOCAL_CCFLAGS = -D_IRIX_SOURCE
LOCAL_LDFLAGS =
CXX_EXCEPTION =
SYS_INCPATH =
SYS_LIBPATH =


OS = SunOS
LOCAL_CCFLAGS = -D_SUNOS_SOURCE
CXX_EXCEPTION =
SYS_INCPATH =
SYS_LIBPATH =

OS = Windows_NT
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE
CXX_EXCEPTION =
SYS_INCPATH =
SYS_LIBPATH =
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
