/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIADMOWrappings_h
#define CATIADMOWrappings_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedBySMTInterfacesPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __SMTInterfacesPubIDL
#define ExportedBySMTInterfacesPubIDL __declspec(dllexport)
#else
#define ExportedBySMTInterfacesPubIDL __declspec(dllimport)
#endif
#else
#define ExportedBySMTInterfacesPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIACollection.h"

class CATIADMOWrapping;
class CATIADocument;
class CATIAGroup;
class CATIAProduct;

extern ExportedBySMTInterfacesPubIDL IID IID_CATIADMOWrappings;

class ExportedBySMTInterfacesPubIDL CATIADMOWrappings : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall ComputeAWrapping(CATIAGroup * GroupOfSelectedProducts, double iAccuracy, double iRation, double iAccuracyForSimplification, CATIADocument *& WrappingDocument)=0;

    virtual HRESULT __stdcall ComputeAWrappingWithAReference(CATIAGroup * iGroupOfSelectedProducts, CATIAProduct * iReferenceProduct, double iAccuracy, double iRation, double iAccuracyForSimplification, CATIADocument *& WrappingDocument)=0;

    virtual HRESULT __stdcall WrappingShapeName(CATBSTR *& Name)=0;

    virtual HRESULT __stdcall Add(CATIAProduct * iProductToWrapping, double iAccuracy, double iRatio, const CATBSTR & iShapeName, CATLONG iActivatedShape, CATLONG iDefaultShape, CATIADMOWrapping *& oWrapping)=0;

    virtual HRESULT __stdcall CleanUp()=0;

    virtual HRESULT __stdcall ComputeWrappingWithConvexHull(CATIAGroup * iGroupOfSelectedProducts, CATIAProduct * iReferenceProduct, double iAccuracy, CAT_VARIANT_BOOL iPerformSimplification, double iAccuracyForSimplification, CATIADocument *& WrappingDocument)=0;


};

CATDeclareHandler(CATIADMOWrappings, CATIACollection);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIADMOWrapping.h"
#include "CATIADocument.h"
#include "CATIAGroup.h"
#include "CATSafeArray.h"
#include "CATVariant.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
