// COPYRIGHT Dassault Systemes 2004
//===================================================================
//
// CATIMfgPrismMachiningDirectionMgt.h
//
//===================================================================
//
// Usage notes:
//   Interface to manage the machining direction of Prismatic Machining Operations.
//
//===================================================================
//  Dec 2004  Creation: Code generated by the CAA wizard  lbp
//===================================================================
#ifndef CATIMfgPrismMachiningDirectionMgt_H
#define CATIMfgPrismMachiningDirectionMgt_H

/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "PmgItfEnv.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByPmgItfEnv IID IID_CATIMfgPrismMachiningDirectionMgt;
#else
extern "C" const IID IID_CATIMfgPrismMachiningDirectionMgt ;
#endif

//------------------------------------------------------------------

/**
* Interface to manage the machining direction of Prismatic Machining Operations.
* <br><b>Role</b>: CATIMfgPrismMachiningDirectionMgt has methods to manage the machining direction of Prismatic Machining Operations.
*/

class ExportedByPmgItfEnv CATIMfgPrismMachiningDirectionMgt: public CATBaseUnknown
{
  CATDeclareInterface;
	
public:
	
	/**
	* Retrieves the Machining Direction Feature of the Prismatic Machining Operation. 
	*/
	
	virtual HRESULT GetMachiningDirectionFeature (CATBaseUnknown_var & oMachiningDirectionFeature) = 0; 
	
};

CATDeclareHandler(CATIMfgPrismMachiningDirectionMgt, CATBaseUnknown);
#endif
