#ifndef CATIAManufacturingPrismaticMachiningArea_IDL
#define CATIAManufacturingPrismaticMachiningArea_IDL
/*IDLREP*/

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 2002
//=================================================================
//								   
// CATIAManufacturingPrismaticMachiningArea:						   
// Exposed interface for Mfg2DMAFeature
//								   
//=================================================================
// Oct 02 Creation	                         			  C.Vasseur
//=================================================================
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

#include "CATIAManufacturingMachinableArea.idl"

/**
 * ManufacturingPrismaticMachiningArea defines a set of properties and methods.
 */
interface CATIAManufacturingPrismaticMachiningArea : CATIAManufacturingMachinableArea
{

#pragma PROPERTY Type

   /**
   * Returns or sets the Type of a Manufacturing Prismatic Machining Area.<br>
   * <dl>
   * <dt><b>Examples:</b>
   * <dd>The following example returns the feature type <tt>ThisType</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim ThisType As CATBSTR
   * ThisType = CurrentPMA.<font color="red">Type</font>
   * </pre>
   * <dd>The next example sets the feature type of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * CurrentPMA.<font color="red">Type</font> = "<b>MfgPocketType</b>"
   * <br>To be allowed to change <font color="red">Type</font> into <b>MfgPocketType</b> or into <b>MfgContouringType</b>, Contours and Islands geometries must be removed first.
   * </pre>
   * <dt><b>Legal values</b>: <font color="red">Type</font> can be
   *   <dl>
   *     <dt><tt><b>MfgPocketType</b></tt>
   *     <dt><tt><b>MfgContouringType</b></tt>
   *   </dl> 
   * </dl>
   */
   HRESULT get_Type(inout /*IDLRETVAL*/ CATBSTR oType);  

   HRESULT put_Type(in CATBSTR iType);

#pragma PROPERTY BottomType

   /**
   * Returns or sets the Hardness Mode on Bottom of a Manufacturing Prismatic Machining Area.<br>
   * <dl>
   * <dt><b>Examples:</b>
   * <dd>The following example returns the hardness mode on bottom <tt>ThisBottomType</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim ThisBottomType As CATBSTR
   * ThisBottomType = CurrentPMA.<font color="red">BottomType</font>
   * </pre>
   * <dd>The next example sets the hardness mode on bottom of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * CurrentPMA.<font color="red">BottomType</font> = "<b>MfgHard</b>"
   * <br>To be allowed to change <font color="red">BottomType</font> into <b>MfgSoft</b>, Islands geometries must be removed first.
   * </pre>
   * <dt><b>Legal values</b>: <font color="red">BottomType</font> can be
   *   <dl>
   *     <dt><tt><b>MfgHard</b></tt>
   *     <dt><tt><b>MfgSoft</b></tt>
   *   </dl> 
   * </dl>
   */
   HRESULT get_BottomType(inout /*IDLRETVAL*/ CATBSTR oBottomType);  

   HRESULT put_BottomType(in CATBSTR iBottomType);

#pragma PROPERTY TopType

   /**
   * Returns or sets the Hardness Mode on top of a Manufacturing Prismatic Machining Area.<br>
   * <dl>
   * <dt><b>Examples:</b>
   * <dd>The following example returns the hardness mode on top <tt>ThisTopType</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim ThisTopType As CATBSTR
   * ThisTopType = CurrentPMA.<font color="red">TopType</font>
   * </pre>
   * <dd>The next example sets the hardness mode on top of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * CurrentPMA.<font color="red">TopType</font> = "<b>MfgHard</b>"
   * </pre>
   * <dt><b>Legal values</b>: <font color="red">TopType</font> can be
   *   <dl>
   *     <dt><tt><b>MfgHard</b></tt>
   *     <dt><tt><b>MfgSoft</b></tt>
   *   </dl> 
   * </dl>
   */
   HRESULT get_TopType(inout /*IDLRETVAL*/ CATBSTR oTopType);  

   HRESULT put_TopType(in CATBSTR iTopType);

#pragma PROPERTY IslandsCount

   /**
   * Retreives the number of Island of a Manufacturing Prismatic Machining Area.<br>
   * <dl>
   * <dt><b>Example:</b>
   * <dd>The following example returns the number of Island <tt>NumberOfIsland</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim NumberOfIsland As Long
   * NumberOfIsland = CurrentPMA.<font color="red">IslandsCount</font>
   * </pre>
   * </dl>
   */
   HRESULT get_IslandsCount(out /*IDLRETVAL*/ long oNumberOfIsland);  

#pragma PROPERTY ContoursCount

   /**
   * Retreives the number of Contour of a Manufacturing Prismatic Machining Area.<br>
   * <dl>
   * <dt><b>Example:</b>
   * <dd>The following example returns the number of Contour <tt>NumberOfContour</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim NumberOfContour As Long
   * NumberOfContour = CurrentPMA.<font color="red">ContoursCount</font>
   * </pre>
   * </dl>
   */
   HRESULT get_ContoursCount(out /*IDLRETVAL*/ long oNumberOfContour);  

   // Method SetGeometry
 
   /**
   * Sets a geometry of a specified type to a Manufacturing Prismatic Machining Area.
   * @param iGeometryType
   * <b>Legal values</b>: iGeometryType can be
   *   <dl>
   *     <dt><tt>RelimitingPlane</tt> <dd> to set the top plane   
   *     <dt><tt>Parts</tt>           <dd> to set the bottom
   *     <dt><tt>Checks</tt>          <dd> to set a check element
   *   </dl> 
   * @param iReference
   *   The geometry to be set.
   * @param iProduct
   *   The product containing the geometry to be set. 
   * @param iPosition
   *   0
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example sets the top plane <tt>Plane2</tt> to the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Call CurrentPMA.<font color="red">SetGeometry</font>("RelimitingPlane",Plane2,PartMachined,0)
   * </pre>
   * </dl>
   */
   HRESULT SetGeometry(in CATBSTR iGeometryType, in CATIABase iReference, in CATIABase iProduct, in short iPosition);

   // Method RemoveAllGeometry

   /**
   * Removes all the geometry of a specified type linked to a Manufacturing Prismatic Machining Area.
   * @param iGeometryType
   *   <b>Legal values</b>: iGeometryType can be
   *   <dl>
   *     <dt><tt>RelimitingPlane</tt> <dd> to remove the top plane   
   *     <dt><tt>Parts</tt>           <dd> to remove the bottom
   *     <dt><tt>Checks</tt>          <dd> to remove the check elements
   *     <dt><tt>Contours</tt>        <dd> to remove the guiding elements
   *     <dt><tt>Islands</tt>         <dd> to remove the islands
   *   </dl> 
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example removes the bottom of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Call CurrentPMA.<font color="red">RemoveAllGeometry</font>("Parts")
   * </pre>
   * </dl>
   */

   HRESULT RemoveAllGeometry(in CATBSTR iGeometryType);

   // Method SetGeometries
 
   /**
   * Sets or adds geometry in a collection of a specified type to a Manufacturing Prismatic Machining Area.
   * @param iGeometryType
   *   <b>Legal values</b>: iGeometryType can be
   *   <dl>
   *     <dt><tt>Contours</tt> <dd> to set or to add a guiding element
   *     <dt><tt>Islands</tt>  <dd> to set or to add an island<br>(not allowed if Type == "MfgContouringType" or <br> if BottomType == "MfgSoft") (see Properties).
   *   </dl> 
   * @param iMode
   *   <b>Legal values</b>: iMode can be
   *   <dl>
   *     <dt><tt>0</tt> <dd> by Edges
   *   </dl> 
   * @param iGeometryNumber
   *   The geometry index inside the collection.
   *   <dl>
   *     <dt><dd>Must be 1 if Type == "MfgPocketType" (see Properties) and iGeometryType == "Contours".
   *     <dt><dd>Must be between 1 and IslandsCount + 1 (or ContoursCount + 1) (see Properties).
   *   </dl> 
   * @param iReference
   *   The geometry to be set.
   * @param iProduct
   *   The product containing the geometry to be set. 
   * @param iPosition
   *   0
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example sets 3 Islands, linked to 2 circles and 3 lines, to the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim iGeometryNumber As Long
   * iGeometryNumber = 0
   * ...
   * 'Get number of Island of CurrentPMA and add 1 to create a new island (Island number 1)
   * iGeometryNumber = CurrentPMA.IslandsCount + 1
   * Call CurrentPMA.<font color="red">SetGeometries</font>("Islands",0,iGeometryNumber,Circle1,PartMachined,0)
   *
   * 'Get number of Island of CurrentPMA and add 1 to create a new island  (Island number 2)
   * iGeometryNumber = CurrentPMA.IslandsCount + 1
   * Call CurrentPMA.<font color="red">SetGeometries</font>("Islands",0,iGeometryNumber,Circle2,PartMachined,0)
   *
   * 'Get number of Island of CurrentPMA and add 1 to create a new island  (Island number 3)
   * iGeometryNumber = CurrentPMA.IslandsCount + 1
   * Call CurrentPMA.<font color="red">SetGeometries</font>("Islands",0,iGeometryNumber,Line5,PartMachined,0)
   *
   * 'Adding Line6 to Island number 3
   * Call CurrentPMA.<font color="red">SetGeometries</font>("Islands",0,iGeometryNumber,Line6,PartMachined,0)
   *
   * 'Adding Line7 to Island number 3
   * Call CurrentPMA.<font color="red">SetGeometries</font>("Islands",0,iGeometryNumber,Line7,PartMachined,0)
   * </pre>
   * </dl>
   */
   HRESULT SetGeometries(in CATBSTR iGeometryType, in short iMode, in long iGeometryNumber, in CATIABase iReference, in CATIABase iProduct, in short iPosition);

   // Method GetContourSide
 
   /**
   * Gets the side of one contour of a Manufacturing Prismatic Machining Area.
   * @param iContourNumber
   *   The geometry index inside the collection.
   *   <dl>
   *     <dt><dd>Must be between 1 and ContoursCount (see Properties).
   *   </dl> 
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example gets the side of the contour number <tt>iContourNumber</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim iContourNumber As Long
   * iContourNumber = 3
   *
   * Dim oContourSide As short
   * oContourSide = CurrentPMA.<font color="red">GetContourSide</font>(iContourNumber)
   * </pre>
   * </dl>
   */
   HRESULT GetContourSide(in long iContourNumber, out /*IDLRETVAL*/ short oSide);

   // Method SetContourSide
 
   /**
   * Sets the side of one contour of a Manufacturing Prismatic Machining Area.
   * @param iContourNumber
   *   The geometry index inside the collection.
   *   <dl>
   *     <dt><dd>Must be between 1 and ContoursCount (see Properties).
   *   </dl> 
   * @param iSide
   *   <b>Legal values</b>: iSide can be
   *   <dl>
   *     <dt><tt>1</tt>
   *     <dt><tt>2</tt>
   *   </dl> 
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example sets the side of the contour number <tt>iContourNumber</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim iContourNumber As Long
   * iContourNumber = 3
   *
   * Dim iContourSide As Short
   * iContourSide = 2
   * Call CurrentPMA.<font color="red">SetContourSide</font>(iContourNumber,iContourSide)
   * </pre>
   * </dl>
   */
   HRESULT SetContourSide(in long iContourNumber, in short iSide);

   // Method GetGeometriesAquisitionMode
 
   /**
   * Gets the aquisition mode of one geometry of a Manufacturing Prismatic Machining Area.
   * @param iGeometryType
   *   <b>Legal values</b>: iGeometryType can be
   *   <dl>
   *     <dt><tt>Contours</tt> <dd> to get the aquisition mode of a guiding element
   *     <dt><tt>Islands</tt>  <dd> to get the aquisition mode of an island<br>(not allowed if Type == "MfgContouringType" or <br> if BottomType == "MfgSoft") (see Properties).
   *   </dl> 
   * @param iGeometryNumber
   *   The geometry index inside the collection.
   *   <dl>
   *     <dt><dd>Must be 1 if Type == "MfgPocketType" (see Properties) and iGeometryType == "Contours".
   *     <dt><dd>Must be between 1 and IslandsCount + 1 (or ContoursCount + 1) (see Properties).
   *   </dl> 
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example gets the aquisition mode of the contour number <tt>iGeometryNumber</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim iGeometryNumber As Long
   * iGeometryNumber = 3
   *
   * Dim oMode As Short
   * oMode = CurrentPMA.<font color="red">GetGeometriesAquisitionMode</font>("Contours",iGeometryNumber)
   * </pre>
   * <dt><b>Legal values</b>: <font color="red">GetGeometriesAquisitionMode</font> value can be
   *   <dl>
   *     <dt><tt>0</tt> <dd> by Edges
   *     <dt><tt>1</tt> <dd> by Belt of Faces
   *     <dt><tt>2</tt> <dd> by Boundary of Faces (Islands only)
   *     <dt><tt>5</tt> <dd> by Boundary of Faces (Contours only)
   *   </dl> 
   * </dl>
   */
   HRESULT GetGeometriesAquisitionMode(in CATBSTR iGeometryType, in long iGeometryNumber, out /*IDLRETVAL*/ short oMode);

   // Method IsContourClosed
 
   /**
   * Return the status of one contour of a Manufacturing Prismatic Machining Area : closed or open.
   * @param iContourNumber
   *   The geometry index inside the collection.
   *   <dl>
   *     <dt><dd>Must be between 1 and ContoursCount (see Properties).
   *   </dl> 
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example returns the status of the contour number <tt>iContourNumber</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim iContourNumber As Long
   * iContourNumber = 3
   *
   * Dim oIsClosed As short
   * oIsClosed = CurrentPMA.<font color="red">IsContourClosed</font>(iContourNumber)
   * </pre>
   * <dt><b>Legal values</b>: <font color="red">IsContourClosed</font> value can be
   *   <dl>
   *     <dt><tt>0</tt> (means open contour)
   *     <dt><tt>1</tt> (means closed contour)
   *   </dl>
   * </dl>
   */
   HRESULT IsContourClosed(in long iContourNumber, out /*IDLRETVAL*/ short oIsClosed);

   // Method SetOpenContourSide
 
   /**
   * Sets the side of one  open contour of a Manufacturing Prismatic Machining Area.
   * @param iContourNumber
   *   The geometry index inside the collection.
   *   <dl>
   *     <dt><dd>Must be between 1 and ContoursCount (see Properties).
   *   </dl> 
   * @param iPoint
   *   A point near one of both limits of the contour.
   *   <dl>
   *     <dt><dd>From this limit to the other one, the side of the contour is on the left.
   *   </dl> 
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example sets the side of the open contour number <tt>iContourNumber</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim iContourNumber As Long
   * iContourNumber = 3
   *
   * Dim Point1 As CATIABase
   * ...
   * Set Point1 = hybridShapes1.Item("Point.1")
   * ...
   *
   * Call CurrentPMA.<font color="red">SetOpenContourSide</font>(iContourNumber,Point1)
   * </pre>
   * </dl>
   */
   HRESULT SetOpenContourSide(in long iContourNumber, in CATIABase iPoint);

   // Method SetClosedContourSide
 
   /**
   * Sets the side of one closed contour of a Manufacturing Prismatic Machining Area.
   * @param iContourNumber
   *   The geometry index inside the collection.
   *   <dl>
   *     <dt><dd>Must be between 1 and ContoursCount (see Properties).
   *   </dl> 
   * @param iSide
   *   <b>Legal values</b>: iSide can be
   *   <dl>
   *     <dt><tt>Inside</tt>
   *     <dt><tt>Outside</tt>
   *   </dl> 
   * </dl>
   * <dl>
   * <br>
   * <dt><b>Example:</b>
   * The following example sets the side of the closed contour number <tt>iContourNumber</tt> of the manufacturing prismatic machining area <tt>CurrentPMA</tt>
   * <pre>
   * Dim iContourNumber As Long
   * iContourNumber = 3
   *
   * Dim iContourSide As CATBSTR
   * iContourSide = "Inside"
   * Call CurrentPMA.<font color="red">SetClosedContourSide</font>(iContourNumber,iContourSide)
   * </pre>
   * </dl>
   */
   HRESULT SetClosedContourSide(in long iContourNumber, in CATBSTR iSide);

};

// Interface name : CATIAManufacturingPrismaticMachiningArea
#pragma ID CATIAManufacturingPrismaticMachiningArea "DCE:73986FE6-60FF-4d1c-A557B87D578B65EE"
#pragma DUAL CATIAManufacturingPrismaticMachiningArea

// VB object name : ManufacturingPrismaticMachiningArea (Id used in Visual Basic)
#pragma ID ManufacturingPrismaticMachiningArea "DCE:53A6CD90-1C35-4d89-9247304C11F528CE"
#pragma ALIAS CATIAManufacturingPrismaticMachiningArea ManufacturingPrismaticMachiningArea


#endif // CATIAManufacturingPrismaticMachiningArea_IDL
