# COPYRIGHT DASSAULT SYSTEMES 1999
#======================================================================
# Imakefile for module DTKSystem.m
#======================================================================
# 13.03.2018 : RAQ : Désactivation build sous MOBILE
#  Jul 2004  Optimisation O2                                        amr
#  Dec 2003  Modification pour le 64bits NT			    pr
#  Nov 1999  BUILT_OBJECT_TYPE=NONE for the bigger module           mmo
#            CATCurveBasedInfrastructure.m
#  Oct 1999  Ajout de la directive BUILD_PRIORITY=0 pour forcer     mmo
#            le build de cette libairie en premier c'est la 
#            librairie COMDYN_MODULE.
#  Oct 1999  supression de JS0ERROR JS0CORBA                        jfi
#  Jun 1999  Creation: Code generated by the CAA wizard             jfi
#======================================================================
#
# SHARED LIBRARY 
#
IMPACT_ON_IMPORT = YES

BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
BUILD_PRIORITY=0

LINK_WITH = 

#if os MOBILE           
BUILD=NO
#endif

OS = AIX
SYS_LIBS = -lxlf -lxlf90 -lxlfpad

OS = IRIX
SYS_LIBS = -lftn

# +++ PR64
# OS = Windows_NT
OS = intel_a
# +++ PR64

OS = HP-UX
#if os hpux_a
SYS_LIBS = -lf
#else
SYS_LIBS= -lF90
#endif                

OS = SunOS
SYS_LIBS = -lF77 -lM77
# +++ PR64

OS = intel_a64
LOCAL_FFLAGS = /I ../../LocalInterfaces
# +++ PR64

#
OS = Windows_NT
#if os win_b64
#else
OPTIMIZATION_CPP = /O2
#endif

