#
BUILT_OBJECT_TYPE=LOAD MODULE
#
#OS = COMMON
PROGRAM_NAME = CATSoftwareMgtAdmin
#
OS = UNIX
BUILD = NO

OS = Windows_NT
LINK_WITH = CXINSTDATA  NS0S3STR CXINSTUTIL
SYS_LIBS = version.lib 
MANIFESTUAC_ADMIN=yes
DESCRIPTION = "V5 Software Management"

