#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

# pour referencer le modules prereq
# meme vide, il faut le laisser

#LINK_WITH = SY0PAR CAPPFRM SpecsModeler VE0GROUP \
#   	    MF0STARTUP MF0ROOT MF0CST CK0FEAT \
#	    AD0XXBAS AC0XXLNK AC0SPBAS JS03TRA JS0MRSHL JS0FM JS0DSPA \
#	    JS0SCBAK JS0CTYP NS0S3STR JS0ERROR CO0LSTPV ON0PROP JS0CATOS \
#	    JS0COL JS0CORBA JS0COMP JS0LIB0 JS0LOGRP JS0SCBAK \
#	    JS0SETT JS0STR JT0TRCBK CO0HDICO YN000MAT YP00IMPL PRTFACTORY \
#	    SketcherItf PartItf YI00IMPL KnowledgeItf MecModItf SY0PAR
	    # JE DOIS CHANGER LA LIGNE CI_DESSUS

LOCAL_CPP_FLAGS = -g

