# COPYRIGHT Dassault Systemes 2003
#======================================================================
# Imakefile for module LiteralsEditorUUID.m
#======================================================================
#
#  Jan 2003  Creation: Code generated by the CAA wizard  soc
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
