#ifndef CATAxisOrientationType_IDL
#define CATAxisOrientationType_IDL
/*IDLREP*/
/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */
// COPYRIGHT Dassault Systemes 2006
//==================================================================================
/**
 * Orientation of coordinate system.
 * <b>Role:</b> CATAxisOrientationType defines the orientation type 
 * @param catSamCoordinateSystem_Undefined 
 *  The Orientation is not defined.
 * @param catSamCoordinateSystem_Cartesian 
 *  The Orientation is of cartesian type.
 * @param catSamCoordinateSystem_Cylindrical 
 *  The Orientation is of Cylindrical type.
 * @param catSamCoordinateSystem_Spherical 
 *  The Orientation is of Spherical type.
 */

//Use this enumeration in order to define the orientation of coordinate system

enum CATAxisOrientationType	
{
  catSamCoordinateSystem_Cartesian,
  catSamCoordinateSystem_Cylindrical,
  catSamCoordinateSystem_Spherical,
  catSamCoordinateSystem_Undefined
};

#endif  //CATAxisOrientationType_IDL
