#ifndef CATIAAnalysisEntities_IDL
#define CATIAAnalysisEntities_IDL
/*IDLREP*/
// COPYRIGHT Dassault Systemes 2000
//===================================================================
//
// CATIAAnalysisEntities.idl
// Automation interface for the AnalysisEntities element 
//
//===================================================================
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
#include "CATIACollection.idl"
#include "CATVariant.idl"

interface CATIAAnalysisEntity;

/**  
 * The collection of analysis entities.
 */
interface CATIAAnalysisEntities : CATIACollection 
{
/**
 * Creates a new analysis entity and adds it to the analysis entities collection.<br>
 * This collection may be extracted from an analysis set.The Analysis entity will be created on the Analysis Model.
 * @param iType under the form : oStartUpName@oCatalogName?oClientId (For User defined Startups).
 * The type of the entity to create.
 * @return The created analysis entity
 *
 * @sample
 * This example create <tt>ThisAnalysisEntity</tt> in the <tt>analysisEntities</tt> collection <br>
 * The entity to create is supposed to be a pressure defined in a load set.<br>
 * <pre>
 * Dim analysisEntities As CATIAAnalysisEntities
 * Dim ThisAnalysisEntity As AnalysisEntity
 * Set ThisAnalysisEntity = analysisEntities.Add("SAMPressure")
 * </pre>
 */
    HRESULT     Add
                ( in	  CATBSTR				                    iType, 
                  out   /*IDLRETVAL*/ CATIAAnalysisEntity oEntity );

 /**
  * Returns an analysis entity using its index or its name from the analysis entities collection. 
  * @param iIndex
  *   The index or the name of the analysis entity to retrieve from
  *   the collection of analysis entities.
  *   As a numerics, this index is the rank of the analysis entity
  *   in the collection.
  *   The index of the first analysis entity in the collection is 1, and
  *   the index of the last analysis entity is Count.
  *   As a string, it is the name you assigned to the analysis entity using
  *   the @href CATIABase#Name property or when creating it using
  *   the @href #Add method.
  * @return The retrieved analysis entity
  */
    HRESULT     Item(in                CATVariant           iIndex,
                 out /*IDLRETVAL*/ CATIAAnalysisEntity    oEntity);

/**
 * Removes a entity using its index or its name from the entity collection.
 * @param iIndex
 *   The index or the name of the entity to retrieve from
 *   the collection of entities.
 *   As a numeric, this index is the rank of the entity
 *   in the collection. The index of the first entity in the collection is 1,
 *   and the index of the last entity is Count.
 *   As a string, it is the name you assigned to the entity using
 *   the @href CATIABase#Name property.
*/

	HRESULT Remove(in CATVariant iIndex);


};

// Interface name : CATIAAnalysisEntities
#pragma ID CATIAAnalysisEntities "DCE:5613ca4c-92fb-11d4-9f0a00508b6a3154"
#pragma DUAL CATIAAnalysisEntities

// VB object name : AnalysisEntities (Id used in Visual Basic)
#pragma ID AnalysisEntities "DCE:5613ca4d-92fb-11d4-9f0a00508b6a3154"
#pragma ALIAS CATIAAnalysisEntities AnalysisEntities

#endif
