#ifndef CATIAAnalysisMeshManager_IDL
#define CATIAAnalysisMeshManager_IDL
/*IDLREP*/
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CATIAAnalysisMeshManager.idl
// Automation interface for the AnalysisMeshManager element 
//
//===================================================================

#include "CATIAAnalysisSet.idl"
interface CATIAAnalysisMeshParts;

/**  
 * The interface to access a CATIAAnalysisMeshManager.
 */
interface CATIAAnalysisMeshManager : CATIAAnalysisSet 
{
/**
  * Returns the meshpart collection from the current analysis mesh manager.
  */
#pragma PROPERTY AnalysisMeshParts
	HRESULT get_AnalysisMeshParts(out /*IDLRETVAL*/ CATIAAnalysisMeshParts oMeshParts);
};

// Interface name : CATIAAnalysisMeshManager
#pragma ID CATIAAnalysisMeshManager "DCE:a385ca50-dfb3-42ad-a2c8dda1df004104"
#pragma DUAL CATIAAnalysisMeshManager

// VB object name : AnalysisMeshManager (Id used in Visual Basic)
#pragma ID AnalysisMeshManager "DCE:aba30fed-cae6-4057-8b39a0cd37517508"
#pragma ALIAS CATIAAnalysisMeshManager AnalysisMeshManager

#endif
