
#ifndef CATISamExplicit_H
#define CATISamExplicit_H
//=================================================================================
// COPYRIGHT DASSAULT SYSTEMES 1999  
/**
  * @CAA2Level L1
  * @CAA2Usage U3
  */
//=================================================================================
#include "CATAnalysisInterface.h"
#include "CATAnalysisExplicitDefinitions.h"
#include "CATString.h"
#include "CATBaseUnknown.h"
#include "CATListOfInt.h"
#include "CATBoolean.h"

class CATAnalysisExplicitChild;
class CATAnalysisExplicitParent;
class CATAnalysisExplicitListUsr;
class CATAnalysisExplicitModel;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATAnalysisInterface IID IID_CATISamExplicit ;
#else
extern "C" const IID IID_CATISamExplicit ;
#endif

//------------------------------------------------------------------

/**
 * Interface to manage the Field model link.
 * <b>Role:</b> Interface used by an analysis feature to manage it's result view in the Field model.<br>
 * It means:
 * <ul>
 * <li> Creation of the Explicit object according to the physical type of the analysis feature.</li>
 * <li> Control the Life Cycle of the Explicit object(s) as the feature one (Remove, Undo/redo,...).</li>
 * <li> Retrieve Explicit object(s) associated to the feature.</li>
 * <li> Tools to generate a new version of explicit object(s). To be used for the implementation of @href CATISamExplicitation.</li>
 * </ul>
 * @see CATISamExplicitation
 */

class ExportedByCATAnalysisInterface CATISamExplicit: public CATBaseUnknown
{
	CATDeclareInterface;

	public :

/**
 * @nodoc
 * Translates Analysis feature into an explicit language.
 */
	virtual HRESULT Explicit() = 0; 

/**
 * @nodoc
 * Associates explicit datum with an analysis feature.
 * @param iContainingData
 * The  datum with an explicitation supposed to contain the 
 * result of the current analysis feature translation
 */
		virtual HRESULT Register(CATISamExplicit* iContainingData = NULL) = 0;

/**
 * @nodoc
 * Removes the explicit data corresponding to analysis feature.
 * @param iContainingData
 * the containing data from which the Explicit object(s) are removed. 
 * If NULL, Explicit object(s) will be removed from whole containing data.
 */
		virtual HRESULT Unregister(CATISamExplicit* iContainingData = NULL) = 0;

/**
 * Retrieves the Physical type of the feature.
 * @return the physical type identifer as String
 */
		virtual CATString GetPhysicalType() const = 0;

/**
 * Retrieves the Physical type of the feature.
 * @return the physical type identifer.
 */
		virtual CATSamPhysicalType GetPhysicalTypeNumber() const = 0;

/**
 * Retrieves the number of Explicit object(s) generated.
 * @return the number of explicit children.
 */
		virtual int GetExplicitTagsNumber() = 0;

/**
 * Retrieves the tag of the explicit datum corresponding to the given index.
 * @param iObjectIndex
 *    Index of the explicit datum. <br>
 * This index must be less or equal to the total number of Explicit object(s).
 *   @return
 *      the tag of the explicit datum.
 */
		virtual int GetExplicitTag(int iObjectIndex = 1) = 0;

/**
 *	 Retrieves the tags of the Explicit object(s) generated during the
 *	 translation.
 *   @param oExplicitTags
 *      The list of explicit tags.
 */
		virtual HRESULT GetExplicitTags(CATListOfInt& oExplicitTags) = 0;
	
/**
 *	 Retrieves one of the Explicit object(s) created for the analysis feature 
 *	 translation.
 *   @param oChild
 *      The Explicit datum corresponding to given index.
 *   @param iObjectIndex
 *      The index of the explicit datum. This index must be less or 
 *		equal to the total number of Explicit object(s).

 */
		virtual HRESULT GetExplicitObject(CATAnalysisExplicitChild &oChild,int iObjectIndex = 1) = 0;

/**
 *	 Retrieves the explicit datum corresponding to the given index.
 *   @param oExplObjects
 *      The list which contains the Explicit object(s) corresponding to the analysis feature
 *		translation.
 */
		virtual HRESULT GetExplicitObjects(CATAnalysisExplicitListUsr &oExplObjects) = 0;

/** @nodoc
 *	Private services for Life cycle management.
 *  @param iModelImpact Internal use Only.
 */

    virtual HRESULT ResetExplicitTags(CATBoolean iModelImpact=TRUE) = 0;

/**
 *	 Retrieves the explicit model associated.
 *   @param returns the CATAnalysisExplicitModel
 */

 		virtual CATAnalysisExplicitModel* GetExplicitModel() const = 0;

/**
 * Return data that currently contain the explicit entities of the given given type.
 * Explicit List of Objects generated by CATISamExplicitation Iplementation.
 * @param oContainingData
 * explicit List which contain the explicit version of this analysis entity.
 * @param iChildPhysType
 * the entity physical type dedicated to filter the returned containing data.
 * Warning! The explicitation of an analysis entity can consist in the creation of several kind
 * of explicit entities. On the other hand, we suppose that every entities of a given kind have
 * the same containing data.
 */
	 virtual HRESULT GetContainingData(CATAnalysisExplicitListUsr& iexplObjects,
                                     CATAnalysisExplicitListUsr& oContainingData,
                                     CATString* iChildPhysType= NULL) = 0;

/**
 * Update the explicit Lists of Objects that are created inside the field model.
 * The steps that are done in this method consists in :
 *<ul> 
 *<li> Delete the objects in the iexplObjects.</li>
 *<li> Create the link (parent/ Children) between the objects in the iContainingData 
 * and the iexplObjects objects.</li> </ul> 
 * @param iexplObjects    : List of pre-existing version.
 * @param iContainingData : List of containing data.
 * @param iNewObjects     : List of new version data.
 */

	 virtual HRESULT UpdateExplicitList(CATAnalysisExplicitListUsr& iexplObjects,
                                     CATAnalysisExplicitListUsr& iContainingData,
                                     CATAnalysisExplicitListUsr& iNewObjects) = 0;


 /**
  * @nodoc .
  * Set the activity state of an analysis feature.
	* @param iActive:
  *      param to specify the activity state of an analysis feature (True Feature is Active).
	*/
	  virtual HRESULT SetActivity(CATBoolean iActive) = 0 ;
    
 /**
  * @nodoc .
  * Get the activity state of an analysis feature.
	*/
	  virtual CATBoolean GetActivity() const = 0 ;

/**
 * Toolkit to manage local creation of deletion children.
 * This methode should not be used with objects that are already managed by the UpdateExplicitList method.
 * <b>Note:</b> In case of deletion this method will delete your object.
 * @param ilAdd informs about creation or deletion.
 *	<b>Legal values</b>:
 *	<br><tt>TRUE :</tt>  Create
 * 	<br><tt>FALSE:</tt>  Delete
 * @param iExplObjects Liste of objects to take into account.
 */
    virtual HRESULT LogCreateDelete (CATBoolean ilAdd,CATAnalysisExplicitListUsr& iExplObjects)  = 0;

    /**
 * @nodoc .
 * Log for Undo/Redo mechanism the AddChild / RemoveChild.
 * This method needs to be called only for link modification on existing objects.
 * @param iAddRemove : kind of modification.
 *	<b>Legal values</b>:
 *	<br><tt>1 :</tt>   AddChild
 * 	<br><tt>2:</tt>    RemoveChild
 * @param iParent : The parent.
 * @param iChildrenList : The children list.
 */

//	 virtual HRESULT LogChildModification(int iAddRemove,
//                                        CATAnalysisExplicitParent & iParent,
//                                        CATAnalysisExplicitListUsr& iChildrenList) = 0;

//=======================================================================================

};

CATDeclareHandler( CATISamExplicit, CATBaseUnknown );

#endif
