#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

BUILD = NO


LOCAL_LDFLAGS=-framework OpenGLES -framework GLKit

OS = Windows
BUILD = YES
LOCAL_CCFLAGS = -DFULL_NVFX
SYS_LIBS = -lcg -lcgGL

OS = iOS
BUILD = YES
LOCAL_CCFLAGS = -DOGLES2 -DLAME_USE -DFULL_NVFX

#OS = Android
#BUILD = YES
#LOCAL_CCFLAGS = -DOGLES2 -DLAME_USE -DFULL_NVFX
