#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#

#
OS = AIX
BUILD=NO
LINK_WITH=  VPMConfig db2 db2apie
LOCAL_LDFLAGS=  -e trueval
#
OS = HP-UX
BUILD=NO
LINK_WITH=  VPMConfig
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
#
OS = IRIX
BUILD=NO
#SYS_INCPATH =  -I$(WSROOT)/Db2/include/irix_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO VPMConfig  db2
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
LOCAL_LDFLAGS= -rpath /opt/IBMdb2/V5.0/lib32
#
OS = SunOS
BUILD=NO
#SYS_INCPATH =  -I$(WSROOT)/Db2/include/solaris_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO VPMConfig  db2
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY

OS = alpha_a
BUILD=NO

OS = intel_a
BUILD=NO
#SYS_INCPATH =  -I$(WSROOT)\Db2\Include\win_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO VPMConfig  db2cli
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
  








