#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATVisUUID \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# 
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
INCLUDED_MODULES = ToolsVisu

ALIASES_ON_IMPORT=CATGviUtilities CATGraphicProperties

LINK_WITH=$(LINK_WITH_FOR_IID)  \
AD0XXBAS \
JS03TRA \
JS0CORBA \
JS0ERROR \
VE0BASE \
CATViz \
VE0MDL \
JS0FM \

