/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef Cat3DColorInheritanceMode_h
#define Cat3DColorInheritanceMode_h

enum Cat3DColorInheritanceMode {
        cat3DColorInheritanceModeOff,
        cat3DColorInheritanceModeOn
};

#endif
