/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatDrawingStandard_h
#define CatDrawingStandard_h

enum CatDrawingStandard {
        catANSI,
        catISO,
        catJIS
};

#endif
