/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatDrawingViewType_h
#define CatDrawingViewType_h

enum CatDrawingViewType {
        catViewBackground,
        catViewFront,
        catViewLeft,
        catViewRight,
        catViewTop,
        catViewBottom,
        catViewRear,
        catViewAuxiliary,
        catViewIsom,
        catViewSection,
        catViewSectionCut,
        catViewDetail,
        catViewUntyped,
        catViewMain,
        catViewPure_Sketch,
        catViewUnfolded
};

#endif
