/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatDimFramedElement_h
#define CatDimFramedElement_h

enum CatDimFramedElement {
        catFraValue,
        catFraValueTol,
        catFraValueTolText
};

#endif
