/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIADrawingTable_h
#define CATIADrawingTable_h

#ifndef ExportedByDraftingPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __DraftingPubIDL
#define ExportedByDraftingPubIDL __declspec(dllexport)
#else
#define ExportedByDraftingPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByDraftingPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"
#include "CATSafeArray.h"
#include "CatTablePropertiesEnum.h"

class CATIADrawingLeaders;
class CATIADrawingText;
class CATIADrawingTextProperties;

extern ExportedByDraftingPubIDL IID IID_CATIADrawingTable;

class ExportedByDraftingPubIDL CATIADrawingTable : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_x(double & oPositionX)=0;

    virtual HRESULT __stdcall put_x(double oPositionX)=0;

    virtual HRESULT __stdcall get_y(double & oPositionY)=0;

    virtual HRESULT __stdcall put_y(double iPositionY)=0;

    virtual HRESULT __stdcall Move(double iDeltaX, double iDeltaY)=0;

    virtual HRESULT __stdcall get_Angle(double & oAngle)=0;

    virtual HRESULT __stdcall put_Angle(double iAngle)=0;

    virtual HRESULT __stdcall get_OrientationReference(CATLONG & oOri)=0;

    virtual HRESULT __stdcall put_OrientationReference(CATLONG iOri)=0;

    virtual HRESULT __stdcall Rotate(double iDeltaAngle)=0;

    virtual HRESULT __stdcall SetCellString(CATLONG iRow, CATLONG iCol, const CATBSTR & iString)=0;

    virtual HRESULT __stdcall GetCellString(CATLONG iRow, CATLONG iCol, CATBSTR & oString)=0;

    virtual HRESULT __stdcall SetCellObject(CATLONG iRow, CATLONG iCol, CATIADrawingText * iText)=0;

    virtual HRESULT __stdcall GetCellObject(CATLONG iRow, CATLONG iCol, CATIADrawingText *& oText)=0;

    virtual HRESULT __stdcall SetCellBorderType(CATLONG iRow, CATLONG iCol, CATLONG iType)=0;

    virtual HRESULT __stdcall GetCellBorderType(CATLONG iRow, CATLONG iCol, CatTableBorderType & oType)=0;

    virtual HRESULT __stdcall SetCellAlignment(CATLONG iRow, CATLONG iCol, CatTablePosition iAlign)=0;

    virtual HRESULT __stdcall GetCellAlignment(CATLONG iRow, CATLONG iCol, CatTablePosition & oAlign)=0;

    virtual HRESULT __stdcall SetCellName(CATLONG iRow, CATLONG iCol, const CATBSTR & iName)=0;

    virtual HRESULT __stdcall GetCellName(CATLONG iRow, CATLONG iCol, CATBSTR & oName)=0;

    virtual HRESULT __stdcall get_NumberOfRows(CATLONG & oRow)=0;

    virtual HRESULT __stdcall get_NumberOfColumns(CATLONG & oCol)=0;

    virtual HRESULT __stdcall SetRowSize(CATLONG iRow, double iRowSize)=0;

    virtual HRESULT __stdcall GetRowSize(CATLONG iRow, double & oRowSize)=0;

    virtual HRESULT __stdcall SetColumnSize(CATLONG iCol, double iColSize)=0;

    virtual HRESULT __stdcall GetColumnSize(CATLONG iCol, double & oColSize)=0;

    virtual HRESULT __stdcall AddRow(CATLONG iRow)=0;

    virtual HRESULT __stdcall RemoveRow(CATLONG iRow)=0;

    virtual HRESULT __stdcall AddColumn(CATLONG iCol)=0;

    virtual HRESULT __stdcall RemoveColumn(CATLONG iCol)=0;

    virtual HRESULT __stdcall get_AnchorPoint(CatTablePosition & oPos)=0;

    virtual HRESULT __stdcall put_AnchorPoint(CatTablePosition iPos)=0;

    virtual HRESULT __stdcall InvertMode(CatTableInvertMode iMode)=0;

    virtual HRESULT __stdcall get_ComputeMode(CatTableComputeMode & oMode)=0;

    virtual HRESULT __stdcall put_ComputeMode(CatTableComputeMode iMode)=0;

    virtual HRESULT __stdcall MergeCells(CATLONG iFirstRow, CATLONG iFirstCol, CATLONG iNbRowMerge, CATLONG iNbColMerge)=0;

    virtual HRESULT __stdcall UnMergeCells(CATLONG iRow, CATLONG iCol)=0;

    virtual HRESULT __stdcall GetCellsMerge(CATSafeArrayVariant & oListOfMergeCells)=0;

    virtual HRESULT __stdcall GetMergeInfos(CATLONG iRow, CATLONG iCol, CATLONG & oFirstRow, CATLONG & oFirstCol, CATLONG & oNbRow, CATLONG & oNbCol)=0;

    virtual HRESULT __stdcall get_Leaders(CATIADrawingLeaders *& oLeaders)=0;

    virtual HRESULT __stdcall get_TextProperties(CATIADrawingTextProperties *& oTextProperties)=0;


};

CATDeclareHandler(CATIADrawingTable, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIADrawingText.h"
#include "CatTextAnchorPosition.h"
#include "CatTextFrameType.h"
#include "CatTextProperty.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
