/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIADrawingPictures_h
#define CATIADrawingPictures_h

#ifndef ExportedByDraftingPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __DraftingPubIDL
#define ExportedByDraftingPubIDL __declspec(dllexport)
#else
#define ExportedByDraftingPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByDraftingPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIACollection.h"
#include "CATVariant.h"

class CATIADrawingPicture;

extern ExportedByDraftingPubIDL IID IID_CATIADrawingPictures;

class ExportedByDraftingPubIDL CATIADrawingPictures : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Add(const CATBSTR & iDrawingPicturePath, double iPositionX, double iPositionY, CATIADrawingPicture *& oNewDrawingPictureInst)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIADrawingPicture *& oItem)=0;


};

CATDeclareHandler(CATIADrawingPictures, CATIACollection);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
