/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatPointsProjectionMode_h
#define CatPointsProjectionMode_h

enum CatPointsProjectionMode {
        catPointsProjectionModeOff,
        catPointsProjectionModeOn
};

#endif
