/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatProjViewType_h
#define CatProjViewType_h

enum CatProjViewType {
        catRightView,
        catLeftView,
        catTopView,
        catBottomView,
        catRearView
};

#endif
