/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatTextFlipMode_h
#define CatTextFlipMode_h

enum CatTextFlipMode {
        catTextNoFlip,
        catTextHorizontalFlip,
        catTextVerticalFlip,
        catTextHorizontalAndVerticalFlip,
        catTextAutoFlip
};

#endif
