/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatTextFrameType_h
#define CatTextFrameType_h

enum CatTextFrameType {
        catNone,
        catRectangle,
        catSquare,
        catCircle,
        catScoredCircle,
        catDiamond,
        catTriangle,
        catRightFlag,
        catLeftFlag,
        catBothFlag,
        catOblong,
        catEllipse,
        catCustom
};

#endif
