// COPYRIGHT DASSAULT SYSTEMES 2010, ALL RIGHTS RESERVED.
//===================================================================
//
// CATCGMTessParam
//
//===================================================================
//
// August 2010  Creation: NDO
//===================================================================
#ifndef CATCGMTessParam_H
#define CATCGMTessParam_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
*/

#include "CATGMModelInterfaces.h"
#include "CATMathConstant.h"
#include "CATMathLimits.h"

class CATCGMTessParam;  // To prevent CAA tags in doc generated by Doxygen.


/**
* Class for the tessellation parameters.  
*/
class ExportedByCATGMModelInterfaces CATCGMTessParam
{

public:

  /**
   * Default constructor.
   */
  inline CATCGMTessParam ();

  /**
   * Constructs an instance of CATCGMTessParam given the sag and optional step and angle parameters.
   * @param iSag
   *   The sag to be met by the tessellated body.
   * @param iStep
   *   An optional step size parameter not to be exceeded.  
   * @param iMaxAngle
   *   An optional angle parameter not to be exceeded.
   */
  inline CATCGMTessParam (float iSag, 
                          float iStep = (float) CATMathInfinite, 
                          float iMaxAngle = (float) (CATPI * 0.25));

  ~CATCGMTessParam () {}

public:

  /**
   * Returns the sag.
   */
  inline float GetSag () const;

  /**
   * Returns the step size.
   */
  inline float GetStep () const;

  /**
   * Returns the angle not to be exceeded .
   */
  inline float GetMaxAngle () const;

public:

  /**
   * Sets the sag.
   */
  inline void SetSag (float iSag);

  /**
   * Sets the step size.
   */
  inline void SetStep (float iStep);

  /**
   * Sets the angle not to be exceeded.
   */
  inline void SetMaxAngle (float iMaxAngle);

protected:
  
  float _Sag;
  float _Step;
  float _MaxAngle;

};


inline CATCGMTessParam::CATCGMTessParam () :
  _Sag (0), 
  _Step (0), 
  _MaxAngle (0)
{
}

inline CATCGMTessParam::CATCGMTessParam (float iSag, float iStep, float iMaxAngle) :
  _Sag (iSag), 
  _Step (iStep), 
  _MaxAngle (iMaxAngle)
{
}

inline float CATCGMTessParam::GetSag () const
{
  return _Sag;
}

inline float CATCGMTessParam::GetStep () const
{
  return _Step;
}

inline float CATCGMTessParam::GetMaxAngle () const
{
  return _MaxAngle;
}

inline void CATCGMTessParam::SetSag (float iSag)
{
  _Sag = iSag;
}

inline void CATCGMTessParam::SetStep (float iStep)
{
  _Step = iStep;
}

inline void CATCGMTessParam::SetMaxAngle (float iMaxAngle)
{
  _MaxAngle = iMaxAngle;
}

#endif // !CATCGMTessParam_H
