#ifndef CATIAConstraintSatisfaction_IDL
#define CATIAConstraintSatisfaction_IDL
/*IDLREP*/

               
// COPYRIGHT DASSAULT SYSTEMES 1999

#include "CATIARelation.idl"
#include "CATIAParameter.idl"
#include "CATIASetOfEquation.idl"

/** 
 * @CAA2Level L1
 * @CAA2Usage U3
 */

/**
 * Represents the set of equation.
 */
interface CATIAConstraintSatisfaction : CATIASetOfEquation
{
	/**
	* Solves the constraint satisfaction problem.
	*/
	HRESULT Solve();
};
// Interface name : CATIAConstraintSatisfaction
#pragma ID CATIAConstraintSatisfaction "DCE:b0814111-8916-11d6-807a0010b5d45472"
#pragma DUAL CATIAConstraintSatisfaction

// VB object name : SetOfEquation (Id used in Visual Basic)
#pragma ID ConstraintSatisfaction "DCE:ffada811-8916-11d6-807a0010b5d45472"
#pragma ALIAS CATIAConstraintSatisfaction ConstraintSatisfaction


#endif // CATIAConstraintSatisfaction_IDL

