#ifndef CATIALength_IDL
#define CATIALength_IDL
/*IDLREP*/

               
// COPYRIGHT DASSAULT SYSTEMES 1999

/** 
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIADimension.idl"

/**
 * Represents the length parameter.
 * The following example shows how to create it: 
 * <pre>
 * Dim CATDocs As Documents
 * Set CATDocs = CATIA.Documents
 * Dim part1 As Document
 * Set part1   = CATDocs.Add("CATPart") 
 * Dim Width As Length
 * Set width   = part1.Part.Parameters.CreateDimension("width", "LENGTH", 20.)
 * </pre>
 * By default the units are the default units of the IS of units.
 */

//-----------------------------------------------------------------
interface CATIALength : CATIADimension
{
};

// Interface name : CATIALength
#pragma ID CATIALength "DCE:dc86d83d-6756-11d1-a27f0000f87546fd"
#pragma DUAL CATIALength

// VB object name : Length (Id used in Visual Basic)
#pragma ID Length "DCE:dc8cce1e-6756-11d1-a27f0000f87546fd"
#pragma ALIAS CATIALength Length


#endif
// CATIALength_IDL

