#ifndef CatOptimizationType_IDL
#define CatOptimizationType_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 2000
//--------------------------------------------------------------------------
// CATOptimizationType Enum
// tvq 
//--------------------------------------------------------------------------


/** 
 * @CAA2Level L1
 * @CAA2Usage U1
 */


// Optimization types
    /**
     * Optimization types.
     * @param catMinimum
     * minimum of objective parameter is looked for
     * @param catMaximum
     * maximum of objective parameter is looked for
	 * @param catTargetValue
	 * defined target is looked for for objective parameter
	 * @param catOnlyBoundedVariation
	 * no doc.
	 * @param catNone
	 * when the type of the optimization is not defined yet.
	 * @param catCstOnly
	 * when the type of the optimization handles only constraints.

     */
enum CatOptimizationType
{
  catMinimum,
  catMaximum,
  catTargetValue,
  catOnlyBoundedVariation,
  catNone, 
  catCstOnly
};

#endif
