#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
LINK_WITH = SystemUUID JS0ERROR CATXMLParserItf

INCLUDED_MODULES = xmlxerces xmlicuuc XMLUtils

CXX_EXCEPTION =

OS = intel_a
LOCAL_CCFLAGS = -DPROJ_XMLUTIL -DPROJ_XMLPARSER -DPROJ_SAX4C -DPROJ_DOM -DPROJ_PARSERS -DPROJ_VALIDATORS \
-DNATIVE_EXCEPTION -DXML_USE_WIN32_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS

OS = intel_c
LOCAL_CCFLAGS = -DPROJ_XMLUTIL -DPROJ_XMLPARSER -DPROJ_SAX4C -DPROJ_DOM -DPROJ_PARSERS -DPROJ_VALIDATORS \
-DNATIVE_EXCEPTION -DXML_USE_WIN32_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS 

OS = win_b64
LOCAL_CCFLAGS = -DPROJ_XMLUTIL -DPROJ_XMLPARSER -DPROJ_SAX4C -DPROJ_DOM -DPROJ_PARSERS -DPROJ_VALIDATORS \
-DNATIVE_EXCEPTION -DXML_USE_WIN32_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS 

OS = win_a
LOCAL_CCFLAGS = -DPROJ_XMLUTIL -DPROJ_XMLPARSER -DPROJ_SAX4C -DPROJ_DOM -DPROJ_PARSERS -DPROJ_VALIDATORS \
-DNATIVE_EXCEPTION -DXML_USE_WIN32_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS -D_WIN9X_SOURCE

## @c++ansi fbq 2004-08-03.17:53:01 [win_b support] ##
OS = win_b
LOCAL_CCFLAGS = -DPROJ_XMLUTIL -DPROJ_XMLPARSER -DPROJ_SAX4C -DPROJ_DOM -DPROJ_PARSERS -DPROJ_VALIDATORS \
-DNATIVE_EXCEPTION -DXML_USE_WIN32_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS

OS = IRIX
LOCAL_CCFLAGS= -DNATIVE_EXCEPTION -DXML_USE_ICONV_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS
CXX_EXCEPTION=
LOCAL_LDFLAGS = -v
CXX_TEMPLATE_INC    = -auto_include
CXX_TEMPLATE_PRELK  = -prelink
CXX_TEMPLATE_INST   = -ptused
SYS_LIBS = -lgen

OS = AIX
LOCAL_CCFLAGS =  -DXML_USE_ICONV_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS -DNATIVE_EXCEPTION -D_AIX
SYS_LIBS=-liconv

OS = SunOS
LOCAL_CCFLAGS = -DXML_USE_ICONV_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS -DNATIVE_EXCEPTION -instances=static


OS = HP-UX
LOCAL_CCFLAGS = -DNATIVE_EXCEPTION -DXML_USE_ICONV_TRANSCODER -DXML_USE_V5_MSGLOADER -DAPP_NO_THREADS
LOCAL_POST_CCFLAGS = +inst_all

