#@ autoformat 16:08:07
# COPYRIGHT Dassault Systemes 2010
#======================================================================
# Imakefile for module CATGuiContour.m
#======================================================================
#
#  Sep 2010  Creation: Code generated by the CAA wizard  kqz
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 

LINK_WITH_V5_ONLY=
#
LINK_WITH_V6_ONLY=
#

LINK_WITH = \
    $(LINK_WITH_V5_ONLY)           \
    $(LINK_WITH_V6_ONLY)           \ 
    CATMecModLiveUseItf            \ # CATMecModLiveUseItf            CATMecModLiveUseItf
    CATSurfacicInterfaces          \ # CATSurfacicInterfaces          CATSurfacicInterfaces
    CATSurfResError                \ # CATSurfacicResources           CATSurfacicResources
    CATSurfacicUIResources         \ # CATSurfacicUIResources         CATSurfacicUIResources
    CATV6V5MonocodeServices        \ # CATV6V5ModelServices           CATV6V5ModelServices
    DI0PANV2                       \ # Dialog                         DI0PANV2
    DI0STATE                       \ # DialogEngine                   CATDialogEngine
    NewTopologicalObjectsItf       \ # GMModelInterfaces              CATGMModelInterfaces
    CATGitInterfaces               \ # GSMInterfaces                  CATGitInterfaces
    CATGMGeometricInterfaces       \ # GeometricObjects               CATGMGeometricInterfaces
    CATInteractiveInterfaces       \ # InteractiveInterfaces          CATInteractiveInterfaces
    KnowledgeItf                   \ # KnowledgeInterfaces            KnowledgeItf
    YN000MAT                       \ # Mathematics                    CATMathematics
    SpecCmd                        \ # MechanicalModelerUI            CATMechanicalModelerUI
    CATObjectModelerBase           \ # ObjectModelerBase              CATObjectModelerBase
    CATObjectSpecsModeler          \ # ObjectSpecsModeler             CATObjectSpecsModeler
    JS0FM                          \ # System                         JS0FM
    NS0S3STR                       \ # System                         JS0GROUP
    CATSysTS                       \ # SystemTS                       CATSysTS
#

OS = COMMON
#if defined(CATIAR201)
LINK_WITH_V6_ONLY= \
	CATAfrItf                      \ # AfrInterfaces                  CATAfrItf
    CATAfrFrame                    \ # AfrFoundation                  CATAfrFoundation
    CATGSMUseItf                   \ # CATGSMUseItf                   CATGSMUseItf
    CATMecModUIUseItf              \ # CATMecModUIUseItf              CATMecModUIUseItf
    CATMecModUseItf                \ # CATMecModUseItf                CATMecModUseItf
    CATSurfResError                \ # CATSurfacicResources           CATSurfacicResources
	CATSurfResMecMod               \ # CATSurfacicResources           CATSurfResMecMod
	CATSurfacicResourcesInit       \ # CATSurfacicResources           CATSurfacicResourcesInit
    CATSurfacicUtilities           \ # CATSurfacicResources           CATSurfacicResources
    CATV6V5MonocodeServices        \ # CATV6V5ModelServices           CATV6V5ModelServices
	CATMagnitude                   \ # Magnitude                      CATMagnitude
    MecModItfCPP                   \ # MecModInterfaces               CATMecModInterfaces
    MecModLiveItf                  \ # MecModLiveInterfaces           CATMecModLiveInterfaces
    MF0GEOM                        \ # MechanicalModeler              CATMechanicalModeler
    CATVisItf                      \ # VisualizationInterfaces        CATVisItf
#
#else
#if defined(CATIAV5R21)
LINK_WITH_V5_ONLY= \
	CATLifDictionary               \ # LiteralFeatures                CATLiteralFeatures
    CD0FRAME                       \ #                                
    CATViz                         \ #                                
#
#endif
#endif
