#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=EL LIBRARY

LINK_WITH = CATVizBase JS0CORBA JS03TRA JS0STR JS0SCBAK CO0LSTPV CO0HTAB YN000MAT JS0FM CATMathStream JS0MT

LOCAL_CCFLAGS  = -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS   = -DCATVIZ_SPECIFICATION


OS = AIX

OS = HP-UX

OS = IRIX
LOCAL_CCFLAGS  = -float -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS   = -float -DCATVIZ_SPECIFICATION

OS = SunOs

OS = wnt40i 
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION

OS = wnt40a
LOCAL_CCFLAGS = -D_WNT40A_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40A_SOURCE -DCATVIZ_SPECIFICATION
