/**
 * @CAA2Level L0
 * @CAA2Usage U5
 */
// COPYRIGHT Dassault Systemes 2001
//===================================================================
//
// CATISweptAble.h
// Define the CATISweptAble interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2001  Creation: Code generated by the CAA wizard  SBC
//===================================================================
#ifndef CATISweptAble_H
#define CATISweptAble_H

#include "SMTInterfacesItfCPP.h"
#include "CATBaseUnknown.h"

#include "CATMathTransformation.h"

#include "CATMathTransformation.h"
#include "CATIAProduct.h"

extern ExportedBySMTInterfacesItfCPP IID IID_CATISweptAble ;

//------------------------------------------------------------------

/**
 * Describe the functionality of your interface here
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class ExportedBySMTInterfacesItfCPP CATISweptAble: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
	
	virtual HRESULT GetMovingProducts (CATIAProduct **& oProductsToSwept, int& oNbProducts)=0;
	virtual HRESULT GetDuration (double& oDuration)=0 ;
	virtual HRESULT SetCurrentTime (double iTime)=0;
	virtual HRESULT GetNextTime (double& iTime)=0;
	virtual HRESULT GetCurrentPosition (int iProductIndex, CATMathTransformation &Matrice)=0;
	virtual HRESULT Clean()=0;
	virtual HRESULT GetMovingElements (CATBaseUnknown **& oElementsToSwept, int& oNbElements)=0;

};


CATDeclareHandler( CATISweptAble, CATBaseUnknown );
//------------------------------------------------------------------

#endif
