// COPYRIGHT Dassault Systemes 2002
//===================================================================
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
 
#ifndef CATIASweptVolume_IDL
#define CATIASweptVolume_IDL
/*IDLREP*/

#include "CATIABase.idl"

/**  
 * Interface to access a CATIASweptVolume
 */

interface CATIASweptVolume : CATIABase 
{
		
};

// Interface name : CATIAPartComp
#pragma ID CATIASweptVolume "DCE:8c4197e6-39a4-0000-0280030d89000000"
#pragma DUAL CATIASweptVolume

// VB object name : SweptVolume (Id used in Visual Basic)
#pragma ID SweptVolume "DCE:8c41986d-9c06-0000-0280030d89000000"
#pragma ALIAS CATIASweptVolume SweptVolume

#endif
