// COPYRIGHT Dassault Systemes 2002
//===================================================================
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
 
#ifndef CATIADMOThickness_IDL
#define CATIADMOThickness_IDL
/*IDLREP*/

#include "CATIABase.idl"


/**  
 * Interface to access a CATIADMOThickness  
 */
interface CATIADMOThickness : CATIABase 
{
		
};

// Interface name : CATIADMOThickness
#pragma ID CATIADMOThickness "DCE:c2807c00-24ad-11d3-a796006094eb381a"
#pragma DUAL CATIADMOThickness

// VB object name : DMOThickness (Id used in Visual Basic)
#pragma ID DMOThickness "DCE:c2807c01-24ad-11d3-a796006094eb381a"
#pragma ALIAS CATIADMOThickness DMOThickness

#endif
