/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIABehaviorVBScript_h
#define CATIABehaviorVBScript_h

#ifndef ExportedByCO0BPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CO0BPubIDL
#define ExportedByCO0BPubIDL __declspec(dllexport)
#else
#define ExportedByCO0BPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCO0BPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABehavior.h"

class CATIABase;

extern ExportedByCO0BPubIDL IID IID_CATIABehaviorVBScript;

class ExportedByCO0BPubIDL CATIABehaviorVBScript : public CATIABehavior
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall TestInternal(const CATBSTR & pName, CATLONG & iExist)=0;

    virtual HRESULT __stdcall GetInternal(const CATBSTR & pName, CATIABase *& oValue)=0;

    virtual HRESULT __stdcall PutInternal(const CATBSTR & pName, CATIABase * oValue)=0;

    virtual HRESULT __stdcall Start()=0;

    virtual HRESULT __stdcall Done()=0;

    virtual HRESULT __stdcall Suspend()=0;

    virtual HRESULT __stdcall Cancel()=0;


};

CATDeclareHandler(CATIABehaviorVBScript, CATIABehavior);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
