#
# Module : CATTechnomogicalPackageUI.m
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
#

LINK_WITH = JS0GROUP
        
#

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
#LINK_WITH = ... $(WIZARD_LINK_MODULES) ...
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP JS0FM JS0GROUP CATTechnologicalPackageUIItfUUID 
# END WIZARD EDITION ZONE
