#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= SHARED LIBRARY

OS = COMMON

LINK_WITH = VE0BASE YN000MAT DI0PANV2 JS0GROUP JS0FM CD0FRAME CD0WIN AD0XXBAS CD0STWIN CATViz

OS = AIX

OS = HP-UX

OS = IRIX
SYS_LIBS = -lXt

OS = SunOS
SYS_LIBS = -lsocket -lnsl -lXt

OS = Windows_NT
SYS_LIBS = vfw32.lib wsock32.lib
LOCAL_LDFLAGS =  $(SUB_CON)
