#
BUILT_OBJECT_TYPE=LOAD MODULE
LINK_WITH =  DI0PANV2 CATDlgStandard JS0SCBAK JS0CORBA JS0FM JS0STR JS0ERROR NS0S3STR NS0S1MSG CXINSTUTIL WFTOCTools

OS = Windows_NT
LOCAL_LDFLAGS=$(SUB_WIN)
MKMFC_DEPENDENCY=Yes 



