/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAColorSTDObjectSettingAtt_h
#define CATIAColorSTDObjectSettingAtt_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByStructurePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __StructurePubIDL
#define ExportedByStructurePubIDL __declspec(dllexport)
#else
#define ExportedByStructurePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByStructurePubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIASettingController.h"

extern ExportedByStructurePubIDL IID IID_CATIAColorSTDObjectSettingAtt;

class ExportedByStructurePubIDL CATIAColorSTDObjectSettingAtt : public CATIASettingController
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetShapeColor(CATLONG & oShapeColorR, CATLONG & oShapeColorG, CATLONG & oShapeColorB)=0;

    virtual HRESULT __stdcall SetShapeColor(CATLONG iShapeColorR, CATLONG iShapeColorG, CATLONG iShapeColorB)=0;

    virtual HRESULT __stdcall GetShapeColorInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetShapeColorLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall GetPlateColor(CATLONG & oPlateColorR, CATLONG & oPlateColorG, CATLONG & oPlateColorB)=0;

    virtual HRESULT __stdcall SetPlateColor(CATLONG iPlateColorR, CATLONG iPlateColorG, CATLONG iPlateColorB)=0;

    virtual HRESULT __stdcall GetPlateColorInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetPlateColorLock(CAT_VARIANT_BOOL iLocked)=0;


};

CATDeclareHandler(CATIAColorSTDObjectSettingAtt, CATIASettingController);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATSafeArray.h"
#include "CATVariant.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
