/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAStrAnchorPoint_h
#define CATIAStrAnchorPoint_h

#ifndef ExportedByStructurePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __StructurePubIDL
#define ExportedByStructurePubIDL __declspec(dllexport)
#else
#define ExportedByStructurePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByStructurePubIDL
#endif
#endif

#include "CATIABase.h"
#include "CATSafeArray.h"

class CATIADocument;
class CATIAParameter;

extern ExportedByStructurePubIDL IID IID_CATIAStrAnchorPoint;

class ExportedByStructurePubIDL CATIAStrAnchorPoint : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetCoordinates(CATSafeArrayVariant & oCoord)=0;


};

CATDeclareHandler(CATIAStrAnchorPoint, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIAAnalyze.h"
#include "CATIACollection.h"
#include "CATIAMove.h"
#include "CATIAParameters.h"
#include "CATIAPosition.h"
#include "CATIAProduct.h"
#include "CATIAPublications.h"
#include "CATIAStrObject.h"
#include "CATIAStrServices.h"
#include "CATVariant.h"
#include "CatFileType.h"
#include "CatProductSource.h"
#include "CatRepType.h"
#include "CatWorkModeType.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
