/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAStrCutback_h
#define CATIAStrCutback_h

#ifndef ExportedByStructurePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __StructurePubIDL
#define ExportedByStructurePubIDL __declspec(dllexport)
#else
#define ExportedByStructurePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByStructurePubIDL
#endif
#endif

#include "CATIAAssemblyFeature.h"
#include "CATIAStrServices.h"

class CATIADocument;
class CATIAParameter;
class CATIAStrAnchorPoint;
class CATIAStrSection;

extern ExportedByStructurePubIDL IID IID_CATIAStrCutback;

class ExportedByStructurePubIDL CATIAStrCutback : public CATIAAssemblyFeature
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Type(CatStrCutbackType & oCutback)=0;

    virtual HRESULT __stdcall get_Offset(CATIAParameter *& oOffset)=0;


};

CATDeclareHandler(CATIAStrCutback, CATIAAssemblyFeature);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIAParameter.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
