# COPYRIGHT DASSAULT SYSTEMES 2003
#
# LOAD MODULE for VaultClientSetup.m
#

BUILT_OBJECT_TYPE = LOAD MODULE

LINK_WITH = JS0GROUP JS0FM DI0PANV2 VaultClientSetupDLL CommonSetupDLLA CXINSTUTIL

OS = Windows_NT 
MKMFC_DEPENDENCY=Yes
LOCAL_LDFLAGS = $(SUB_WIN)

OS = win_b64
#BUILD=NO

OS = SunOS
SYS_LIBS = -lXm -lXt -lX11

OS = aix_a64
#BUILD=NO

OS = irix_a64
BUILD=NO
