#ifndef CatVisuIn3DMode_IDL
#define CatVisuIn3DMode_IDL
// COPYRIGHT DASSAULT SYSTEMES 2005
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 * 3D Visu Mode.
 * @param catShowAll
 *  Show all geometry and annotation in the 3D Viewer.
 * @param catHideAll
 *  Hide all geometry and annotation in the 3D Viewer.
 */
enum CatVisuIn3DMode 
{	
  catShowAll, 
  catHideAll  
};

#endif


