#ifndef CatViewSide_IDL
#define CatViewSide_IDL
// COPYRIGHT DASSAULT SYSTEMES 2005
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 * CatViewSide is used in conjonction with a reference View2DL
 * and a ViewBox.
 * It then determines precisely a View2DL type in the ViewBox.
 * example: with the default ViewBox:
 *  - Front + TopSide  = Top.
 *  - Right + LeftSide = Front.
 *  - Front + TRCorner = isometric on the corner near Front, Right, Top.
 */
enum CatViewSide 
{	
  catTopSide   , 
  catBottomSide,   
  catLeftSide  , 
  catRightSide , 
  catTLCorner  ,
  catTRCorner  ,
  catBLCorner  ,
  catBRCorner  
};

#endif


