// COPYRIGHT DASSAULT SYSTEMES 2000
//===================================================================
//
// CATIPDMId.h
// Define the CATIPDMId interface
//
//===================================================================
//

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

// Usage notes:
//   Retrieve PDM Identifier information
//
//===================================================================
//
//  Apr 2000  Creation: Code generated by the CAA wizard  GDC
//  Oct-02    Moving the intf to CATPDMInterfaces and renaming it
//===================================================================
#ifndef CATIPDMId0_H
#define CATIPDMId0_H

#include "CATPDMBaseItfCPP.h"
#include "CATBaseUnknown.h"
#include "sequence_octet.h"

class CATUnicodeString;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATPDMBaseItfCPP IID IID_CATIPDMId0 ;
#else
extern "C" const IID IID_CATIPDMId0 ;
#endif


//------------------------------------------------------------------

/**
 * Retrieve PDM Identifier information
 */
class ExportedByCATPDMBaseItfCPP CATIPDMId0: public CATBaseUnknown
{
  CATDeclareInterface;

public:
	
//-----------------------------------------------------------------------
/**   Returns the PDM Environment
 *
 *    @param iIID
 *      IID
 *    @param oPDMEnvironment
 *      PDM Environment.
 *
 *    @return
 *      S_OK PDM Environment found.
 *      else E_FAIL
 */
virtual HRESULT GetPDMEnvironment(const IID &iIID, void** oPDMEnvironment) = 0;

//-----------------------------------------------------------------------
/**   Returns the identifier of the PDM using this service, 
 *    similar method is GetPrintableId
 *
 *    @param oIdentifier
 *      Identifier.
 *
 *    @return
 *      S_OK Identifier found.
 *      else E_FAIL
 */
virtual HRESULT GetIdentifier(SEQUENCE(octet) &  oIdentifier) = 0;
	
//-----------------------------------------------------------------------
/**   Returns the Type of the PDM using this service
 *
 *    @param oType
 *      PDM Type.
 *
 *    @return
 *      S_OK PDM Type found.
 *      else E_FAIL
 */
virtual HRESULT GetType(CATUnicodeString & oType) = 0;

//-----------------------------------------------------------------------
/**   Returns the Id of the PDM using this service 
 *
 *    @param oIdentifier
 *      Identifier.
 *
 *    @return
 *      S_OK Identifier found.
 *      else E_FAIL
 */
virtual HRESULT GetPrintableId(CATUnicodeString &  oIdentifier) = 0;

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

CATDeclareHandler( CATIPDMId0, CATBaseUnknown );

#endif
