// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATIPDMUnixNTMapping.h
//  mapping of UNIX and NT paths while loading & saving a document to PDM
//===================================================================
//
// Usage notes:
//  Interface to implement  to define a mapping between UNIX path and NT mount of this path
// This interface has to be implemented on the late type : CATPdmUnixNtMapping
//
//===================================================================
//
//  Sep 2002  Creation: Code generated by the CAA wizard  rci
//===================================================================
#ifndef CATIPDMUnixNTMapping_H
#define CATIPDMUnixNTMapping_H

#include "CATPDMBaseItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

/**
 * @CAA2Level L1
 * @CAA2Usage U5
 */ 

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATPDMBaseItfCPP IID IID_CATIPDMUnixNTMapping;
#else
extern "C" const IID IID_CATIPDMUnixNTMapping ;
#endif

//------------------------------------------------------------------

/**
*  Interface to implement  to define a mapping between UNIX path and NT mount of this path
* This interface has to be implemented on the late type : CATPdmUnixNtMapping
 */
class ExportedByCATPDMBaseItfCPP CATIPDMUnixNTMapping: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
     * Method used while loading document from PDM, enabling to mapp a UNIX disc on NT
     * <dl>
     * <pre>
     *       
		 * The implementation has to check that the disc is really mapped
          *   @param iUnixPath
           *      Unix path
          *   @param oNTPath
           *      mapped NT path
     * </pre>
     * </dl>
     */
	virtual HRESULT UnixPathToNTPath(CATUnicodeString iUnixPath, CATUnicodeString& oNTPath) = 0;

    /**
     * Method used while saving document to PDM to access Unix path for save.
	 * The environnement vairiable CATVpmTemp has to be valuated to descibe 
	 *  where to save data, and NtPathToUnix is ised to transfer data on the right
	 *	server ....
     * <dl>
     * <pre>
     *       
		 * will be used only if the environnement variable CATVpmTemp is valuated
          *   @param iUnixPath
           *      Unix path
          *   @param oNTPath
           *      mapped NT path
     * </pre>
     * </dl>
     */
	virtual HRESULT NtPathToUnix(CATUnicodeString iNTPath , CATUnicodeString& oUnixPath) = 0;

};

//------------------------------------------------------------------

#endif
