BUILT_OBJECT_TYPE = SHARED LIBRARY
ENCODING_KEY = System
LINK_WITH = JS0LIB0 NS0S3STR JS0LCC JS0STDLIB JS0MT JS0DSLOCK JS0DSLUTILS 
#
# Values for COMMON_CCFLAGS
#  -DAUTH_MINFWS                        # To authorize the predefined list of frameworks
#  -DLAST_CHANCE_LICENSE=x::Make        # required
#
COMMON_CCFLAGS = -DUKU_SUPPORT\
                 -DLAST_CHANCE_LICENSER=DSUKU::Make\
                 -DAUTH_MINFWS\
                 -UHACK_TEST

LOCAL_CCFLAGS = $(COMMON_CCFLAGS)

OS = AIX
# Force AIX to store strings in Writeable are
LOCAL_CCFLAGS = $(COMMON_CCFLAGS)\
                -qNORO\
                -D_AIX_SOURCE


OS = Windows_NT
BUILT_OBJECT_TYPE = EL LIBRARY
BUILD_DLK = YES
#SRC_LINK_WITH = JS0DSLIC JS0DSLUTILS JS0LCC 

#if (defined MK_MSCVER) 
#if (MK_MSCVER >= 1900)   
MSVCR_FLAGS = -D__MSVCR_DLL_NAME="vcruntime140.dll" -D_ENABLE_UCRTBASE_ATEXIT
#elif (MK_MSCVER == 1700)    
MSVCR_DFLAG = -D__MSVCR_DLL_NAME="MSVCR110.dll"
#endif
#endif

NT_CCFLAGS    = -DDSUKU_REQUEST  -DUKU_SUPPORT -DHTTPARCH -D__OPENSSL -D__JS0DSLOCK -DUKU_LICENSE_2 -D__JS0LCC -D_DISABLE_UNINITALIZED_PRODMAN_STATIC_STRUCT  ${MSVCR_FLAGS} 
LOCAL_CCFLAGS = $(NT_CCFLAGS) $(COMMON_CCFLAGS)  -D__JS0MT -D_X86_SOURCE -D__JS0LCC -DWINNT -URESTORE_TZ

LINK_WITH   = LCCArch DSLSArch SSLArch JS0LIB0 NS0S3STR JS0STDLIB JS0DSLOCK  
LOCAL_LDFLAGS = /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:uafxcw.lib
SYS_LIBS =  wsock32.lib wininet.lib dnsapi.lib Ws2_32.lib PowrProf.lib




OS = iOS
BUILT_OBJECT_TYPE = NONE

