#ifndef CatDimFrame_IDL
#define CatDimFrame_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 
//--------------------------------------------------------------------------
// 
// ept - 10/98 Extracted from CATIADrawingDimension.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 * Dimension value frame.
 * <b>Role</b>: CatDimFrame is used to specify dimension value frame.
 * @param catFraNone
 *   None. 
 * @param catFraCircle,
 *   Circle.  
 * @param catFraScoredCircle,
 *   Scored circle.
 * @param catFraDiamondShaped,
 *   Diamond shaped.
 * @param catFraSquare,
 *   Square.
 * @param catFraRectangle,
 *   Rectangle.
 * @param catFraOblong,
 *   Oblong.
 * @param catFraRightFlag,
 *   Right flag.
 * @param catFraRightTriangle,
 *   Right triangle.
 */
enum CatDimFrame
{
	catFraNone,
	catFraCircle,
	catFraScoredCircle,
	catFraDiamondShaped,
	catFraSquare,
	catFraRectangle,
	catFraOblong,
	catFraRightFlag,
	catFraRightTriangle
};
	                     
#endif
