#ifndef CatDimFake_IDL
#define CatDimFake_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 
//--------------------------------------------------------------------------
// 
// ept - 10/98 Extracted from CATIADrawingDimension.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 * Dimension value fake mode.
 * <b>Role</b>: CatDimFake is used to specify dimension value fake mode.
 * @param catDimFakeNone
 *   None. 
 * @param catDimFakeNumValue,
 *   Numerical value.  
 * @param catDimFakeText,
 *   Text.
 */
enum CatDimFake
{
	catDimFakeNone,
	catDimFakeNumValue,
	catDimFakeText
};

	                     
#endif
