#ifndef CatDrawingStandard_IDL
#define CatDrawingStandard_IDL

/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

// COPYRIGHT DASSAULT SYSTEMES 1998
//--------------------------------------------------------------------------
// aco 06/98  creation
//--------------------------------------------------------------------------

    /**
     * The standard for the drawing document.
     * @param catANSI
     *   The standard is ANSI
     * @param catISO
     *   The standard is ISO
     * @param catJIS
     *   The standard is JIS
     */

enum CatDrawingStandard
{
  catANSI,
  catISO,
  catJIS
};

#endif
