#ifndef CatDimLineGraphRep_IDL
#define CatDimLineGraphRep_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 
//--------------------------------------------------------------------------
// 
// ept - 10/98 Extracted from CATIADrawingDimension.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 * Dimension line graphical representation.
 * <b>Role</b>: CatDimLineGraphRep is used to specify dimension line graphical representation.
 * @param catDimLine1Part
 *   Dimension line one part. 
 * @param catDimLine2Parts,
 *   Dimension line two parts.
 * @param catDimLineLeader1Part,
 *   Dimension line with one part leader. 
 * @param catDimLineLeader2Part,
 *   Dimension line with two part leader.  
 */
enum CatDimLineGraphRep
{
	catDimLine1Part,
	catDimLine2Parts,
	catDimLineLeader1Part,
	catDimLineLeader2Part
};

	                     
#endif
