#ifndef CatDimScore_IDL
#define CatDimScore_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 
//--------------------------------------------------------------------------
// 
// ept - 10/98 Extracted from CATIADrawingDimValue.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 *  Dimension scoring mode.
 *  <b>Role</b>: Define the scoring mode. 
 *  @param catDimScoreNone
 *   None.
 *  @param catDimUnderScored
 *   Underscored.
 *  @param catDimScored
 *   Scored.
 *  @param catCATDrwDimOverScored
 *   Overscored.
 */
enum CatDimScore
{
	catDimScoreNone,
	catDimUnderScored,
	catDimScored,
	catCATDrwDimOverScored
};
	                     
#endif
