#ifndef CatHiddenLineMode_IDL
#define CatHiddenLineMode_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1997
//--------------------------------------------------------------------------
// CatHiddenLineMode Enum
// psr - 04/98 Extracted from CATIAGenerativeBehavior.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

    /**
     * View hidden line drawing mode.
     * @param catHlrModeOff
     *   The view is drawn with hidden lines seen
     * @param catHlrModeOn
     *   The view is drawn with hidden lines removed
     */
enum CatHiddenLineMode
{
  catHlrModeOff,
  catHlrModeOn
};

#endif
