#ifndef CatProjViewType_IDL
#define CatProjViewType_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1997
//--------------------------------------------------------------------------
// CatProjViewType Enum
// psr - 04/98 Extracted from CATIAGenerativeViewBehavior.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

    /**
     * View projection mode.
     * @param catRightView
     *   The view is a right view
     * @param catLeftView
     *   The view is a left view
     * @param catTopView
     *   The view is a top view
     * @param catBottomView
     *   The view is a bottom view
     */
enum CatProjViewType
{
  catRightView,
  catLeftView,
  catTopView,
  catBottomView,
  catRearView
};

#endif
