#ifndef CatPicture_IDL
#define CatPicture_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
* Picture format parameters.
* Enum used to specified picture format parameters.
* @param catPictureNONE
* @param catPicturePNG
* @param catPictureJPEG
* @param catPictureCCITTG3
*/
enum CatPictureFormat { 
  catPictureNONE, 
  catPicturePNG, 
  catPictureJPEG,
  catPictureCCITTG3   }; 
	                     
#endif
