#ifndef CatSheetProjectionMethod_IDL
#define CatSheetProjectionMethod_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1997
//--------------------------------------------------------------------------
// CatSheetProjectionMethod Enum
// mmr - 10/98 
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

    /**
     * Sheet projection Method.
     * @param catFirstAngle
     *   The views are created using first angle standard
     * @param catThirdAngle
     *   The views are created using third angle standard
     */
enum CatSheetProjectionMethod
{
  catFirstAngle,
  catThirdAngle
};

#endif
