#ifndef CatThreadType_IDL
#define CatThreadType_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 
/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 *  Thread type.
 *  <b>Role</b>: Define the thread type.
 *  @param catThreaded
 *   Threaded thread
 *  @param catTaped
 *   Taped thread
 */
enum CatThreadType
{
  catThreaded,
	catTaped
};
	                     
#endif
