#ifndef CatTextAnchorPosition_IDL
#define CatTextAnchorPosition_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1997
//--------------------------------------------------------------------------
// CatTextAnchorPosition Enum
// ept - 10/98 Extracted from CATIADrawingText.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

    /**
     * Drawing text anchor position.
	 * @param catUnsusedValue1
	 *   Unused value
     * @param catTopLeft
     *   The anchor point is at the top left of the text box
	 * @param catMiddleLeft
     *   The anchor point is at the middle left of the text box
     * @param catBottomLeft
     *   The anchor point is at the bottom left of the text box
     * @param catTopCenter
     *   The anchor point is at the top center of the text box
     * @param catMiddleCenter
     *   The anchor point is at the middle center of the text box
     * @param catBottomCenter
     *   The anchor point is at the bottom center of the text box
     * @param catTopRight
     *   The anchor point is at the top right of the text box
     * @param catMiddleRight
     *   The anchor point is at the middle right of the text box
     * @param catBottomRight
     *   The anchor point is at the bottom right of the text box
     * @param catUnsusedValue2
     *   Unused value
	 * @param catCapLeft
	 *   The anchor point is on the left of the cap line of text block first line. 
	 * @param catHalfLeft
	 *   The anchor point is at the middle left of the text box.
	 * @param catBaseLeft
	 *   The anchor point is on the left of the base line of text block last line. 
	 * @param catCapCenter
	 *   The anchor point is at the center of the cap line of text block first line. 
	 * @param catHalfCenter
	 *   The anchor point is at the middle center of the text box. 
	 * @param catBaseCenter
	 *   The anchor point is at the center of the base line of text block last line. 
	 * @param catCapRight
	 *   The anchor point is on the right of the cap line of text block first line. 
	 * @param catHalfRight
	 *   The anchor point is at the middle right of the text box. 
	 * @param catBaseRight
	 *   The anchor point is on the right of the base line of text block last line.
	 */
enum CatTextAnchorPosition 
{ 
  catUnsusedValue1,
  catTopLeft      , 
  catMiddleLeft   , 
  catBottomLeft   , 
  catTopCenter    , 
  catMiddleCenter , 
  catBottomCenter , 
  catTopRight     ,   
  catMiddleRight  ,   
  catBottomRight  ,
  catUnsusedValue2,
  catCapLeft      ,
  catHalfLeft     ,
  catBaseLeft     , 
  catCapCenter    ,
  catHalfCenter   ,
  catBaseCenter   ,
  catCapRight     ,
  catHalfRight    ,
  catBaseRight  
};
                         
#endif
