#ifndef CatTextFlipMode_IDL
#define CatTextFlipMode_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 2006

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 *  Text mirroring mode.
 *  <b>Role</b>: Defines the mirror mode of the text. 
 *  @param catTextNoFlip
 *   No mirroring : the text is not flipped horizontally nor vertically.
 *  @param catTextHorizontalFlip
 *   The text is flipped horizontally.
 *  @param catTextVerticalFlip
 *   The text is flipped vertically.
 *  @param catTextHorizontalAndVerticalFlip
 *   The text is flipped both horizontally and vertically.
 *  @param catTextAutoFlip
 *   The text is automatically flipped.
 */
enum CatTextFlipMode
{
	catTextNoFlip,
	catTextHorizontalFlip,
	catTextVerticalFlip,
	catTextHorizontalAndVerticalFlip,
	catTextAutoFlip
};
	                     
#endif
