#ifndef CatThreadLinkedTo_IDL
#define CatThreadLinkedTo_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 
/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 *  Specifies the kind of link the thread has.
 *  <b>Role</b>: Define the thread link to.
 *  @param catNotDefined
 *   The link is undefined. This casemay never happen
 *  @param catNoLink
 *   Thread is linked to nothing.
 *  @param cat2DPoint
 *   Thread is linked to a 2D point (only in case of isolated views)
 *  @param cat2DCircle
 *   Thread is linked to a 2D circle
 *  @param cat3DGeom
 *   Thread is linked to a generated geometry
 *  @param cat3DHole
 *   Thread is linked to a 3D hole which is not threaded
 *  @param cat3DThread
 *   Thread is linked to a 3D hole which is threaded
 */
enum CatThreadLinkedTo
{
  catNotDefined,
  catNoLink,
  cat2DPoint,
	cat2DCircle,
  cat3DGeom,
  cat3DHole,
  cat3DThread
};
	                     
#endif
