#ifndef CatTextProperty_IDL
#define CatTextProperty_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1997
//--------------------------------------------------------------------------
// CatTextAnchorPosition Enum
// ept - 10/98 Extracted from CATIADrawingText.idl
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

    /**
     * Drawing text properties.
     * @param catBold
     *   The text is formatted as bold
     * @param catItalic
     *  The text is formatted as italic
     * @param catUnderline
     *  The text is underlined
     * @param catOverline
     *  The text is overlined
     * @param catStrikethrough
     *   The text is formatted as strike through
     * @param catSubscript
     *  The text is formatted as subscript
     * @param catSuperscript
     *  The text is formatted as superscript
     * @param catFontSize
     *  The font size.
	 *  This value is expressed in mm.
     * @param catParagraph
     *  To consider a piece of the text as a paragraph.
	 * @param catPlain
	 *  Internal use only.
     * @param catColor
     *  Color of the characters
     * @param catFontName
     *  The name of the font used.
     * @param catBorder
     *  The text is
     * @param catAlignment
     *  Alignment of the piece of text. 
	 *  @see CatJustification
	 * @param catRatio
     *  Ratio between character height and width.
	 *  The value is a percentage of the font size and corresponds to the ratio height by width.
	 * @param catCharSpacing
     *  Space between each character.
	 *  The value is a percentage of the font size (may be a negative value).
     */
enum CatTextProperty
{ 
  catBold         , 
  catItalic       , 
  catUnderline    ,   
  catOverline     ,
  catStrikethrough, 
  catSubscript    , 
  catSuperscript  ,  
  catFontSize     ,
  catParagraph    ,
  catPlain        ,
  catColor        ,
  catFontName     ,    
  catBorder       ,
  catAlignment    ,
  catCharRatio    ,
  catCharSpacing  ,
  catKerning
};

    /**
     * Drawing text justification.
     * @param catLeft
     *   The text is left justified
     * @param catCenter
     *   The text is centered
     * @param catRight
     *   The text is right justified
	 */
enum CatJustification
{ 
  catLeft         , 
  catCenter       , 
  catRight           
};	 
	                     
#endif
