#ifndef CatWeldingParameters_IDL
#define CatWeldingParameters_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1997
//--------------------------------------------------------------------------
// CatWeldingParameters Enum
//--------------------------------------------------------------------------

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 * Active drawing welding.
 * <b>Role</b>: CatWelding is used to specify which welding is active,
 * that is the one you can work on.
 * @param catNoneWelding
 *   No welding is set as active
 * @param catFirstWelding
 *   The first welding is set as active
 * @param catSecondWelding
 *   The second welding is set as active
 * @see CATIADrawingWelding
 */
enum CatWelding { catNoneWelding , // faux mais permet d'etre en phase
				  catFirstWelding   , 
                  catSecondWelding }; // DOUBLE 

/**
 * Drawing welding symbol.
 * <b>Role</b>: The symbol represents the weld type.
 * @param catNoneMainWelding
 *   Unspecified welding
 * @param catSquareWelding
 *   Square welding symbol
 * @param catVGrooveWelding
 *   V groove welding symbol
 * @param catHVGrooveWelding
 *   HV groove welding symbol
 * @param catYGrooveWelding
 *   Y groove welding symbol
 * @param catHYGrooveWelding
 *   HY groove welding symbol
 * @param catUGrooveWelding
 *   U groove welding symbol
 * @param catHUGrooveWelding
 *   HU groove welding symbol
 * @param catFilletWelding
 *   Fillet welding symbol
 * @param catCFlangeWelding
 *   xx welding symbol
 * @param catEFlangeWelding
 *   xx welding symbol
 * @param catVFlareWelding
 *   xx welding symbol
 * @param catHVFlareWelding
 *   xx welding symbol
 * @param catSpotWelding
 *   xx welding symbol
 * @param catBackWelding
  *  Back welding symbol
 * @param catHVOGrooveWelding
 *   HVO Groove welding symbol
 * @param catVOGrooveWelding
 *   VO Groove welding symbol
 * @param catPlugWelding
 *   Plug welding symbol
 * @param catMRWelding
 *   MR welding symbol
 * @param catMWelding
 *   M welding symbol
 * @param catRechargWelding
  *  Recharg welding symbol
 * @param catSpotJISWelding
 *   Spot JIS welding symbol
 * @param catEFlangeISOWelding
 *   E Flange ISO welding symbol
 * @param catSeamWelding
  *  Seam welding symbol
 * @param catScarfWelding
  *  Scarf welding symbol
 * @param catStudWelding
  *  Stud welding symbol
 * @param catEdgeWelding
  *  Edge welding symbol
 * @param catMeltThruWelding
  *  Melt Thru welding symbol
 * @param catSurfaceJointWelding
  *  Surface Joint welding symbol
 * @param catInclinedJointWelding
  *  Inclined Joint welding symbol
 * @see CATIADrawingWelding
 * @param catEndToEndWelding
  *  EndToEnd welding symbol
 * @see CATIADrawingWelding
 */
enum CatWeldingSymbol { catNoneMainWelding,
                        catSquareWelding,
                        catVGrooveWelding,
                        catHVGrooveWelding,
                        catYGrooveWelding,
                        catHYGrooveWelding,
                        catUGrooveWelding,
                        catHUGrooveWelding,
                        catFilletWelding, 
                        catCFlangeWelding, 
                        catEFlangeWelding, 
                        catVFlareWelding,
                        catHVFlareWelding,
                        catSpotWelding,
                        catBackWelding,
                        catHVOGrooveWelding,
                        catVOGrooveWelding,
                        catPlugWelding,
                        catMRWelding,
                        catMWelding,
                        catRechargWelding,
                        catSpotJISWelding,
                        catEFlangeISOWelding,
                        catSeamWelding,
                        catScarfWelding,
                        catStudWelding,
                        catEdgeWelding,
                        catMeltThruWelding,
                        catSurfaceJointWelding,
                        catInclinedJointWelding,
                        catEndToEndWelding};

/**
 * Drawing welding additional symbol.
 * @param catNoneAddWelding
 *   Unspecified welding
 * @param catFlatWelding
 *   Flat welding symbol
 * @param catConvexWelding
 *   Convex welding symbol
 * @param catConcaveWelding
 *   Concave welding symbol
 * @param catFlushWelding
 *   Flush welding symbol
 * @param catSmoothWelding
 *   Smooth welding symbol
 * @see CATIADrawingWelding
 */
enum CatWeldAdditionalSymbol { catNoneAddWelding,
                               catFlatWelding, 
                               catConvexWelding, 
                               catConcaveWelding, 
                               catFlushWelding, 
                               catSmoothWelding };

/**
 * Drawing welding side.
 * @param catWeldingUp
 *   Up welding
 * @param catWeldingDown
 *   Down welding
 * @see CATIADrawingWelding
 */
enum CatWeldingSide{ catWeldingUp,
                     catWeldingDown   };

/**
 * Drawing welding field.
 * @param catWeldingNone
 *   Unspecified welding field
 * @param catWeldingFieldOne
 *   The first welding field
 * @param catWeldingFieldTwo
 *   The second welding field
 * @param catWeldingFieldThree
 *   The third welding field
 * @param catWeldingFieldFour
 *   The fourth welding field
 * @param catWeldingFieldFive
 *   The fith welding field
 * @param catWeldingFieldSix
 *   The sixth welding field
 * @param catWeldingFieldSeven
 *   The seventh welding field
 * @see CATIADrawingWelding
 */
enum CatWeldingField{ catWeldingNone,  // faux mais permet d'etre en phase
                      catWeldingFieldOne,
                      catWeldingFieldTwo,
                      catWeldingFieldThree,
                      catWeldingFieldFour,
                      catWeldingFieldFive,
                      catWeldingFieldSix,
                      catWeldingFieldSeven   };  
/**
* Drawing welding tail.
* @param catDftWeldingTailNO
*   To hide the welding symbol tail
* @param catDftWeldingTailYES
*   To display the welding symbol tail
*/
enum CatDftWeldingTail{ catDftWeldingTailNO,
                                             catDftWeldingTailYES}  ;

/**
* Finish symbol of Drawing welding.
* @param catDftLetterCWelding
*   Symbol "C"
* @param catDftLetterFWelding
*   Symbol "F"
* @param catDftLetterGWelding
*   Symbol "G"
* @param catDftLetterHWelding
*   Symbol "H"
* @param catDftLetterMWelding
*   Symbol "M"
* @param catDftLetterRWelding
*   Symbol "R"
* @param catDftLetterUWelding
*   Symbol "U"
* @param catDftLetterPWelding
*   Symbol "P"
* @param catDftLetterXWelding
*   Symbol "X"
* @param catDftEqualWelding
*   Symbol "Equal"
* @param catDftPerpendicularWelding
*   Symbol "Perpendicular"
*/
 enum CatDftWeldFinishSymbol{catFinishWeldingNone, 
                                                        catDftLetterCWelding, 
                                                        catDftLetterFWelding,
                                                        catDftLetterGWelding,
                                                        catDftLetterHWelding,
                                                        catDftLetterMWelding,
                                                        catDftLetterRWelding,
                                                        catDftLetterUWelding, 
														catDftLetterPWelding,
													    catDftLetterXWelding,
													    catDftEqualWelding,
													    catDftPerpendicularWelding};
#endif
