#ifndef RasterLevelOfDetail_IDL
#define RasterLevelOfDetail_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 2000

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

    /**
     * Precision for views generated as raster (DPI).
     * @param NormalQuality
     *	With this precision, an edge from raster view will
	 *  have the correct width for print purpose.
     * @param LowQuality
     *	This precision is 4 times smaller than NormalQuality
     * @param HighQuality
     *	This precision is 4 times bigger than NormalQuality
	 * @param Customize
     *	Whenever you want to define the value (DPI)
	 */
enum RasterLevelOfDetail
{
  LowQuality,
  NormalQuality,
  HighQuality,
  Customize
};

#endif

