BUILT_OBJECT_TYPE=NONE
OS = AIX
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"' -DRELEASE_SPKLEVEL='"$(Mkmk_SPKLEVEL)"' -DRELEASE_HFXLEVEL='"$(Mkmk_HFXLEVEL)"'
OS = HP-UX
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"' -DRELEASE_SPKLEVEL='"$(Mkmk_SPKLEVEL)"' -DRELEASE_HFXLEVEL='"$(Mkmk_HFXLEVEL)"'
OS = IRIX
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"' -DRELEASE_SPKLEVEL='"$(Mkmk_SPKLEVEL)"' -DRELEASE_HFXLEVEL='"$(Mkmk_HFXLEVEL)"'
OS = SunOS
RD=$(RELEASE_STARTDATE) 
LOCAL_CCFLAGS= -D RELEASE_STARTDATE='"$(RD)"' -DRELEASE_SPKLEVEL='"$(Mkmk_SPKLEVEL)"' -DRELEASE_HFXLEVEL='"$(Mkmk_HFXLEVEL)"'
OS = Windows_NT
RD=\"$(RELEASE_STARTDATE)\"
LOCAL_CCFLAGS= /D RELEASE_STARTDATE=$(RD) -DRELEASE_SPKLEVEL=\"$(Mkmk_SPKLEVEL)\" -DRELEASE_HFXLEVEL=\"$(Mkmk_HFXLEVEL)\"

