/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIALaw_h
#define CATIALaw_h

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIARelation.h"

extern ExportedByKnowledgePubIDL IID IID_CATIALaw;

class ExportedByKnowledgePubIDL CATIALaw : public CATIARelation
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddFormalParameter(const CATBSTR & iName, const CATBSTR & iMagnitude)=0;

    virtual HRESULT __stdcall RemoveFormalParameter(const CATBSTR & iName)=0;


};

CATDeclareHandler(CATIALaw, CATIARelation);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAKnowledgeActivableObject.h"
#include "CATIAKnowledgeObject.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
