/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAUnit_h
#define CATIAUnit_h

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"

extern ExportedByKnowledgePubIDL IID IID_CATIAUnit;

class ExportedByKnowledgePubIDL CATIAUnit : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Magnitude(CATBSTR & oMagnitude)=0;

    virtual HRESULT __stdcall get_Symbol(CATBSTR & oSymbol)=0;

    virtual HRESULT __stdcall ConvertToMKS(double iValueInThisUnit, double & oValueInMKS)=0;

    virtual HRESULT __stdcall ConvertFromMKS(double iValueInMKS, double & oValueInThisUnit)=0;

    virtual HRESULT __stdcall ConvertToStorageUnit(double iValueInThisUnit, double & oValueInStorageUnit)=0;

    virtual HRESULT __stdcall ConvertFromStorageUnit(double iValueInStorageUnit, double & oValueInThisUnit)=0;


};

CATDeclareHandler(CATIAUnit, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
