/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAIntParam_h
#define CATIAIntParam_h

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATIAParameter.h"
#include "CATSafeArray.h"

extern ExportedByKnowledgePubIDL IID IID_CATIAIntParam;

class ExportedByKnowledgePubIDL CATIAIntParam : public CATIAParameter
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Value(CATLONG & oValue)=0;

    virtual HRESULT __stdcall put_Value(CATLONG iValue)=0;

    virtual HRESULT __stdcall get_RangeMin(CATLONG & oRangeMin)=0;

    virtual HRESULT __stdcall put_RangeMin(CATLONG iRangeMin)=0;

    virtual HRESULT __stdcall get_RangeMax(CATLONG & oRangeMax)=0;

    virtual HRESULT __stdcall put_RangeMax(CATLONG iRangeMax)=0;

    virtual HRESULT __stdcall get_RangeMinValidity(CATLONG & oRangeMinValidity)=0;

    virtual HRESULT __stdcall put_RangeMinValidity(CATLONG iRangeMinValidity)=0;

    virtual HRESULT __stdcall get_RangeMaxValidity(CATLONG & oRangeMaxValidity)=0;

    virtual HRESULT __stdcall put_RangeMaxValidity(CATLONG iRangeMaxValidity)=0;

    virtual HRESULT __stdcall GetEnumerateValues(CATSafeArrayVariant & oSafeArray)=0;

    virtual HRESULT __stdcall GetEnumerateValuesSize(CATLONG & oValue)=0;

    virtual HRESULT __stdcall SetEnumerateValues(const CATSafeArrayVariant & iSafeArray)=0;

    virtual HRESULT __stdcall SuppressEnumerateValues()=0;


};

CATDeclareHandler(CATIAIntParam, CATIAParameter);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIARealParam.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
