/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAFormula_h
#define CATIAFormula_h

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATIARelation.h"

extern ExportedByKnowledgePubIDL IID IID_CATIAFormula;

class ExportedByKnowledgePubIDL CATIAFormula : public CATIARelation
{
    CATDeclareInterface;

public:

};

CATDeclareHandler(CATIAFormula, CATIARelation);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIAKnowledgeActivableObject.h"
#include "CATIAKnowledgeObject.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
