/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAReportGenerationSheetSettingAtt_h
#define CATIAReportGenerationSheetSettingAtt_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIASettingController.h"

extern ExportedByKnowledgePubIDL IID IID_CATIAReportGenerationSheetSettingAtt;

class ExportedByKnowledgePubIDL CATIAReportGenerationSheetSettingAtt : public CATIASettingController
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_CheckReportHtml(short & oCheckReportHtml)=0;

    virtual HRESULT __stdcall put_CheckReportHtml(short iCheckReportHtml)=0;

    virtual HRESULT __stdcall GetCheckReportHtmlInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetCheckReportHtmlLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_AllChecksReport(short & oAllChecksReport)=0;

    virtual HRESULT __stdcall put_AllChecksReport(short iAllChecksReport)=0;

    virtual HRESULT __stdcall GetAllChecksReportInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetAllChecksReportLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ReportCheckAdvisor(short & oReportCheckAdvisor)=0;

    virtual HRESULT __stdcall put_ReportCheckAdvisor(short iReportCheckAdvisor)=0;

    virtual HRESULT __stdcall GetReportCheckAdvisorInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetReportCheckAdvisorLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ReportParametersInformation(short & oReportParametersInformation)=0;

    virtual HRESULT __stdcall put_ReportParametersInformation(short iReportParametersInformation)=0;

    virtual HRESULT __stdcall GetReportParametersInformationInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetReportParametersInformationLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ReportCheckExpert(short & oReportCheckExpert)=0;

    virtual HRESULT __stdcall put_ReportCheckExpert(short iReportCheckExpert)=0;

    virtual HRESULT __stdcall GetReportCheckExpertInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetReportCheckExpertLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ReportPassedObjects(short & oReportPassedObjects)=0;

    virtual HRESULT __stdcall put_ReportPassedObjects(short iReportPassedObjects)=0;

    virtual HRESULT __stdcall GetReportPassedObjectsInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetReportPassedObjectsLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ReportObjectsInformation(short & oReportObjectsInformation)=0;

    virtual HRESULT __stdcall put_ReportObjectsInformation(short iReportObjectsInformation)=0;

    virtual HRESULT __stdcall GetReportObjectsInformationInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetReportObjectsInformationLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ReportHtmlInCatiaSession(short & oReportHtmlInCatiaSession)=0;

    virtual HRESULT __stdcall put_ReportHtmlInCatiaSession(short iReportHtmlInCatiaSession)=0;

    virtual HRESULT __stdcall GetReportHtmlInCatiaSessionInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetReportHtmlInCatiaSessionLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_DirectoryForInputXsl(CATBSTR & oDirectoryForInputXsl)=0;

    virtual HRESULT __stdcall put_DirectoryForInputXsl(const CATBSTR & iDirectoryForInputXsl)=0;

    virtual HRESULT __stdcall GetDirectoryForInputXslInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetDirectoryForInputXslLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ReportOutputDirectory(CATBSTR & oReportOutputDirectory)=0;

    virtual HRESULT __stdcall put_ReportOutputDirectory(const CATBSTR & iReportOutputDirectory)=0;

    virtual HRESULT __stdcall GetReportOutputDirectoryInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetReportOutputDirectoryLock(CAT_VARIANT_BOOL iLocked)=0;


};

CATDeclareHandler(CATIAReportGenerationSheetSettingAtt, CATIASettingController);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATSafeArray.h"
#include "CATVariant.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
