/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAParameterSets_h
#define CATIAParameterSets_h

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIACollection.h"
#include "CATVariant.h"

class CATIAParameterSet;

extern ExportedByKnowledgePubIDL IID IID_CATIAParameterSets;

class ExportedByKnowledgePubIDL CATIAParameterSets : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAParameterSet *& oParameterSet)=0;

    virtual HRESULT __stdcall CreateSet(const CATBSTR & iName, CATIAParameterSet *& oParameterSet)=0;


};

CATDeclareHandler(CATIAParameterSets, CATIACollection);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
