/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAUnitsSheetSettingAtt_h
#define CATIAUnitsSheetSettingAtt_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIASettingController.h"
#include "CATSafeArray.h"

extern ExportedByKnowledgePubIDL IID IID_CATIAUnitsSheetSettingAtt;

class ExportedByKnowledgePubIDL CATIAUnitsSheetSettingAtt : public CATIASettingController
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall SaveRepositoryForUnits()=0;

    virtual HRESULT __stdcall RollbackForUnits()=0;

    virtual HRESULT __stdcall CommitForUnits()=0;

    virtual HRESULT __stdcall ResetToAdminValuesForUnits()=0;

    virtual HRESULT __stdcall get_ListOfMagnitudes(CATSafeArrayVariant *& oListOfMagnitudes)=0;

    virtual HRESULT __stdcall get_ListOfMagnitudesSize(double & oListOfMagnitudesSize)=0;

    virtual HRESULT __stdcall GetMagnitudeValues(CATBSTR & iMagnitudeName, CATBSTR & oUnitName, double & oDecimalPlaceReadWrite, double & oDecimalPlaceReadOnly)=0;

    virtual HRESULT __stdcall GetDecimalReadWrite(CATBSTR & iMagnitudeName, double & oDecimalPlaceReadWrite)=0;

    virtual HRESULT __stdcall GetDecimalReadOnly(CATBSTR & iMagnitudeName, double & oDecimalPlaceReadOnly)=0;

    virtual HRESULT __stdcall SetMagnitudeValues(CATBSTR & iMagnitudeName, CATBSTR & iUnitName, double iDecimalPlaceReadWrite, double iDecimalPlaceReadOnly)=0;

    virtual HRESULT __stdcall GetListOfMagnitudesInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetListOfMagnitudesLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall GetDimensionsDisplayInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetDimensionsDisplayLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_DisplayTrailingZeros(short & oDisplayTrailingZeros)=0;

    virtual HRESULT __stdcall put_DisplayTrailingZeros(short iDisplayTrailingZeros)=0;

    virtual HRESULT __stdcall GetDisplayTrailingZerosInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetDisplayTrailingZerosLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ExpNotationValuesGreater(double & oExpNotationValuesGreater)=0;

    virtual HRESULT __stdcall put_ExpNotationValuesGreater(double iExpNotationValuesGreater)=0;

    virtual HRESULT __stdcall GetExpNotationValuesGreaterInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetExpNotationValuesGreaterLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_ExpNotationValuesLower(double & oExpNotationValuesLower)=0;

    virtual HRESULT __stdcall put_ExpNotationValuesLower(double iExpNotationValuesLower)=0;

    virtual HRESULT __stdcall GetExpNotationValuesLowerInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetExpNotationValuesLowerLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall get_SameDisplay(short & oSameDisplay)=0;

    virtual HRESULT __stdcall put_SameDisplay(short iSameDisplay)=0;

    virtual HRESULT __stdcall GetSameDisplayInfo(CATBSTR & ioAdminLevel, CATBSTR & ioLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall SetSameDisplayLock(CAT_VARIANT_BOOL iLocked)=0;


};

CATDeclareHandler(CATIAUnitsSheetSettingAtt, CATIASettingController);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATVariant.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
