/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAOptimizationConstraints_h
#define CATIAOptimizationConstraints_h

#ifndef ExportedByKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __KnowledgePubIDL
#define ExportedByKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByKnowledgePubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIACollection.h"
#include "CATVariant.h"

class CATIAOptimizationConstraint;

extern ExportedByKnowledgePubIDL IID IID_CATIAOptimizationConstraints;

class ExportedByKnowledgePubIDL CATIAOptimizationConstraints : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAOptimizationConstraint *& oConstraint)=0;

    virtual HRESULT __stdcall AddConstraint(const CATBSTR & constraintExpression, CATIAOptimizationConstraint *& oConstraint)=0;

    virtual HRESULT __stdcall RemoveConstraint(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIAOptimizationConstraints, CATIACollection);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
