// COPYRIGHT DASSAULT SYSTEMES 2008
#ifndef SWKIAManikinPart_IDL
#define SWKIAManikinPart_IDL

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

/*IDLREP*/

// ****************************************************************************
// Framework DNBHumanModelingInterfaces
// Copyright Safework (2000) Inc.
// ****************************************************************************
//  Abstract:
//  ---------
//
//  This interface represents any part of the manikin that is persistent.
//
// ****************************************************************************
//  Usage:
//  ------
//
// ****************************************************************************
//  Inheritance:
//  ------------
//   CATIABase
//
// ****************************************************************************
//  Main Methods:
//  -------------
//
//   get_Memo
//   put_Memo
// ****************************************************************************
//  History
//  -------
//
//  Author: Jean-Guy AUGUSTIN
//  Date  : 26/01/00
//  Goal  : Creation
// ****************************************************************************
//
// --- System
#include "CATIABase.idl"

/**  
  *  This interface represents any part of the manikin that is persistent.
  **/
interface SWKIAManikinPart : CATIABase
{
 // ===========================================================================
 //  get_Memo
 //  --------
 //  put_Memo
 //  --------
 //
    /**
      * Returns or records miscellaneous user-added information about the part.
      **/
#pragma PROPERTY Memo
    HRESULT get_Memo(inout /*IDLRETVAL*/ CATBSTR pioText);
    HRESULT put_Memo(in CATBSTR piText);
};

// Interface name : SWKIAManikinPart
#pragma ID SWKIAManikinPart "DCE:5d576970-d404-11d3-8092005004d3fe74"
#pragma DUAL SWKIAManikinPart

// VB object name : SWManikinPart (Id used in Visual Basic)
#pragma ID SWKManikinPart "DCE:5d576971-d404-11d3-8092005004d3fe74"
#pragma ALIAS SWKIAManikinPart SWKManikinPart

#endif
