#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

LOCAL_CCFLAGS = -DSDAI_NOSTR

LINK_LIST = CO0LSTPV CO0HTAB CO0HDICO CO0SETST JS0STR NS0S3STR AD0XXBAS AC0XXLNK
LINK_WITH = $(LINK_LIST)

OS = AIX

OS = HP-UX

OS = IRIX

OS = SunOS

OS = Windows_NT
# must allow recursive dependency
LINK_WITH = KS0LATE $(LINK_LIST)
