#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
#
INCLUDED_MODULES = CATIAPrjEntity CATV4Attributes
#
DUMMY_LINK_WITH = CATCdbEntity JS0GROUP JS0FILE AC0CATPL
#
OS = COMMON
LINK_WITH = $(DUMMY_LINK_WITH)
SYS_LIBPATH = 
