#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = FE0XY 

LINK_WITH = JS0GROUP JS0CORBA JS0SCBAK JS0FM JS0STR VE0GROUP CO0RCDBL CO0LSTPV NS0S3STR \
            YN000MAT  YN000FUN YN000MFL  YN000M2D PG0BASE PG0DLG DI0PANV2 \
            FunctionEditorItfCPP CATViz CATPrt CATMathStream

OS = Windows_NT

OS = AIX

OS = HP-UX

OS = IRIX

OS = SunOS
