/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatClashExportType_h
#define CatClashExportType_h

enum CatClashExportType {
        CatClashExportTypeXMLResultOnly
};

#endif
