/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAClashResult_h
#define CATIAClashResult_h

#ifndef ExportedBySPAPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __SPAPubIDL
#define ExportedBySPAPubIDL __declspec(dllexport)
#else
#define ExportedBySPAPubIDL __declspec(dllimport)
#endif
#else
#define ExportedBySPAPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"
#include "CatClashExportType.h"

class CATIAConflicts;

extern ExportedBySPAPubIDL IID IID_CATIAClashResult;

class ExportedBySPAPubIDL CATIAClashResult : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Conflicts(CATIAConflicts *& oConflicts)=0;

    virtual HRESULT __stdcall Export(CatClashExportType iType, const CATBSTR & iPath)=0;


};

CATDeclareHandler(CATIAClashResult, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIAAnalyze.h"
#include "CATIACollection.h"
#include "CATIAConflict.h"
#include "CATIAConflicts.h"
#include "CATIAMove.h"
#include "CATIAParameters.h"
#include "CATIAPosition.h"
#include "CATIAProduct.h"
#include "CATIAPublications.h"
#include "CATSafeArray.h"
#include "CATVariant.h"
#include "CatConflictComparison.h"
#include "CatConflictStatus.h"
#include "CatConflictType.h"
#include "CatFileType.h"
#include "CatProductSource.h"
#include "CatRepType.h"
#include "CatWorkModeType.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
