/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAInertias_h
#define CATIAInertias_h

#ifndef ExportedBySPAPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __SPAPubIDL
#define ExportedBySPAPubIDL __declspec(dllexport)
#else
#define ExportedBySPAPubIDL __declspec(dllimport)
#endif
#else
#define ExportedBySPAPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATVariant.h"

class CATIABase;
class CATIAInertia;

extern ExportedBySPAPubIDL IID IID_CATIAInertias;

class ExportedBySPAPubIDL CATIAInertias : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Add(CATIABase * iObject, CATIAInertia *& oInertia)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAInertia *& oInertia)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIAInertias, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIAInertia.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
