/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAConflicts_h
#define CATIAConflicts_h

#ifndef ExportedBySPAPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __SPAPubIDL
#define ExportedBySPAPubIDL __declspec(dllexport)
#else
#define ExportedBySPAPubIDL __declspec(dllimport)
#endif
#else
#define ExportedBySPAPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATVariant.h"

class CATIAConflict;

extern ExportedBySPAPubIDL IID IID_CATIAConflicts;

class ExportedBySPAPubIDL CATIAConflicts : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall SendToDB()=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAConflict *& oConflict)=0;


};

CATDeclareHandler(CATIAConflicts, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIAAnalyze.h"
#include "CATIABase.h"
#include "CATIAConflict.h"
#include "CATIAMove.h"
#include "CATIAParameters.h"
#include "CATIAPosition.h"
#include "CATIAProduct.h"
#include "CATIAPublications.h"
#include "CATSafeArray.h"
#include "CatConflictComparison.h"
#include "CatConflictStatus.h"
#include "CatConflictType.h"
#include "CatFileType.h"
#include "CatProductSource.h"
#include "CatRepType.h"
#include "CatWorkModeType.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
