/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef SWKIAManikin_h
#define SWKIAManikin_h

#ifndef ExportedBySWKHumanModelingPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __SWKHumanModelingPubIDL
#define ExportedBySWKHumanModelingPubIDL __declspec(dllexport)
#else
#define ExportedBySWKHumanModelingPubIDL __declspec(dllimport)
#endif
#else
#define ExportedBySWKHumanModelingPubIDL
#endif
#endif

#include "SWKIAManikinPart.h"

class CATIAMove;
class SWKIAAnthro;
class SWKIABody;
class SWKIAErgo;
class SWKIAIKManager;
class SWKIALineOfSightNode;
class SWKIANode;
class SWKIASegmentNode;
class SWKIAVision;

extern ExportedBySWKHumanModelingPubIDL IID IID_SWKIAManikin;

class ExportedBySWKHumanModelingPubIDL SWKIAManikin : public SWKIAManikinPart
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Body(SWKIABody *& poBody)=0;

    virtual HRESULT __stdcall get_BodyNode(SWKIASegmentNode *& poBodyNode)=0;

    virtual HRESULT __stdcall get_Anthro(SWKIAAnthro *& poAnthro)=0;

    virtual HRESULT __stdcall get_Vision(SWKIAVision *& poVision)=0;

    virtual HRESULT __stdcall get_Ergo(SWKIAErgo *& poErgo)=0;

    virtual HRESULT __stdcall get_IKManager(SWKIAIKManager *& poIKManager)=0;

    virtual HRESULT __stdcall get_Move(CATIAMove *& poMove)=0;

    virtual HRESULT __stdcall get_SettingsNode(SWKIANode *& poNode)=0;

    virtual HRESULT __stdcall get_LineOfSightNode(SWKIALineOfSightNode *& poNode)=0;

    virtual HRESULT __stdcall get_ProfilesNode(SWKIANode *& poNode)=0;


};

CATDeclareHandler(SWKIAManikin, SWKIAManikinPart);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
