# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CATObjectRelItf.m 
#======================================================================
#
#  May 2003  Creation: Code generated by the CAA wizard  s223254
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0FM JS0GROUP  
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

INCLUDED_MODULES = \
                  CATObjectRelItfCPP \
