// COPYRIGHT Dassault Systemes 2000
//===================================================================
//
// CATSIMActionAdapter.h
// Provide implementation to interface
//    CATIASIMAction
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   IMPLEMENTATION
//   TIE: CATIASIMAction
//End CAA2 Wizard Generation Report
//
//  Nov 2000  Creation: Code generated by the CAA wizard  pba
//===================================================================
/**
 * @CAA2Level L0
 * @CAA2Usage U3
 */
#ifndef CATSIMActionAdapter_H
#define CATSIMActionAdapter_H

#include "CATSIMSequenceModel.h"
#include "CATISIMAction.h"
#include "CATEventSubscriber.h"
#include "CATNotification.h"
#include "CATListOfInt.h"
#include "CATListOfCATBaseUnknown.h"
class CATError;
//-----------------------------------------------------------------------


/**
* Class Object modeler implementation class.
* <br>
* It implements the interfaces :
*  <ol>
*  <li>@see SIMSequenceInterfaces.CATIASIMAction
*  </ol>
* Using this prefered syntax will enable mkdoc to document your class.
*/

// Specific Notification for Adapter
//==================================
class ExportedByCATSIMSequenceModel CATSIMActionAdapterNotification : public CATNotification
  {
  CATDeclareClass;
  public:
    CATSIMActionAdapterNotification();
    virtual ~CATSIMActionAdapterNotification();
  };


// Specific Notification for Event Subscriber
//===========================================
class ExportedByCATSIMSequenceModel CATSIMActionEventSubscriber : public CATEventSubscriber
  {
  CATDeclareClass;
  public:
    CATSIMActionEventSubscriber();
    virtual ~CATSIMActionEventSubscriber();
  };



class ExportedByCATSIMSequenceModel CATSIMActionAdapter: public CATSIMActionEventSubscriber
  {
  public:
    
    
    // Standard constructors and destructors for an implementation class
    // -----------------------------------------------------------------
    CATSIMActionAdapter (CATISIMAction::DurationLockMode iLockMode = CATISIMAction::Locked);
    virtual ~CATSIMActionAdapter ();

    HRESULT virtual ChangeComponentState
      (ComponentState iFromState,
       ComponentState iToState,
       const CATSysChangeComponentStateContext * iContext);
    

    /**
    * Implements a function from an interface.
    * @see SIMSequenceInterfaces.CATIASIMAction#AddWatchOutDuration
    */
    HRESULT AddWatchOut
      (CATBaseUnknown* iActivity);
    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#RemoveWatchOutDuration
    */
    
    HRESULT RemoveWatchOut
      (CATBaseUnknown* iActivity);
    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#GetDuration
    */
    virtual HRESULT GetDuration 
      (double&  oDuration) = 0;
    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#TestSequenceInsertion
      * 0 is KO   and 1 is OK
    */
    virtual HRESULT TestSequenceInsertion
      (CATBaseUnknown* iCandidateSequence, int& oInsertionIsValid); 
    

    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#GetDuration
    */
    virtual HRESULT UpdateWatchOut 
      ();
    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#GetDurationChangeNotifier
    */
    virtual HRESULT GetDurationChangeNotifier
      (CATEventSubscriber*& oEventSubscriber); 
    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#GetLockMode
    */
    virtual HRESULT GetLockMode 
      (CATISIMAction::DurationLockMode& oMode); 
    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#SetAutoDuration
    */
    virtual HRESULT SetAutoDuration       
      (CATBaseUnknown* iActivity);
    
      /**
      * Implements a function from an interface.
      * @see SIMSequenceInterfaces.CATIASIMAction#SetAutoDuration
    */
    virtual HRESULT TestAutoDuration       
      (int& oAutoDurationActive);
    
   /** The default adapter returns the object that can be attached 
     * sequence editor(tracks,clash,...)
     */
     virtual HRESULT GetNavigateExtendedObject(CATBaseUnknown** opBU);
  
  private:
    // The copy constructor and the equal operator must not be implemented
    // -------------------------------------------------------------------
    
    CATSIMActionAdapter (CATSIMActionAdapter &);
    CATSIMActionAdapter& operator=(CATSIMActionAdapter&);

    void SIMAllMemberDataClean();

    HRESULT ErrorManagement(CATError* pError);
    
    CATISIMAction::DurationLockMode   _LockMode;

    CATListOfInt                      _ListCBDuration;
    CATListValCATBaseUnknown_var      _ListParmDuration;

    CATSIMActionAdapterNotification   _DurationChangeNotif;
    
    CATBaseUnknown*                   _Activity;
    
    int                               _AntiDeadLockFlagOnDuration;
    
    void DurationChange
      (CATCallbackEvent,void*,CATNotification*,CATSubscriberData,CATCallback);

    static CATSIMActionEventSubscriber         _sSIMAdapterGlobalEventSubscriber;
  };


//-----------------------------------------------------------------------

#endif
