#@ autoformat 06:11:07
#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
#
#else
LINK_WITH_FOR_IID =
#endif
#
# CATGotItf.m Makefile for the .idl files
#

BUILT_OBJECT_TYPE = SHARED LIBRARY

LINK_WITH_V5_ONLY=
LINK_WITH_V6_ONLY=
#LINK_WITH=$(LINK_WITH_FOR_IID) JS0CORBA \
#	JS0GROUP  JS03TRA JS0ERROR JS0DSPA JS0LOGRP JS0CTYP JS0INF \
#	MecModItf \
#	Collections 
  
INCLUDED_MODULES= CATGotItfCPP


LINK_WITH=\
    $(LINK_WITH_V5_ONLY)           \
    $(LINK_WITH_V6_ONLY)           \
#

OS = COMMON
#if defined(CATIAR201)
LINK_WITH_V6_ONLY= \
#
#else
#if defined(CATIAV5R21)
LINK_WITH_V5_ONLY= \
#
#endif
#endif
