#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID \
CATFunctSystemUIUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = \
          JS0GROUP CATApplicationFrame CATObjectModelerBase
# END WIZARD EDITION ZONE

LINK_WITH=$(LINK_WITH_FOR_IID)  $(WIZARD_LINK_MODULES) \
    CATFunctSystem
