#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY


#
OS = AIX
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0FM CATMainwin SystemUUID
LOCAL_CCFLAGS=-DCATMAINWIN
SYS_LIBS = -liconv

#
OS = HP-UX
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0FM CATMainwin SystemUUID
LOCAL_CCFLAGS=-DCATMAINWIN
#if os hpux_a
SYS_LIBS= -lf -lcl
#else
SYS_LIBS= -lF90
#endif

#
OS = hpux_b64 
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0FM CATMainwin SystemUUID
LOCAL_CCFLAGS=-DCATMAINWIN
#if os hpux_a
SYS_LIBS= -lf -lcl
#else
SYS_LIBS= -lF90 -lcps 
#endif

#
OS = IRIX
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0FM CATMainwin SystemUUID
LOCAL_CCFLAGS=-DCATMAINWIN
SYS_LIBS = -lexc -lmangle

#
OS = SunOS
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0FM CATMainwin SystemUUID
LOCAL_CCFLAGS=-DCATMAINWIN
SYS_LIBS = -lXm -lXext

#
OS = linux_a
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0FM CATMainwin SystemUUID
LOCAL_CCFLAGS=-DCATMAINWIN

#
OS = Windows_NT
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP JS0FM 
LOCAL_LDFLAGS = /NODEFAULTLIB:libC.lib

