# COPYRIGHT DASSAULT SYSTEMES 1999
#======================================================================
# Imakefile for module CATClnPrd.m
#======================================================================
#
#  Jun. 1999  Creation: Code generated by the CAA wizard  GDC
#  Nov. 2001  Modif : migration interfaces vers CATClnBase
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = \
JS0GROUP CATObjectSpecsModeler CATClnSpecs CATClnBase \
CATMecModInterfaces CATObjectModelerBase AC0SPBAS \
AS0STARTUP CATPrsRep JS0FM KnowledgeItf TECHNLNK \
CATClnPrd \
DataAdmin 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
   CATMathematics ObjectModelerBaseUUID CATMathStream CATVisualization \
   CATProductStructureInterfaces YP0LOGRP  

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
