#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATVisUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
#BUILT_OBJECT_TYPE=EL LIBRARY
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID)  CATVizBase VE0BASE VE0PIX JS0MRSHL JS03TRA JS0CORBA JS0SCBAK JS0STR CO0HTAB CO0LSTPV NS0S3STR YN000MFL YN000MAT CATMathStream

LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION


OS = IRIX
LOCAL_CCFLAGS  = -float -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS   = -float -DCATVIZ_SPECIFICATION

