#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
OS = COMMON
#
LINK_WITH = JS0GROUP orbix

#
OS = AIX
LOCAL_LDFLAGS=-brtl

#
OS = IRIX
LOCAL_CCFLAGS = -D_IRIX_SOURCE
LOCAL_LDFLAGS =
CXX_EXCEPTION = 

#
OS = HP-UX
LOCAL_CCFLAGS = -D_HPUX_SOURCE -D_REENTRANT -DNATIVE_EXCEPTION
SYS_INCPATH = 
SYS_LIBPATH = 
CXX_EXCEPTION = 

#
OS = intel_a
#BUILD=NO
LINK_WITH = JS03TRA JS0LIB0 ITMi
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /GX /Od /Zi  -DORBIX_DLL
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

#
OS = win_b
#BUILD=NO
LINK_WITH = JS03TRA JS0LIB0 ITMi
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /GX /Od /Zi  -DORBIX_DLL
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

#
OS = win_b64
#BUILD=NO
LINK_WITH = JS03TRA JS0LIB0 ITMi
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL
#SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

#
OS = alpha_a
BUILD = NO

#
OS = win_a
#BUILD=NO
LINK_WITH = JS03TRA ITMi
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /GX /Od /Zi  -DORBIX_DLL
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 
