#
BUILT_OBJECT_TYPE=LOAD MODULE
PROGRAM_NAME = KillV5Process
OS = COMMON
LINK_WITH = JS0GROUP CATSysTS CXINSTUTIL


OS = Windows_NT
SH_SYS_LIBPATH = $(SYS_LIBPATH)
SYS_LIBS =  psapi.lib 
LOCAL_CCFLAGS =
LOCAL_CFLAGS = /SUBSYSTEM:WINDOWS

OS = Android
BUILD = NO

OS = iOS
BUILD=NO
