# COPYRIGHT DASSAULT SYSTEMES 2003
#

BUILT_OBJECT_TYPE=JAVA
# BUILT_OBJECT_TYPE=JSHARP

LOCAL_JAVA_FLAGS=-J-ms16m -J-mx96m
LINK_WITH=CATJWSModel qname CATJSystem CATJWSInfra
LOCAL_JSHARP_FLAGS= /r:"System.Web.Services.dll"

BUILD=NO
