#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# PG0GRAST : Raster driver
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID) CATPrt CATPrtBase JS0GROUP JS0FM DI0PANV2 NS0S3STR CATLightXml VE0PIX CATMMediaImageFile XMLParserItf CATMathematics

