# COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CATPolyMathBV.m
#======================================================================
#
#  Jan 2009  Creation: Code generated by the CAA wizard  jxo
#======================================================================
#
# NONE 
#
BUILT_OBJECT_TYPE=NONE 
#
OS = Windows_NT
#if os win_b64
#else
OPTIMIZATION_CPP = /O2
#endif
#
