#ifndef CatDescriptionLengthType_IDL
#define CatDescriptionLengthType_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 2000

/** 
* @CAA2Level L1
* @CAA2Usage U3
*/


/**
* Precision of the text report.
* @param ShortText the report only shows status.
* @param LongText the report shows status and t-uples for each check.
*/

enum CatDescriptionLengthType
{
    ShortText,
    LongText
};

#endif
