#ifndef CatVisualizationType_IDL
#define CatVisualizationType_IDL
/*IDLREP*/


// COPYRIGHT DASSAULT SYSTEMES 2000

/** 
* @CAA2Level L1
* @CAA2Usage U3
*/

/**
* Type of checks to be chosen for the Expert Knowledge  Report.
*
* @param Passed  True checks.
* @param Failed  False checks.
* @param Both    True and false checks.
*/
enum CatVisualizationType
{  
	Passed,
    Failed,
	Both
};

#endif
