/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAKWECorrectFunction_h
#define CATIAKWECorrectFunction_h

#ifndef ExportedByGenerativeKnowledgePubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GenerativeKnowledgePubIDL
#define ExportedByGenerativeKnowledgePubIDL __declspec(dllexport)
#else
#define ExportedByGenerativeKnowledgePubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGenerativeKnowledgePubIDL
#endif
#endif

#include "CATIABase.h"
#include "CATSafeArray.h"

class CATBaseDispatch;

extern ExportedByGenerativeKnowledgePubIDL IID IID_CATIAKWECorrectFunction;

class ExportedByGenerativeKnowledgePubIDL CATIAKWECorrectFunction : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall ListFailedElements(CATSafeArrayVariant & oListElementsOfTupleFailed)=0;

    virtual HRESULT __stdcall GetNumberOfListFailedElements(CATLONG & oArraySize)=0;

    virtual HRESULT __stdcall Check(CATBaseDispatch *& oAssociatedCheck)=0;


};

CATDeclareHandler(CATIAKWECorrectFunction, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
