#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID \
CATVisUUID \
MarkerUUID \
NavigatorInterfacesUUID \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = MK0LINK

LINK_WITH=$(LINK_WITH_FOR_IID)  JS0CORBA JS0SCBAK JS0STR JS0FM JS03TRA NS0S3STR\
            CO0RCINT CO0LSTST CO0LSTPV VE0BASE YN000MFL\
            AC0XXLNK AD0XXBAS AC0SPBAS MK0BASE CATVisualization TECHNLNK AS0STARTUP\
            CD0WIN CD0FRAME DI0PANV2 DI0STATE DI0GRAF DI0APPLI CATNavigatorItf CATNavigator2Itf CD0AUTOSTART\
	    CATInteractiveInterfaces CATFmuServices CATFileMenu SIMItf CATViz CATMathStream CATInfInterfaces
