BUILT_OBJECT_TYPE = ARCHIVE
ENCODING_KEY = System
DELIVERABLE = NO
BUILD=NO

COMMON_CCFLAGS=-D_TRACE_UKUSERVER=$(TRACE_UKUSERVER:-"0") -DUKU_SUPPORT  -DHTTPARCH -D__OPENSSL 
COMMON_LINK_WITH= DSLSArch


OS = Windows_NT
LOCAL_CCFLAGS = $(COMMON_CCFLAGS) -D__JS0DSLOCK 
LINK_WITH = $(COMMON_LINK_WITH)
SYS_LIBS = ShFolder.lib  iphlpapi.lib  Wininet.lib advapi32.dll
BUILD=YES


OS = AIX
LOCAL_CCFLAGS = $(COMMON_CCFLAGS) 
LINK_WITH = $(COMMON_LINK_WITH)
BUILD=YES

OS = Linux
LOCAL_CCFLAGS =$(COMMON_CCFLAGS) 
LINK_WITH = $(COMMON_LINK_WITH)
BUILD=YES

OS=SunOS
LOCAL_CCFLAGS = $(COMMON_CCFLAGS)
LINK_WITH = $(COMMON_LINK_WITH)
BUILD=YES

OS= Darwin
LOCAL_CCFLAGS =  $(COMMON_CCFLAGS)
LINK_WITH = $(COMMON_LINK_WITH)
BUILD=YES


OS= iOS
LOCAL_CCFLAGS =  $(COMMON_CCFLAGS)
LINK_WITH = $(COMMON_LINK_WITH)
BUILD=YES
