#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=NONE

LINK_WITH = CATVizBase JS0MRSHL JS0CORBA JS0SCBAK JS0FM JS0ERROR JS0STR JS03TRA \
CO0LSTPV CO0HTAB VE0MDL VE0FONT VE0PIX DI0PANV2 NS0S3STR YN000MFL \
YN000MAT YN000M2D VE0HLR VE0LOD 

LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION

OS = aix_a
LOCAL_CCFLAGS = -qfloat=hsflt  -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXt -lXi -lX11

OS = aix_a64
LOCAL_CCFLAGS = -qfloat=hsflt -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXt -lXi -lX11

OS = HP-UX
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = IRIX
SYS_LIBS = -lXm -lXt -lX11 -lXext
LOCAL_CCFLAGS  = -float -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS   = -float -DCATVIZ_SPECIFICATION

OS = SunOS
SYS_LIBS = -lXm -lXt -lXi -lX11
LOCAL_CFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS

OS = Windows_NT
SYS_LIBS = vfw32.lib wsock32.lib winmm.lib

OS = intel_a 
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION

OS = intel_a64
LOCAL_CCFLAGS = -D_WNT40I_SOURCE
LOCAL_CFLAGS  = -D_WNT40I_SOURCE

OS = alpha_a
LOCAL_CCFLAGS = -D_WNT40A_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40A_SOURCE -DCATVIZ_SPECIFICATION
