#
BUILT_OBJECT_TYPE=LOAD MODULE
LINK_WITH = WFTOCTools DI0PANV2 CATDlgStandard JS0SCBAK  JS0FM JS0STR JS0ERROR NS0S3STR NS0S1MSG CXINSTUTIL
#
OS = SunOS
SYS_LIBS = -lXm 


OS = Windows_NT
LINK_WITH = WFTOCTools JS0SCBAK JS0CORBA JS0FM JS0STR JS0ERROR NS0S3STR NS0S1MSG CXINSTUTIL DI0PANV2 CATDlgStandard
LOCAL_LDFLAGS=$(SUB_WIN)  /STACK:2100000
MKMFC_DEPENDENCY=Yes 
MANIFESTUAC_ADMIN=yes
LOCAL_CFLAGS = /SUBSYSTEM:WINDOWS
