// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATIPPRHubContext.h
// Define the CATIPPRHubContext interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jun 2002  Creation: Code generated by the CAA wizard  PCM
//===================================================================
#ifndef CATIPPRHubContext_H
#define CATIPPRHubContext_H

/**
  * @CAA2Level L0
  * @CAA2Usage U5
**/

#include "CATPPRHubWtpItfCPP.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATPPRHubWtpItfCPP IID IID_CATIPPRHubContext;
#else
extern "C" const IID IID_CATIPPRHubContext ;
#endif

//------------------------------------------------------------------



class CATIPPRHubWorkSpace;
class CATIPPRHubTransaction;

/**
* Interface for PPR Hub contexts.
* <b>Role</b>: Contexts are specific workspaces which allow data saving.
*/
class ExportedByCATPPRHubWtpItfCPP CATIPPRHubContext: public CATBaseUnknown
{
  CATDeclareInterface;

  public:


  /**
  *   Copy PPR Hub objects of a workspace in the curent context.
  *   @param ipWS
  *      WorkSpace to Copy.
  */
    
  virtual HRESULT AddWSInContext( CATIPPRHubWorkSpace *iWS ) =0;

  /**
  *   Creates a transaction for the curent context.
  *   @param oTransac
  *      Created transaction.
  */
  
  virtual HRESULT CreateTransaction(CATIPPRHubTransaction **oTransac) =0;


  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
