#ifndef CATIAItem_IDL
#define CATIAItem_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1999

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

/**
 * The object that represents an item.
 */

#include "CATIABase.idl"
#include "CATBSTR.idl"
#include "CATVariant.idl"

#include "CATIAItems.idl"

interface CATIAItem : CATIABase
{

};

// Interface name : CATIAItem
#pragma ID CATIAItem "DCE:8736a06a-979a-0000-0280030e1c000000"
#pragma DUAL CATIAItem

// VB object name : Item
#pragma ID Item "DCE:8736a110-c235-0000-0280030e1c000000"
#pragma ALIAS CATIAItem Item

#endif


