BUILT_OBJECT_TYPE=SHARED LIBRARY 

LINK_WITH = $(WIZARD_LINK_MODULES) \
	CK0FEAT AC0SPBAS CATProductStructureInterfaces TECHNLNK AD0XXBAS CATOmbCluster CATOmiClusterItf MecModProIDL

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP JS0FM JS0GROUP KnowledgeModelerUUID 
# END WIZARD EDITION ZONE
