
# module CATPspEditProp
BUILT_OBJECT_TYPE = SHARED LIBRARY
#LINK_WITH = JS0CORBA JS0ERROR JS0SCBAK JS0FM JS0STR \
#            NS0S3STR \
#            AD0XXBAS \
#            DI0PANV2 \
#            JS03TRA \
#            OM0EDPRO \
#            VE0BASE VE0MDL


LINK_WITH = VE0BASE DI0PANV2 JS0FM  DI0PANV2 DI0STATE \
JS0CORBA JS0SCBAK JS0STR JS0LIB0 VE0MDL NS0S3STR JS0SETT YN000M2D YN000MAT AD0XXBAS OM0EDPRO \
AS0STARTUP \
AC0SPBAS \
CATPspUUID  CATPspUtilities \
KnowledgeItf  


OS = COMMON
