// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// CATIElbSupport.h
// Define the CATIElbSupport interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Sep 2009  Creation: Code generated by the CAA wizard  HQF
//===================================================================
#ifndef CATIElbSupport_H
#define CATIElbSupport_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATBaseUnknown.h"
#include "CATListOfDouble.h"
#include "ExportedByCATElbInterfaces.h"
class CATListValCATBaseUnknown_var;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATElbInterfaces IID IID_CATIElbSupport;
#else
extern "C" const IID IID_CATIElbSupport ;
#endif

//------------------------------------------------------------------

/**
* This interface allows user to retrieve the information of the Support
* This interface is implemeneted on Electrical Support.
*/

class ExportedByCATElbInterfaces CATIElbSupport: public CATBaseUnknown
{
  CATDeclareInterface;
  
public:
  
  /**
  * Get the number of sections in support.
  *
  * @param oNbSections
  *   oNbSections is updated with Number of sections.
  *
  * @return
  *   Return code S_OK   if oNbSections is correctly retrieved
  *               E_FAIL if oNbSections cannot be retrieved.
  **/
  virtual HRESULT GetNumberOfSections(int &oNbSections) = 0;

    /**
   * List the Segments routed through section "iSectionNumber" of a multi-sectional support. 
   * This function also list all U and V positional values of segments on one to one mapping basis.
   * .i.e. first elements of "oppListOfSegmentU" and "oppListOfSegmentV" will correspond to U and V of first segment in "opListOfSegments"
   *
   * @param oppListOfSegments
   *   This List is updated with segments passing through section specified by "iSectionNumber".
   *
   * @param iSectionNumber
   *   section number through which list routed segments along with their U and V is required
   *   section number starts from 1.
   *
   * @param oppListOfSegmentU
   *   This list is updated with U values corresponding to segments updated in list "oppListOfSegments". 
   *   First element in this list corresponds to U value of first segment in list "oppListOfSegments"
   *
   * @param oppListOfSegmentU
   *   This list is updated with V values corresponding to segments updated in list "oppListOfSegments". 
   *   First element in this list corresponds to V value of first segment in list "oppListOfSegments"
   *
   * @return
   *   Return code S_OK   if oppListOfSegments is correctly retrieved.
   *               S_FALSE  with oppListOfSegments->Size() = 0 when no Segments routed through section.
   *               E_FAIL if oppListOfSegments cannot be retrieved.             
   **/
  virtual HRESULT ListSegments(CATListValCATBaseUnknown_var **oppListOfSegments,
                               int                            iSectionNumber = 1,
                               CATListOfDouble              **oppListOfSegmentU = NULL, 
                               CATListOfDouble              **oppListOfSegmentV = NULL) = 0;

    /**
   * Sets U and V of List the Segments routed through a particular section of a multi-sectional support. 
   * There must be one to one mapping between elements of Lists "ipListOfSegments", "ipListOfSegmentU" and 
   * "ipListOfSegmentV"
   *     i.e U value of first element in List "ipListOfSegments" = value of first element in List :ipListOfSegmentU"
   *         V value of first element in List "ipListOfSegments" = value of first element in List :ipListOfSegmentV"
   *        
   *         U value of second element in List "ipListOfSegments" = value of second element in List :ipListOfSegmentU"
   *         V value of second element in List "ipListOfSegments" = value of second element in List :ipListOfSegmentV" 
   *         and so on.....
   * @param ipListOfSegments
   *   Contains List segments routed through section specified by "iSectionNumber".
   *
   * @param ipListOfSegmentU
   *   Contains U values of segments in list "ipListOfSegments". 
   *
   * @param ipListOfSegmentV
   *   Contains V values of segments in list "ipListOfSegments".
   *
   * @param iSectionNumber
   *   section number through which segments specified by list of segments "ipListOfSegments" are routed
   *   section number starts from 1.
   *
   * @return
   *   Return code S_OK   if Segment Positions are correctly set.
   *               E_FAIL if Segment Positions cannot be set.
   **/
  virtual HRESULT SetSegmentPositions(CATListValCATBaseUnknown_var *ipListOfSegments,                                      
                                      CATListOfDouble              *ipListOfSegmentU, 
                                      CATListOfDouble              *ipListOfSegmentV,
                                      int                           iSectionNumber = 1) = 0;

};
CATDeclareHandler(CATIElbSupport, CATBaseUnknown );
//------------------------------------------------------------------

#endif
