#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=NONE

LINK_WITH = JS0ERROR JS0CORBA JS0LIB0 NS0S3STR

LOCAL_CCFLAGS  = -DCATVIZ_SPECIFICATION 
LOCAL_CFLAGS   = -DCATVIZ_SPECIFICATION


OS = IRIX
LOCAL_CCFLAGS  = -float -DCATVIZ_SPECIFICATION -G0  
LOCAL_LDFLAGS  =  -G0
LOCAL_CFLAGS   = -float -DCATVIZ_SPECIFICATION

OS = AIX
LOCAL_CCFLAGS  = -DCATVIZ_SPECIFICATION 
LOCAL_CFLAGS   = -DCATVIZ_SPECIFICATION

OS = SunOS
LOCAL_CCFLAGS  = -DCATVIZ_SPECIFICATION 
LOCAL_CFLAGS   = -DCATVIZ_SPECIFICATION

OS = HP-UX
LOCAL_CCFLAGS  = -DCATVIZ_SPECIFICATION 
LOCAL_CFLAGS   = -DCATVIZ_SPECIFICATION
