#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=NONE

LINK_WITH = VE0GRPH2 \
	    VE0BASE \
	    DI0PANV2 \
            JS0CORBA JS0SCBAK JS0FM JS0ERROR JS0STR JS03TRA \
	    AD0XXBAS \
	    ON0GRBAS ON0GREXT ON0INVOK \
	    NS0S3STR \
	    CO0LSTPV CO0LSTST CO0RCINT \
	    ON0MAIN ON0INVOK

# for tracing :
# LOCAL_CCFLAGS= -DTRACE_ON

