#
# LOAD MODULE
#
BUILT_OBJECT_TYPE= NONE

LINK_WITH = JS0CORBA JS0FM JS0SCBAK  JS0GROUP JS0STR JS03TRA JS0LIB0 JS0ERROR\
            DI0PANV2 NS0S3STR NS0S1MSG CO0LSTPV JS0CATLM CATDlgStandard\
            CATApplicationFrame CATWorkbenchUtil 
