#
BUILT_OBJECT_TYPE=LOAD MODULE
#
#OS = COMMON
PROGRAM_NAME = CATSoftwareMgt
#
#BUILD=NO
LINK_WITH = WFTOCTools CXINSTDATA CXINSTUTIL DI0PANV2 JS0SCBAK JS0CORBA JS0FM JS0STR JS0ERROR NS0S3STR NS0S1MSG 

SYS_LIBS =
SH_SYS_LIBS = $(SYS_LIBS)
SYS_LIBPATH =
SH_SYS_LIBPATH = $(SYS_LIBS)

OS = SunOS
SYS_LIBS = -lXm
FORTRAN_LIBS =

OS = Windows_NT
LINK_WITH = WFTOCTools CXINSTDATA CXINSTUTIL DI0PANV2 JS0SCBAK JS0CORBA JS0FM JS0STR JS0ERROR NS0S3STR NS0S1MSG CATDumpConfig 
SYS_LIBS =
MKMFC_DEPENDENCY=Yes 
LOCAL_LDFLAGS=$(SUB_WIN) /STACK:2100000
DESCRIPTION = "V5 Software Management"

