#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#

LINK_WITH = CORBAServerInfraUUID orbix JS0GROUP GW0COMUN CATCsbCORBA GW0LIBCX GW0SecuMgrAccess GW0EXIT CATSysDbSettings
CATCsbCORBA = SERVER

OS = AIX
LOCAL_CCFLAGS = -D_AIX_SOURCE
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH =
SYS_LIBS = -brtl 

OS = HP-UX
LOCAL_CCFLAGS = -D_HPUX_SOURCE -D_REENTRANT
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
#if os hpux_a
SYS_LIBS = -lcma
# libcma sur HP11 incompatible avec libpthread
#endif

OS = IRIX
LOCAL_CCFLAGS = -D_IRIX_SOURCE 
LOCAL_LDFLAGS = 
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
SYS_LIBS = -lgen -lCsup
SH_SYS_LIBS = $(SYS_LIBS)

OS = SunOS
LOCAL_CCFLAGS = -D_SUNOS_SOURCE -DNATIVE_EXCEPTION
LOCAL_LDFLAGS = -lsocket
CXX_EXCEPTION = 
SYS_INCPATH = 
SH_SYS_LIBPATH = $(SYS_LIBPATH)
SYS_LIBPATH =
# shared lib non multithreadee
SYS_LIBS =
SH_SYS_LIBS = $(SYS_LIBS)


OS = intel_a
#BUILD=NO
LINK_WITH = CORBAServerInfraUUID GW0COMUN JS0GROUP ITMi CATCsbCORBA GW0LIBCX GW0SecuMgrAccess GW0EXIT CATSysDbSettings
CATCsbCORBA = SERVER

LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /GX /Od /Zi  -DORBIX_DLL -DIT_EX_MACROS
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

OS = win_b
#BUILD=NO
LINK_WITH = CORBAServerInfraUUID GW0COMUN JS0GROUP ITMi CATCsbCORBA GW0LIBCX GW0SecuMgrAccess GW0EXIT CATSysDbSettings
CATCsbCORBA = SERVER

LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /GX /Od /Zi  -DORBIX_DLL -DIT_EX_MACROS
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

OS = win_b64
#BUILD=NO
LINK_WITH = CORBAServerInfraUUID GW0COMUN JS0GROUP ITMi CATCsbCORBA GW0LIBCX GW0SecuMgrAccess GW0EXIT CATSysDbSettings
CATCsbCORBA = SERVER
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DIT_EX_MACROS
#SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

OS = alpha_a
BUILD = NO

OS = win_a
BUILD = NO

