#Created by fl9 - cf the update on lex/bison with mkmk 
BUILT_OBJECT_TYPE = NONE
BUILD = NO


#FLAGS AND BISON CONFIGURATION
#FxParser_ will be the prefix of the generated method
LOCAL_BYFLAGS= -pDSFXParser
FLEX_VERSION=2.5.35
BISON_VERSION=2.4.1

OS = Windows
BUILD = YES
LOCAL_CCFLAGS = -DUSE_OLDPROGRAM -DFULL_NVFX

OS = iOS
BUILD = YES
LOCAL_CCFLAGS = -DUSE_OLDPROGRAM -DFULL_NVFX
LOCAL_CCFLAGS = -DOGLES2 -DLAME_USE -DFULL_NVFX
