#for SRC_LINK_WITH in fw CATCDSDebug.tst
ALLOW_STATIC_LINK=YES 

# COPYRIGHT DASSAULT SYSTEMES 2012
#======================================================================
# Imakefile for module CDSModel.m
#======================================================================
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=NONE

# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP CATMathematics \
CATCDSUtilities

# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

LOCAL_CCFLAGS_ASSERT=-DNOT_CDS_ASSERT $(MKMK_DEBUG:+"-DCDS_ASSERT")

#if os Windows
LOCAL_CCFLAGS=-D_HAS_EXCEPTIONS=0 $(LOCAL_CCFLAGS_ASSERT)
#elif os Linux
LOCAL_CCFLAGS=-std=c++0x -DCPP11_AVALAIBLE $(LOCAL_CCFLAGS_ASSERT)
#else
LOCAL_CCFLAGS=$(LOCAL_CCFLAGS_ASSERT)
#endif
