#
BUILT_OBJECT_TYPE = SHARED LIBRARY

#

#
OS = AIX
#SYS_INCPATH =  -I$(WSROOT)/Db2/include/aix_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  db2
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
#
OS = HP-UX
BUILD=YES
#SYS_INCPATH =  -I$(WSROOT)/Db2/include/hpux_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  db2
LOCAL_CCFLAGS= +p  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
#
OS = IRIX
BUILD=YES
#SYS_INCPATH =  -I$(WSROOT)/Db2/include/irix_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO db2
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
LOCAL_LDFLAGS= -rpath /opt/IBMdb2/V6.1/lib32
#LOCAL_LDFLAGS= 
#
OS = SunOS
BUILD=YES
#SYS_INCPATH =  -I$(WSROOT)/Db2/include/solaris_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO  db2
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY

OS = alpha_a
BUILD=NO

OS = intel_a
BUILD=YES
#SYS_INCPATH =  -I$(WSROOT)\Db2\Include\win_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO db2cli db2api
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY

OS = intel_a64
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO db2cli db2api
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
  
OS = win_a
BUILD=YES
#SYS_INCPATH =  -I$(WSROOT)\Db2\Include\win_a
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO db2cli db2api
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY

OS = win_b64
BUILD=YES
LINK_WITH=  PR0BASE JS0STR JS0ERROR JS03TRA JS0CORBA NS0S3STR CO0LSTPV CO0HDICO db2api
LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY
