#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
#
LINK_WITH = CO0LSTPV\
	JS0CORBA NS0S3STR\
	CO0RCINT CO0LSTPV\
	AC0SPBAS AD0XXBAS AC0DOMAIN\
	CO0LSTST\
	PCBoard PCBServices KnowledgeItf

LOCAL_CCFLAGS=  -D_CPP_IOSTREAMS -D__EXTERN_C__ -DCATDYNMRY

OS = Windows_NT
LOCAL_CCFLAGS = -D_CATNoWarningPromotion_
LOCAL_CFLAGS = -D_CATNoWarningPromotion_
#
