#
# SHARED LIBRARY : CATPrsSettings.m
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = PRDSettings

LINK_WITH = AD0XXBAS AS0STARTUP CD0FRAME CD0WIN Collections\
            DI0PANV2 JS0FM JS0GROUP NS0S3STR\
            ObjectModeler OM0EDPRO VE0MDL VE0BASE\
            CATDlgStandard \
            CATViz
#
