#
# STDFRAME
#

BUILT_OBJECT_TYPE=NONE

LINK_WITH= \
        CD0WIN CD0FRAME \
        DI0PANV2 \
        JS03TRA JS0STR JS0CORBA JS0FM JS0LIB0 JS0SCBAK \
        NS0S3STR \
        AD0XXBAS ON0MAIN ON0FRAME \
        VE0BASE VE0MDL VI0OMVUE

SYS_LIBS =

SYS_INCPATH =
SYS_LIBPATH =

