/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAArrNomenclatures_h
#define CATIAArrNomenclatures_h

#ifndef ExportedByCATArrangementPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATArrangementPubIDL
#define ExportedByCATArrangementPubIDL __declspec(dllexport)
#else
#define ExportedByCATArrangementPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATArrangementPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIACollection.h"
#include "CATVariant.h"

class CATIAArrNomenclature;

extern ExportedByCATArrangementPubIDL IID IID_CATIAArrNomenclatures;

class ExportedByCATArrangementPubIDL CATIAArrNomenclatures : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddUserNomenclature(const CATBSTR & iName, const CATBSTR & iIconName, const CATBSTR & iClassType, const CATBSTR & iSuperType, CATIAArrNomenclature *& oUserNomenclature)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAArrNomenclature *& oUserNomenclature)=0;


};

CATDeclareHandler(CATIAArrNomenclatures, CATIACollection);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
