/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAArrangementPathways_h
#define CATIAArrangementPathways_h

#ifndef ExportedByCATArrangementPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATArrangementPubIDL
#define ExportedByCATArrangementPubIDL __declspec(dllexport)
#else
#define ExportedByCATArrangementPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATArrangementPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATSafeArray.h"
#include "CATVariant.h"

class CATIAArrangementPathway;
class CATIAMove;

extern ExportedByCATArrangementPubIDL IID IID_CATIAArrangementPathways;

class ExportedByCATArrangementPubIDL CATIAArrangementPathways : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddPathway(CATIAMove * iRelAxis, const CATSafeArrayVariant & iListofMathPoints, const CATSafeArrayVariant & iMathDirection, CATIAArrangementPathway *& oArrPathway)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAArrangementPathway *& oArrPathway)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIAArrangementPathways, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
