/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAArrangementRectangles_h
#define CATIAArrangementRectangles_h

#ifndef ExportedByCATArrangementPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATArrangementPubIDL
#define ExportedByCATArrangementPubIDL __declspec(dllexport)
#else
#define ExportedByCATArrangementPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATArrangementPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATSafeArray.h"
#include "CATVariant.h"

class CATIAArrangementRectangle;
class CATIAMove;

extern ExportedByCATArrangementPubIDL IID IID_CATIAArrangementRectangles;

class ExportedByCATArrangementPubIDL CATIAArrangementRectangles : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddRectangle(CATIAMove * iRelAxis, const CATSafeArrayVariant & iPosition, double iWidth, double iLength, CATIAArrangementRectangle *& oArrRectangle)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAArrangementRectangle *& oArrRectangle)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIAArrangementRectangles, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
