/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAArrangementItemReservations_h
#define CATIAArrangementItemReservations_h

#ifndef ExportedByCATArrangementPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATArrangementPubIDL
#define ExportedByCATArrangementPubIDL __declspec(dllexport)
#else
#define ExportedByCATArrangementPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATArrangementPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATSafeArray.h"
#include "CATVariant.h"

class CATIAArrangementItemReservation;
class CATIAMove;

extern ExportedByCATArrangementPubIDL IID IID_CATIAArrangementItemReservations;

class ExportedByCATArrangementPubIDL CATIAArrangementItemReservations : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddItemReservation(CATIAMove * iRelAxis, const CATSafeArrayVariant & iPosition, double iXMin, double iYMin, double iZMin, double iXMax, double iYMax, double iZMax, CATIAArrangementItemReservation *& oArrItemReservation)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAArrangementItemReservation *& oArrItemReservation)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIAArrangementItemReservations, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
