/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAArrangementBoundaries_h
#define CATIAArrangementBoundaries_h

#ifndef ExportedByCATArrangementPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATArrangementPubIDL
#define ExportedByCATArrangementPubIDL __declspec(dllexport)
#else
#define ExportedByCATArrangementPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATArrangementPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATSafeArray.h"
#include "CATVariant.h"

class CATIAArrangementBoundary;
class CATIAMove;

extern ExportedByCATArrangementPubIDL IID IID_CATIAArrangementBoundaries;

class ExportedByCATArrangementPubIDL CATIAArrangementBoundaries : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall AddBoundary(CATIAMove * iRelAxis, const CATSafeArrayVariant & iListofMathPoints, const CATSafeArrayVariant & iMathDirection, CATIAArrangementBoundary *& oArrBoundary)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAArrangementBoundary *& oArrBoundary)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIAArrangementBoundaries, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
