#ifndef CATIAPlantReviewWorkBench_IDL
#define CATIAPlantReviewWorkBench_IDL

/*IDLREP*/

// ****************************************************************************
// CATIA Version 5 Release 2 Framework AECReview Interfaces
// Copyright Dassault Systemes 1998
// ****************************************************************************
//  Abstract:
//  ---------
//    
//  Interfaces for VB Plant Review Workbench
//    
// ****************************************************************************
//  Usage:
//  ------
//  Select the AEC Objects By Name or Type
//
//  WARNING: this Interface is for DEMO only
//  --------
//  
// ****************************************************************************
//  Inheritance:
//  ------------
//  
// ****************************************************************************
//  Main Methods:
//  -------------
//    
// ****************************************************************************
//  Historic
//  --------
//
//  Author: Laurent Bianchi
//  Date  : 27/11/98
//  But   : Creation
//
// ****************************************************************************

#include "CATIABase.idl"
#include "CATIAWorkbench.idl"
          
  /**
   * The interfaces to select Plant or Ship objects in the current document.
   */
interface CATIAPlantReviewWorkBench : CATIAWorkbench
{

  /**
   * Select Plant Objects By their Name.
   */

  HRESULT SelectByName(in CATBSTR  iObjectName);

  /**
   * Select Plant Objects By their Type.
   */

  HRESULT SelectByType(in CATBSTR  iObjectType);

};

// Interface name : CATIAPlantReviewWorkBench
#pragma ID CATIAPlantReviewWorkBench "DCE:b87aa4b5-efc2-0000-0280020cc2000000"
#pragma DUAL CATIAPlantReviewWorkBench

// VB object name : PlantReviewWorkbench
#pragma ID PlantReviewWorkbench "DCE:87aa4d24-7ad6-0000-0280020cc2000000"
#pragma ALIAS CATIAPlantReviewWorkBench PlantReviewWorkbench

#endif


