#ifndef CATIACGRAdhesionSettingAtt_IDL
#define CATIACGRAdhesionSettingAtt_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 2007
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIABase.idl"
#include "CATVariant.idl"
#include "CATSafeArray.idl"
#include "CATIASettingController.idl"
#include "CATBSTR.idl"

/**
* Represents the base object to handle the parameters of the cache.
*/
interface CATIACGRAdhesionSettingAtt : CATIASettingController
{
#pragma PROPERTY V4_Model_CommentPage
   /**
   * Retrieves the V4_Model_CommentPage container activation state.
   */
   HRESULT get_V4_Model_CommentPage     ( out /*IDLRETVAL*/ boolean oIsActive);    

   /**
   * Sets the V4_Model_CommentPage container activation state.
   */
   HRESULT put_V4_Model_CommentPage     ( in boolean iIsActive);    

   /** 
   * Locks or unlocks the V4_Model_CommentPage container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT GetV4_Model_CommentPageInfo  ( inout CATBSTR AdminLevel, inout CATBSTR oLocked, out  /*IDLRETVAL*/ boolean oModified);    

   /** 
   * Retrieves information about the V4_Model_CommentPage container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT SetV4_Model_CommentPageLock  ( in boolean iLocked);    


#pragma PROPERTY V4_Model_LnF

   /**
   * Retrieves the V4_Model_LnF container activation state.
   */
   HRESULT get_V4_Model_LnF     ( out /*IDLRETVAL*/ boolean oIsActive);    

   /**
   * Sets the V4_Model_LnF container activation state.
   */
   HRESULT put_V4_Model_LnF     ( in boolean iIsActive);    

   /** 
   * Retrieves information about the V4_Model_LnF container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT GetV4_Model_LnFInfo  ( inout CATBSTR AdminLevel, inout CATBSTR oLocked, out  /*IDLRETVAL*/ boolean oModified);    

   /** 
   * Locks or unlocks the V4_Model_LnF container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT SetV4_Model_LnFLock  ( in boolean iLocked);    

#pragma PROPERTY V5_SPA

   /**
   * Retrieves the V5_SPA container activation state.
   */
   HRESULT get_V5_SPA     ( out /*IDLRETVAL*/ boolean oIsActive);    

   /**
   * Sets the V5_SPA container activation state.
   */
   HRESULT put_V5_SPA     ( in boolean iIsActive);    

   /** 
   * Retrieves information about the V5_SPA container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT GetV5_SPAInfo  ( inout CATBSTR AdminLevel, inout CATBSTR oLocked, out  /*IDLRETVAL*/ boolean oModified);    

   /** 
   * Locks or unlocks the V5_SPA container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT SetV5_SPALock  ( in boolean iLocked);    

#pragma PROPERTY V4V5_FDT

   /**
   * Retrieves the V4V5_FDT container activation state.
   */
   HRESULT get_V4V5_FDT     ( out /*IDLRETVAL*/ boolean oIsActive);    

   /**
   * Sets the V4V5_FDT container activation state.
   */
   HRESULT put_V4V5_FDT     ( in boolean iIsActive);    

   /** 
   * Retrieves information about the V4V5_FDT container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT GetV4V5_FDTInfo  ( inout CATBSTR AdminLevel, inout CATBSTR oLocked, out  /*IDLRETVAL*/ boolean oModified);    

   /** 
   * Locks or unlocks the V4V5_FDT container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT SetV4V5_FDTLock  ( in boolean iLocked);    

#pragma PROPERTY Voxels
   /**
   * Retrieves the Voxels container activation state.
   */
   HRESULT get_Voxels     ( out /*IDLRETVAL*/ boolean oIsActive);    

   /**
   * Sets the Voxels container activation state.
   */
   HRESULT put_Voxels     ( in boolean iIsActive);    

   /** 
   * Retrieves information about the Voxels container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT GetVoxelsInfo  ( inout CATBSTR AdminLevel, inout CATBSTR oLocked, out  /*IDLRETVAL*/ boolean oModified);    

   /** 
   * Locks or unlocks the Voxels container activation state.
   * <br>Refer to @href CATSysSettingController for a detailed description.
   */
   HRESULT SetVoxelsLock  ( in boolean iLocked);    
};

// Interface Name : CATIAVisCGRAdhesionSettingAtt
#pragma ID CATIACGRAdhesionSettingAtt "DCE:d402b65d-7bed-4e55-a95091a38de2d45c"
#pragma DUAL CATIACGRAdhesionSettingAtt

// VB Object Name : CGRAdhesionSettingAttAtt
#pragma ID CGRAdhesionSettingAtt "DCE:8d33c141-05b7-4840-9887c0bcf5ca4f8f"
#pragma ALIAS CATIACGRAdhesionSettingAtt CGRAdhesionSettingAtt

#endif
