#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE
#

INCLUDED_MODULES = AC0CATNAV

COMDYN_MODULE = V4SysCOMD

DUMMY_LINK_WITH = CATCdbEntity AD0XXBAS AC0XXLNK \
            JS0CORBA JS0SCBAK JS03TRA JS0SETT JS0STR JS0COMP \
            JT0TRCBK JS0LIB0 \
            NS0S3STR NS0S7TIM \
            CO0LSTPV CO0LSTST \
            YP00IMPL 

#
OS = COMMON
#SOURCES_PATH=ProtectedInterfaces 
#COMPILATION_IDL=YES
LINK_WITH = $(DUMMY_LINK_WITH) 

SYS_LIBPATH = 
