#
BUILT_OBJECT_TYPE = SHARED LIBRARY
INCLUDED_MODULES = CDMA_PS_MAPPING
#
OS = COMMON

LINK_WITH=	PR0BASE DI0PANV2 JS0FM \
			CDMAMapping NS0S1MSG CDMAdoc \
			CATCinServer AD0XXBAS CD0WIN CATPDMBaseUI AS0STARTUP \
            CATDlgStandard


