#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ObjectModelerBaseUUID \
PCBoardBaseUUID \
ProductStructureUUID
#else
LINK_WITH_FOR_IID =
#endif
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
#
LINK_WITH=$(LINK_WITH_FOR_IID)   CO0LSTPV \
             JS0CORBA AD0XXBAS  NS0S3STR  \
             CO0RCINT CO0LSTPV AC0XXLNK \
             CD0FRAME JS0FM \
	     CO0LSTST AS0STARTUP \
	     CD0WIN \
	     PCBoard PCBoardParse DI0PANV2 PCBServices \
	     DI0PANV2 PCBHeader JS0FILE CATObjectSpecsModeler

OS = COMMON
# 
OS = HP-UX
#
OS=IRIX
#


#
OS = SunOS
LINK_WITH=$(LINK_WITH_FOR_IID)  	CO0LSTPV\
		JS0CORBA AD0XXBAS NS0S3STR\
		CO0RCINT CO0LSTPV AC0XXLNK YI00IMPL\
		CD0FRAME DI0STATE OM0EDPRO JS0FM\
	        CO0LSTST YN000MFL VE0BASE AS0STARTUP\
		CXMODEL YN000MAT\
		SketcherItf MF0STARTUP CK0FEAT CD0WIN PCBoard \
	        PCBoardParse PCBServices DI0PANV2 \
		ProductStructureProtIDL PCBHeader JS0FILE CATObjectSpecsModeler
#
OS = wnt40i
LINK_WITH=$(LINK_WITH_FOR_IID)   	CO0LSTPV \
		JS0CORBA AC0CATPL AD0XXBAS NS0S3STR\
		CO0RCINT CO0LSTPV AC0XXLNK YI00IMPL\
		CD0FRAME DI0STATE OM0EDPRO JS0FM\
		CO0LSTST YP00IMPL YN000MFL VE0BASE AS0STARTUP\
		CXMODEL YN000MAT \
		SketcherItf MF0STARTUP CK0FEAT CD0WIN MecModItfCPP PartItf \
		PCBoard DI0PANV2 PCBHeader JS0FILE CATObjectSpecsModeler


    
#
OS = wnt40a
BUILD = NO
