# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CATTlgImpl.m
#======================================================================
#
#  Mar 2003  Creation: Code generated by the CAA wizard  fdm
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=NONE
 
LINK_WITH =

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
