# COPYRIGHT DASSAULT SYSTEMES 1999
#======================================================================
# Imakefile for module CATAsdJointItf.m 
#======================================================================
#
#  Nov 1999  Creation: Code generated by the CAA wizard  PLT
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0FM
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

INCLUDED_MODULES = \
                  CATAsdJointItfCPP \
                  CATAsdJointPubIDL \
                  CATAsdJointProIDL \
