#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# PG0GEPS : PostScript driver
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
LINK_WITH=$(LINK_WITH_FOR_IID) CATPrt JS0GROUP JS0FM DI0PANV2 Mathematics CATViz CATLightXml XMLParserItf

