# COPYRIGHT Dassault Systemes 2008
#======================================================================
# Imakefile for module CATToolingItfCPPUUID.m
#======================================================================
#
#  Jan 2008  Creation: Code generated by the CAA wizard  FFJ
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
