// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CATTlgUIItf
#======================================================================
#  2015/10/21 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH = \
            AC0SPBAS							\  # ObjectSpecsModeler
			CATLifSpecs							\  #KnowledgeInterfaces
			JS0GROUP							\
			MecModItfCPP						\  
			ObjectModelerSystemUUID				\



