BUILT_OBJECT_TYPE = LOAD MODULE
PROGRAM_NAME = CATIAENV
LINK_WITH = JS0GROUP JS0FM DI0PANV2 CATDlgStandard JS0SCBAK JS0CORBA JS0STR NS0S3STR JS0INITENV

#OS = AIX
#BUILD=NO

#OS = HP-UX
#BUILD=NO

#OS = IRIX
#BUILD=NO

OS = SunOS
SYS_LIBS = -lXm
#BUILD=NO

OS = Windows_NT
LOCAL_LDFLAGS= $(SUB_WIN)
MKMFC_DEPENDENCY=Yes 
DESCRIPTION="V5 Environment Management"
