#
# CATArrTransfer.m
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=  CO0LSTPV CO0LSTST \
AD0XXBAS AC0XXLNK CD0FRAME CD0WIN \
JS03TRA JS0STR JS0CORBA JS0FM JS0LIB0 JS0SCBAK \
NS0S3STR ON0MAIN VE0MDL \
DI0STATE DI0GRAF DI0APPLI YN000MFL YN000MAT \
VE0BASE ON0GREXT AS0STARTUP CATObjectSpecsModeler \
CATPspUUID \
ArrUtility ArrArrangement \
CATArrangementItf \
RouRoutableInterfaces 

#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_IID=CATArrangementInterfacesUUID CATRoutableUUID CATArrangementUUID CATArrangementUIUUID
#else
LINK_WITH_IID=
#endif

#------------
OS = COMMON
