BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=  JS0CORBA JS0FM JS0SCBAK JS0STR JS03TRA JS0LIB0 JS0ERROR JS0SETT\
            AD0XXBAS AC0XXLNK VE0BASE NS0S3STR NS0S1MSG CD0WIN CD0FRAME\
            DI0PANV2 YN000MFL \
            ON0FRAME CO0LSTST VE0GRPH2 CATDMUBase \
            CATNavigatorItf CATDMUModel CATDMUWind \
            CATPspUUID \
            AECReviewItf AS0STARTUP CATEsuProductServices

