#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#

BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = KS0LATE

LOCAL_CCFLAGS = -DSDAI_NOSTR

LINK_WITH=$(LINK_WITH_FOR_IID)  KS0SIMPL CO0LSTPV CO0HTAB CO0RCINT CO0LSTST CO0HDICO \
	    JS0CORBA NS0S3STR CO0SETST JS0SETT JS0STR AD0XXBAS 
OS = AIX

OS = HP-UX

OS = IRIX

OS = SunOS

