#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = CATIAEnable
COMDYN_MODULE = V4SysCOMD
#
DUMMY_LINK_WITH = CATCdbEntity CATObjectModelerBase CATObjectModelerCATIA \
         JS0CORBA JS0SCBAK JS03TRA JS0SETT JS0STR JS0COMP JS0FILE\
         JT0TRCBK JS0LIB0  NS0S3STR CO0LSTPV CO0LSTST \
         CATAIXServices CATIAPrjEntity CATOmx
#
OS = COMMON
LINK_WITH = $(DUMMY_LINK_WITH)
SYS_LIBPATH = 
