#
# LOAD MODULE
#
BUILT_OBJECT_TYPE=LOAD MODULE

PROGRAM_NAME=VPMSettings

LINK_WITH = GUIDVPMServices ObjectModeler VX0TOOLS JS0SETT JS0STR \
            JS0SCBAK JS03TRA JS0LIB0 JS0ERROR       \
            NS0S3STR GUIDVPMInterfaces


OS = AIX
OS = HP-UX
OS = IRIX
OS = SunOS
OS = Windows_NT

