BUILT_OBJECT_TYPE = SHARED LIBRARY 
BUILD = YES 

LINK_WITH = \
  CATCDSUtilities \
  CATCDS		  \
  CATWBx

SRC_LINK_WITH = \
  CATCDSPlug2DImpl

LOCAL_LD_ADDED_OBJECTS =

LOCAL_CCFLAGS_ASSERT=-DNOT_CDS_ASSERT $(MKMK_DEBUG:+"-DCDS_ASSERT")

#if os Windows
LOCAL_CCFLAGS=-D_HAS_EXCEPTIONS=0 $(LOCAL_CCFLAGS_ASSERT)
#elif os Linux
LOCAL_CCFLAGS=-std=c++0x -DCPP11_AVALAIBLE $(LOCAL_CCFLAGS_ASSERT)
#else
LOCAL_CCFLAGS=$(LOCAL_CCFLAGS_ASSERT)
#endif
