# COPYRIGHT Dassault Systemes 2005
#======================================================================
# Imakefile for module CATPS2InterfacesUUID.m
#======================================================================
#
#  May 2005  Creation: Code generated by the CAA wizard  bcy
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
