#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
DatabaseServicesUUID
#else
LINK_WITH_FOR_IID =
#endif
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
OS = COMMON

#LINK_WITH= PR0BASE JS0CORBA  JS0STR JS03TRA JS0ERROR NS0S3STR CO0LSTPV CO0HDICO
# CO0LSTPV CO0SETST CO0LSTST JS0SETT  JS0SCBAK CO0RCINT JS0LIB0
LINK_WITH=$(LINK_WITH_FOR_IID)  JS0CORBA  CO0HDICO

OS = AIX
LOCAL_CCFLAGS=   -D_AIX_SOURCE
LOCAL_LDFLAGS = -bloadmap:load.log
SYS_LIBS  = 

#
OS = HP-UX

#
OS = IRIX

#
OS = SunOS

#
OS = Windows_NT
#BUILD = NO
