#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
Navigator4DBaseUUID \
NavigatorInterfacesUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID) JS0CORBA JS0FM JS0SCBAK JS0STR JS03TRA JS0LIB0 JS0ERROR JS0SETT \
            AD0XXBAS AC0XXLNK VE0BASE NS0S3STR NS0S1MSG CD0WIN CD0FRAME \
            DI0PANV2 DI0STATE YN000MFL \
            CO0LSTST CATFileMenu \
            CATPrint CATNavigatorItf CATDMUModel CATCafRasterDocument \
			AC0CATPL SELECT CP0CLIP CP0SPEC DraftingItf CATCdbEntity CATDlgStandard \
			CATNavigator2Itf CATPrt CATMathStream CATViz 


