/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIATrack_h
#define CATIATrack_h

enum DMUTrackMoveMode {
        DMUTrackSpeedMode,
        DMUTrackTimeMode
};

#ifndef ExportedByFittingPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __FittingPubIDL
#define ExportedByFittingPubIDL __declspec(dllexport)
#else
#define ExportedByFittingPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByFittingPubIDL
#endif
#endif

#include "CATIASampled.h"
#include "CATIATrack.h"
#include "CATSafeArray.h"

extern ExportedByFittingPubIDL IID IID_CATIATrack;

class ExportedByFittingPubIDL CATIATrack : public CATIASampled
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Speed(double & oSpeed)=0;

    virtual HRESULT __stdcall put_Speed(double iSpeed)=0;

    virtual HRESULT __stdcall Mirror(const CATSafeArrayVariant & iPoint, const CATSafeArrayVariant & iNormal)=0;

    virtual HRESULT __stdcall Move(const CATSafeArrayVariant & iTransfo)=0;

    virtual HRESULT __stdcall GetMatrixAll(CATSafeArrayVariant & oMatrixAll)=0;

    virtual HRESULT __stdcall get_MoveMode(DMUTrackMoveMode & oMoveMode)=0;

    virtual HRESULT __stdcall put_MoveMode(DMUTrackMoveMode iMoveMode)=0;


};

CATDeclareHandler(CATIATrack, CATIASampled);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
