/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASampleds_h
#define CATIASampleds_h

#ifndef ExportedByFittingPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __FittingPubIDL
#define ExportedByFittingPubIDL __declspec(dllexport)
#else
#define ExportedByFittingPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByFittingPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATVariant.h"

class CATIASampled;

extern ExportedByFittingPubIDL IID IID_CATIASampleds;

class ExportedByFittingPubIDL CATIASampleds : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Add(CATIASampled *& oNewSampled)=0;

    virtual HRESULT __stdcall AddFromSel(CATIASampled *& oNewSampled)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIASampled *& oSampled)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIASampleds, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIASampled.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
