#for SRC_LINK_WITH in fw CATCDSDebug.tst
ALLOW_STATIC_LINK=YES 

#
BUILT_OBJECT_TYPE = NONE
#
LINK_WITH = \
  JS0GROUP

LOCAL_CCFLAGS_ASSERT=-DNOT_CDS_ASSERT $(MKMK_DEBUG:+"-DCDS_ASSERT")

#if os Windows
LOCAL_CCFLAGS=-D_HAS_EXCEPTIONS=0 $(LOCAL_CCFLAGS_ASSERT)
#else
LOCAL_CCFLAGS=$(LOCAL_CCFLAGS_ASSERT)
#endif
