#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID \
CATIAApplicationFrameUUID \
CATVisUUID \
ObjectModelerBaseUUID \
SystemUUID \
InteractiveInterfacesUUID
#else
LINK_WITH_FOR_IID =
#endif

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID) CATDialogEngine CD0FRAME CATVisualization CATViz DI0PANV2 JS0STR JS0FM \
 ON0MAIN ON0FRAME VE0GRPH2 ON0GRAPH NS0S3STR CO0LSTST JS0CORBA CD0STWIN CATTreeOptions AC0XXLNK\ 




