# COPYRIGHT Dassault Systemes 2008
#======================================================================
# Imakefile for module CATCldBasicTemp.m
#======================================================================
#
#  Apr 2008  Creation: Code generated by the CAA wizard  dnr
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE = NONE
 
LINK_WITH = 

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
