#
BUILT_OBJECT_TYPE= SHARED LIBRARY
#

LINK_WITH=CD0FRAME JS0FM JS0STR JS0CORBA JS0SCBAK NS0S1MSG NS0S3STR\
           JS0ERROR AD0XXBAS DI0PANV2\
           SELECT\
           ObjectModeler CATPrdCommands\
           JS0CATLM PRDCommands CATPrsWksPRDWorkshop\
		   AS0STARTUP



