#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID \
CATVisUUID \
NavigatorInterfacesUUID \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID)  JS0FM AD0XXBAS NS0S1MSG CD0FRAME DI0PANV2 \
								VE0BASE  YN000MFL ON0FRAME CATInfInterfaces\
								ON0GRAPH CATNavigatorItf CATViz\
								CATMathStream
            
