// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CATToolingSurfacic
#======================================================================
#  2013/06/10 Creation: Code generated by the 3DS wizard
#======================================================================
#
#
# NONE
#
BUILT_OBJECT_TYPE=NONE


#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: THE 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP   \
CATToolingSurfacicItfCPP
# END WIZARD EDITION ZONE
