/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAFunctActionsGroup_h
#define CATIAFunctActionsGroup_h

#ifndef ExportedByCATFunctSystemPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATFunctSystemPubIDL
#define ExportedByCATFunctSystemPubIDL __declspec(dllexport)
#else
#define ExportedByCATFunctSystemPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATFunctSystemPubIDL
#endif
#endif

#include "CATIABase.h"
#include "CATVariant.h"

class CATIAFunctionalAction;

extern ExportedByCATFunctSystemPubIDL IID IID_CATIAFunctActionsGroup;

class ExportedByCATFunctSystemPubIDL CATIAFunctActionsGroup : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_ActionsCount(CATLONG & oCount)=0;

    virtual HRESULT __stdcall Retrieve(const CATVariant & iIndex, CATIAFunctionalAction *& oAction)=0;

    virtual HRESULT __stdcall Add(CATIAFunctionalAction * iAction)=0;

    virtual HRESULT __stdcall Remove(CATIAFunctionalAction * iAction)=0;

    virtual HRESULT __stdcall RemovePosition(CATLONG iPosition)=0;

    virtual HRESULT __stdcall GetExtremities(double & oInputX, double & oInputY, double & oOutputX, double & oOutputY)=0;

    virtual HRESULT __stdcall SetExtremities(double iInputX, double iInputY, double iOutputX, double iOutputY)=0;


};

CATDeclareHandler(CATIAFunctActionsGroup, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
