/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAFunctionalDocument_h
#define CATIAFunctionalDocument_h

#ifndef ExportedByCATFunctSystemPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATFunctSystemPubIDL
#define ExportedByCATFunctSystemPubIDL __declspec(dllexport)
#else
#define ExportedByCATFunctSystemPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATFunctSystemPubIDL
#endif
#endif

#include "CATIADocument.h"

class CATIAFunctFacetManagers;
class CATIAFunctionalDescription;

extern ExportedByCATFunctSystemPubIDL IID IID_CATIAFunctionalDocument;

class ExportedByCATFunctSystemPubIDL CATIAFunctionalDocument : public CATIADocument
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_FacetManagers(CATIAFunctFacetManagers *& oLstFM)=0;

    virtual HRESULT __stdcall get_OriginalDescription(CATIAFunctionalDescription *& oOriginal)=0;

    virtual HRESULT __stdcall get_CurrentDescription(CATIAFunctionalDescription *& oCurrent)=0;


};

CATDeclareHandler(CATIAFunctionalDocument, CATIADocument);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
