/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAFunctMultiRepMgr_h
#define CATIAFunctMultiRepMgr_h

#ifndef ExportedByCATFunctSystemPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATFunctSystemPubIDL
#define ExportedByCATFunctSystemPubIDL __declspec(dllexport)
#else
#define ExportedByCATFunctSystemPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATFunctSystemPubIDL
#endif
#endif

#include "CATIAFunctionalFacet.h"

class CATIAFunctAssociations;

extern ExportedByCATFunctSystemPubIDL IID IID_CATIAFunctMultiRepMgr;

class ExportedByCATFunctSystemPubIDL CATIAFunctMultiRepMgr : public CATIAFunctionalFacet
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_CurrentAssoc(CATLONG & oCurrentAssoc)=0;

    virtual HRESULT __stdcall put_CurrentAssoc(CATLONG iCurrentAssoc)=0;

    virtual HRESULT __stdcall get_Associations(CATIAFunctAssociations *& oAssociations)=0;


};

CATDeclareHandler(CATIAFunctMultiRepMgr, CATIAFunctionalFacet);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
