#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

LINK_WITH = AC0SPBAS AD0XXBAS AS0STARTUP CD0FRAME CD0WIN Collections\
            VE0GRPH2 DI0PANV2 JS0FM JS0GROUP NS0S3STR\
            ObjectModeler OM0EDPRO VE0MDL YN000MAT VE0BASE YN000MFL\
            ProductStructureItf AS0STNAV CATObjectSpecsModeler\
#
