BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH = AC0SPBAS AD0XXBAS CD0FRAME CD0WIN DI0PANV2 DI0STATE JS0GROUP JS0FM \
			ON0PROP VE0GEDIT YN000MFL \
			KnowledgeItf CATVisualization CATSktAssistant \
            CATProductStructure1 CATPspUtilities CATPspItfCPP CATPspUUID \
			CATEsuUtil 

SH_LINK_WITH= $(LINK_WITH)


