#
BUILT_OBJECT_TYPE = SHARED LIBRARY 
INCLUDED_MODULES = HighlightInPSN
#
OS = COMMON

LINK_WITH=	CO0LSTPV JS0FM DI0STATE AS0STARTUP AD0XXBAS AC0XXLNK\
			CD0FRAME CATCinDispatcher CATIPSInteroperability CDMAServer\
			TalkingToPSN CATPDMInteropVPMCommand CATPDMBaseItfCPP CDMAdoc
