#ifndef CreateTopCorner_H 
#define CreateTopCorner_H 
//
// COPYRIGHT DASSAULT SYSTEMES 2003

/**
 * @CAA2Level L0
 * @CAA2Usage U0
 */ 

#include "FrFTopologicalOpe.h"
#include "CATSkillValue.h"
#include "CATGeoToTopOperator.h"
#include "CATTopDef.h"
#include <stdlib.h>
//
class CATTopCorner;
class CATGeoFactory;
class CATGeometry;
class CATBody;
class CATCGMJournalList;
class CATLaw;


/**
* Creates the operator defining a corner between two wires. 
* The wire can be degenerated by one vertex
 * @param iFactory
 * The pointer to the factory that creates the resulting body.
 * @param iTopData
 * The pointer to the data defining the software configuration and the journal. 
 * If the journal inside <tt>iTopData</tt> 
 * is <tt>NULL</tt>, it is not filled. 
 * @param iPassage1
 * The first wire.
 * @param iPassage2
 * The second wire.
* @param iSupport
 * The underlying support.
 * @param Radius
 * The radius
 * @return
 * The pointer to the created operator. 
 * To delete with the usual C++ <tt>delete</tt> operator after use.
 */
ExportedByFrFTopologicalOpe
CATTopCorner * CreateTopCornerBiTgt            (CATGeoFactory     * iFactory,
                                                CATTopData        * iTopData,
                                                CATBody           * iPassage1,
                                                CATBody           * iPassage2,
                                                CATBody           * iSupport,
                                                double              Radius);

/** @nodoc */
// Create CornerOnSupport beetwen a Vertex(iPt) on a Wire(iCrvPt) and a Wire(iCrv)
// only available for support == CATPlane
ExportedByFrFTopologicalOpe
CATTopCorner * CreateTopCornerTgtByPoint       (CATGeoFactory     * iFactory,
                                                CATBody           * iPassage,
                                                CATBody           * iCrvPt,
                                                CATBody           * iPt,
                                                CATBody           * iSupport,
                                                CATTopData        * iTopData);
/** @nodoc */
// Create CornerOnSupport beetwen three Wires
// only available for support == CATPlane 
ExportedByFrFTopologicalOpe
CATTopCorner * CreateTopCornerTriTangent       (CATGeoFactory     * iFactory,
                                                CATBody           * iPassage1,
                                                CATBody           * iPassage2,
                                                CATBody           * iPassage3,
                                                CATBody           * iSupport,
                                                CATTopData        * iTopData);

/** @nodoc */
ExportedByFrFTopologicalOpe
CATTopCorner * CreateTopCornerTgtCenterOnPt     (CATGeoFactory     * iFactory,
                                                CATTopData        * iTopData,
                                                CATBody           * iCrv    ,
                                                CATBody           * iPt     ,
                                                CATBody           * iSupport);

/** @nodoc */
ExportedByFrFTopologicalOpe
CATTopCorner * CreateTopCornerTgtCenterOnCrvRad(CATGeoFactory     * iFactory,
                                                CATTopData        * iTopData,
                                                CATBody           * iCurveCenter,
                                                CATBody           * iCurveTgt,
                                                double              iRadius,
                                                CATBody           * iSupport);

//
/** @nodoc */
ExportedByFrFTopologicalOpe
void Remove( CATTopCorner *&iTopologicalCorner );

//
#endif


