/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIACircPattern_h
#define CATIACircPattern_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByPartPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __PartPubIDL
#define ExportedByPartPubIDL __declspec(dllexport)
#else
#define ExportedByPartPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByPartPubIDL
#endif
#endif

#include "CATIAPattern.h"
#include "CATPatternDefs.h"
#include "CATSafeArray.h"

class CATIAAngularRepartition;
class CATIAIntParam;
class CATIALinearRepartition;
class CATIAReference;

extern ExportedByPartPubIDL IID IID_CATIACircPattern;

class ExportedByPartPubIDL CATIACircPattern : public CATIAPattern
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_RadialDirectionRow(CATIAIntParam *& oRadialRow)=0;

    virtual HRESULT __stdcall get_AngularDirectionRow(CATIAIntParam *& oAngularRow)=0;

    virtual HRESULT __stdcall get_RadialAlignment(CAT_VARIANT_BOOL & oIsAligned)=0;

    virtual HRESULT __stdcall put_RadialAlignment(CAT_VARIANT_BOOL iIsAligned)=0;

    virtual HRESULT __stdcall get_RotationOrientation(CAT_VARIANT_BOOL & oIsAligned)=0;

    virtual HRESULT __stdcall put_RotationOrientation(CAT_VARIANT_BOOL iIsAligned)=0;

    virtual HRESULT __stdcall get_RadialRepartition(CATIALinearRepartition *& oOnRadialRepartition)=0;

    virtual HRESULT __stdcall get_AngularRepartition(CATIAAngularRepartition *& oAngularRepartition)=0;

    virtual HRESULT __stdcall get_CircularPatternParameters(CatCircularPatternParameters & oParameters)=0;

    virtual HRESULT __stdcall put_CircularPatternParameters(CatCircularPatternParameters iParameters)=0;

    virtual HRESULT __stdcall GetRotationCenter(CATSafeArrayVariant & ioRotationCenter)=0;

    virtual HRESULT __stdcall SetRotationCenter(CATIAReference * iRotationCenter)=0;

    virtual HRESULT __stdcall GetRotationAxis(CATSafeArrayVariant & ioRotationAxis)=0;

    virtual HRESULT __stdcall SetRotationAxis(CATIAReference * iRotationAxis)=0;

    virtual HRESULT __stdcall SetUnequalStep(CATLONG iInstanceNumber)=0;

    virtual HRESULT __stdcall SetInstanceAngularSpacing(CATLONG iInstanceNumber, double iAngularSpacing)=0;

    virtual HRESULT __stdcall SetUnequalInstanceNumber(CATLONG iInstanceNumber)=0;


};

CATDeclareHandler(CATIACircPattern, CATIAPattern);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIAShape.h"
#include "CATIATransformationShape.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
