/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIADraftDomains_h
#define CATIADraftDomains_h

#ifndef ExportedByPartPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __PartPubIDL
#define ExportedByPartPubIDL __declspec(dllexport)
#else
#define ExportedByPartPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByPartPubIDL
#endif
#endif

#include "CATIACollection.h"
#include "CATVariant.h"

class CATIADraftDomain;

extern ExportedByPartPubIDL IID IID_CATIADraftDomains;

class ExportedByPartPubIDL CATIADraftDomains : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIADraftDomain *& oDraftDomain)=0;


};

CATDeclareHandler(CATIADraftDomains, CATIACollection);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
