/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAPrismExt_h
#define CATIAPrismExt_h

#ifndef ExportedByPartPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __PartPubIDL
#define ExportedByPartPubIDL __declspec(dllexport)
#else
#define ExportedByPartPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByPartPubIDL
#endif
#endif

#include "CATIABase.h"

class CATIAReference;

extern ExportedByPartPubIDL IID IID_CATIAPrismExt;

class ExportedByPartPubIDL CATIAPrismExt : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetProfileElement(CATIAReference * iPrismObj, CATIAReference *& oProfileElement)=0;


};

CATDeclareHandler(CATIAPrismExt, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
