/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAThread_h
#define CATIAThread_h

#ifndef ExportedByPartPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __PartPubIDL
#define ExportedByPartPubIDL __declspec(dllexport)
#else
#define ExportedByPartPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByPartPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIADressUpShape.h"
#include "CATThreadDefs.h"

class CATIALength;
class CATIAReference;
class CATIAStrParam;

extern ExportedByPartPubIDL IID IID_CATIAThread;

class ExportedByPartPubIDL CATIAThread : public CATIADressUpShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_LateralFaceElement(CATIAReference *& oLateralFaceElement)=0;

    virtual HRESULT __stdcall put_LateralFaceElement(CATIAReference * iLateralFaceElement)=0;

    virtual HRESULT __stdcall get_LimitFaceElement(CATIAReference *& oLimitFaceElement)=0;

    virtual HRESULT __stdcall put_LimitFaceElement(CATIAReference * iLimitFaceElement)=0;

    virtual HRESULT __stdcall ReverseDirection()=0;

    virtual HRESULT __stdcall get_Side(CatThreadSide & oThreadSide)=0;

    virtual HRESULT __stdcall put_Side(CatThreadSide iThreadSide)=0;

    virtual HRESULT __stdcall get_Depth(double & oDepth)=0;

    virtual HRESULT __stdcall put_Depth(double iDepth)=0;

    virtual HRESULT __stdcall get_Diameter(double & oDiameter)=0;

    virtual HRESULT __stdcall put_Diameter(double iDiameter)=0;

    virtual HRESULT __stdcall get_Pitch(double & oPitch)=0;

    virtual HRESULT __stdcall put_Pitch(double iPitch)=0;

    virtual HRESULT __stdcall get_ThreadDescription(CATIAStrParam *& oThreadDescParam)=0;

    virtual HRESULT __stdcall CreateStandardThreadDesignTable(CatThreadStandard iStandardType)=0;

    virtual HRESULT __stdcall CreateUserStandardDesignTable(const CATBSTR & iStandardName, const CATBSTR & iPath)=0;

    virtual HRESULT __stdcall SetExplicitPolarity(CatThreadPolarity iThreadPolarity)=0;


};

CATDeclareHandler(CATIAThread, CATIADressUpShape);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATIAShape.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
