/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATPatternDefs_h
#define CATPatternDefs_h

enum CatCircularPatternParameters {
        catInstancesandAngularSpacing,
        catCompleteCrown,
        catUnequalAngularSpacing
};

enum CatRectangularPatternParameters {
        catInstancesandSpacing,
        catUnequalSpacing
};

#endif
