# COPYRIGHT DASSAULT SYSTEMES 1999
#======================================================================
# Imakefile for module ArrArrangementInterfaces.m
#======================================================================
#
#  Jun 1999  Creation: Code generated by the CAA wizard  sd00ahi
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
SELECT \
CATApplicationFrame \
Collections \
CATMathematics \
CATObjectModelerBase CATObjectSpecsModeler \
CATProductStructure1 ProductStructureItf \
CATArrangementItf \
CATArrProductServices \
CATVisualization \
RouRoutableInterfaces \
CATMecModInterfaces \
CATMechanicalModeler \
CATGeometricObjects KnowledgeItf CATPspUUID CATEsuProductServices CATPspUtilities
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_IID=CATArrangementInterfacesUUID CATRoutableUUID
#else
LINK_WITH_IID=
#endif

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
