#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
INCLUDED_MODULES =	CATDataSendToObject
#
LINK_WITH1 = JS0GROUP DI0PANV2 CATApplicationFrame CATObjectModelerBase JS0FM JS0FILE VE0BASE\
			CATFileMenu InfItf CATViz CATAfrMail 
#
OS = COMMON
LINK_WITH=$(LINK_WITH1) 
OS = intel_a
LINK_WITH=$(LINK_WITH1) JS0SMT

OS = win_b
LINK_WITH=$(LINK_WITH1) JS0SMT

OS = win_b64
LINK_WITH=$(LINK_WITH1) JS0SMT

OS = intel_a64
LINK_WITH=$(LINK_WITH1) JS0SMT

OS = win_a
LINK_WITH=$(LINK_WITH1) JS0SMT
