#
BUILT_OBJECT_TYPE= NONE

#LOCAL_CCFLAGS = -DPRODSTRU_PROTO
#
INCLUDED_MODULES = PRDCommands

LINK_WITH= CD0FRAME JS0FM JS0STR JS0CORBA JS0SCBAK JS0FILE NS0S1MSG NS0S3STR\
           JS0ERROR AD0XXBAS DI0PANV2 AS0STARTUP CATPrdCommands\
           VE0BASE VE0MDL YN000MAT SELECT DI0STATE\
           AS0STNAV ProductStructureItf InfPubIDL\
           CATPrint CATIAEntity PRDExport ObjectModeler SpecsModeler\
           VE0GRPH2 JS0XXC0 JS0CATLM CATAssCommands CATPrsRep CATPrdIntegration
#

