#==================================================================================================
# COPYRIGHT DASSAULT SYSTEMES 1999
#==================================================================================================
# Imakefile for module CATCloudEditorInterfaces.m 
#==================================================================================================
#  Oct 1999  Creation: Code generated by the CAA wizard  sta
#==================================================================================================

BUILT_OBJECT_TYPE = SHARED LIBRARY
 
INCLUDED_MODULES = \
  CATCloudEditorItf \
  CATCloudEditorItfCPP 

LINK_WITH = \
  CATApplicationFrame \
  CATCloudEditorInterfacesUUID \
  JS0CORBA \
  JS0FM \
  JS0GROUP
