#
BUILT_OBJECT_TYPE=LOAD MODULE
#
BUILD=NO

OS = Windows_NT
BUILD = YES
LINK_WITH =  DSYAdmInfSA
LOCAL_CCFLAGS= -D_DSYAdmInf_Archive_SA /D RELEASE_STARTDATE=$(RD)
LOCAL_LDFLAGS=/SUBSYSTEM:WINDOWS
SYS_LIBS = Psapi.lib
STATIC_LIBS = yes
