# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module DNBStateAutomation.m
#======================================================================
#
#  Feb 2009  Creation: Code generated by the CAA wizard  XOL
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=NONE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP DNBStatePubIDL DNBStateInterfacesUUID
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
