# COPYRIGHT DASSAULT SYSTEMES 1999
#======================================================================
# Imakefile for module CATFcaMultiDirectedGraph.m
#======================================================================
#
#  Aug 1999  Creation: Code generated by the CAA wizard  PHB
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=NONE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0FM JS0GROUP  \
JS0SCBAK 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
