# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module DNBPertTypeLib.m
# Module for compilation of the typelib
#======================================================================
#
#  Feb 2001  Creation: Code generated by the CAA wizard  aditya
#======================================================================
#
# TYPELIB          
#

BUILT_OBJECT_TYPE=TYPELIB
# no more BUILD_PRIORITY=4

LINK_WITH = InfTypeLib 


OS = Windows_NT
#LOCAL_CCFLAGS=-FR
