#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
## FOR SMALL SYSTEM export MK_V5_LEVEL_ADDON=CATV5_SMALLSYSTEM


BUILT_OBJECT_TYPE=SHARED LIBRARY

#ifdef CATV5_SMALLSYSTEM
COMMON_MODULES = JS0CORBA JS03TRA JS0LIB0 JS0ERROR JS0SCBAK JS0STR \
	JS0CATOS JS0COMP  \
	CO0LSTPV CO0LSTST CO0SETST CO0RCINT CO0RCDBL CO0RCFLT CO0HTAB 
	CO0HDICO \
	Collections NS0S1MSG NS0S3STR NS0S7TIM NS0SI18N  CATBuildLevel \
	JS0HTTP JS0FILEEXIT  JS0SETT JS0MRSHL JS0CRYPTLBEXIT\
	GroupStubs JS0STDLIB JS0TSLIB JS0DRMDOC DSYSysBase DSYSysScramble DSYAdmInf
#	IClassFactoryImpl ListImpl JT0TRCBK 


#else
COMMON_MODULES = JS0CORBA JS03TRA JS0LIB0 JS0ERROR JS0SETT JS0SCBAK JS0MRSHL \
	JS0STR JS0CATOS JS0COMP JS0CTYP JT0TRCBK JS0DSPA JS0COL JS0LOGRP \
	JS0INF CO0LSTPV CO0LSTST CO0SETST CO0RCINT CO0RCDBL CO0RCFLT CO0HTAB \
	CO0HDICO Collections NS0S1MSG NS0S3STR NS0S7TIM NS0SI18N  \
	CATBuildLevel JS0CATLM COMPONENTV2 JS0HTTP JS0FILEEXIT JS0CRYPTLBEXIT \
	ConnectionPtsImpl ListImpl IClassFactoryImpl JS0STDLIB JS0TSLIB JS0DRMDOC \
	DSYSysBase DSYSysScramble DSYAdmInf
#endif

#ifdef CATV5_SMALLSYSTEM
COMMON_CCF=-DSYSTEM_IS_CUT
#else
COMMON_CCF=
#endif

INCLUDED_MODULES = $(COMMON_MODULES) 

#ifdef CATV5_SMALLSYSTEM
COMMON_LINK_WITH = JS0MT CATSysAllocator
#else
COMMON_LINK_WITH = JS0DSLOCK JS0MT CATSysAllocator CATSysTS JS0ZLIB	
#endif
SYS_INCPATH =
SYS_LIBPATH =

#
OS = AIX
#ifdef CATV5_SMALLSYSTEM
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID
#else
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID CATMainwin
#endif
SYS_LIBS = -liconv -lpthread
#ifdef CATIAV5R11
LOCAL_CREATEEXPFLAGS = $(WS_LIBPATH) 
#else
LOCAL_LDFLAGS =  $(WS_LIBPATH)
#endif

#
OS = HP-UX
#ifdef CATV5_SMALLSYSTEM
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID 
#else
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID CATMainwin
#endif
#if os hpux_a
SYS_LIBS= -lf -lcl
#else
SYS_LIBS= -lF90
#endif
LOCAL_LDFLAGS =  $(WS_LIBPATH) 

#
OS = hpux_b64 
#ifdef CATV5_SMALLSYSTEM
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID 
#else
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID CATMainwin
#endif
#if os hpux_a
SYS_LIBS= -lf -lcl
#else
SYS_LIBS= -lF90 -lcps 
#endif
LOCAL_LDFLAGS =  $(WS_LIBPATH) 

#
OS = IRIX
#ifdef CATV5_SMALLSYSTEM
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID 
#else
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID CATMainwin
#endif
SYS_LIBS = -lexc -lmangle -lpthread
LOCAL_LDFLAGS = $(LD_LIBPATH) 

#
OS = SunOS
#ifdef CATV5_SMALLSYSTEM
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID 
#else
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID CATMainwin
#endif
SYS_LIBS =
LOCAL_LDFLAGS =
# Remove the default Fortran libs
FORTRAN_LIBS = 

#
OS = solaris_a64
#ifdef CATV5_SMALLSYSTEM
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID 
#else
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID CATMainwin
#endif
SYS_LIBS = -ldemangle
LOCAL_LDFLAGS =

#
OS = Linux
#ifdef CATV5_SMALLSYSTEM
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID
#else
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID CATMainwin
#endif
SYS_LIBS =
LOCAL_LDFLAGS = 

#
OS = win_b64
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID
INCLUDED_MODULES = $(COMMON_MODULES) JS0CATREG
SYS_LIBS = wsock32.lib imagehlp.lib OldNames.lib KERNEL32.lib secur32.lib ADVAPI32.lib ole32.lib OLEAUT32.lib winmm.lib version.lib wininet.lib Mpr.lib shfolder.lib wbemuuid.lib Iphlpapi.lib
LOCAL_LDFLAGS = /NODEFAULTLIB:libC.lib /NODEFAULTLIB:libcmt.lib\
	        $(WS_LIBPATH)

#
OS = Windows_NT
LINK_WITH=$(LINK_WITH_FOR_IID)  $(COMMON_LINK_WITH) SystemUUID ShFolder
INCLUDED_MODULES = $(COMMON_MODULES) JS0CATREG
SYS_LIBS = wsock32.lib imagehlp.lib OldNames.lib KERNEL32.lib secur32.lib ADVAPI32.lib ole32.lib OLEAUT32.lib winmm.lib version.lib wininet.lib Mpr.lib shfolder.lib wbemuuid.lib Iphlpapi.lib
#SYS_LIBS = wsock32.lib netapi32.lib imagehlp.lib MSVCRT.lib OldNames.lib KERNEL32.lib ADVAPI32.lib ole32.lib OLEAUT32.lib MSVCIRT.lib winmm.lib
LOCAL_LDFLAGS = /NODEFAULTLIB:libC.lib\
	        $(WS_LIBPATH)
