#ifndef CATIAGeometry2D_IDL
#define CATIAGeometry2D_IDL
/*IDLREP*/

// COPYRIGHT DASSAULT SYSTEMES 1999

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIAGeometricElement.idl"

/**
 * 2D wireframe geometric element.
 */

interface CATIAGeometry2D : CATIAGeometricElement
{
    //        ================
    //        == PROPERTIES ==
    //        ================

#pragma PROPERTY ReportName
        /**
        *       Returns the report name of the 2D geometry          
        *       @param oReportName
        *       The integer value of the report name
        */
    HRESULT    get_ReportName   
                ( out  /*IDLRETVAL*/      long          oReportName );

//
        /**
        *       Imposes the report name of the 2D geometry
        *       @param iReportName
        *       The integer value of the report name
        */
    HRESULT    put_ReportName   
                ( in   long          iReportName );
//

#pragma PROPERTY Construction
        /**
        *       Returns the construction mode of the 2D geometry 
        */
    HRESULT    get_Construction   
                ( out   /*IDLRETVAL*/ boolean       oConstruction );

//
        /**
        *       Sets the construction mode of the 2D geometry 
        */
    HRESULT    put_Construction   
                ( in   boolean       iConstruction );
//

    //        =============
    //        == METHODS ==
    //        =============
};

// Interface name : CATIAGeometry2D
#pragma ID CATIAGeometry2D "DCE:0c438515-6a88-11d1-a2800000f87546fd"
#pragma DUAL CATIAGeometry2D

// VB object name : Geometry2D (Id used in Visual Basic)
#pragma ID Geometry2D "DCE:0c5b5c99-6a88-11d1-a2800000f87546fd"
#pragma ALIAS CATIAGeometry2D Geometry2D


#endif
// CATIAGeometry2D_IDL

