# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CATSddObjectNavigator.m
#======================================================================
#
#  Mar 2002  Creation: Code generated by the CAA wizard  sa00259
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \ \
JS0GROUP JS0FM DI0PANV2 CATApplicationFrame  \
CATPlantShipUIUUID 
# END WIZARD EDITION ZONE

LINK_WITH = JS0GROUP JS0FM JS0SCBAK JS0CORBA DI0PANV2 CATIAApplicationFrame \
            ObjectModelerBaseUUID CATApplicationFrame ON0GRAPH VE0BASE VE0MDL JS0DSPA \
            CATObjectModelerBase CATNavigatorItf CATDMUModel CATDMUWind VE0GRPH2 \
            CATProductStructure1 AD0XXBAS \
            CATDMUBase CATEsuUtil CATViz \
            CATObjectSpecsModeler \
            CATVisualization  \
            ProductStructureProtIDL  \
            CATPspUUID\

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
