// COPYRIGHT Dassault Systemes 2006
/**
  * @CAA2Level L1
  * @CAA2Usage U4 CATEAPspDesignValidation
  */
//===================================================================
//
// CATIPspDesignValidation.h
// Define the CATIPspDesignValidation interface
//
//===================================================================
// Users implementing this interface must derive from the adapter 
// CATEAPspDesignValidation in case new methods are added.
// This interface is called by the CATIA design validation code.
// Users can plug in their own implementations of this interface
// to perform their own design check. A line in a *.dic file must be 
// created to tie the interface to the design check objects.  For example:
// CATDVRun					   CATIPspDesignValidation         libUserValidation
//
//===================================================================
//
// Usage notes:
//   CATIPspDesignValidation is a subtype of CATIPspValidation.
//
//
//  May 2006  Creation: Code generated by the CAA wizard  bpk
//===================================================================
#ifndef CATIPspDesignValidation_H
#define CATIPspDesignValidation_H

#include "CATIPspValidation.h"

extern "C" const IID IID_CATIPspDesignValidation ;

//------------------------------------------------------------------

/**
 * Interface that user can implement to add design validation checks.
 * <b>Role</b>: To add design validation checks.
 * <p><b>BOA  information</b>:  this  interface  can  be  implemented 
 *  using  the  BOA  (Basic  Object  Adapter). 
 *  To  know  more  about  the  BOA,  refer  to  the  CAA  Encyclopedia  home  page.   
 *  Click  Middleware  at  the  bottom  left,  then  click  the  Object  Modeler  tab  page. 
 *  Several  articles  deal  with  the  BOA.</p>
 */

class CATIPspDesignValidation: public CATIPspValidation
{
  public:

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
