#ifndef CATIPspPlacePart_H
#define CATIPspPlacePart_H

//	COPYRIGHT DASSAULT SYSTEMES 2007
/**
  * @CAA2Level L1
  * @CAA2Usage U3
  */
// System
#include "IUnknown.h"
#include "CATListOfDouble.h"

class CATIUnknownList;
class CATUnicodeString;
class CATMathDirection;
class CATMathPoint;

extern "C" const IID IID_CATIPspPlacePart ;

/**
 * Interface to place physical parts.
 * <b>Role</b>: To place physical parts.
 */

class CATIPspPlacePart : public IUnknown
{
  public:  
  
 /**
  * Place a part in space given its reference.
  * <br><b>Role</b>: A part instance is derived from
  * the given reference with respect to the given parent product.
  * The Part Placement Engine will not perform any of it's normal 
  * checks for interactions with nearby parts.
  * Part is placed non-spec.
  *   @param iuStandard
  *      Standard for application attribute values.
  *   @param iuFunctionType
  *      Type of function (e.g. Block valve, branch). Used when no function is specified but functional part placement is required.
  *   @param ipiReferencePart
  *      The reference part from which to derive the instance part.
  *   @param ipiParentProduct
  *      The parent product (in the design model) for the new instance part.
  *   @param ipiLogicalLine
  *      Logical line (e.g. piping line) which contains the instance part.
  *   @param iuPlacedPartID
  *      Name of the placed part in the design model. 
  *      Null uses the standard ID generated by the Part Placement Engine.
  *   @param iUpDirection
  *      Up direction for placed part.
  *      Value is relative to ipiParentProduct.
  *   @param iHorizontalOrientation
  *      Orientation of part in "horizontal" plane (plane perpendicular to up direction).
  *      Must be perpendicular to iUpDirection.
  *      Value is relative to ipiParentProduct.
  *   @param iPosition
  *      Poition of part.
  *      Value is relative to ipiParentProduct and expressed in millimeters.
  *   @param opiInstancePart
  *      The placed instance part.
  *   @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */

    virtual HRESULT PlacePartInSpace (const CATUnicodeString &iuStandard, 
                                      const CATUnicodeString &iuFunctionType, 
                                      const IUnknown *ipiReferencePart, 
                                      const IUnknown *ipiParentProduct, 
                                      const IUnknown *ipiLogicalLine, 
                                      const CATUnicodeString &iuPlacedPartID, 
                                      const CATMathDirection &iUpDirection, 
                                      const CATMathDirection &iHorizontalOrientation, 
                                      const CATMathPoint &iPosition, 
                                      IUnknown *&opiInstancePart) = 0;

 /**
  * Route a string part.
  * <br><b>Role</b>: A string part instance, such as a pipe, a tube, or a duct, is derived from
  * the given reference with respect to the given parent product.
  * The Part Placement engine will not perform any of it's normal 
  * checks for interactions with nearby parts.
  * Part is placed non-spec.
  *   @param iuStandard
  *      The standard for application attribute values.
  *   @param iuFunctionType
  *      The type of function (e.g. Block valve, branch).
  *   @param ipiReferencePart
  *      The reference part from which to derive the instance part.
  *   @param ipiParentProduct
  *      The parent product (in the design model) for the new instance part.
  *   @param ipiLogicalLine
  *      The logical line (e.g. piping line) which contains the instance part.
  *   @param iuPlacedPartID
  *      The name of the placed part in the design model. 
  *      Null uses the standard ID generated by the part placement engine.
  *   @param iFirstPointUpDirection
  *      The up direction of the first point of the string part. 
  *      The list has three values which represent the x, y and z values of a unit direction vector.
  *      Value is relative to ipiParentProduct.
  *   @param ipiListPoints
  *      The list of points that describe the path of the string. 
  *      If the string part is stretchable, the list should contain two points.
  *      Points are relative ipiParentProduct and are in milimeters.
  *   @param iListBendRadii
  *      The list of bend radii at each corner of the string part.
  *      This list is ignored if the string part is stretchable.
  *      This list is only for interior points and so should have two less elements than ipiListPoints.
  *      (for example, if ipiListPoints has six points, iListBendRadii should have four radii values).
  *      Values are in milimeters.
  *   @param opiInstancePart
  *      The routed string part.
  *   @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */

    virtual HRESULT RouteStringPartInSpace (const CATUnicodeString &iuStandard, 
                                            const CATUnicodeString &iuFunctionType, 
                                            const IUnknown *ipiReferencePart, 
                                            const IUnknown *ipiParentProduct, 
                                            const IUnknown *ipiLogicalLine, 
                                            const CATUnicodeString &iuPlacedPartID, 
                                            const CATMathDirection &iFirstPointUpDirection, 
                                            const CATIUnknownList *ipiListPoints, 
                                            const CATListOfDouble &iListBendRadii, 
                                            IUnknown *&opiInstancePart) = 0;

 /**
  * Retrieves the message associated with the last error.
  * <br><b>Role</b>: If an error occurs when placing or routing a part, a message
  * is associated with the error. 
  *   @param obErrorMessage
  *     The error message associated with the last error. Null if no error.
  *   @return
  *     An HRESULT value.
  *     <br><b>Legal values</b>:
  *     <dl>
  *       <dt>S_OK</dt>
  *       <dd>operation is successful</dd>
  *       <dt>E_FAIL</dt>
  *       <dd>operation failed</dd>
  *     </dl>
  */

    virtual HRESULT GetErrorMessage (CATUnicodeString &ouErrorMessage) = 0;
};
#endif
