#ifndef CATIPspID_H
#define CATIPspID_H

//	COPYRIGHT DASSAULT SYSTEMES 2000

/**
  * @CAA2Level L1
  * @CAA2Usage U3
  */


// System
#include "IUnknown.h"
#include "CATBooleanDef.h"

class CATUnicodeString;

extern "C" const IID IID_CATIPspID ;

/**
 * Interface to generate and set IDs for the Plant Ship Objects.
 * <b>Role</b>: This is the interface for Plant Ship object ID generation.
 */


class CATIPspID : public IUnknown
{
  public:  
  
  /**
  * ID is generated with the sequence number and is stored on the object.
  * @param oGeneratedID
  *   ID associated with the Plant Ship Object
  * @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */
  virtual HRESULT GenAndPutID ( CATUnicodeString &oGeneratedID, int ResetSeqNum = 0 ) = 0;

  /**
  * ID is generated without sequence number and is stored on the object.
  * @param oGeneratedID
  *   ID associated with the Plant Ship Object
  * @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */
  virtual HRESULT GenAndPutIDNoGenSeqNum ( CATUnicodeString &oGeneratedID ) = 0;

  /**	
  * ID is generated without sequence number.
  * @param oGeneratedID
  *   ID associated with the Plant Ship Object
  * @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */
  virtual HRESULT GenIDNoGenSeqNum ( CATUnicodeString &oGeneratedID ) = 0;
  
  /**
  * Get ID of the object.
  * @param oID
  *   ID associated with the Plant Ship Object. Null string if no ID
  * @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */
  virtual HRESULT GetID ( CATUnicodeString &oID ) = 0;

  /**
  * Set ID of the object with the user defined string.
  * @param iID
  *   input ID
  * @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */
  virtual HRESULT SetID ( CATUnicodeString &iID ) = 0;

  /**
  *  Is Object ID generated by the ID schema.		
  * @param fResult
  *   TRUE if generated by the ID Schema
  * @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */
  virtual HRESULT IsIDGenerated ( CATBoolean& fResult )= 0;

  /**
  * Get LocalID of the object.
  * @param oID
  *   ID associated with the Plant Ship Object. Null string if no ID is generated
  * @return
  *   An HRESULT value.
  *   <br><b>Legal values</b>:
  *   <dl>
  *     <dt>S_OK</dt>
  *     <dd>operation is successful</dd>
  *     <dt>E_FAIL</dt>
  *     <dd>operation failed</dd>
  *   </dl>
  */
  virtual HRESULT GetLocalID ( CATUnicodeString &oLocalID ) = 0;
 
};
#endif
