#ifndef CATIAPspListOfDoubles_IDL
#define CATIAPspListOfDoubles_IDL

/*IDLREP*/

//	COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */


#include "CATIABase.idl"

/**
 * Represents a collection of double values.
 * <b>Role</b>: Collection of double.
 */
interface CATIAPspListOfDoubles : CATIABase
{
  /**
   * Returns the number of doubles in the list.
   * <! @sample >
   * <dl>
   * <dt><b>Example:</b>
   * <dd>
   * This example retrieves in  <tt>NumberOfdoubles</tt> the number of doubles
   * currently gathered in <tt>MyList</tt>.
   * <pre>
   * NumberOfdoubles = MyList.<font color="red">Count</font>
   * </pre>
   * </dl>
   */
#pragma PROPERTY Count
  HRESULT get_Count (out /*IDLRETVAL*/ long oNbItems);

  /**
  * Returns a double from its index in the list.
  * @param iIndex
  *   The index of the first double in the collection is 1, and
  *   the index of the last double is Count.
  * @return the retrieved double.
  *
  * @sample
  * The following example returns in the third double in the list.
  * <pre>
  * Dim MyDouble As double
  * Dim MyList As PspListOfDoubles
  * MyDouble = PspListOfDoubles.<font color="red">Item</font>(3)
  * </pre>
  */
  HRESULT Item (in long iIndex,  out /*IDLRETVAL*/ double oDouble);

  /**
  * Adds a double to the end of the list.
  * @param iDouble
  *   The double to be added to the list.
  *
  * @sample
  * The following example appends an object to the list.
  * <pre>
  * Dim MyDouble As Double
  * MyDouble = 0.6789
  * Dim MyList As PspListOfDoubles
  * MyList.<font color="red">Append</font>(MyDouble)
  * </pre>
  */
  HRESULT Append (in double iDouble);

  /**
  * Removes a double from the list by specifying its position in the list.
  * @param iIndex
  *   The position of the double to be removed in the list.
  *
  * @sample
  * The following example removes the second entry in the list. Please note that the
  * list index starts with 1.
  * <pre>
  * Dim MyList As PspListOfDoubles
  * MyList.<font color="red">RemoveByIndex</font>(2)
  * </pre>
  */

  HRESULT RemoveByIndex (in long iIndex);

};

// Interface name : CATIAPspListOfDoubles
#pragma ID  CATIAPspListOfDoubles "DCE:a9138996-b646-44c0-b5335b53b18f5456"
#pragma DUAL CATIAPspListOfDoubles

// VB object name : PspListOfDoubles
#pragma ID  PspListOfDoubles "DCE:63ea14f0-fca6-4f1d-a8f3ba7ed9b15d3b"
#pragma ALIAS CATIAPspListOfDoubles PspListOfDoubles

#endif
