#ifndef CatPspIDLDomainID_IDL
#define CatPspIDLDomainID_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004


/**
 * Doamin IDs.
 * <b>Role</b>: Represents Domain identification
 * @param catPspIDLNone,
 *   No domain
 * @param catPspIDLCATPIP,
 *   CATPIP Domain
 * @param catPspIDLCATINS,
 *   CATINS Domain
 * @param catPspIDLCATHVA
 *   CATHVA Domain
 * @param catPspIDLCATEQT
 *   CATEQT Domain
 * @param catPspIDLCATTUB
 *   CATTUB Domain
 * @param catPspIDLCATMLD
 *   CATMLD Domain
 * @param catPspIDLCATWVG
 *   CATWVG Domain
 * @param catPspIDLCATRWY
 *   CATRWY Domain
 * @param catPspIDLCATCND
 *   CATCND Domain
 * @param catPspIDLCATHGR
 *   CATHGR Domain
 * @param catPspIDLCATCAM
 *   CATCAM Domain
 * @param catPspIDLCATELE
 *   CATELE Domain
 * 
 */

enum CatPspIDLDomainID
{
	catPspIDLNone,
	catPspIDLCATPIP,
	catPspIDLCATINS,
	catPspIDLCATHVA,
	catPspIDLCATEQT,
	catPspIDLCATTUB,
	catPspIDLCATMLD,
	catPspIDLCATWVG,
	catPspIDLCATRWY,
	catPspIDLCATCND,
	catPspIDLCATHGR,
	catPspIDLCATCAM,
	catPspIDLCATELE

};


#endif
