#ifndef CatPspIDLPartConnectorType_H
#define CatPspIDLPartConnectorType_H

/**
  * @CAA2Level L1
  * @CAA2Usage U1
  */

  //	COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * Part Connector types.
 * <b>Role</b>: Types of part connector.
 *
 *  @param CatPspIDLPartCtrTypeNotRecognized
 *       Undefined.
 *  @param CatPspIDLPartCtrTypeFace
 *       Face connector
 *  @param CatPspIDLPartCtrTypeSupport
 *       Support type connect
 *  @param CatPspIDLPartCtrTypeCenter 
 *      Center
 *  @param CatPspIDLPartCtrTypeTop
 *      Top
 *  @param CatPspIDLPartCtrTypeBottom
 *      Buttom
 *  @param CatPspIDLPartCtrTypeLeft 
 *      Left
 *  @param CatPspIDLPartCtrTypeRight
 *      Right
 *  @param CatPspIDLPartCtrTypeTopLeft
 *      Top-Left
 *  @param CatPspIDLPartCtrTypeTopRight
 *      Top-Right
 *  @param CatPspIDLPartCtrTypeBottomLeft
 *      Bottom-Left
 *  @param CatPspIDLPartCtrTypeBottomRight
 *      Bottom-Right
 *  @param CatPspIDLPartCtrTypeCircular
 *      Circular
 *  @param CatPspIDLPartCtrTypeRectangular
 *      Rectangular
 *  @param CatPspIDLPartCtrTypeUpOnly  
 *      Up only
 *   
 */
enum CatPspIDLPartConnectorType 
{
  catPspIDLPartCtrTypeNotRecognized, 
  catPspIDLPartCtrTypeFace, 
  catPspIDLPartCtrTypeSupport, 
  catPspIDLPartCtrTypeCenter, 
  catPspIDLPartCtrTypeTop, 
  catPspIDLPartCtrTypeBottom, 
  catPspIDLPartCtrTypeLeft, 
  catPspIDLPartCtrTypeRight, 
  catPspIDLPartCtrTypeTopLeft, 
  catPspIDLPartCtrTypeTopRight, 
  catPspIDLPartCtrTypeBottomLeft, 
  catPspIDLPartCtrTypeBottomRight, 
  catPspIDLPartCtrTypeCircular, 
  catPspIDLPartCtrTypeRectangular, 
  catPspIDLPartCtrTypeUpOnly  
};

#endif
