#ifndef CatPspIDLFunctionStatus_IDL
#define CatPspIDLFunctionStatus_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004


/**
 * Indicates if function has network data and if it is linked to 
 * a physical part.
 * <b>Role</b>: Function object status.
 * @param catPspIDLFuncUndefined
 *   Function data is undefined.
 * @param catPspIDLInFuncNet
  *  Function with network data and is not linked to any physical part
 * @param catPspIDLFuncNetPhysType
 *   Function with network data and has only physical type information.
 * @param catPspIDLFuncNetPhysNoPos
 *   Function with network data and has physical information but no 3D position.
 * @param catPspIDLFuncNoNetPhys
 *  Function with no network data and is linked to a resolved physical part with 3D position.
 * @param catPspIDLFuncNetPhys
 *   Function with network data and is linked to a resolved physical part with 3D position.
 *
 */
enum CatPspIDLFunctionStatus
{
  catPspIDLFuncUndefined,
  catPspIDLInFuncNet,
  catPspIDLFuncNetPhysType,
  catPspIDLFuncNetPhysNoPos,
  catPspIDLFuncNoNetPhys,
  catPspIDLFuncNetPhys
};





#endif
