# COPYRIGHT DASSAULT SYSTEMES 2000
#======================================================================
# Imakefile for module CATMldGate.m
#======================================================================
#
#  Mar 2000  Creation: Code generated by the CAA wizard  cqo
#======================================================================
#
# NONE 
#
BUILT_OBJECT_TYPE=NONE 
 
LINK_WITH = 

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
