# COPYRIGHT Dassault Systemes 2006
#======================================================================
# Imakefile for module ResourceModelerUUID.m
#======================================================================
#
#  Dec 2006  Creation: Code generated by the CAA wizard  gny
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
