#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#

LINK_WITH = JS0FM JS0GROUP

OS = AIX
LINK_WITH = JS0FM JS0GROUP orbix
LOCAL_CCFLAGS = -D_AIX_SOURCE 
LOCAL_LDFLAGS = -brtl
CXX_EXCEPTION = 
SYS_INCPATH =
SYS_LIBPATH =
SYS_LIBS = -lc_r -blibpath:/usr/lib/threads:/lib:/usr/lib -lpthreads_compat -ls

OS = HP-UX
LINK_WITH = JS0FM JS0GROUP orbix
LOCAL_CCFLAGS = -D_HPUX_SOURCE -D_REENTRANT
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
#if os hpux_a
SYS_LIBS =  -lcma -Wl,-a,archive -Wl,-a,shared
# libcma sur HP11 incompatible avec libpthread
#endif

OS = IRIX
LINK_WITH = JS0FM JS0GROUP orbix
LOCAL_CCFLAGS = -D_IRIX_SOURCE 
LOCAL_LDFLAGS =
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
SYS_LIBS = -lCsup

OS = SunOS
LINK_WITH = JS0FM JS0GROUP orbix
LOCAL_CCFLAGS = -D_SUNOS_SOURCE
CXX_EXCEPTION = 
SYS_INCPATH = 
#SYS_LIBPATH = 
SYS_LIBS = -Bdynamic -lnsl -lsocket

OS = intel_a
BUILD = YES
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -DIT_EX_MACROS -MD /GX /Od /Zi -DORBIX_DLL
LINK_WITH = ITMi JS0FM JS0GROUP
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib rpcrt4.lib

OS = win_b
BUILD = YES
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -DIT_EX_MACROS -MD /GX /Od /Zi -DORBIX_DLL
LINK_WITH = ITMi JS0FM JS0GROUP
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib rpcrt4.lib

OS=win_b64
BUILD = YES
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DIT_EX_MACROS -DORBIX_DLL
LINK_WITH = ITMi JS0FM JS0GROUP
SYS_LIBS = Wsock32.LIB

OS = win_a
BUILD = NO
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -DIT_EX_MACROS -MD /GX /Od /Zi -DORBIX_DLL
LINK_WITH = ITMi GW0LIBCX GW0COMUN
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib rpcrt4.lib

OS = alpha_a
BUILD = NO

OS = irix_a64
BUILD = NO

OS = hpux_b64
BUILD = NO

OS = intel_a64
BUILD = NO
