
BUILT_OBJECT_TYPE= NONE

LINK_WITH = 

OS = IRIX
LOCAL_CCFLAGS= -DIRIX -DNATIVE_EXCEPTION
CXX_EXCEPTION=
LOCAL_LDFLAGS = -v
CXX_TEMPLATE_INC    = -auto_include
CXX_TEMPLATE_PRELK  = -prelink
CXX_TEMPLATE_INST   = -ptused
