BUILT_OBJECT_TYPE = CORBA

CORBA_BUILD_TYPE = SHAREDLIBRARY

CORBA_CPP_CS = SERVER CLIENT

CORBA_CPP_OPTS = -A -B

SYS_LIBS = -lorbix

OS = aix_a

LOCAL_LDFLAGS=-brtl

OS = intel_a
#BUILD=NO
SYS_LIBS = ITMi.lib
LOCAL_CCFLAGS = -DORBIX_DLL -DWIN32_LEAN_AND_MEAN -DWIN32 -DIT_EX_MACROS

OS = win_b
#BUILD=NO
SYS_LIBS = ITMi.lib
LOCAL_CCFLAGS = -DORBIX_DLL -DWIN32_LEAN_AND_MEAN -DWIN32 -DIT_EX_MACROS

OS = win_a
#BUILD=NO
SYS_LIBS = ITMi.lib
LOCAL_CCFLAGS = -DORBIX_DLL -DWIN32_LEAN_AND_MEAN -DWIN32 -DIT_EX_MACROS

OS = irix_a64
BUILD = NO

OS = aix_a64
LOCAL_CCFLAGS= -DSIXTY_FOUR_BIT_LONGS 
LOCAL_LDFLAGS=-brtl
#BUILD = NO

OS = hpux_b64
BUILD = NO

OS = win_b64
#BUILD=NO
SYS_LIBS = ITMi.lib
LOCAL_CCFLAGS = -DORBIX_DLL -DIT_EX_MACROS

