# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module CAToffsetflouRep.m
#======================================================================
#
# 01.10.2014 : RAQ : Suppression de LINK_WITH CATStoUtil
#  September, 2004 : RAQ : Ajout CATCGMGeoMath CATMathStream
#  Aug 2001  Creation: Code generated by the CAA wizard  ATV
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 

 
LINK_WITH = CATGeometricObjects \
            CATMathematics \
            CATMathematics \
            JS0GROUP \
            CATSubdivisionObjects \
            CATSubdivisionMeshOperators \
            CATSgoOperators \
            YI00IMPL \
            Y30E3PMG \
            CATCGMGeoMath \
            CATMathStream \
            AdvancedMathematics \
            CATGMModelInterfaces \
            CATGMAdvancedOperatorsInterfaces  \
            CATSmgAdvOperators  \
            PolyhedralModel

#ifdef CATIAV5R20
ALIASES_ON_IMPORT=CATStoFitting CATGMModelInterfaces CATGMOperatorsInterfaces CATGMAdvancedOperatorsInterfaces
#endif

OS = AIX
SYS_LIBS = -lxlf -lxlf90 -lxlfpad

OS = IRIX
SYS_LIBS = -lftn
#
OS = Windows_NT
#if os win_b64
#else
OPTIMIZATION_CPP = /O2
#endif
#
OS = HP-UX
#if os hpux_a
SYS_LIBS = -lf
#else
SYS_LIBS= -lF90
#endif                

OS = hpux_b64 
#if os hpux_a
SYS_LIBS = -lf
#else
SYS_LIBS= -lF90 -lcps 
#endif

OS = SunOS
SYS_LIBS = -lF77 -lM77
