#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
OS = COMMON
#
LINK_WITH = JS03TRA orbix

#
OS = AIX 
#LOCAL_CCFLAGS =  -D_AIX_SOURCE -D_AIX_PTHREADS_D7
LOCAL_CCFLAGS =  -D_AIX_SOURCE
CXX_EXCEPTION =
LOCAL_LDFLAGS = -brtl
#SYS_LIBS = -lmalloc

#
OS = SunOS
BUILD = NO
LOCAL_CCFLAGS = -D_SUNOS_SOURCE -DNATIVE_EXCEPTION
CXX_EXCEPTION =
LOCAL_LDFLAGS =
#SYS_LIBS = -lmalloc

#
OS = IRIX
BUILD = NO
LOCAL_CCFLAGS = -D_IRIX_SOURCE
LOCAL_LDFLAGS =
CXX_EXCEPTION = 

#
OS = HP-UX
BUILD = NO
LOCAL_CCFLAGS = -D_HPUX_SOURCE -D_REENTRANT -DNATIVE_EXCEPTION
SYS_INCPATH = 
SYS_LIBPATH = 
CXX_EXCEPTION = 

#
OS = intel_a
BUILD = NO
LINK_WITH = JS03TRA ITMi
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /GX /Od /Zi  -DORBIX_DLL
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

#
OS = alpha_a
BUILD = NO

#
OS = win_a
BUILD = NO

OS = win_b
BUILD=NO

OS = win_b64
BUILD=NO
LINK_WITH = JS03TRA ITMi
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 
