# COPYRIGHT Dassault Systemes 2007
#======================================================================
# Imakefile for module CATMldTechnoResultItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Jan 2007  Creation: Code generated by the CAA wizard  FDM
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE
