/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATAxisOrientationType_h
#define CATAxisOrientationType_h

enum CATAxisOrientationType {
        catSamCoordinateSystem_Cartesian,
        catSamCoordinateSystem_Cylindrical,
        catSamCoordinateSystem_Spherical,
        catSamCoordinateSystem_Undefined
};

#endif
