/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAAnalysisCases_h
#define CATIAAnalysisCases_h

#ifndef ExportedByCATAnalysisPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATAnalysisPubIDL
#define ExportedByCATAnalysisPubIDL __declspec(dllexport)
#else
#define ExportedByCATAnalysisPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATAnalysisPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIACollection.h"
#include "CATVariant.h"

class CATIAAnalysisCase;

extern ExportedByCATAnalysisPubIDL IID IID_CATIAAnalysisCases;

class ExportedByCATAnalysisPubIDL CATIAAnalysisCases : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Add(CATIAAnalysisCase *& oCase)=0;

    virtual HRESULT __stdcall AddExistingCase(CATIAAnalysisCase * iCase)=0;

    virtual HRESULT __stdcall NewCase(const CATBSTR & iType, CATIAAnalysisCase *& oCase)=0;

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CATIAAnalysisCase *& oCase)=0;

    virtual HRESULT __stdcall Remove(const CATVariant & iIndex)=0;


};

CATDeclareHandler(CATIAAnalysisCases, CATIACollection);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
