/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAAnalysisLocalEntity_h
#define CATIAAnalysisLocalEntity_h

#ifndef ExportedByCATAnalysisPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATAnalysisPubIDL
#define ExportedByCATAnalysisPubIDL __declspec(dllexport)
#else
#define ExportedByCATAnalysisPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATAnalysisPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"
#include "CATVariant.h"

class CATIAAnalysisImages;
class CATIAAnalysisSupports;
class CATIABasicComponents;
class CATIAConstraint;
class CATIAProduct;
class CATIAPublication;
class CATIAReference;
class CATIAReferences;

extern ExportedByCATAnalysisPubIDL IID IID_CATIAAnalysisLocalEntity;

class ExportedByCATAnalysisPubIDL CATIAAnalysisLocalEntity : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Type(CATBSTR & oType)=0;

    virtual HRESULT __stdcall get_BasicComponents(CATIABasicComponents *& oComponents)=0;

    virtual HRESULT __stdcall GetValue(const CATBSTR & iComponent, const CATBSTR & iLabel, CATLONG iLineIndex, CATLONG iColumnIndex, CATLONG iLayerIndex, CATVariant & iValue)=0;

    virtual HRESULT __stdcall SetValue(const CATBSTR & iComponent, const CATBSTR & iLabel, CATLONG iLineIndex, CATLONG iColumnIndex, CATLONG iLayerIndex, const CATVariant & iValue)=0;

    virtual HRESULT __stdcall GetReference(const CATBSTR & iComponent, const CATBSTR & iLabel, CATLONG iLineIndex, CATLONG iColumnIndex, CATLONG iLayerIndex, CATIAReference *& iValue)=0;

    virtual HRESULT __stdcall SetReference(const CATBSTR & iComponent, const CATBSTR & iLabel, CATLONG iLineIndex, CATLONG iColumnIndex, CATLONG iLayerIndex, CATIAReference * iValue)=0;

    virtual HRESULT __stdcall get_AnalysisSupports(CATIAAnalysisSupports *& oSupports)=0;

    virtual HRESULT __stdcall AddSupportFromReference(CATIAReference * iReference, CATIAReference * iSupport)=0;

    virtual HRESULT __stdcall AddSupportFromConstraint(CATIAProduct * iConstraintProduct, CATIAConstraint * iConstraint)=0;

    virtual HRESULT __stdcall AddSupportFromProduct(CATIAProduct * iProduct, CATIAReference * iSupport)=0;

    virtual HRESULT __stdcall AddSupportFromPublication(CATIAProduct * iProduct, CATIAPublication * iPublication)=0;

    virtual HRESULT __stdcall get_AnalysisImages(CATIAAnalysisImages *& oAnalysisImages)=0;


};

CATDeclareHandler(CATIAAnalysisLocalEntity, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
