/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAAnalysisCase_h
#define CATIAAnalysisCase_h

#ifndef ExportedByCATAnalysisPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATAnalysisPubIDL
#define ExportedByCATAnalysisPubIDL __declspec(dllexport)
#else
#define ExportedByCATAnalysisPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATAnalysisPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"

class CATIAAnalysisSet;
class CATIAAnalysisSets;

extern ExportedByCATAnalysisPubIDL IID IID_CATIAAnalysisCase;

class ExportedByCATAnalysisPubIDL CATIAAnalysisCase : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_AnalysisSets(CATIAAnalysisSets *& oAnalysisSets)=0;

    virtual HRESULT __stdcall AddSolution(const CATBSTR & iSolutionType, CATIAAnalysisSet *& oSolution)=0;

    virtual HRESULT __stdcall Compute()=0;

    virtual HRESULT __stdcall ComputeMeshOnly()=0;


};

CATDeclareHandler(CATIAAnalysisCase, CATIABase);

#include "CATAnalysisSetType.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIAAnalysisSet.h"
#include "CATIAAnalysisSets.h"
#include "CATIACollection.h"
#include "CATVariant.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
