BUILT_OBJECT_TYPE = LOAD MODULE
#
OS = COMMON

LINK_WITH= PR0BASE JS0CORBA  JS0STR JS03TRA JS0ERROR NS0S3STR CO0LSTPV CO0HDICO CO0LSTPV CO0SETST  JS0SCBAK JS0SETT CATSysDbSettings
#CATVBTXMLParser

OS = AIX
LOCAL_LDFLAGS =-F:$(LD)

#
OS = HP-UX
#LOCAL_LDFLAGS = -Wl,-aarchive -Wl,-L/lib -lhppa \
#-Wl,-E \
#-Wl,-uallow_unaligned_data_access \
#-Wl,-ashared 

#
OS = IRIX
#SYS_LIBS = -lpthread 

#
OS = SunOS

#
OS = Windows_NT
LOCAL_LDFLAGS=/SUBSYSTEM:CONSOLE
