#ifndef CATCGMCreateTopCorner_h_
#define CATCGMCreateTopCorner_h_

// COPYRIGHT DASSAULT SYSTEMES 2006

/**
 * @CAA2Level L1
 * @CAA2Usage U1
*/

#include "CATGMOperatorsInterfaces.h"

class CATBody;
class CATCGMJournalList;
class CATGeoFactory;
class CATGeometry;
class CATLaw;
class CATICGMTopCorner;
class CATTopData;

/**
* Creates the operator defining a corner between two wires. 
* The wire can be degenerated by one vertex
 * @param iFactory
 * The pointer to the factory that creates the resulting body.
 * @param iTopData
 * The pointer to the data defining the software configuration and the journal. 
 * If the journal inside <tt>iTopData</tt> 
 * is <tt>NULL</tt>, it is not filled. 
 * @param iPassage1
 * The first wire.
 * @param iPassage2
 * The second wire.
* @param iSupport
 * The underlying support.
 * @param Radius
 * The radius
 * @return [out, IUnknown#Release]
 * The pointer to the created operator. 
 * To be released with the <tt>Release</tt> method after use.
 */
ExportedByCATGMOperatorsInterfaces CATICGMTopCorner *CATCGMCreateTopCornerBiTgt(
  CATGeoFactory *iFactory,
  CATTopData *iTopData,
  CATBody *iPassage1,
  CATBody *iPassage2,
  CATBody *iSupport,
  double Radius);

#endif /* CATCGMCreateTopCorner_h_ */
