BUILT_OBJECT_TYPE = ARCHIVE
#BUILD = NO

BUILD = YES
SRC_LINK_WITH =  JS0MT CO0HTAB JS0HTTP
LOCAL_CCFLAGS = -DHTTPARCH


OS = Windows_NT
# in order to compile with /MT flags
LOCAL_POST_CCFLAGS=/U_AFXDLL
STATIC_LIBS=YES
