#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
GenericNamingUUID
#else
LINK_WITH_FOR_IID =
#endif
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = GN0NAME

LINK_WITH=$(LINK_WITH_FOR_IID)  JS0GROUP    \
            NS0S3STR
