BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH = AD0XXBAS CD0FRAME CD0WIN DI0PANV2 JS0GROUP JS0FM \
			ON0PROP YN000MFL AC0ITEMS \
            CATPspUtilities CATPspUUID CATPspPropExpImp CATEsuUI CATEsuUtil CATEsuUUID


SH_LINK_WITH= $(LINK_WITH)


