BUILT_OBJECT_TYPE = SHARED LIBRARY
BUILD=YES

LINK_WITH=JS0GROUP \
          CATObjectModelerBase

OS = Windows_NT

#if defined (CATIAV5R29)
LOCAL_POST_CCFLAGS = /D"_CATIA_DEPENDENCY_R29_ONWARD"
#endif
