# COPYRIGHT DASSAULT SYSTEMES 2006
#======================================================================
# Imakefile for module CATDataExchItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Feb 2006  Creation: Code generated by the CAA wizard  JFI
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE
