#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
FeatureDictionaryUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY


LINK_WITH= JS0GROUP CATCclInterfaces
#useless linkwith JS0FM AD0XXBAS
