#
# Imakefile to build a load
#

BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = Services

LINK_WITH= JS0ERROR JS0CORBA JS0FM JS0SCBAK JS03TRA JS0STR CO0LSTPV DI0PANV2 \
           VE0MDL VE0BASE CD0FRAME NS0S3STR AC0SPBAS \
           AD0XXBAS AC0XXLNK CATInteractiveInterfaces CATCafSearch CATViz

