# COPYRIGHT DASSAULT SYSTEMES 2004
#======================================================================
# Imakefile for module CATPrsNaming.m
#======================================================================
#
#  Feb 2004  Creation: Code generated by the CAA wizard  aif
#======================================================================
BUILT_OBJECT_TYPE= NONE

LINK_WITH = JS0GROUP JS0ERROR CATObjectSpecsModeler  
 
#
OS = AIX

# 
OS = HP-UX

#
OS = IRIX

#
OS = SunOS

OS = Windows_NT

