#
# AEC Utilities
#

BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = AECBUtilities

LINK_WITH= AD0XXBAS AC0XXLNK \
        CO0LSTPV CO0LSTST CO0RCINT CO0RCDBL \
        JS03TRA JS0CORBA JS0ERROR JS0FM JS0LIB0 JS0SCBAK JS0STR \
        JS0SETT \
        CD0FRAME CD0WIN DI0PANV2 DI0STATE DI0GRAF DI0APPLI\
        NS0S3STR\
        ON0MAIN ON0FRAME ON0GREXT\
        CK0FEAT\
        VE0MDL VE0BASE\
        AECReviewItfCPP\
        CATDMUBase CATEsuUtil\
        CATProductStructure1  

#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_IID= AECReviewInterfacesUUID
#else
LINK_WITH_IID=
#endif

# Search AECElement	
#------
OS = COMMON
# removed 110601 kny
# ON0GRAPH VE0GRPH2 
