#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = AC0SCHEMAS

LINK_WITH = AD0XXBAS KS0SIMPL KS0LATE

#LINK_WITH = AC0XXLNK AD0XXBAS \
#            JS0CORBA JS0SCBAK JS0STR   JS0SETT JS0ERROR JS03TRA  \
#            NS0S3STR \
#            KS0SIMPL KS0LATE  KS0BINA  KS0STEP \
#            CO0LSTPV CO0LSTST CO0RCINT

LOCAL_CKMFLAGS= -gLate 

# for tracing :
# LOCAL_CCFLAGS= -DTRACE_ON

#
OS = AIX

#
OS = HP-UX

#
OS = IRIX

#
OS = SunOS

#
OS = Windows_NT
