# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module CATCloudQsrInterfacesUUID.m
#======================================================================
#
#  Jul 2001  Creation: Code generated by the CAA wizard  cqo
#======================================================================
#
# ARCHIVE 
#
BUILT_OBJECT_TYPE=ARCHIVE 
 

