#
BUILT_OBJECT_TYPE=NONE
OS=COMMON
#
OS = Windows_NT
#if os win_b64
#else
OPTIMIZATION_CPP = /O2
#endif
#

#LOCAL_CCFLAGS= -DGMPOLYPROTO -DGMPOLYTRACES
#LOCAL_CCFLAGS= -DCATGMPolyTessBodyTopExt_Perfo
#LOCAL_CCFLAGS= -D____CATGMPolyTessBodyDriverTraces
