#
# SHARED LIBRARY          
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=  CATLiteralFeatures AC0SPBAS CD0FRAME VE0MDL JS0LOGRP AC0WINLNK DI0PANV2 JS0FM CATKnowledgeModeler CATProductStructureInterfaces

		

