#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

INCLUDED_MODULES = ImUICommands

LINK_WITH = JS0FM JS0GROUP CATVisualization CATMathematics CATApplicationFrame YN000MAT YN000FUN \
           DI0PANV2 DI0STATE CD0FRAME CD0WIN DI0STATE \
           JS0CORBA JS0SCBAK JS0STR JS0FM NS0S3STR VE0BASE \
           SELECT CATViz
