# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module CATOBMItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Jul 2001  Creation: Code generated by the CAA wizard  JPI
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE
