// COPYRIGHT DASSAULT SYSTEMES 2000
//===================================================================
//
// CatClashComputationType.idl
//   This automation declaration enumerates values of interface parameter.
//
//===================================================================
#ifndef CatSectioningSettingsTypes_IDL
#define CatSectioningSettingsTypes_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

/**
 * Definition of all types required for Sectioning Settings automation.
 */

/**
 * The different default normals for the section plane.
 * It is used by the @href CATIASectioningSettingAtt object to specify the plane's normal in settings.
 * @param catSectionNormal_X
 *   The normal of the section plane is along the X axis.
 * @param catSectionNormal_Y
 *   The normal of the section plane is along the Y axis.
 * @param catSectionNormal_Z
 *   The normal of the section plane is along the Z axis.
 */
enum CatSectionPlaneNormal
{ 
  catSectionNormal_X,
  catSectionNormal_Y,
  catSectionNormal_Z
};




/**
 * The different default origins for the section plane.
 * It is used by the @href CATIASectioningSettingAtt object to specify the plane's origin in settings.
 * @param catSectionOrigin_0
 *   The origin of the section plane is at coordinates (0,0,0).
 * @param catSectionOrigin_Selection
 *   The origin of the section plane is on the selected point.
 */

enum CatSectionPlaneOrigin
{
  catSectionOrigin_0,
  catSectionOrigin_Selection
};




/**
 * The different modes for section grid positioning.
 * It is used by the @href CATIASectioningSettingAtt object to specify the section grid's positioning mode in settings.
 * @param catGridPositionMode_Absolute
 *   The grid's positioning is absolute.
 * @param catGridPositionMode_Relative
 *   The grid's positioning is relative.
 */
enum CatGridPositionMode
{
  catGridPositionMode_Absolute,
  catGridPositionMode_Relative
};




/**
 * The different styles of the section grid.
 * It is used by the @href CATIASectioningSettingAtt object to specify the section grid's style in settings.
 * @param catSectionGridStyle_Lines
 *   The grid's lines are displayed.
 * @param catSectionGridStyle_Crosses
 *   Only the grid's intersections are displayed.
 */

enum CatSectionGridStyle
{
  catSectionGridStyle_Lines,
  catSectionGridStyle_Crosses
};




/**
 * The different algorithmes used to computate the section result.
 * It is used by the @href CATIASectioningSettingAtt object to specify the section's computation mode.
 * @param catSection_Software
 *   The section is software computed (the result is more precise but slower).
 * @param catSection_OpenGL
 *   The section is computed by the graphic card (the result is faster but less precise).
 */

enum CatSectionClippingMode
{
  catSection_Software,
  catSection_OpenGL

};


/**
 * The different modes of opening the sectioning windows
 * It is used by the @href CATIASectioningSettingAtt object to specify the mode of opening the section window in settings.
 * @param catSecWindow_DefaultSize
 *   Open the sectioning window with the default size specified in the Tools->Options.
 * @param catSecWindow_TileVertically
 *   Tile the sectioning window vertically in the viewer
 */

enum CatSecWindowOpenMode
{
  catSecWindow_DefaultSize,
  catSecWindow_TileVertically
};


#endif
