# COPYRIGHT Dassault Systemes 2003
#======================================================================
# Imakefile for module CATStrSettingsTypeLib.m
# Module for compilation of the typelib
#======================================================================
#
#  Nov 2003  Creation: Code generated by the CAA wizard  jcm
#======================================================================
#
# TYPELIB          
#

BUILT_OBJECT_TYPE=TYPELIB
# no more BUILD_PRIORITY=4
 
LINK_WITH = InfTypeLib
