// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATIFunctActionsGroup.h
// Define the CATIFunctActionsGroup interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2002  Creation: Code generated by the CAA wizard  phb
//===================================================================
#ifndef CATIFunctActionsGroup_H
#define CATIFunctActionsGroup_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "FunctionalAnalysisItfCPP.h"
#include "CATIFunctElement.h"
#include "CATLISTV_CATBaseUnknown.h"

class CATIFunctAction;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByFunctionalAnalysisItfCPP IID IID_CATIFunctActionsGroup;
#else
extern "C" const IID IID_CATIFunctActionsGroup ;
#endif

//------------------------------------------------------------------
/**
 * The interface to access a group of functional actions in a system.
 */
class ExportedByFunctionalAnalysisItfCPP CATIFunctActionsGroup: public CATIFunctElement
{
  CATDeclareInterface;

  public:


	/** 
	  * Get the list of Functional Actions included in the group.
	  */
	virtual CATLISTV(CATBaseUnknown_var)*  GetActions() = 0;

    /**
     * Adds an action to the actions' group. 
	 * <p>
     * @param iAction
     *   The action to be added to the group of actions.
	 */
    virtual HRESULT Add	( CATIFunctAction*  iAction ) = 0 ;

    /**
     * Removes an action from the actions' group. 
	 * <p>
     * @param iPosition
     *   The position of the action to be removed from the group of actions.
	 */
    virtual HRESULT RemovePosition	( long  iPosition ) = 0 ;

    /**
     * Get coordinates of Input and Output extremities.
     */
    virtual HRESULT GetExtremities
            ( double&  oInputX
			, double&  oInputY
			, double&  oOutputX
			, double&  oOutputY ) = 0 ;

    /**
     * Set coordinates of Input and Output extremities.
     */
    virtual HRESULT SetExtremities
            ( double  iInputX
			, double  iInputY
			, double  iOutputX
			, double  iOutputY ) = 0 ;

};

//------------------------------------------------------------------
CATDeclareHandler( CATIFunctActionsGroup, CATBaseUnknown );

#endif
