// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATIFunctFacetManagers.h
// Define the CATIFunctFacetManagers interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2002  Creation: Code generated by the CAA wizard  phb
//===================================================================
#ifndef CATIFunctFacetManagers_H
#define CATIFunctFacetManagers_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "FunctionalAnalysisItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATLISTV_CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByFunctionalAnalysisItfCPP IID IID_CATIFunctFacetManagers;
#else
extern "C" const IID IID_CATIFunctFacetManagers ;
#endif

//------------------------------------------------------------------
/**
 * The interface to access the Functional Facet's Managers. 
 */
class ExportedByFunctionalAnalysisItfCPP CATIFunctFacetManagers: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
     * Get the list of facet managers. 
	 * <p>
     * @param ioLst
     *   The list to be filled with the facet managers.
	 */
    virtual HRESULT GetListOfFacetManagers( CATLISTV(CATBaseUnknown_var)&	ioLst ) = 0 ;

};

//------------------------------------------------------------------
CATDeclareHandler( CATIFunctFacetManagers, CATBaseUnknown );

#endif
