// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATIFunctNodeGraphLayout.h
// Define the CATIFunctNodeGraphLayout interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Feb 2002  Creation: Code generated by the CAA wizard  phb
//===================================================================
#ifndef CATIFunctNodeGraphLayout_H
#define CATIFunctNodeGraphLayout_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "FunctionalAnalysisItfCPP.h"
#include "CATIFunctFacet.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByFunctionalAnalysisItfCPP IID IID_CATIFunctNodeGraphLayout;
#else
extern "C" const IID IID_CATIFunctNodeGraphLayout ;
#endif

//------------------------------------------------------------------
/**
 * Interface to resize Nodes representing Functional Objects.
 * <p>
 * It handles the "GRL" facet that may be hooked on Functional Object.
 */
class ExportedByFunctionalAnalysisItfCPP CATIFunctNodeGraphLayout: public CATIFunctFacet
{
  CATDeclareInterface;

  public:

  /** 
   * Get the Height coord.
   */
  virtual HRESULT  get_Height
	   ( double&   oHeight ) = 0 ;


  /** 
   * Get the Width coord.
   */
  virtual HRESULT  get_Width
	   ( double&   oWidth ) = 0 ;


  /** 
   * Set the height and width.
   */
  virtual HRESULT  SetHeightAndWidth
	   ( const double&   iHeight
	   , const double&   iWidth
       ) = 0 ;
};

//------------------------------------------------------------------

#endif
