// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATIFunctVariant.h
// Define the CATIFunctVariant interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2002  Creation: Code generated by the CAA wizard  phb
//===================================================================
#ifndef CATIFunctVariant_H
#define CATIFunctVariant_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "FunctionalAnalysisItfCPP.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByFunctionalAnalysisItfCPP IID IID_CATIFunctVariant;
#else
extern "C" const IID IID_CATIFunctVariant ;
#endif

class CATIFunctDescription;

//------------------------------------------------------------------
/**
 * The interface to access a Functional Variant. 
 */
class ExportedByFunctionalAnalysisItfCPP CATIFunctVariant: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

	/** 
	* Returns the Original Description the Variant comes from. 
	*/
	virtual HRESULT	GetOriginalDescription
			( CATIFunctDescription*&  oDesc ) = 0 ;

};

//------------------------------------------------------------------
CATDeclareHandler( CATIFunctVariant, CATBaseUnknown );

#endif
