// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATIFunctPosition.h
// Define the CATIFunctPosition interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2002  Creation: Code generated by the CAA wizard  phb
//===================================================================
#ifndef CATIFunctPosition_H
#define CATIFunctPosition_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "FunctionalAnalysisItfCPP.h"
#include "CATIFunctElement.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByFunctionalAnalysisItfCPP IID IID_CATIFunctPosition;
#else
extern "C" const IID IID_CATIFunctPosition ;
#endif

//------------------------------------------------------------------
/**
 * Describe the functionality of your interface here
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class ExportedByFunctionalAnalysisItfCPP CATIFunctPosition: public CATIFunctElement
{
  CATDeclareInterface;

  public:

  /** 
   * Get the X coord.
   */
  virtual HRESULT  get_X( double&   oX ) = 0 ;


  /** 
   * Get the Y coord.
   */
  virtual HRESULT  get_Y( double&   oY ) = 0 ;


  /** 
   * Set the coordinates.
   */
  virtual HRESULT  SetCoords
	   ( double   iX
	   , double   iY
       ) = 0 ;

};

//------------------------------------------------------------------
CATDeclareHandler( CATIFunctPosition, CATIFunctElement );

#endif
