// COPYRIGHT DASSAULT SYSTEMES 2000
//===================================================================
//
// CATIASiTransiantObject.idl
// Automation interface for the SiTransiantObject element 
//
//===================================================================
#ifndef CATIASiTransiantObject_IDL
#define CATIASiTransiantObject_IDL

#include "CATIABase.idl"

/**
 * @CAA2Level L0
 * @CAA2Usage U0
 */


/**  
 * The interface to access a CATIASiTransiantObject  
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
interface CATIASiTransiantObject : CATIABase 
{
 HRESULT set_TransiantMode (in long iTransiantMode);
 HRESULT get_TransiantMode (out /*IDLRETVAL*/ long iTransiantMode); 
 HRESULT apply_Immediate_Storage ();
 HRESULT clean_Transiant ();
};

// Interface name : CATIASiTransiantObject
#pragma ID CATIASiTransiantObject "DCE:1d1ce428-7a32-11d3-859d001083021312"
#pragma DUAL CATIASiTransiantObject

// VB object name : SiTransiantObject (Id used in Visual Basic)
#pragma ID SiTransiantObject "DCE:1d1ce429-7a32-11d3-859d001083021312"
#pragma ALIAS CATIASiTransiantObject SiTransiantObject

#endif
