# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module DNBStateItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Apr 2003  Creation: Code generated by the CAA wizard  plk
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE

OS = Windows_NT
#LOCAL_CCFLAGS=-FR
