# COPYRIGHT DASSAULT SYSTEMES 2000
#======================================================================
# Imakefile for module PPRProIDL
# Module for compilation of the protected IDL interfaces
#======================================================================
#
#  Jan 2000  Creation: Code generated by the CAA wizard  PMM
#======================================================================
#
# NO BUILD             
#

BUILT_OBJECT_TYPE=NONE

SOURCES_PATH=ProtectedInterfaces
COMPILATION_IDL=YES

