BUILT_OBJECT_TYPE=NONE

#ifdef CATV5_SMALLSYSTEM
OS = COMMON
COMMON_LOCAL_CCFLAGS= -DSYSTEM_IS_CUT

OS = AIX      
LOCAL_CCFLAGS= $(COMMON_LOCAL_CCFLAGS)
OS = IRIX     
LOCAL_CCFLAGS= $(COMMON_LOCAL_CCFLAGS)
OS = SunOS    
LOCAL_CCFLAGS= $(COMMON_LOCAL_CCFLAGS)
OS = HP-UX    
LOCAL_CCFLAGS= $(COMMON_LOCAL_CCFLAGS)
OS = LINUX    
LOCAL_CCFLAGS= $(COMMON_LOCAL_CCFLAGS)

OS = WindowsNT
LOCAL_CCFLAGS= /D SYSTEM_IS_CUT
#else
BUILD=NO

#endif
