#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# PDF driver
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
LINK_WITH=$(LINK_WITH_FOR_IID) CATPrt JS0GROUP JS0FM DI0PANV2 Mathematics CATViz CATLightXml XMLParserItf JS0ZLIB


OS = AIX
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = HP-UX
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = IRIX
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = SunOS
BUILD=YES
SYS_LIBS = -lXt -lX11
#
OS = intel_a
BUILD=YES

