#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION
INCLUDED_MODULES = CATVisShaderCGFX CATVisShaderDSFX
LINK_WITH = CATVizBase CATSysMultiThreading CATMathematics JS0STR CATMathStream VisCgfx2Nvfx


OS = IRIX
SYS_LIBS = -ignore_unresolved -Wl,-woff,157
CXX_TEMPLATE_INC    = -auto_include
CXX_TEMPLATE_PRELK  = -prelink
CXX_TEMPLATE_INST   = -ptused

OS = AIX 
BUILD=NO

OS = HP-UX
BUILD=NO

OS = SunOS
BUILD=NO

OS = win_b64
LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION 
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION
SYS_LIBS = cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGL.dll

OS = intel_a 
LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION
SYS_LIBS = cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGL.dll

OS = win_b 
LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION
SYS_LIBS = cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGL.dll

OS = win_a 
LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION 
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION
SYS_LIBS = cg.lib cgGL.lib delayimp.lib /DELAYLOAD:cg.dll /DELAYLOAD:cgGL.dll
