# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module NomadImport.m
#======================================================================
#
#  Dec 2001  Creation: Code generated by the CAA wizard  ADS
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE
LINK_WITH = $(WIZARD_LINK_MODULES)\
            NS0S3STR AD0XXBAS \
            CATMathematics CATXML4C3 \
            CATProductStructure1 XMLParserItf CATXMLBase \
            CATPDMBase CATPDMBaseItfCPP \
            CATCinDocument CDMAServer CATObjectSpecsModeler DraftingItfCPP


# System dependant variables
#
OS = AIX
#
OS = HP-UX
CXX_EXCEPTION =
LOCAL_CCFLAGS = -DNATIVE_EXCEPTION

#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
SYS_LIBS = Wsock32.lib

