// COPYRIGHT Dassault Systemes 2004
//===================================================================
//
// CATIStmFlange.h
// Define the CATIStmFlange interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Nov 2004  Creation: Code generated by the CAA wizard  jxv
//===================================================================
#ifndef CATIStmFlange_H
#define CATIStmFlange_H

/**
 * @CAA2Level L0
 * @CAA2Usage U0
 */

#include "ExportedByCATSmInterfaces.h"
#include "CATIStmSweptWall.h"

#include "CATTopDefine.h"
#include "CATICkeParm.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATSmInterfaces IID IID_CATIStmFlange;
#else
extern "C" const IID IID_CATIStmFlange ;
#endif

enum CATStmFlangeLengthType { CATStmStandardFlangeLength, CATStmInnerFlangeLength, CATStmOuterFlangeLength, CATStmExtrapolatedFlangeLength };
enum CATStmFlangeAngleType	{ CATStmInternalFlangeAngle, CATStmExternalFlangeAngle};
enum CATStmFlangeTrimType	{ CATStmFlangeWithoutTrim, CATStmFlangeOuterTrim, CATStmFlangeInnerTrim};

//------------------------------------------------------------------

/**
 * Interface to manage the sheet metal <tt>predefined flange</tt> feature.
 * <b>Role</b>: With this interface, you have all the methods to manage the sheet metal
 * <tt>flange</tt> feature. 
 */
class ExportedByCATSmInterfaces CATIStmFlange: public CATIStmSweptWall
{
  CATDeclareInterface;

  public:

	/** 
	* Short role of the method.
	*
	* <br><b>Role</b>: This method gets the flange length parameter
	*
	* @param opiLengthParm [out]
	*   The returned flange length knowledge parameter
	*
	* @return <tt>S_OK</tt>.
	*      The flange length parameter is successfully read.
	* @return <tt>E_FAIL</tt>.
	*      The flange length parameter cannot be read. Use CATError::CATGetLastError()
	*      to retrieve the error by the <tt>HRESULT</tt> value. @see CATError.
	*
	*/
	virtual HRESULT GetLengthParm(CATICkeParm ** opiLengthParm) = 0;

	/** 
	* Short role of the method.
	*
	* <br><b>Role</b>: This method gets the flange angle parameter
	*
	* @param opiAngleParm [out]
	*   The returned flange angle knowledge parameter
	*
	* @return <tt>S_OK</tt>.
	*      The flange angle parameter is successfully read.
	* @return <tt>E_FAIL</tt>.
	*      The flange angle parameter cannot be read. Use CATError::CATGetLastError()
	*      to retrieve the error by the <tt>HRESULT</tt> value. @see CATError.
	*
	*/
	virtual HRESULT GetAngleParm(CATICkeParm ** opiAngleParm) = 0;

	/** 
	* Short role of the method.
	*
	* <br><b>Role</b>: This method gets the flange radius parameter
	*
	* @param opiRadiusParm [out]
	*   The returned flange radius knowledge parameter
	*
	* @return <tt>S_OK</tt>.
	*      The flange radius parameter is successfully read.
	* @return <tt>E_FAIL</tt>.
	*      The flange radius parameter cannot be read. Use CATError::CATGetLastError()
	*      to retrieve the error by the <tt>HRESULT</tt> value. @see CATError.
	*
	*/
	virtual HRESULT GetRadiusParm(CATICkeParm ** opiRadiusParm) = 0;

	/** 
	* Short role of the method.
	*
	* <br><b>Role</b>: This method gets the flange angle type
	*
	* @param oAngleType [out]
	*   The returned flange angle type
	*
	* @return <tt>S_OK</tt>.
	*      The flange angle type parameter is successfully read.
	* @return <tt>E_FAIL</tt>.
	*      The flange angle type parameter cannot be read. Use CATError::CATGetLastError()
	*      to retrieve the error by the <tt>HRESULT</tt> value. @see CATError.
	*
	*/
	virtual HRESULT __stdcall GetAngleType		(CATStmFlangeAngleType & oAngleType) const	= 0;	

	/** 
	* Short role of the method.
	*
	* <br><b>Role</b>: This method gets the flange length type
	*
	* @param oLengthType [out]
	*   The returned flange length type
	*
	* @return <tt>S_OK</tt>.
	*      The flange length type parameter is successfully read.
	* @return <tt>E_FAIL</tt>.
	*      The flange length type parameter cannot be read. Use CATError::CATGetLastError()
	*      to retrieve the error by the <tt>HRESULT</tt> value. @see CATError.
	*
	*/
	virtual HRESULT __stdcall GetLengthType		(CATStmFlangeLengthType & oLengthType) const	= 0;	

	/** 
	* Short role of the method.
	*
	* <br><b>Role</b>: This method retrieves the trim type of the flange
	*
	* @param oTrimType [out]
	*  The returned flange trim type (No trim, inner trim or outer trim)
	*
	* @return <tt>S_OK</tt>.
	*      The flange trim type parameter is successfully read.
	* @return <tt>E_FAIL</tt>.
	*      The flange trim type parameter cannot be read. Use CATError::CATGetLastError()
	*      to retrieve the error by the <tt>HRESULT</tt> value. @see CATError.
	*
	*/	
	virtual HRESULT __stdcall GetTrimType		(CATStmFlangeTrimType & oTrimType) const	= 0;	

	/** 
	* Short role of the method.
	*
	* <br><b>Role</b>: This method gives the flange orientation status
	*
	* @param oDefaultOr [out]
	*   if <tt>CATOrientationPositive</tt> the guide is oriented as default (downward respectively to the guide edges)
	*   otherwise <tt>CATOrientationNegative<\tt>, it has been inverted.
	*
	* @return <tt>S_OK</tt>.
	*      The flange orientation status is successfully read.
	* @return <tt>E_FAIL</tt>.
	*      The flange orientation status cannot be read. Use CATError::CATGetLastError()
	*      to retrieve the error by the <tt>HRESULT</tt> value. @see CATError.
	*/	
	virtual HRESULT __stdcall IsDefaultOrientation(CATOrientation & oDefaultOr) const	= 0;


  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
