#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID) CATPrt JS0GROUP JS0FM VE0PIX DI0PANV2 CATLightXml XMLParserItf
