#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATIAApplicationFrameUUID \
PCBoardBaseUUID
#else
LINK_WITH_FOR_IID =
#endif

#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#
#
LINK_WITH=$(LINK_WITH_FOR_IID)  CO0LSTPV \
		JS0CORBA AD0XXBAS CATPartInterfaces \
		NS0S3STR CATObjectSpecsModeler \
		CO0RCINT CO0LSTPV AC0XXLNK \
		DI0PANV2 OM0EDPRO JS0FM JS0SCBAK \
		CO0LSTST VE0BASE AS0STARTUP \
		CK0FEAT CK0PARAM PCBModeler PCBServices MF0CST\
		CATAssCouMdl CD0WIN JS0CATLM\
		MecModItfCPP AS0SEL MecModProIDL ProductStructureProtIDL \
		JS0INF OM0EDPRO YP00IMPL CATAssemblyInterfaces PCBItf

OS = COMMON
# 
OS = HP-UX
#BUILD = NO
#
OS = SunOS
#
OS = wnt40i   
#
OS = wnt40a
BUILD = NO
