# 
IMPACT_ON_IMPORT = YES

BUILT_OBJECT_TYPE = NONE

COMDYN_MODULE = V4SysCOMD
# 
DUMMY_LINK_WITH = V4SysB V4SysMEM V4SysANL V4SysUTIL
#
OS = COMMON
LINK_WITH = $(DUMMY_LINK_WITH)
SYS_LIBPATH = 

OS = AIX
SYS_LIBS = -lxlf -lxlf90 -lxlfpad

OS = IRIX
LINK_WITH = $(COMDYN_MODULE) $(DUMMY_LINK_WITH)
SYS_LIBS = -lftn

OS = Windows_NT
#if (defined MK_MSCVER) && (MK_MSCVER < 1400)
SYS_LIBS = DFORDLL.LIB
#endif
LOCAL_CCFLAGS = /D_CATNoWarningPromotion_  
LOCAL_CFLAGS = /D_CATNoWarningPromotion_ 
LOCAL_LDFLAGS = /EXPORT:giuclo /EXPORT:giuope /EXPORT:giutrs
OS = Windows_NT
#if (defined MK_MSCVER) && (MK_MSCVER < 1400)
SYS_LIBS = DFORDLL.LIB
#endif

OS = HP-UX
SYS_INCPATH =
SYS_LIBS = -lf

OS = SunOS
SYS_INCPATH = 
SYS_LIBS = -lF77
SYS_LIBPATH =
