#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CORBAServerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#

LINK_WITH=$(LINK_WITH_FOR_IID)  GW0COMUN orbix GW0LIBCX JS0FM AC0XXLNK CD0WIN DI0PANV2 InfItf CATViz\
	    NS0S3STR CO0LSTST CO0LSTPV CO0HDICO CATVisualization CD0STWIN \
            YN000MAT YP00IMPL PG0BASE ProductStructureItf CATCsbCORBA
CATCsbCORBA = SERVER

OS = AIX
LOCAL_CCFLAGS = -D_AIX_SOURCE -DNATIVE_EXCEPTION 
LOCAL_LDFLAGS = -brtl
CXX_EXCEPTION = 
SYS_INCPATH =
SYS_LIBPATH = 

OS = HP-UX
LOCAL_CCFLAGS = -D_HPUX_SOURCE -D_REENTRANT -DNATIVE_EXCEPTION
SYS_INCPATH = 
SYS_LIBPATH = 
CXX_EXCEPTION = 
# shared lib non multithreadee ORBIXS

OS = IRIX
LOCAL_CCFLAGS = -D_IRIX_SOURCE -DNATIVE_EXCEPTION
LOCAL_LDFLAGS = 
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
#shared lib non multithreadee ORBIXS
SYS_LIBS =  -lCsup


OS = SunOS
LOCAL_CCFLAGS = -D_SUNOS_SOURCE -DNATIVE_EXCEPTION
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
#shared lib non multithreadee ORBIXS

OS = intel_a
#BUILD=NO
LINK_WITH=$(LINK_WITH_FOR_IID)  ITMi GW0COMUN GW0LIBCX JS0FM AC0XXLNK CD0WIN DI0PANV2 CATViz CATVisualization\
            InfItf NS0S3STR CO0LSTST CO0LSTPV CO0HDICO  \
            CD0STWIN YN000MAT YP00IMPL PG0BASE ProductStructureItf CATCsbCORBA 
CATCsbCORBA = SERVER

SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DIT_EX_MACROS
CXX_EXCEPTION =


OS = win_b
#BUILD=NO
LINK_WITH=$(LINK_WITH_FOR_IID)  ITMi GW0COMUN GW0LIBCX JS0FM AC0XXLNK CD0WIN DI0PANV2 CATViz CATVisualization\
            InfItf NS0S3STR CO0LSTST CO0LSTPV CO0HDICO  \
            CD0STWIN YN000MAT YP00IMPL PG0BASE ProductStructureItf CATCsbCORBA 
CATCsbCORBA = SERVER

SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DIT_EX_MACROS
CXX_EXCEPTION =

OS = win_b64
#BUILD=NO
LINK_WITH=$(LINK_WITH_FOR_IID)  ITMi GW0COMUN GW0LIBCX JS0FM AC0XXLNK CD0WIN DI0PANV2 CATViz CATVisualization\
            InfItf NS0S3STR CO0LSTST CO0LSTPV CO0HDICO  \
            CD0STWIN YN000MAT YP00IMPL PG0BASE ProductStructureItf CATCsbCORBA 
CATCsbCORBA = SERVER
#SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DIT_EX_MACROS
CXX_EXCEPTION =

OS = alpha_a
BUILD=NO

OS = win_a
#BUILD=NO
LINK_WITH=$(LINK_WITH_FOR_IID)  ITMi GW0COMUN GW0LIBCX JS0FM AC0XXLNK CD0WIN DI0PANV2 VE0GROUP CATViz \ 
            InfItf NS0S3STR CO0LSTST CO0LSTPV CO0HDICO VE0BASE    \
            CD0STWIN YN000MAT YP00IMPL PG0BASE ProductStructureItf CATCsbCORBA 
CATCsbCORBA = SERVER

CXX_EXCEPTION =
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DIT_EX_MACROS


