#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = SI0TOPAC
#
OS = COMMON

LINK_WITH = SI0REPER GN0GRAPH\
            Collections JS0SETT\
            JS0CORBA JS0ERROR\
            JS0SCBAK JS0STR\
            CATCdbEntity \
            AD0XXBAS AC0CATPL\
            YP00IMPL YI00IMPL CATMathematics

