# COPYRIGHT DASSAULT SYSTEMES 2002
#

BUILT_OBJECT_TYPE=JAVA

TYPE= SERVER

LINK_WITH = CATJWSInfra CATJSystem CATJsyTransaction CATJWSIType CATJWSDLIbmImpl CATJWSModel CATJWSUddiItf qname

LOCAL_JAVA_FLAGS=-J-ms16m -J-mx96m


