/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAAnnotationFactory2_h
#define CATIAAnnotationFactory2_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByCATTPSPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATTPSPubIDL
#define ExportedByCATTPSPubIDL __declspec(dllexport)
#else
#define ExportedByCATTPSPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATTPSPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIAFactory.h"
#include "CATVariant.h"

class CATIAAnnotation2;
class CATIADrawingComponent;
class CATIAReference;
class CATIAUserSurface;

extern ExportedByCATTPSPubIDL IID IID_CATIAAnnotationFactory2;

class ExportedByCATTPSPubIDL CATIAAnnotationFactory2 : public CATIAFactory
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall CreateText(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oText)=0;

    virtual HRESULT __stdcall CreateTextOnAnnot(const CATBSTR & iText, CATIAAnnotation2 * iAnnot, CATIAAnnotation2 *& oText)=0;

    virtual HRESULT __stdcall CreateEvoluateText(CATIAUserSurface * iSurf, double iX, double iY, double iZ, CAT_VARIANT_BOOL iWithLeader, CATIAAnnotation2 *& oText)=0;

    virtual HRESULT __stdcall CreateDatum(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oDatum)=0;

    virtual HRESULT __stdcall CreateEvoluateDatum(CATIAUserSurface * iSurf, double iX, double iY, double iZ, CAT_VARIANT_BOOL iWithLeader, CATIAAnnotation2 *& oDatum)=0;

    virtual HRESULT __stdcall CreateRoughness(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oRoughness)=0;

    virtual HRESULT __stdcall CreateFlagNote(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oFlagNote)=0;

    virtual HRESULT __stdcall CreateDatumTarget(CATIAUserSurface * iSurf, CATIAAnnotation2 * iDatum, CATIAAnnotation2 *& oDatum)=0;

    virtual HRESULT __stdcall CreateNonSemanticDimension(CATIAUserSurface * iSurf, const CATVariant & iType, const CATVariant & iSubType, CATIAAnnotation2 *& oDimension)=0;

    virtual HRESULT __stdcall CreateSemanticDimension(CATIAUserSurface * iSurf, const CATVariant & iType, const CATVariant & iSubType, CATIAAnnotation2 *& oDimension)=0;

    virtual HRESULT __stdcall CreateToleranceWithoutDRF(const CATVariant & iIndex, CATIAUserSurface * iSurf, CATIAAnnotation2 *& oTolWoDRF)=0;

    virtual HRESULT __stdcall CreateDatumReferenceFrame(CATIAAnnotation2 *& opDRF)=0;

    virtual HRESULT __stdcall CreateToleranceWithDRF(const CATVariant & iIndex, CATIAUserSurface * iSurf, CATIAAnnotation2 * iDRF, CATIAAnnotation2 *& oTolWiDRF)=0;

    virtual HRESULT __stdcall InstanciateNOA(CATIAAnnotation2 * iNoa, CATIAUserSurface * iSurf, CATIAAnnotation2 *& oNoa)=0;

    virtual HRESULT __stdcall CreateTextNOA(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oNoa)=0;

    virtual HRESULT __stdcall CreateTextNoteObjectAttribute(CATIAUserSurface * iSurf, const CATBSTR & iNOAType, CATIAAnnotation2 *& oNoa)=0;

    virtual HRESULT __stdcall CreateDittoNOA(CATIAUserSurface * iSurf, const CATBSTR & iNOAType, CATIADrawingComponent * iDitto, CAT_VARIANT_BOOL iStickToGeometryOption, CATIAAnnotation2 *& oNoa)=0;

    virtual HRESULT __stdcall CreateWeld(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oWeld)=0;

    virtual HRESULT __stdcall CreateGDT(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oGDT)=0;

    virtual HRESULT __stdcall CreateCoordDimension(CATIAUserSurface * iSurf, CATIAAnnotation2 *& oCoorddimension)=0;


};

CATDeclareHandler(CATIAAnnotationFactory2, CATIAFactory);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
