/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIANoa_h
#define CATIANoa_h

#ifndef ExportedByCATTPSPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATTPSPubIDL
#define ExportedByCATTPSPubIDL __declspec(dllexport)
#else
#define ExportedByCATTPSPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATTPSPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"
#include "CATVariant.h"

class CATIADrawingComponent;
class CATIATPSParallelOnScreen;

extern ExportedByCATTPSPubIDL IID IID_CATIANoa;

class ExportedByCATTPSPubIDL CATIANoa : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Text(CATBSTR & oText)=0;

    virtual HRESULT __stdcall put_Text(const CATBSTR & iText)=0;

    virtual HRESULT __stdcall get_FlagText(CATBSTR & oText)=0;

    virtual HRESULT __stdcall put_FlagText(const CATBSTR & iText)=0;

    virtual HRESULT __stdcall URL(const CATVariant & iIndex, CATBSTR & oUrl)=0;

    virtual HRESULT __stdcall AddURL(const CATBSTR & iUrl)=0;

    virtual HRESULT __stdcall RemoveURL(const CATVariant & iIndex)=0;

    virtual HRESULT __stdcall ModifyURL(CATBSTR & iUrl, const CATVariant & iIndex)=0;

    virtual HRESULT __stdcall GetNbrURL(CATVariant *& oNumberOfURL)=0;

    virtual HRESULT __stdcall GetNbrURL2(CATLONG & oNumberOfURL)=0;

    virtual HRESULT __stdcall GetModifiableTextsCount(CATLONG & oCount)=0;

    virtual HRESULT __stdcall GetModifiableText(const CATVariant & iIndex, CATIABase *& oText)=0;

    virtual HRESULT __stdcall GetDitto(CATIADrawingComponent *& oDitto)=0;

    virtual HRESULT __stdcall TPSParallelOnScreen(CATIATPSParallelOnScreen *& oTPSParallelOnScreen)=0;


};

CATDeclareHandler(CATIANoa, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
