/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAFlagNote_h
#define CATIAFlagNote_h

#ifndef ExportedByCATTPSPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATTPSPubIDL
#define ExportedByCATTPSPubIDL __declspec(dllexport)
#else
#define ExportedByCATTPSPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATTPSPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"
#include "CATVariant.h"

class CATIATPSParallelOnScreen;

extern ExportedByCATTPSPubIDL IID IID_CATIAFlagNote;

class ExportedByCATTPSPubIDL CATIAFlagNote : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Text(CATBSTR & oText)=0;

    virtual HRESULT __stdcall put_Text(const CATBSTR & iText)=0;

    virtual HRESULT __stdcall get_FlagNoteText(CATBSTR & oFlagText)=0;

    virtual HRESULT __stdcall put_FlagNoteText(const CATBSTR & iText)=0;

    virtual HRESULT __stdcall URL(const CATVariant & iIndex, CATBSTR & oUrl)=0;

    virtual HRESULT __stdcall AddURL(const CATBSTR & iUrl)=0;

    virtual HRESULT __stdcall RemoveURL(const CATVariant & iIndex)=0;

    virtual HRESULT __stdcall ModifyURL(CATBSTR & iUrl, const CATVariant & iIndex)=0;

    virtual HRESULT __stdcall GetNbrURL(CATVariant *& oNumberOfURL)=0;

    virtual HRESULT __stdcall GetNbrURL2(CATLONG & oNumberOfURL)=0;

    virtual HRESULT __stdcall TPSParallelOnScreen(CATIATPSParallelOnScreen *& oTPSParallelOnScreen)=0;


};

CATDeclareHandler(CATIAFlagNote, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
