/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIATangentPlane_h
#define CATIATangentPlane_h

#ifndef ExportedByCATTPSPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATTPSPubIDL
#define ExportedByCATTPSPubIDL __declspec(dllexport)
#else
#define ExportedByCATTPSPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATTPSPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIABase.h"

extern ExportedByCATTPSPubIDL IID IID_CATIATangentPlane;

class ExportedByCATTPSPubIDL CATIATangentPlane : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Modifier(CATBSTR & oModifier)=0;

    virtual HRESULT __stdcall put_Modifier(const CATBSTR & iModifier)=0;


};

CATDeclareHandler(CATIATangentPlane, CATIABase);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
