/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIADimensionPattern_h
#define CATIADimensionPattern_h

#ifndef ExportedByCATTPSPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATTPSPubIDL
#define ExportedByCATTPSPubIDL __declspec(dllexport)
#else
#define ExportedByCATTPSPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATTPSPubIDL
#endif
#endif

#include "CATIABase.h"

extern ExportedByCATTPSPubIDL IID IID_CATIADimensionPattern;

class ExportedByCATTPSPubIDL CATIADimensionPattern : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_InstanceCount(double & oInstanceCount)=0;


};

CATDeclareHandler(CATIADimensionPattern, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
