/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIACaptureFactory_h
#define CATIACaptureFactory_h

#ifndef ExportedByCATTPSPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATTPSPubIDL
#define ExportedByCATTPSPubIDL __declspec(dllexport)
#else
#define ExportedByCATTPSPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATTPSPubIDL
#endif
#endif

#include "CATIAFactory.h"

class CATIACapture;

extern ExportedByCATTPSPubIDL IID IID_CATIACaptureFactory;

class ExportedByCATTPSPubIDL CATIACaptureFactory : public CATIAFactory
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall CreateCapture(CATIACapture *& oCapture)=0;


};

CATDeclareHandler(CATIACaptureFactory, CATIAFactory);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
