/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIASemanticGDTNxDisplay_h
#define CATIASemanticGDTNxDisplay_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByCATTPSPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATTPSPubIDL
#define ExportedByCATTPSPubIDL __declspec(dllexport)
#else
#define ExportedByCATTPSPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATTPSPubIDL
#endif
#endif

#include "CATIABase.h"

class CATIASemanticGDTCommonZone;

extern ExportedByCATTPSPubIDL IID IID_CATIASemanticGDTNxDisplay;

class ExportedByCATTPSPubIDL CATIASemanticGDTNxDisplay : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_InstanceCount(CATLONG & oInstanceCount)=0;

    virtual HRESULT __stdcall IsASeparate(CAT_VARIANT_BOOL & oIsSeparate)=0;

    virtual HRESULT __stdcall IsACollection(CAT_VARIANT_BOOL & oIsColl)=0;

    virtual HRESULT __stdcall CommonZone(CATIASemanticGDTCommonZone *& oCommonZone)=0;


};

CATDeclareHandler(CATIASemanticGDTNxDisplay, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
