/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeCombine_h
#define CATIAHybridShapeCombine_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"

class CATIAHybridShapeDirection;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeCombine;

class ExportedByGSMPubIDL CATIAHybridShapeCombine : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Elem1(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_Elem1(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_Direction1(CATIAHybridShapeDirection *& oElem)=0;

    virtual HRESULT __stdcall put_Direction1(CATIAHybridShapeDirection * iElem)=0;

    virtual HRESULT __stdcall get_Elem2(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_Elem2(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_Direction2(CATIAHybridShapeDirection *& oElem)=0;

    virtual HRESULT __stdcall put_Direction2(CATIAHybridShapeDirection * iElem)=0;

    virtual HRESULT __stdcall get_NearestSolution(CATLONG & oSolutionType)=0;

    virtual HRESULT __stdcall put_NearestSolution(CATLONG iSolutionType)=0;

    virtual HRESULT __stdcall get_SolutionTypeCombine(CATLONG & oSolutionTypeCombine)=0;

    virtual HRESULT __stdcall put_SolutionTypeCombine(CATLONG iSolutionTypeCombine)=0;


};

CATDeclareHandler(CATIAHybridShapeCombine, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShapeDirection.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
