/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapePointCenter_h
#define CATIAHybridShapePointCenter_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShapePoint.h"

class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapePointCenter;

class ExportedByGSMPubIDL CATIAHybridShapePointCenter : public CATIAHybridShapePoint
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Element(CATIAReference *& oElement)=0;

    virtual HRESULT __stdcall put_Element(CATIAReference * iElement)=0;


};

CATDeclareHandler(CATIAHybridShapePointCenter, CATIAHybridShapePoint);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShape.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
