/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeExtrapol_h
#define CATIAHybridShapeExtrapol_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"

class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeExtrapol;

class ExportedByGSMPubIDL CATIAHybridShapeExtrapol : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_ElemToExtrapol(CATIAReference *& oElemToExtrapol)=0;

    virtual HRESULT __stdcall put_ElemToExtrapol(CATIAReference * iElemToExtrapol)=0;

    virtual HRESULT __stdcall GetNumberOfExtrapolations(CATLONG & oNumberOfExtrapolations)=0;

    virtual HRESULT __stdcall RemoveExtrapolation(CATLONG iPos)=0;

    virtual HRESULT __stdcall RemoveAllExtrapolationsExceptTheFirstOne()=0;

    virtual HRESULT __stdcall get_Boundary(CATIAReference *& oBoundary)=0;

    virtual HRESULT __stdcall put_Boundary(CATIAReference * iBoundary)=0;

    virtual HRESULT __stdcall GetBoundary(CATLONG iPos, CATIAReference *& oBoundary)=0;

    virtual HRESULT __stdcall SetBoundary(CATLONG iPos, CATIAReference * iBoundary)=0;

    virtual HRESULT __stdcall get_ElemUntil(CATIAReference *& oElemUntil)=0;

    virtual HRESULT __stdcall put_ElemUntil(CATIAReference * iElemUntil)=0;

    virtual HRESULT __stdcall GetElemUntil(CATLONG iPos, CATIAReference *& oElemUntil)=0;

    virtual HRESULT __stdcall SetElemUntil(CATLONG iPos, CATIAReference * iElemUntil)=0;

    virtual HRESULT __stdcall get_Length(CATIALength *& oLength)=0;

    virtual HRESULT __stdcall GetLength(CATLONG iPos, CATIALength *& oLength)=0;

    virtual HRESULT __stdcall SetLengthD(CATLONG iPos, double iLength)=0;

    virtual HRESULT __stdcall SetLength(CATLONG iPos, CATIALength * iLength)=0;

    virtual HRESULT __stdcall get_LimitType(CATLONG & oLim)=0;

    virtual HRESULT __stdcall put_LimitType(CATLONG iLim)=0;

    virtual HRESULT __stdcall GetLimitType(CATLONG iPos, CATLONG & oLim)=0;

    virtual HRESULT __stdcall SetLimitType(CATLONG iPos, CATLONG iLim)=0;

    virtual HRESULT __stdcall get_ContinuityType(CATLONG & oLim)=0;

    virtual HRESULT __stdcall put_ContinuityType(CATLONG iLim)=0;

    virtual HRESULT __stdcall GetContinuityType(CATLONG iPos, CATLONG & oLim)=0;

    virtual HRESULT __stdcall SetContinuityType(CATLONG iPos, CATLONG iLim)=0;

    virtual HRESULT __stdcall get_BorderType(CATLONG & oBorder)=0;

    virtual HRESULT __stdcall put_BorderType(CATLONG iBorder)=0;

    virtual HRESULT __stdcall IsAssemble(CAT_VARIANT_BOOL & oAssemble)=0;

    virtual HRESULT __stdcall SetAssemble(CAT_VARIANT_BOOL iAssemble)=0;

    virtual HRESULT __stdcall get_Support(CATIAReference *& oSupport)=0;

    virtual HRESULT __stdcall put_Support(CATIAReference * iSupport)=0;

    virtual HRESULT __stdcall get_PropagationMode(CATLONG & oPropagationMode)=0;

    virtual HRESULT __stdcall put_PropagationMode(CATLONG iPropagationMode)=0;

    virtual HRESULT __stdcall GetInternalEdgesElement(CATLONG iPos, CATIAReference *& oInternalElement)=0;

    virtual HRESULT __stdcall RemoveAllInternalEdgesElement()=0;

    virtual HRESULT __stdcall get_ExtendEdgesMode(CAT_VARIANT_BOOL & oExtendMode)=0;

    virtual HRESULT __stdcall put_ExtendEdgesMode(CAT_VARIANT_BOOL iExtendMode)=0;

    virtual HRESULT __stdcall get_ConstantLengthMode(CAT_VARIANT_BOOL & oConstantLengthMode)=0;

    virtual HRESULT __stdcall put_ConstantLengthMode(CAT_VARIANT_BOOL iConstantLengthMode)=0;

    virtual HRESULT __stdcall get_ExtrapolBothSidesIdentically(CAT_VARIANT_BOOL & oExtrapolBothSidesIdentically)=0;

    virtual HRESULT __stdcall put_ExtrapolBothSidesIdentically(CAT_VARIANT_BOOL iExtrapolBothSidesIdentically)=0;


};

CATDeclareHandler(CATIAHybridShapeExtrapol, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
