/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapePlane_h
#define CATIAHybridShapePlane_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"
#include "CATSafeArray.h"

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapePlane;

class ExportedByGSMPubIDL CATIAHybridShapePlane : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetOrigin(CATSafeArrayVariant & oOrigin)=0;

    virtual HRESULT __stdcall GetFirstAxis(CATSafeArrayVariant & oFirstAxis)=0;

    virtual HRESULT __stdcall GetSecondAxis(CATSafeArrayVariant & oSecondAxis)=0;

    virtual HRESULT __stdcall PutOrigin(const CATSafeArrayVariant & iOrigin)=0;

    virtual HRESULT __stdcall PutFirstAxis(const CATSafeArrayVariant & iFirstAxis)=0;

    virtual HRESULT __stdcall PutSecondAxis(const CATSafeArrayVariant & iSecondAxis)=0;

    virtual HRESULT __stdcall GetPosition(double & oX, double & oY, double & oZ)=0;

    virtual HRESULT __stdcall SetPosition(double iX, double iY, double iZ)=0;

    virtual HRESULT __stdcall RemovePosition()=0;

    virtual HRESULT __stdcall IsARefPlane(CATLONG & oRef)=0;


};

CATDeclareHandler(CATIAHybridShapePlane, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIAGeometricElement.h"
#include "CATIAReference.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
