/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeCircleBitangentRadius_h
#define CATIAHybridShapeCircleBitangentRadius_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShapeCircle.h"

class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeCircleBitangentRadius;

class ExportedByGSMPubIDL CATIAHybridShapeCircleBitangentRadius : public CATIAHybridShapeCircle
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Curve1(CATIAReference *& oCrv)=0;

    virtual HRESULT __stdcall put_Curve1(CATIAReference * iCrv)=0;

    virtual HRESULT __stdcall get_Curve2(CATIAReference *& oCrv)=0;

    virtual HRESULT __stdcall put_Curve2(CATIAReference * iCrv)=0;

    virtual HRESULT __stdcall get_Support(CATIAReference *& oSupport)=0;

    virtual HRESULT __stdcall put_Support(CATIAReference * iSupport)=0;

    virtual HRESULT __stdcall get_Orientation1(CATLONG & oOri)=0;

    virtual HRESULT __stdcall put_Orientation1(CATLONG iOri)=0;

    virtual HRESULT __stdcall get_Orientation2(CATLONG & oOri)=0;

    virtual HRESULT __stdcall put_Orientation2(CATLONG iOri)=0;

    virtual HRESULT __stdcall get_DiameterMode(CAT_VARIANT_BOOL & oDiameterMode)=0;

    virtual HRESULT __stdcall put_DiameterMode(CAT_VARIANT_BOOL iDiameterMode)=0;

    virtual HRESULT __stdcall get_Radius(CATIALength *& Radius)=0;

    virtual HRESULT __stdcall get_Diameter(CATIALength *& oDiameter)=0;

    virtual HRESULT __stdcall get_DiscriminationIndex(CATLONG & oDiscriminationIndex)=0;

    virtual HRESULT __stdcall put_DiscriminationIndex(CATLONG iDiscriminationIndex)=0;

    virtual HRESULT __stdcall get_BeginOfCircle(CATLONG & oNumWireBegin)=0;

    virtual HRESULT __stdcall put_BeginOfCircle(CATLONG iNumWireBegin)=0;

    virtual HRESULT __stdcall get_TangentOrientation1(CATLONG & oOrientation)=0;

    virtual HRESULT __stdcall put_TangentOrientation1(CATLONG iOrientation)=0;

    virtual HRESULT __stdcall get_TangentOrientation2(CATLONG & oOrientation)=0;

    virtual HRESULT __stdcall put_TangentOrientation2(CATLONG iOrientation)=0;

    virtual HRESULT __stdcall get_TrimMode(CATLONG & oTrim)=0;

    virtual HRESULT __stdcall put_TrimMode(CATLONG iTrim)=0;


};

CATDeclareHandler(CATIAHybridShapeCircleBitangentRadius, CATIAHybridShapeCircle);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIAAngle.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShape.h"
#include "CATIAHybridShapeDirection.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
