/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeFilletBiTangent_h
#define CATIAHybridShapeFilletBiTangent_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"

class CATIAHybridShapeIntegratedLaw;
class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeFilletBiTangent;

class ExportedByGSMPubIDL CATIAHybridShapeFilletBiTangent : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_FirstElem(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_FirstElem(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_SecondElem(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_SecondElem(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_Radius(CATIALength *& oRadius)=0;

    virtual HRESULT __stdcall get_RadiusValue(double & oX)=0;

    virtual HRESULT __stdcall put_RadiusValue(double iX)=0;

    virtual HRESULT __stdcall get_FirstOrientation(CATLONG & oOrientation)=0;

    virtual HRESULT __stdcall put_FirstOrientation(CATLONG iOrientation)=0;

    virtual HRESULT __stdcall get_SecondOrientation(CATLONG & oOrientation)=0;

    virtual HRESULT __stdcall put_SecondOrientation(CATLONG iOrientation)=0;

    virtual HRESULT __stdcall InvertFirstOrientation()=0;

    virtual HRESULT __stdcall InvertSecondOrientation()=0;

    virtual HRESULT __stdcall get_SupportsTrimMode(CATLONG & oTrimMode)=0;

    virtual HRESULT __stdcall put_SupportsTrimMode(CATLONG iTrimMode)=0;

    virtual HRESULT __stdcall get_RibbonRelimitationMode(CATLONG & oRelimitationMode)=0;

    virtual HRESULT __stdcall put_RibbonRelimitationMode(CATLONG iRelimitationMode)=0;

    virtual HRESULT __stdcall get_Spine(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_Spine(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_HoldCurve(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_HoldCurve(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall GetFaceToKeep(CATLONG iPos, CATIAReference *& oFace)=0;

    virtual HRESULT __stdcall AppendNewFaceToKeep(CATIAReference * iFace)=0;

    virtual HRESULT __stdcall RemoveFaceToKeep(CATIAReference * iFace)=0;

    virtual HRESULT __stdcall RemoveAllFacesToKeep()=0;

    virtual HRESULT __stdcall get_FirstLawRelimiter(CATIAReference *& oFirstLaw)=0;

    virtual HRESULT __stdcall put_FirstLawRelimiter(CATIAReference * iFirstLaw)=0;

    virtual HRESULT __stdcall get_SecondLawRelimiter(CATIAReference *& oSecondLaw)=0;

    virtual HRESULT __stdcall put_SecondLawRelimiter(CATIAReference * iSecondLaw)=0;

    virtual HRESULT __stdcall get_IntegratedLaw(CATIAHybridShapeIntegratedLaw *& oIntegratedLaw)=0;

    virtual HRESULT __stdcall put_IntegratedLaw(CATIAHybridShapeIntegratedLaw * iIntegratedLaw)=0;

    virtual HRESULT __stdcall get_RadiusType(CATLONG & oRadiusType)=0;

    virtual HRESULT __stdcall put_RadiusType(CATLONG iRadiusType)=0;

    virtual HRESULT __stdcall get_SectionType(CATLONG & oSectionType)=0;

    virtual HRESULT __stdcall put_SectionType(CATLONG iSectionType)=0;

    virtual HRESULT __stdcall get_ConicalSectionParameter(double & oX)=0;

    virtual HRESULT __stdcall put_ConicalSectionParameter(double iX)=0;


};

CATDeclareHandler(CATIAHybridShapeFilletBiTangent, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShapeIntegratedLaw.h"
#include "CATIAKnowledgeActivableObject.h"
#include "CATIAKnowledgeObject.h"
#include "CATIALaw.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATIARelation.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
