/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeSweepLine_h
#define CATIAHybridShapeSweepLine_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShapeSweep.h"

class CATIAAngle;
class CATIAHybridShapeDirection;
class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeSweepLine;

class ExportedByGSMPubIDL CATIAHybridShapeSweepLine : public CATIAHybridShapeSweep
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_FirstGuideCrv(CATIAReference *& Elem)=0;

    virtual HRESULT __stdcall put_FirstGuideCrv(CATIAReference * Elem)=0;

    virtual HRESULT __stdcall get_SecondGuideCrv(CATIAReference *& Elem)=0;

    virtual HRESULT __stdcall put_SecondGuideCrv(CATIAReference * Elem)=0;

    virtual HRESULT __stdcall get_FirstGuideSurf(CATIAReference *& Elem)=0;

    virtual HRESULT __stdcall put_FirstGuideSurf(CATIAReference * Elem)=0;

    virtual HRESULT __stdcall get_SecondGuideSurf(CATIAReference *& Elem)=0;

    virtual HRESULT __stdcall put_SecondGuideSurf(CATIAReference * Elem)=0;

    virtual HRESULT __stdcall get_Spine(CATIAReference *& Elem)=0;

    virtual HRESULT __stdcall put_Spine(CATIAReference * Elem)=0;

    virtual HRESULT __stdcall get_Mode(CATLONG & Elem)=0;

    virtual HRESULT __stdcall put_Mode(CATLONG Elem)=0;

    virtual HRESULT __stdcall GetAngle(CATLONG iI, CATIAAngle *& Elem)=0;

    virtual HRESULT __stdcall SetAngle(CATLONG iI, double iElem)=0;

    virtual HRESULT __stdcall get_AngleLawType(CATLONG & oElem)=0;

    virtual HRESULT __stdcall put_AngleLawType(CATLONG iElem)=0;

    virtual HRESULT __stdcall get_AngleLawInversion(CATLONG & oElem)=0;

    virtual HRESULT __stdcall put_AngleLawInversion(CATLONG iElem)=0;

    virtual HRESULT __stdcall get_AngleLaw(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_AngleLaw(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall GetLength(CATLONG iI, CATIALength *& Elem)=0;

    virtual HRESULT __stdcall SetLength(CATLONG iI, double iElem)=0;

    virtual HRESULT __stdcall get_FirstLengthLaw(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_FirstLengthLaw(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall GetFirstLengthLaw(CATIALength *& oLength1, CATIALength *& oLength2, CATLONG & oLawType)=0;

    virtual HRESULT __stdcall SetFirstLengthLaw(double iLength1, double iLength2, CATLONG iLawType)=0;

    virtual HRESULT __stdcall get_FirstLengthLawInversion(CATLONG & oElem)=0;

    virtual HRESULT __stdcall put_FirstLengthLawInversion(CATLONG iElem)=0;

    virtual HRESULT __stdcall get_SecondLengthLaw(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_SecondLengthLaw(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall GetSecondLengthLaw(CATIALength *& oLength1, CATIALength *& oLength2, CATLONG & oLawType)=0;

    virtual HRESULT __stdcall SetSecondLengthLaw(double iLength1, double iLength2, CATLONG iLawType)=0;

    virtual HRESULT __stdcall get_SecondLengthLawInversion(CATLONG & oElem)=0;

    virtual HRESULT __stdcall put_SecondLengthLawInversion(CATLONG iElem)=0;

    virtual HRESULT __stdcall GetChoiceNo(CATLONG & oVal1, CATLONG & oVal2, CATLONG & oVal3)=0;

    virtual HRESULT __stdcall SetChoiceNo(CATLONG iVal1, CATLONG iVal2, CATLONG iVal3)=0;

    virtual HRESULT __stdcall get_TrimOption(CATLONG & Elem)=0;

    virtual HRESULT __stdcall put_TrimOption(CATLONG Elem)=0;

    virtual HRESULT __stdcall get_SecondTrimOption(CATLONG & Elem)=0;

    virtual HRESULT __stdcall put_SecondTrimOption(CATLONG Elem)=0;

    virtual HRESULT __stdcall get_SmoothActivity(CAT_VARIANT_BOOL & oSmooth)=0;

    virtual HRESULT __stdcall put_SmoothActivity(CAT_VARIANT_BOOL iSmooth)=0;

    virtual HRESULT __stdcall get_SmoothAngleThreshold(CATIAAngle *& opIAAngle)=0;

    virtual HRESULT __stdcall get_GuideDeviationActivity(CAT_VARIANT_BOOL & oActivity)=0;

    virtual HRESULT __stdcall put_GuideDeviationActivity(CAT_VARIANT_BOOL iActivity)=0;

    virtual HRESULT __stdcall get_GuideDeviation(CATIALength *& opIALength)=0;

    virtual HRESULT __stdcall get_DraftComputationMode(CATLONG & oDraftCompType)=0;

    virtual HRESULT __stdcall put_DraftComputationMode(CATLONG iDraftCompType)=0;

    virtual HRESULT __stdcall get_DraftDirection(CATIAHybridShapeDirection *& oDir)=0;

    virtual HRESULT __stdcall put_DraftDirection(CATIAHybridShapeDirection * iDir)=0;

    virtual HRESULT __stdcall GetNbGuideCrv(CATLONG & oNum)=0;

    virtual HRESULT __stdcall RemoveGuideCrv()=0;

    virtual HRESULT __stdcall GetNbGuideSur(CATLONG & oNum)=0;

    virtual HRESULT __stdcall RemoveGuideSur()=0;

    virtual HRESULT __stdcall GetLongitudinalRelimiters(CATIAReference *& opIAElem1, CATIAReference *& opIAElem2)=0;

    virtual HRESULT __stdcall SetLongitudinalRelimiters(CATIAReference * ipIAElem1, CATIAReference * ipIAElem2)=0;

    virtual HRESULT __stdcall GetRelimiters(CATIAReference *& opIAElem1, CATLONG & opOrient1, CATIAReference *& opIAElem2, CATLONG & opOrient2)=0;

    virtual HRESULT __stdcall SetRelimiters(CATIAReference * ipIAElem1, CATLONG ipOrient1, CATIAReference * ipIAElem2, CATLONG ipOrient2)=0;

    virtual HRESULT __stdcall GetNbAngle(CATLONG & oAng)=0;

    virtual HRESULT __stdcall RemoveAngle()=0;

    virtual HRESULT __stdcall GetAngularLaw(CATIAAngle *& opStartAng, CATIAAngle *& opEndAng, CATLONG & oLawType)=0;

    virtual HRESULT __stdcall SetAngularLaw(double iStartAng, double iEndAng, CATLONG iLawType)=0;

    virtual HRESULT __stdcall GetNbLength(CATLONG & oLen)=0;

    virtual HRESULT __stdcall RemoveLength()=0;

    virtual HRESULT __stdcall SetSmoothAngleThreshold(double iAngle)=0;

    virtual HRESULT __stdcall SetGuideDeviation(double iLength)=0;

    virtual HRESULT __stdcall GetDraftAngleDefinitionLocation(CATLONG iLoc, CATIAReference *& opIAElement, CATIAAngle *& oAngle)=0;

    virtual HRESULT __stdcall GetDraftAngleDefinitionLocationsNb(CATLONG & oCount)=0;

    virtual HRESULT __stdcall AddDraftAngleDefinitionLocation(CATIAReference * ipIALocElem, double iAng)=0;

    virtual HRESULT __stdcall RemoveDraftAngleDefinitionLocationPosition(CATLONG iPos)=0;

    virtual HRESULT __stdcall GetFirstLengthDefinitionType(CATLONG & oFirstType, CATIAReference *& opIAElem)=0;

    virtual HRESULT __stdcall SetFirstLengthDefinitionType(CATLONG iFirstType, CATIAReference * ipIAElem)=0;

    virtual HRESULT __stdcall GetSecondLengthDefinitionType(CATLONG & oSecondType, CATIAReference *& opIAElem)=0;

    virtual HRESULT __stdcall SetSecondLengthDefinitionType(CATLONG iSecondType, CATIAReference * ipIAElem)=0;

    virtual HRESULT __stdcall InsertDraftAngleDefinitionLocation(CATIAReference * iElem, CATIAAngle * iAngle, CATLONG iPos)=0;

    virtual HRESULT __stdcall RemoveAllDraftAngleDefinitionLocations()=0;

    virtual HRESULT __stdcall GetChoiceNbSurfaces(CATLONG & oSurfOri1, CATLONG & oSurfOri2, CATLONG & oSurfCouplOri1, CATLONG & oSurfCouplOri2, CATLONG & oNo)=0;

    virtual HRESULT __stdcall SetChoiceNbSurfaces(CATLONG iSurfOri1, CATLONG iSurfOri2, CATLONG iSurfCouplOri1, CATLONG iSurfCouplOri2, CATLONG iNo)=0;

    virtual HRESULT __stdcall GetLengthLawTypes(CATLONG & oFirstType, CATLONG & oSecondType)=0;

    virtual HRESULT __stdcall SetLengthLawTypes(CATLONG iFirstType, CATLONG iSecondType)=0;

    virtual HRESULT __stdcall get_Context(CATLONG & oContext)=0;

    virtual HRESULT __stdcall put_Context(CATLONG iContext)=0;

    virtual HRESULT __stdcall get_SolutionNo(CATLONG & Elem)=0;

    virtual HRESULT __stdcall put_SolutionNo(CATLONG Elem)=0;

    virtual HRESULT __stdcall get_CanonicalDetection(CATLONG & oDetection)=0;

    virtual HRESULT __stdcall put_CanonicalDetection(CATLONG iDetection)=0;


};

CATDeclareHandler(CATIAHybridShapeSweepLine, CATIAHybridShapeSweep);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIAAngle.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShape.h"
#include "CATIAHybridShapeDirection.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
