/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeExtrude_h
#define CATIAHybridShapeExtrude_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"

class CATIAHybridShapeDirection;
class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeExtrude;

class ExportedByGSMPubIDL CATIAHybridShapeExtrude : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_BeginOffset(CATIALength *& oExtrude)=0;

    virtual HRESULT __stdcall get_EndOffset(CATIALength *& oExtrude)=0;

    virtual HRESULT __stdcall get_Direction(CATIAHybridShapeDirection *& oDir)=0;

    virtual HRESULT __stdcall put_Direction(CATIAHybridShapeDirection * iDir)=0;

    virtual HRESULT __stdcall get_ExtrudedObject(CATIAReference *& oFaceToExtrude)=0;

    virtual HRESULT __stdcall put_ExtrudedObject(CATIAReference * oFaceToExtrude)=0;

    virtual HRESULT __stdcall get_Context(CATLONG & oContext)=0;

    virtual HRESULT __stdcall put_Context(CATLONG iContext)=0;

    virtual HRESULT __stdcall put_Orientation(CAT_VARIANT_BOOL iOrientation)=0;

    virtual HRESULT __stdcall get_Orientation(CAT_VARIANT_BOOL & oOrientation)=0;

    virtual HRESULT __stdcall get_FirstLimitType(CATLONG & oLim1Type)=0;

    virtual HRESULT __stdcall put_FirstLimitType(CATLONG iLim1Type)=0;

    virtual HRESULT __stdcall get_SecondLimitType(CATLONG & oLim2Type)=0;

    virtual HRESULT __stdcall put_SecondLimitType(CATLONG iLim2Type)=0;

    virtual HRESULT __stdcall get_FirstUptoElement(CATIAReference *& oLim1Elem)=0;

    virtual HRESULT __stdcall put_FirstUptoElement(CATIAReference * iLim1Elem)=0;

    virtual HRESULT __stdcall get_SecondUptoElement(CATIAReference *& oLim2Elem)=0;

    virtual HRESULT __stdcall put_SecondUptoElement(CATIAReference * iLim2Elem)=0;

    virtual HRESULT __stdcall get_SymmetricalExtension(CAT_VARIANT_BOOL & oSym)=0;

    virtual HRESULT __stdcall put_SymmetricalExtension(CAT_VARIANT_BOOL iSym)=0;


};

CATDeclareHandler(CATIAHybridShapeExtrude, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShapeDirection.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
