/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapePlaneTangent_h
#define CATIAHybridShapePlaneTangent_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShapePlane.h"

class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapePlaneTangent;

class ExportedByGSMPubIDL CATIAHybridShapePlaneTangent : public CATIAHybridShapePlane
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Surface(CATIAReference *& oSurface)=0;

    virtual HRESULT __stdcall put_Surface(CATIAReference * iSurface)=0;

    virtual HRESULT __stdcall get_Point(CATIAReference *& oPoint)=0;

    virtual HRESULT __stdcall put_Point(CATIAReference * iPoint)=0;


};

CATDeclareHandler(CATIAHybridShapePlaneTangent, CATIAHybridShapePlane);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShape.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
