/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeBoundary_h
#define CATIAHybridShapeBoundary_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"

class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeBoundary;

class ExportedByGSMPubIDL CATIAHybridShapeBoundary : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Propagation(CATLONG & oProp)=0;

    virtual HRESULT __stdcall put_Propagation(CATLONG iProp)=0;

    virtual HRESULT __stdcall get_InitialElement(CATIAReference *& oObject)=0;

    virtual HRESULT __stdcall put_InitialElement(CATIAReference * oObject)=0;

    virtual HRESULT __stdcall get_Support(CATIAReference *& oObject)=0;

    virtual HRESULT __stdcall put_Support(CATIAReference * oObject)=0;

    virtual HRESULT __stdcall get_To(CATIAReference *& opIATo)=0;

    virtual HRESULT __stdcall put_To(CATIAReference * ipIATo)=0;

    virtual HRESULT __stdcall get_From(CATIAReference *& opIAFrom)=0;

    virtual HRESULT __stdcall put_From(CATIAReference * ipIAFrom)=0;

    virtual HRESULT __stdcall get_ToOrientation(CATLONG & oToOrientation)=0;

    virtual HRESULT __stdcall put_ToOrientation(CATLONG iToOrientation)=0;

    virtual HRESULT __stdcall get_FromOrientation(CATLONG & oFromOrientation)=0;

    virtual HRESULT __stdcall put_FromOrientation(CATLONG iFromOrientation)=0;


};

CATDeclareHandler(CATIAHybridShapeBoundary, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIAGeometricElement.h"
#include "CATIAReference.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
