/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapePointOnPlane_h
#define CATIAHybridShapePointOnPlane_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShapePoint.h"

class CATIAHybridShapeDirection;
class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapePointOnPlane;

class ExportedByGSMPubIDL CATIAHybridShapePointOnPlane : public CATIAHybridShapePoint
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Plane(CATIAReference *& oPlane)=0;

    virtual HRESULT __stdcall put_Plane(CATIAReference * iPlane)=0;

    virtual HRESULT __stdcall get_Point(CATIAReference *& oRefPoint)=0;

    virtual HRESULT __stdcall put_Point(CATIAReference * iRefPoint)=0;

    virtual HRESULT __stdcall get_XOffset(CATIALength *& oX)=0;

    virtual HRESULT __stdcall get_YOffset(CATIALength *& oY)=0;

    virtual HRESULT __stdcall get_FirstDirection(CATIAHybridShapeDirection *& oDir)=0;

    virtual HRESULT __stdcall put_FirstDirection(CATIAHybridShapeDirection * iDir)=0;

    virtual HRESULT __stdcall get_ProjectionSurface(CATIAReference *& oProjSur)=0;

    virtual HRESULT __stdcall put_ProjectionSurface(CATIAReference * iProjSur)=0;

    virtual HRESULT __stdcall GetSecondDirection(double & oDirX, double & oDirY, double & oDirZ)=0;

    virtual HRESULT __stdcall SetSecondDirection(double iDirX, double iDirY, double iDirZ)=0;


};

CATDeclareHandler(CATIAHybridShapePointOnPlane, CATIAHybridShapePoint);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShape.h"
#include "CATIAHybridShapeDirection.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
