/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeDevelop_h
#define CATIAHybridShapeDevelop_h

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"

class CATIAAngle;
class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeDevelop;

class ExportedByGSMPubIDL CATIAHybridShapeDevelop : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Mode(CATLONG & oElem)=0;

    virtual HRESULT __stdcall put_Mode(CATLONG iElem)=0;

    virtual HRESULT __stdcall get_ModePos(CATLONG & oElem)=0;

    virtual HRESULT __stdcall put_ModePos(CATLONG iElem)=0;

    virtual HRESULT __stdcall get_WireToDevelop(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_WireToDevelop(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_PositionedWire(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_PositionedWire(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_Support(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_Support(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_PlaneAxisOrigin(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_PlaneAxisOrigin(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall get_PlaneAxisDirection(CATIAReference *& oElem)=0;

    virtual HRESULT __stdcall put_PlaneAxisDirection(CATIAReference * iElem)=0;

    virtual HRESULT __stdcall GetPlaneAxisCoord(CATLONG iCoorIdx, CATIALength *& oCoordValue)=0;

    virtual HRESULT __stdcall SetPlaneAxisCoord(CATLONG iCoorIdx, double iCoordValue)=0;

    virtual HRESULT __stdcall GetPlaneAxisAngle(CATIAAngle *& oAngle)=0;

    virtual HRESULT __stdcall SetPlaneAxisAngle(double iAngle)=0;

    virtual HRESULT __stdcall GetPlaneAxisSwapAxes(CATLONG ii, CATLONG & oInversionValue)=0;

    virtual HRESULT __stdcall SetPlaneAxisSwapAxes(CATLONG iIdx, CATLONG iInversionValue)=0;

    virtual HRESULT __stdcall get_PointOnSupport(CATIAReference *& oOrigin)=0;

    virtual HRESULT __stdcall put_PointOnSupport(CATIAReference * iOrigin)=0;


};

CATDeclareHandler(CATIAHybridShapeDevelop, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIAAngle.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
