/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAHybridShapeCylinder_h
#define CATIAHybridShapeCylinder_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByGSMPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __GSMPubIDL
#define ExportedByGSMPubIDL __declspec(dllexport)
#else
#define ExportedByGSMPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByGSMPubIDL
#endif
#endif

#include "CATIAHybridShape.h"

class CATIAHybridShapeDirection;
class CATIALength;
class CATIAReference;

extern ExportedByGSMPubIDL IID IID_CATIAHybridShapeCylinder;

class ExportedByGSMPubIDL CATIAHybridShapeCylinder : public CATIAHybridShape
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Center(CATIAReference *& oCenter)=0;

    virtual HRESULT __stdcall put_Center(CATIAReference * iCenter)=0;

    virtual HRESULT __stdcall get_Direction(CATIAHybridShapeDirection *& oDir)=0;

    virtual HRESULT __stdcall put_Direction(CATIAHybridShapeDirection * iDir)=0;

    virtual HRESULT __stdcall get_Radius(CATIALength *& oRadius)=0;

    virtual HRESULT __stdcall put_Radius(CATIALength * iRadius)=0;

    virtual HRESULT __stdcall get_Length1(CATIALength *& oLength1)=0;

    virtual HRESULT __stdcall put_Length1(CATIALength * iLength1)=0;

    virtual HRESULT __stdcall get_Length2(CATIALength *& oLength2)=0;

    virtual HRESULT __stdcall put_Length2(CATIALength * iLength2)=0;

    virtual HRESULT __stdcall put_Orientation(CAT_VARIANT_BOOL iOrientation)=0;

    virtual HRESULT __stdcall get_Orientation(CAT_VARIANT_BOOL & oOrientation)=0;

    virtual HRESULT __stdcall InvertOrientation()=0;

    virtual HRESULT __stdcall get_SymmetricalExtension(CAT_VARIANT_BOOL & oSym)=0;

    virtual HRESULT __stdcall put_SymmetricalExtension(CAT_VARIANT_BOOL iSym)=0;


};

CATDeclareHandler(CATIAHybridShapeCylinder, CATIAHybridShape);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATGeometricType.h"
#include "CATIABase.h"
#include "CATIADimension.h"
#include "CATIAGeometricElement.h"
#include "CATIAHybridShapeDirection.h"
#include "CATIALength.h"
#include "CATIAParameter.h"
#include "CATIARealParam.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
