#ifndef CATIAStrFoundation_IDL
#define CATIAStrFoundation_IDL

/*IDLREP*/
// COPYRIGHT DASSAULT SYSTEMES 2000

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

// ****************************************************************************
// CATIA Version 5 Release 1 Framework Structure
// Copyright Dassault Systemes 1997
// ****************************************************************************
//  Abstract:
//  ---------
//    
//  Interfaces for Journalling  
//    
// ****************************************************************************
//  Usage:
//  ------
//    
// ****************************************************************************
//  Inheritance:
//  ------------
//  
//
// ****************************************************************************
//  Main Methods:
//  -------------
//    
// ****************************************************************************
//  Historic
//  --------
//
//  Author: Alain Debuisson
//  Date  : 12/03/01
//  But   : Creation
//
// ****************************************************************************

#include "CATIABase.idl"

	/**
	* Represents a structure foundation assembly.
	*/

interface CATIAStrFoundation : CATIABase
{

};

// Interface name : CATIAStrFoundation
#pragma ID CATIAStrFoundation "DCE:ea9d24b2-16c2-11d5-94ca00108379318c"
#pragma DUAL CATIAStrFoundation

// VB name : StrFoundation
#pragma ID StrFoundation "DCE:f9c1d456-16c2-11d5-94ca00108379318c"
#pragma ALIAS CATIAStrFoundation StrFoundation

#endif
