// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CATIStrTypeESSObjectSettingAtt.h
// Define the CATIStrTypeESSObjectSettingAtt interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Nov 2003  Creation: Code generated by the CAA wizard  jcm
//===================================================================
#ifndef CATIStrTypeESSObjectSettingAtt_H
#define CATIStrTypeESSObjectSettingAtt_H

/**
  * @CAA2Level L1
  * @CAA2Usage U3
  */

#include "CATBaseUnknown.h"
#include "CATStrSettingsItfCPP.h"

class CATSettingInfo;
class CATUnicodeString;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATStrSettingsItfCPP IID IID_CATIStrTypeESSObjectSettingAtt;
#else
extern "C" const IID IID_CATIStrTypeESSObjectSettingAtt ;
#endif

//------------------------------------------------------------------

/**
 * Describe the SFDctionality of your interface here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class ExportedByCATStrSettingsItfCPP CATIStrTypeESSObjectSettingAtt : public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    //***********************************************************************
    // Ensure consistency with the IDL interface that will delegate its work
    // Check allowed signatures in System.CATSysSettingController
    //***********************************************************************
    /**
     * Retrieves the MemberTypes attribute.
     */
     virtual HRESULT GetMemberTypes( CATUnicodeString & oMemberTypes ) = 0;

    /**
     * Sets the MemberTypes attribute.
     */
     virtual HRESULT SetMemberTypes( CATUnicodeString & iMemberTypes ) = 0;

    /**
     * Retrieves the state of the MemberTypes parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetMemberTypesInfo( CATSettingInfo*    oInfo ) = 0;

    /** 
     * Locks or unlocks the MemberTypes parameter.
     * <br><b>Role</b>: Locks or unlocks the MemberTypes parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>   to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetMemberTypesLock( unsigned char      iLocked ) = 0;

    /**
     * Retrieves the PlateTypes attribute.
     */
     virtual HRESULT GetPlateTypes( CATUnicodeString & oPlateTypes ) = 0;

    /**
     * Sets the PlateTypes attribute.
     */
     virtual HRESULT SetPlateTypes( CATUnicodeString & iPlateTypes ) = 0;

    /**
     * Retrieves the state of the PlateTypes parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetPlateTypesInfo( CATSettingInfo*    oInfo ) = 0;

    /** 
     * Locks or unlocks the PlateTypes parameter.
     * <br><b>Role</b>: Locks or unlocks the PlateTypes parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>   to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetPlateTypesLock( unsigned char      iLocked ) = 0;

	// No constructors or destructors on this pure virtual base class
    // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
