# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CATMatProIDL
# Module for compilation of the protected IDL interfaces
#======================================================================
#
#  May 2002  Creation: Code generated by the CAA wizard  AST
#======================================================================
#
# NO BUILD             
#

BUILT_OBJECT_TYPE=NONE

SOURCES_PATH=ProtectedInterfaces
COMPILATION_IDL=YES

