#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
InfInterfacesUUID
#else
LINK_WITH_FOR_IID =
#endif

BUILT_OBJECT_TYPE = SHARED LIBRARY
LINK_WITH=$(LINK_WITH_FOR_IID) JS0GROUP CATBatProtocol CATBatchUtils CATBatCliMonitor \
