#ifndef CATIMSHStudioSpec_H
#define CATIMSHStudioSpec_H
// COPYRIGHT Dassault Systemes 2002

/**
 * @CAA2Level L0 
 * @CAA2Usage U4 CATMSHStudioSpec
 */
//===================================================================
//
// CATIMSHStudioSpec.h
// Define the CATIMSHStudioSpec interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2002  Creation: Code generated by the CAA wizard  GSE
//===================================================================

#include "MSHStudio.h"
#include "CATBaseUnknown.h"
#include "CATMSHStudioStruct.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByMSHStudio IID IID_CATIMSHStudioSpec;
#else
extern "C" const IID IID_CATIMSHStudioSpec ;
#endif

class CATMarshal;
class CATIMSHStudio;
class CATIMSHStPartition;
class CATIMSHLocalSpecification;
class CATMSHStGeometryLink;
class CATMSHStListOfPartitions;
class CATRep;
class CATUnicodeString;
class CATTrace;
class CATIMSHSizeMap;

/**
 * Interface representing a user mesh specification.
 * <b>Role</b>: This interface provides all necessary informations about a 
 * mesh specification.
 * <p><b>BOA information</b>: this interface can be implemented using the BOA (Basic Object Adapter).
 * To know more about the BOA, refer to the CAA Encyclopedia home page. 
 * Click Middleware at the bottom left, then click the Object Modeler tab page.
 * Several articles deal with the BOA.</p>
 */
class ExportedByMSHStudio CATIMSHStudioSpec: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

/**
 * @nodoc
 */  
  enum State
  {
    Unknown         = 0,
    Invalid         = 1,
    ManualUpdate    = 2,
    AutomaticUpdate = 3,
    UpToDate        = 4,
    Failed          = 5
  };

/**
 * Read the current Studio.<dd>
 * This method doesn't <tt>AddRef()</tt> the Studio.
 * @return
 *   An interface to @href CATIMSHStudio.
 */
  virtual CATIMSHStudio * GetStudio() const=0;
/**
 * Write the current Studio.
 * @param Studio
 *   An interface to @href CATIMSHStudio.
 */
  virtual void SetStudio ( CATIMSHStudio * Studio ) =0;
/**
 * Read the link to support impacted by the meshing specification.
 * @return
 *   An HRESULT.
 *   <br><b>Legal values</b>:
 *   <dl><dt>S_OK</dt><dd>The support is valid.
 *   <dt>E_FAIL</dt><dd>The support is invalid.
 *   </dl>
 * @param GeometryLink
 *   A @href CATMSHStGeometryLink.
 */
  virtual HRESULT GetSupport(CATMSHStGeometryLink * &GeometryLink )=0;
/**
 * Write the link to support impacted by the meshing specification.
 * @return
 *   An HRESULT.
 *   <br><b>Legal values</b>:
 *   <dl><dt>S_OK</dt><dd>The support is valid.
 *   <dt>E_FAIL</dt><dd>The support is invalid.
 *   </dl>
 * @param GeometryLink
 *   A @href CATMSHStGeometryLink.
 */
  virtual HRESULT SetSupport(CATMSHStGeometryLink * GeometryLink) =0;
/**
 * Read the list of partitions impacted by the meshing specification.
 * @return
 *   An HRESULT.
 *   <br><b>Legal values</b>:
 *   <dl><dt>S_OK</dt><dd>The list of partitions is valid.
 *   <dt>E_FAIL</dt><dd>The list of partitions is invalid.
 *   </dl>
 * @param Partitions
 *   A @href CATMSHStListOfPartitions.
 */
  virtual HRESULT GetPartitions(CATMSHStListOfPartitions &Partitions )=0;
/**
 * Write the list of partitions impacted by the meshing specification.
 * @return
 *   An HRESULT.
 *   <br><b>Legal values</b>:
 *   <dl><dt>S_OK</dt><dd>The list of partitions is valid.
 *   <dt>E_FAIL</dt><dd>The list of partitions is invalid.
 *   </dl>
 * @param Partitions
 *   A @href CATMSHStListOfPartitions.
 */
  virtual HRESULT SetPartitions(CATMSHStListOfPartitions &Partitions) =0;
/**
 * Compute the mesh specification condition for the partition.
 * @return
 *   An HRESULT.
 *   <br><b>Legal values</b>:
 *   <dl><dt>S_OK</dt><dd>Compute is OK.
 *   <dt>E_FAIL</dt><dd>Compute has failed..
 *   </dl>
 * @param Partition 
 *   The partition impacted by the mesh specification.
 * @param Mesh 
 *    The mesh condition @href #CATMSHStSpecCondition on the partition.
 */
  virtual HRESULT ComputeMeshCondition( const CATIMSHStPartition * Partition, CATMSHStSpecCondition &Mesh )=0; 
/**
 * Read the impact mode for the meshing specification.
 * @return
 *   <br><b>Legal values</b>:
 *   <dl><dt>0</dt><dd>The meshing specification doesn't impact neighbours mesh domains.
 *   <dt>1</dt><dd>The meshing specification impacts neighbours mesh domains.
 *   </dl>
 */
 virtual int GetImpactMode() const=0;
/**
 * Write the impact mode for the meshing specification.
 * @param WithImpact
 *   <br><b>Legal values</b>:
 *   <dl><dt>0</dt><dd>The meshing specification doesn't impact neighbours mesh domains.
 *   <dt>1</dt><dd>The meshing specification impacts neighbours mesh domains.
 *   </dl>
 */
 virtual void SetImpactMode( int WithImpact )=0;

/**
 * Read the number of values in an attribute.
 * @param iName
 *   Name of the attribute. 
 * @param oNumber
 *   Number of values stored in the attribute. 
 */
 virtual HRESULT GetNumberOfValues ( const CATUnicodeString &iName , int &oNumber )=0;
/**
 * Valuates a local mesh specification attribute to a real double value.
 * @param iName
 *   Name of the local specification. 
 * @param iNumber
 *   Number of iValues. 
 * @param iValues
 *   Real double value to be used for the specification. 
 */
 virtual HRESULT SetLocalSpecification ( const CATUnicodeString &iName, int iNumber, const double iValues[] )=0;
/**
 * Retreives the real double value of a local mesh specification attribute.
 * @param iName
 *   Name of the local specification. 
 * @param iNumber
 *   Number of oValues. 
 * @param oValue
 *   Real double values of the attribute. 
 */
 virtual HRESULT GetLocalSpecification ( const CATUnicodeString &iName, int iNumber, double oValues[] )=0;
/**
 * Valuates a local mesh specification attribute to a integer table value.
 * @param iName
 *   Name of the local specification. 
 * @param iNumber
 *   Number of iValues. 
 * @param iValue
 *   Integers values to be used for the attribute. 
 */
 virtual HRESULT SetLocalSpecification ( const CATUnicodeString &iName, int iNumber , const int iValues[] )=0;
/**
 * Retreives the integer value of a local mesh specification attribute.
 * @param iName
 *   Name of the local specification. 
 * @param iNumber
 *   Number of oValues. 
 * @param oValues
 *   Integers values of the attribute. 
 */
 virtual HRESULT GetLocalSpecification ( const CATUnicodeString &iName, int iNumber, int oValues[] )=0;
/**
 * Valuates a local mesh specification attribute to a character value.
 * @param iName
 *   Name of the local specification. 
 * @param iNumber
 *   Number of oValues. 
 * @param iValue
 *   Character value to be used for the specification. 
 */
 virtual HRESULT SetLocalSpecification ( const CATUnicodeString &iName, int iNumber, const CATUnicodeString iValue[] )=0;
/**
 * Retreives the character value of a local mesh specification attribute.
 * @param iName
 *   Name of the local specification. 
 * @param iNumber
 *   Number of oValues. 
 * @param oValue
 *   Character value of the specification. 
 */
 virtual HRESULT GetLocalSpecification ( const CATUnicodeString &iName, int iNumber, CATUnicodeString oValue[] )=0;
/**
 * Valuates a local mesh specification attribute to partitions list.
 * @param iName
 *   Name of the local specification. 
 * @param iPartitions 
 *   List of partitions 
 */
 virtual HRESULT SetLocalSpecification ( const CATUnicodeString &iName, const CATMSHStListOfPartitions &iPartitions )=0;
/**
 * Retreives the partitions list of a local mesh specification attribute.
 * @param iName
 *   Name of the local specification. 
 * @param oPartitions 
 *   List of partitions 
 */
  virtual HRESULT GetLocalSpecification ( const CATUnicodeString &iName, CATMSHStListOfPartitions &oPartitions )=0;
/**
  * Returns the status of the specification concerning the mesh.
  * @param oUpToUpdate
  *  !=0: the mesh is up to date.<br>
  *    0: the mesh needs to be updated.
  */
  virtual HRESULT IsMeshUpToDate( int &oUpToUpdate ) =0;
/**
  * Modify the specified size map to take account the specification.
  * @param Partition 
  *   The partition impacted by the mesh for default specification only.
  */
  virtual HRESULT UpdateSizeMap(CATIMSHSizeMap * iMap, CATIMSHStPartition * Partition=NULL)=0;
/**
  * Returns support dimension need for spec
  */
  virtual int GetSupportDimension() =0;
/**
 * @nodoc
 */
  virtual HRESULT UpdateMesh( CATIMSHStPartition * Partition=NULL)=0;
/**
 * @nodoc
 */
  virtual int IsExclusivePartition( const CATIMSHStPartition * Partition )=0;
/**
 * @nodoc
 * Retourne si la perennité de la spec ( supporte les variations topologiques )
 */
  virtual int GetPerpetuity() const=0;
/**
 * @nodoc
 * Ecrit perennité de la spec ( supporte les variations topologiques )
 */
  virtual void SetPerpetuity(int Perpetuity) =0;
/**
 * @nodoc
 */  
  virtual unsigned int GetInternalTag () const=0;
/**
 * @nodoc
 */  
  virtual void SetInternalTag (unsigned int Tag) =0;
/**
 * @nodoc
 */  
  virtual unsigned int GetExternalTag () const=0;
/**
 * @nodoc
 */  
  virtual unsigned int * GetPExternalTag () const=0;
/**
 * @nodoc
 */  
  virtual void SetExternalTag (unsigned int Tag) =0;
/**
 * @nodoc
 */  
  virtual void SetAttributesStamp (unsigned int Stamp) =0;
/**
 * @nodoc
 */  
  virtual State GetState () =0;
/**
 * @nodoc
 */  
  virtual void SetState (State) =0;
/**
 * @nodoc
 */
  virtual HRESULT ComputeState(State &StateSpec)=0;
/**
 * @nodoc
 */
  virtual HRESULT ComputeMeshState(CATMSHStMeshState &State)=0;
/**
 * @nodoc
 */
  virtual HRESULT SetCompatibility( const CATMSHStSpecCompatibility Compatibility[] ) =0;
/**
 * @nodoc
 */
  virtual const CATMSHStSpecCompatibility * GetCompatibility() const=0;
/**
 * @nodoc
 */
  virtual CATRep * BuildRep () = 0;
/**
 * @nodoc
 */  
  virtual void Dump ( CATTrace * Trace=NULL ) const=0;
/**
 * @nodoc
 * Renvoie le nom NLS
 */  
  virtual HRESULT GetName ( CATUnicodeString & Name ) =0;
/**
 * @nodoc
 */  
  virtual void DeleteAttributes () =0;
/**
 * @nodoc
 */  
  virtual HRESULT Load() =0;
/**
 * @nodoc
 */  
  virtual HRESULT LoadAttributes ( CATIMSHLocalSpecification * LocalSpec ) =0;
/**
 * @nodoc
 */  
  virtual CATIMSHStudioSpec * Clone () =0;
/**
 * @nodoc
 */  
  virtual void InvalidComputation () =0;
/**
 * @nodoc
 */  
  virtual HRESULT MigrateData ( int StreamVersion ) =0;
/**
 * @nodoc
 */  
  virtual HRESULT Remove () =0;
/**
 * @nodoc
 */
  virtual void AddInstanceListener() =0;
/**
 * @nodoc
 */
  virtual void RemoveInstanceListener() =0;
/**
 * @nodoc
 */  
  virtual void ResetSupport () =0;

};

#endif
