// COPYRIGHT DASSAULT SYSTEMES 2000
//===================================================================
//
// CatAnnotatedViewCmdOption.idl
//   This automation declaration enumerates values of interface parameter.
//
//===================================================================
//
//  Feb 2004  Creation: PVO
//
//===================================================================
#ifndef CatAnnotatedViewCmdOption_IDL
#define CatAnnotatedViewCmdOption_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

/**
 * The different behavior of annotated view command
 * @see CATIANavigatorWorkbench.


 * @param CatAnnotatedViewCmdOption_NoToolbar
 *   When Applying an annotated view, no edition toolbar will pops up
 * @param CatAnnotatedViewCmdOption_NoAnimation
 *   When Applying an annotated view, no viewpoint animation will be performed
 */
#define CatAnnotatedViewCmdOption_NoToolbar     ((short)(1 << 0))
#define CatAnnotatedViewCmdOption_NoAnimation   ((short)(1 << 1))

#endif
