// COPYRIGHT DASSAULT SYSTEMES 2000
//===================================================================
//
// CatAnnotatedViewBehavior.idl
//   This automation declaration enumerates values of interface parameter.
//
//===================================================================
//
//  Feb 2004  Creation: PVO
//
//===================================================================
#ifndef CatAnnotatedViewBehavior_IDL
#define CatAnnotatedViewBehavior_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

/**
 * The different behavior of annotated view
 * @see CATIAAnnotatedView.
 * @param CatAnnotatedViewBehaviorLink
 *   The annotated view is linked to the viewpoint.
 * @param CatAnnotatedViewBehaviorUnlink
 *   The annotated view is notlinked to the viewpoint. Viewpoint modification will not alter the annotared view.
 */
enum CatAnnotatedViewBehavior
{
  CatAnnotatedViewBehaviorLink,
  CatAnnotatedViewBehaviorUnlink
};

#endif
