
# module CATPspEditProp
BUILT_OBJECT_TYPE = SHARED LIBRARY

LINK_WITH = VE0BASE DI0PANV2 JS0FM  DI0PANV2 DI0STATE DI0GRAF DI0APPLI \
            CD0WIN CD0FRAME  CK0UNIT \
            JS0CORBA JS0SCBAK JS0STR JS0LIB0 VE0MDL NS0S3STR JS0SETT YN000M2D YN000MAT AD0XXBAS OM0EDPRO \
            AS0STARTUP AC0SPBAS \
            CATLiteralFeatures CATKnowledgeModeler \
            CATPspUIUtils  CATPspUtilities CATPspUUID \
            CATEsuUtil AECReviewItf CATAruUtilities    
 

OS = COMMON
