BUILT_OBJECT_TYPE=ARCHIVE
DELIVERABLE = NO
SRC_LINK_WITH = DSYAdmInf CATSysTS01
STATIC_LIBS = yes
ALLOW_STATIC_LINK=YES

# -D_CATSysTS_H -DExportedByCATSysTS for cpp in CATSysTS01
LOCAL_CCFLAGS= -D_DSYAdmInf_Archive_SA -D_CATSysTS_H -DExportedByCATSysTS=""

