#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
SDMRuntimeUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = KS0SIMPL

LOCAL_CCFLAGS = -DSDAI_NOSTR

LINK_LIST = CO0LSTPV CO0HTAB CO0HDICO CO0SETST JS0STR NS0S3STR AD0XXBAS AC0XXLNK
LINK_WITH=$(LINK_WITH_FOR_IID)  KS0LATE $(LINK_LIST)

OS = AIX

OS = HP-UX

OS = IRIX

OS = SunOS

OS = Windows_NT
# must allow recursive dependency
LINK_WITH=$(LINK_WITH_FOR_IID)  KS0LATE $(LINK_LIST)
