#
BUILT_OBJECT_TYPE = NONE
#

# option naturelle pas naturelle... (PR 01/04)
# ATTENTION CETTE OPTION REND INCOMPATIBLE TOUT DECODAGE D'OBJET DEFINI
# DANS UN AUTRE MODULE NON CONSTRUIT AVEC CETTE OPTION SI LES ALIGNEMENTS NATURELS
# DES DONNEES N'Y SONT PAS CORRECTS. CAS DE CATTolerance. 
# NE FAIRE DONC DANS CE MODULE AUCUN RECOURS A DES OBJETS EXTERNES
# NLD270907
OS = AIX
// 10/01/2020 JSX on requset of CQB (423 AIX Xlc 16)
#if (defined MK_IBMVAVER) && (MK_IBMVAVER < 16)
LOCAL_CCFLAGS = -q align=natural
#endif
#
OS = Windows_NT
#if os win_b64
#else
OPTIMIZATION_CPP = /O2
#endif
#
