#ifndef CATV4IV5V4AssociativityModeEnum_IDL
#define CATV4IV5V4AssociativityModeEnum_IDL
/*IDLNOGEN*/   // Prevent the IDL compiler from generating the C++ enum counterpart
               // This enum is supplied in the same folder
/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */
// COPYRIGHT DASSAULT SYSTEMES 2003
//--------------------------------------------------------------------------
// CATV4IV5V4AssociativityModeEnum Enum
//--------------------------------------------------------------------------

    /**
     * The associativity mode of migration during Save As Model.
     * @param AssociativeMode
     *   The migration is made using the associative mode.
     * @param NonAssociativeMode
     *   The migration is made using the non associative mode.
	 * @param NonAssociativityModeAndNoSolidCreation
	 *   The migration is made using the non associative mode and no solid will be created.
	 * @see CATIAV4WritingSettingAtt
     */
enum CATV4IV5V4AssociativityModeEnum{AssociativeMode, NonAssociativeMode, NonAssociativityModeAndNoSolidCreation};
#endif

