#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
Navigator2InterfacesUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID) JS0GROUP

