#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATVisUUID \
SystemUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID) CATViz JS0MRSHL JS0CORBA JS0SCBAK JS03TRA JS0STR JS0LIB0 JS0ERROR JS0FM DI0PANV2 CO0HTAB CO0LSTPV NS0S3STR YN000MFL YN000MAT YN000M2D JS0CATLM CATVisVR CATSysMultiThreading CATVisUUID SystemUUID CATSysAllocator CATVizBaseUUID CATMathStream CATVizIterators

INCLUDED_MODULES = VE0GROUP VE0MDL VE0BASE VE0PANEL CATVisLightModel CATVisIteratorsImpl CATVisColorChooser

ALIASES_ON_IMPORT=CATVisualization CATViz


OS = aix_a
LOCAL_CCFLAGS = -qfloat=hsflt 
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = aix_a64
LOCAL_CCFLAGS = -qfloat=hsflti
SYS_LIBS = -lXm -lXt -lXi -lX11
 
OS = HP-UX
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = SunOS
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = Windows_NT
SYS_LIBS = vfw32.lib wsock32.lib winmm.lib

OS = IRIX
LINK_WITH=$(LINK_WITH_FOR_IID) CATViz JS0MRSHL JS0CORBA JS0SCBAK JS03TRA JS0STR JS0LIB0 JS0ERROR JS0FM DI0PANV2 CO0HTAB CO0LSTPV NS0S3STR YN000MFL YN000MAT YN000M2D JS0CATLM CATVisVR CATSysMultiThreading CATVisUUID SystemUUID CATSysAllocator CATVisShader CATVizBaseUUID CATVizIterators 
SYS_LIBS = -lXsgivc -lXm -lXt -lX11 -lXext
LOCAL_CCFLAGS  = -float
LOCAL_CFLAGS   = -float
