BUILT_OBJECT_TYPE= NONE

#LOCAL_CCFLAGS = -DPRODSTRU_PROTO

LINK_WITH = AS0STARTUP \
    JS0SCBAK JS0CORBA JS0STR JS03TRA JS0ERROR JS0GROUP JS0LIB0\
    JS0LOGRP JS0DSPA JS0CTYP JS0COL JS0COMP JS0INF\
    AD0XXBAS AC0XXLNK  AC0SPBAS\
    ProductStructureItf InfItf KnowledgeItf\
    ON0MAIN ON0FRAME ON0PROP\
    NS0S3STR \
    Collections YN000MAT \
    CD0FRAME CD0WIN CD0STWIN CD0AUTO VE0MDL	\
    VE0BASE YN000MFL GN0NAME \
    PRDExport CATPrdEnoviaV5Interface \
	DI0APPLI DI0PANV2 CATCafAutostart CD0AUTOSTART CATScriptReplayInteractions \


#
OS = AIX

# 
OS = HP-UX

#
OS = IRIX

#
OS = SunOS

OS = Windows_NT

