// COPYRIGHT Dassault Systemes 2002
//===================================================================
//
// CATSIMParameterCharacteristics.h
// Header definition of CATSIMParameterCharacteristics
//
//===================================================================
//
// Usage notes: Class ONLY used in the Agent<->Player communication 
// protocol. It contains basic informations on a parameter.
//
//===================================================================
//
//  Apr 2002  Creation: Code generated by the CAA wizard  STV
//===================================================================
#ifndef CATSIMParameterCharacteristics_H
#define CATSIMParameterCharacteristics_H

/**
  * @CAA2Level L0
  * @CAA2Usage U3
  */


#include "SIMItfCPP.h"
#include "CATBoolean.h"
#include "CATListOfDouble.h"

//-----------------------------------------------------------------------
enum CATSIMParameterType {CATSIMDiscreet, CATSIMContinuous, CATSIMAutoControlled};
enum CATSIMLabellingMode {CATSIMNone, CATSIMExclusiveLabel, CATSIMUnitsLabel, CATSIMMagnitudeName};

/** @nodoc */
//===================================================================
//
// Object ONLY used in the Agent<->Player communication protocol.
// It contains basic informations on a parameter.
//
//===================================================================
class ExportedBySIMItfCPP CATSIMParameterCharacteristics
{
public:
    
    
    // members
    CATSIMParameterType  _ParamType;
    CATBoolean           _BackwardAbility;
    double               _StartValue;
    double               _EndValue;
    CATListOfDouble      _Steps;
    
    // Standard constructors and destructors
    // -------------------------------------
    CATSIMParameterCharacteristics ();
    virtual ~CATSIMParameterCharacteristics ();
    
    // Copy constructor and equal operator
    // -----------------------------------
    CATSIMParameterCharacteristics (CATSIMParameterCharacteristics &);
    CATSIMParameterCharacteristics& operator=(CATSIMParameterCharacteristics&);
    
};

//-----------------------------------------------------------------------

#endif
