// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CATIRdgRenderingSettingAtt.h
// Define the CATIRdgRenderingSettingAtt interface
//
//===================================================================
//
// Usage notes:
//   New interface: Interface for PHS settings access
//
//===================================================================
//
//  Dec 2003  Creation: Code generated by the CAA wizard  ego
//===================================================================
#ifndef CATIRdgRenderingSettingAtt_H
#define CATIRdgRenderingSettingAtt_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATRdgItfCPP.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATRdgItfCPP IID IID_CATIRdgRenderingSettingAtt;
#else
extern "C" const IID IID_CATIRdgRenderingSettingAtt;
#endif

class CATSettingInfo;
class CATUnicodeString;


/**
 * Interface for PHS settings access.
 */
class ExportedByCATRdgItfCPP CATIRdgRenderingSettingAtt: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    //***********************************************************************
    // Ensure consistency with the IDL interface that will delegate its work
    // Check allowed signatures in System.CATSysSettingController
    //***********************************************************************
    /**
     * Retrieves the OutputSizeFrom attribute.
     */
     virtual HRESULT GetOutputSizeFrom(int& ioOutputSizeFrom) = 0;

    /**
     * Sets the OutputSizeFrom attribute.
     */
     virtual HRESULT SetOutputSizeFrom(int iOutputSizeFrom) = 0;

    /**
     * Retrieves the state of the OutputSizeFrom parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetOutputSizeFromInfo(CATSettingInfo* oInfo) = 0;

    /** 
     * Locks or unlocks the OutputSizeFrom parameter.
     * <br><b>Role</b>: Locks or unlocks the OutputSizeFrom parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>  to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetOutputSizeFromLock(unsigned char iLocked) = 0;

    /**
     * Retrieves the OutputWidth attribute.
     */
     virtual HRESULT GetOutputWidth(int& ioOutputWidth) = 0;

    /**
     * Sets the OutputWidth attribute.
     */
     virtual HRESULT SetOutputWidth(int iOutputWidth) = 0;

    /**
     * Retrieves the state of the OutputWidth parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetOutputWidthInfo(CATSettingInfo* oInfo) = 0;

    /** 
     * Locks or unlocks the OutputWidth parameter.
     * <br><b>Role</b>: Locks or unlocks the OutputWidth parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>  to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetOutputWidthLock(unsigned char iLocked) = 0;

    /**
     * Retrieves the OutputHeight attribute.
     */
     virtual HRESULT GetOutputHeight(int& ioOutputHeight) = 0;

    /**
     * Sets the OutputHeight attribute.
     */
     virtual HRESULT SetOutputHeight(int iOutputHeight) = 0;

    /**
     * Retrieves the state of the OutputHeight parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetOutputHeightInfo(CATSettingInfo* oInfo) = 0;

    /** 
     * Locks or unlocks the OutputHeight parameter.
     * <br><b>Role</b>: Locks or unlocks the OutputHeight parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>  to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetOutputHeightLock(unsigned char iLocked) = 0;

    /**
     * Retrieves the OutputType attribute.
     */
     virtual HRESULT GetOutputType(int& ioOutputType) = 0;

    /**
     * Sets the OutputType attribute.
     */
     virtual HRESULT SetOutputType(int iOutputType) = 0;

    /**
     * Retrieves the state of the OutputType parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetOutputTypeInfo(CATSettingInfo* oInfo) = 0;

    /** 
     * Locks or unlocks the OutputType parameter.
     * <br><b>Role</b>: Locks or unlocks the OutputType parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>  to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetOutputTypeLock(unsigned char iLocked) = 0;

    /**
     * Retrieves the OutputPath attribute.
     */
     virtual HRESULT GetOutputPath(CATUnicodeString& ioOutputPath) = 0;

    /**
     * Sets the OutputPath attribute.
     */
     virtual HRESULT SetOutputPath(const CATUnicodeString& iOutputPath) = 0;

    /**
     * Retrieves the state of the OutputPath parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetOutputPathInfo(CATSettingInfo* oInfo) = 0;

    /** 
     * Locks or unlocks the OutputPath parameter.
     * <br><b>Role</b>: Locks or unlocks the OutputPath parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>  to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetOutputPathLock(unsigned char iLocked) = 0;

    /**
     * Retrieves the SaveAutoIncrement attribute.
     */
     virtual HRESULT GetSaveAutoIncrement(unsigned char& ioSaveAutoIncrement) = 0;

    /**
     * Sets the SaveAutoIncrement attribute.
     */
     virtual HRESULT SetSaveAutoIncrement(unsigned char iSaveAutoIncrement) = 0;

    /**
     * Retrieves the state of the SaveAutoIncrement parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetSaveAutoIncrementInfo(CATSettingInfo* oInfo) = 0;

    /** 
     * Locks or unlocks the SaveAutoIncrement parameter.
     * <br><b>Role</b>: Locks or unlocks the SaveAutoIncrement parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>  to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetSaveAutoIncrementLock(unsigned char iLocked) = 0;

    /**
     * Retrieves the EngineInterface attribute.
     */
     virtual HRESULT GetEngineInterface(CATUnicodeString& ioEngineInterface) = 0;

    /**
     * Sets the EngineInterface attribute.
     */
     virtual HRESULT SetEngineInterface(const CATUnicodeString& iEngineInterface) = 0;

    /**
     * Retrieves the state of the EngineInterface parameter.
     * @param oInfo
     *	Address of an object CATSettingInfo.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT GetEngineInterfaceInfo(CATSettingInfo* oInfo) = 0;

    /** 
     * Locks or unlocks the EngineInterface parameter.
     * <br><b>Role</b>: Locks or unlocks the EngineInterface parameter if the
     * operation is allowed in the current administrated environment. In user mode 
     * this method will always return E_FAIL.
     * @param iLocked
     *	the locking operation to be performed
     *	<b>Legal values</b>:
     *	<br><tt>1 :</tt>  to lock the parameter.
     * 	<br><tt>0:</tt>   to unlock the parameter.
     * @return
     *	<b>Legal values</b>:
     *	<br><tt>S_OK :</tt>   on Success
     * 	<br><tt>E_FAIL:</tt>  on failure
     */
     virtual HRESULT SetEngineInterfaceLock(unsigned char iLocked) = 0;
};

/** @nodoc */
CATDeclareHandler(CATIRdgRenderingSettingAtt,CATBaseUnknown);

#endif
