/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATGenConferencing_h
#define CATGenConferencing_h

enum CATGenConferencing {
        NetMeeting,
        Backbone
};

#endif
