/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAMacrosSettingAtt_h
#define CATIAMacrosSettingAtt_h

#include "CATCORBABoolean.h"
#include "CAT_VARIANT_BOOL.h"

#ifndef ExportedByInfPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __InfPubIDL
#define ExportedByInfPubIDL __declspec(dllexport)
#else
#define ExportedByInfPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByInfPubIDL
#endif
#endif

#include "CATBSTR.h"
#include "CATIASettingController.h"
#include "CATSafeArray.h"
#include "CATScriptLanguage.h"

extern ExportedByInfPubIDL IID IID_CATIAMacrosSettingAtt;

class ExportedByInfPubIDL CATIAMacrosSettingAtt : public CATIASettingController
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetLanguageEditor(CATScriptLanguage iLanguage, CATBSTR & oEditorPath)=0;

    virtual HRESULT __stdcall SetLanguageEditor(CATScriptLanguage iLanguage, const CATBSTR & iEditorPath)=0;

    virtual HRESULT __stdcall SetLanguageEditorLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall GetLanguageEditorInfo(CATBSTR & AdminLevel, CATBSTR & oLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall GetExternalReferences(CATSafeArrayVariant *& oReferences)=0;

    virtual HRESULT __stdcall SetExternalReferences(const CATSafeArrayVariant & iReferences)=0;

    virtual HRESULT __stdcall SetExternalReferencesLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall GetExternalReferencesInfo(CATBSTR & AdminLevel, CATBSTR & oLocked, CAT_VARIANT_BOOL & oModified)=0;

    virtual HRESULT __stdcall GetDefaultMacroLibraries(CATSafeArrayVariant *& oLibraries)=0;

    virtual HRESULT __stdcall SetDefaultMacroLibraries(const CATSafeArrayVariant & iLibraries)=0;

    virtual HRESULT __stdcall SetDefaultMacroLibrariesLock(CAT_VARIANT_BOOL iLocked)=0;

    virtual HRESULT __stdcall GetDefaultMacroLibrariesInfo(CATBSTR & AdminLevel, CATBSTR & oLocked, CAT_VARIANT_BOOL & oModified)=0;


};

CATDeclareHandler(CATIAMacrosSettingAtt, CATIASettingController);

#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "CATVariant.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
