/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATMultiSelectionMode_h
#define CATMultiSelectionMode_h

enum CATMultiSelectionMode {
        CATMonoSel,
        CATMultiSelTriggWhenSelPerf,
        CATMultiSelTriggWhenUserValidatesSelection
};

#endif
