/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatPrintQuality_h
#define CatPrintQuality_h

enum CatPrintQuality {
        catPrintQualityDraft,
        catPrintQualityLow,
        catPrintQualityMedium,
        catPrintQualityHigh,
        catPrintQualityCustom
};

#endif
