/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CatVisPropertyTypes_h
#define CatVisPropertyTypes_h

enum CatVisPropertyType {
        catVisPropertyLineType,
        catVisPropertyWidth,
        catVisPropertyColor,
        catVisPropertyOpacity
};

#endif
