# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CATToolingProIDL
# Module for compilation of the protected IDL interfaces
#======================================================================
#
#  Jun 2002  Creation: Code generated by the CAA wizard  fdm
#======================================================================
#
# NO BUILD             
#

BUILT_OBJECT_TYPE=NONE

SOURCES_PATH=ProtectedInterfaces
COMPILATION_IDL=YES

