#ifndef CATAsmConstraintSettingDefs_IDL
#define CATAsmConstraintSettingDefs_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 2004
//=================================================================
//								   
// CATAsmConstraintSettingDefs:						   
// enumerations for Constraint Assembly options
//								   
//=================================================================
// Usage notes:
//
//=================================================================

/**
* Component Paste mode.
* @param catPasteWithoutCsts
*    The component's constraints will not be recreated.
* @param catPasteWithCstOnCopy
*    The component's constraints will only be recreated after a Copy.
* @param catPasteWithCstOnCut
*    The component's constraints will only be recreated after a Cut.
* @param catPasteWithCstOnCopyAndCut
*    The component's constraints will be recreated after a Copy or a Cut.
*/
enum CatAsmPasteComponentMode	
{
  catPasteWithoutCsts,
  catPasteWithCstOnCopy,
  catPasteWithCstOnCut,
  catPasteWithCstOnCopyAndCut
};

/**
* Constraint creation mode.
* @param catUseAnyGeometry
*    The constraint can be created on any kind of geometry.
* @param catUsePublishedGeometryChildLevel
*    The constraint can only be created on geometry published on the direct child level.
* @param catUsePublishedGeometryAnyLevel
*    The constraint can only be created on geometry published on any assembly level.
*/
enum CatAsmConstraintCreationMode	
{
  catUseAnyGeometry,
  catUsePublishedGeometryChildLevel,
  catUsePublishedGeometryAnyLevel
};

/**
* Quick constraint mode.
* @param catSpecifiedOrder
*    Use the specified order.
* @param catVerifiedConstraintFirst
*    Create verified constraint first.
*/
enum CatAsmQuickConstraintMode	
{
  catSpecifiedOrder,
  catVerifiedConstraintFirst
};
/**
* Redundancy check mode.
* @param catUnChecked
*    Check for redundancy for constraint creation.
* @param catChecked
*    Does not Check for redundancy for constraint creation.
*/
enum CatAsmRedundancyMode	
{
  catUnChecked,
  catChecked
};

#endif
// CATAsmConstraintSettingDefs_IDL

