// COPYRIGHT Dassault Systemes 2004
//===================================================================
//
// CATIAsmGeneralSettingAtt.h
// Define the CATIAsmGeneralSettingAtt interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Feb 2004  Creation: Code generated by the CAA wizard  pcc
//===================================================================
#ifndef CATIAsmGeneralSettingAtt_H
#define CATIAsmGeneralSettingAtt_H

#include "CATAssemblyInterfaces.h"
#include "CATBaseUnknown.h"

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

class CATSettingInfo;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCATAssemblyInterfaces IID IID_CATIAsmGeneralSettingAtt;
#else
extern "C" const IID IID_CATIAsmGeneralSettingAtt ;
#endif

//------------------------------------------------------------------

/**  
* Interface to modify Assembly Design options.
* <b>Role</b>: This interface may be used to read 
* or modify the options of Assembly Design.
*/

class ExportedByCATAssemblyInterfaces CATIAsmGeneralSettingAtt: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
    * Update command mode.
    * The mode is used as input parameter in @href #SetAutoUpdateMode
    * and as output parameter in @href #GetAutoUpdateMode
    * @param ManualUpdate
    *    The user will need to launch the Update command.
    * @param AutomaticUpdate 
    *    The Update command will be automatically launched.
    */
    enum UpdateMode	
    {
      ManualUpdate = 0,
      AutomaticUpdate = 1
    };

    /**
    * Retrieves the automatic update option.
    * @param oAutoUpdateMode
    *	<b>Legal values</b>:
    *	<br><tt>ManualUpdate :</tt>   Manual update mode
    * <br><tt>AutomaticUpdate :</tt>   Automatic update mode 
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetAutoUpdateMode( UpdateMode & oAutoUpdateMode ) = 0;

    /**
    * Sets the automatic update option.
    * @param iAutoUpdateMode
    *	<b>Legal values</b>:
    *	<br><tt>ManualUpdate :</tt>   Manual update mode
    * <br><tt>AutomaticUpdate :</tt>   Automatic update mode 
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetAutoUpdateMode( const UpdateMode iAutoUpdateMode ) = 0;

    /**
    * Retrieves the state of the automatic update option.
    * @param oInfo
    *	Address of the @href CATSettingInfo object.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetAutoUpdateModeInfo (CATSettingInfo* oInfo)=0;

    /**  
    * Locks or unlocks the automatic update option.
    * @param iLock
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>1 :</tt>   to lock the parameter.
    * <br><tt>0 :</tt>   to unlock the parameter.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetAutoUpdateModeLock (unsigned char iLock)=0;

    /**
    * Real update status computation mode.
    * The mode is used as input parameter in @href #SetUpdateStatusMode
    * and as output parameter in @href #GetUpdateStatusMode
    * @param ManualCompute
    *    The user chooses when he want to compute the exact Update status.
    * @param AutomaticCompute 
    *    Additional data are being loaded to compute an exact Update status.
    */
    enum UpdateStatusComputeMode	
    {
      ManualCompute = 0,
      AutomaticCompute = 1
    };

    /**
    * Retrieves the update status computation option.
    * Note that this option is useful only when the Cache option is activated
    * @param oUpdateStatusMode
    *	<b>Legal values</b>:
    *	<br><tt>ManualCompute :</tt>   At open the update status is unknown
    * <br><tt>AutomaticCompute :</tt>   Additional data are being loaded at open
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetUpdateStatusMode( UpdateStatusComputeMode & oUpdateStatusMode)=0;

    /**
    * Sets the update status computation option.
    * Note that this option is useful only when the Cache option is activated
    * @param iUpdateStatusMode
    *	<b>Legal values</b>:
    *	<br><tt>ManualCompute :</tt>   At open the update status is unknown
    * <br><tt>AutomaticCompute :</tt>   Additional data are being loaded at open
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetUpdateStatusMode(const UpdateStatusComputeMode iUpdateStatusMode)=0;

    /**
    * Retrieves the state of the update status computation option.
    * @param oInfo
    *	Address of the @href CATSettingInfo object.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetUpdateStatusModeInfo (CATSettingInfo* oInfo)=0;

    /**  
    * Locks or unlocks the update status computation option.
    * @param iLock
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>1 :</tt>   to lock the parameter.
    * <br><tt>0 :</tt>   to unlock the parameter.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetUpdateStatusModeLock (unsigned char iLock)=0;

    /**
    * Option managing the implicit switch from visualization mode to design mode.
    * The mode is used as input parameter in @href #SetAutoSwitchToDesignMode
    * and as output parameter in @href #GetAutoSwitchToDesignMode
    * @param AutoSwitchUnavailable 
    *    No automatic switch to design mode.
    * @param AutoSwitchAvailable
    *    Parts are being switched to necessary design mode when needed.
    */
    enum AutoSwitchToDesignMode	
    {
      AutoSwitchAvailable = 0,
      AutoSwitchUnavailable = 1
    };

    /**
    * Retrieves the implicit switch from visualization mode to design mode option.
    * Note that this option is useful only when the Cache option is activated
    * @param oAutoSwitchToDM
    *	<b>Legal values</b>:
    * <br><tt>AutoSwitchAvailable :</tt>   Automatic switch to design mode available
    *	<br><tt>AutoSwitchUnavailable :</tt>   Automatic switch to design mode unavailable
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetAutoSwitchToDesignMode( AutoSwitchToDesignMode & oAutoSwitchToDM ) = 0;

    /**
    * Sets the implicit switch from visualization mode to design mode option.
    * Note that this option is useful only when the Cache option is activated
    * @param iAutoSwitchToDM
    *	<b>Legal values</b>:
    * <br><tt>AutoSwitchAvailable :</tt>   Automatic switch to design mode available 
    *	<br><tt>AutoSwitchUnavailable :</tt>   Automatic switch to design mode unavailable
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetAutoSwitchToDesignMode( const AutoSwitchToDesignMode iAutoSwitchToDM ) = 0;

    /**
    * Retrieves the state of the implicit switch from visualization mode to design mode option.
    * @param oInfo
    *	Address of the @href CATSettingInfo object.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetAutoSwitchToDesignModeInfo (CATSettingInfo* oInfo)=0;

    /**  
    * Locks or unlocks the implicit switch from visualization mode to design mode option.
    * @param iLock
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>1 :</tt>   to lock the parameter.
    * <br><tt>0 :</tt>   to unlock the parameter.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetAutoSwitchToDesignModeLock (unsigned char iLock)=0;

    /**
    * Option managing the extension of a move 
    * to the components involved in a FixTogether.
    * The mode is used as input parameter in @href #SetMoveWithFixTExtendMode
    * and as output parameter in @href #GetMoveWithFixTExtendMode
    * @param NeverExtendMove
    *	  Never extend move to all components involved in a FixTogether
    * @param AskIfExtendMove 
    *   Ask question to extend move to all component involved in a FixTogether
    * @param AlwaysExtendMove 
    *   always extend move to all component involved in a FixTogether
    */
    enum ExtendMoveToFixT	
    {
      NeverExtendMove = 0,
      AskIfExtendMove = 1,
      AlwaysExtendMove = 2
    };

    /**
    * Retrieves the option managing the extension of a move 
    * to the components involved in a FixTogether.
    * @param oMvFixTExtendMode
    *	<b>Legal values</b>:
    *	<br><tt>NeverExtendMove :</tt>   Never extend move to all component involved in a FixTogether
    * <br><tt>AskIfExtendMove :</tt>   Ask question to extend move to all component involved in a FixTogether
    * <br><tt>AlwaysExtendMove :</tt>   allways extend move to all component involved in a FixTogether
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetMoveWithFixTExtendMode( ExtendMoveToFixT & oMvFixTExtendMode ) = 0;

    /**
    * Sets the the option managing the extension of a move 
    * to the components involved in a FixTogether.
    * @param iMvFixTExtendMode
    *	<b>Legal values</b>:
    *	<br><tt>NeverExtendMove :</tt>   Never extend move to all component involved in a FixTogether
    * <br><tt>AskIfExtendMove :</tt>   Ask question to extend move to all component involved in a FixTogether
    * <br><tt>AlwaysExtendMove :</tt>   allways extend move to all component involved in a FixTogether
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetMoveWithFixTExtendMode( const ExtendMoveToFixT iMvFixTExtendMode ) = 0;

    /**
    * Retrieves the state of the the option managing the extension of a move 
    * to the components involved in a FixTogether.
    * @param oInfo
    *	Address of the @href CATSettingInfo object.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT GetMoveWithFixTExtendModeInfo (CATSettingInfo* oInfo)=0;

    /**  
    * Locks or unlocks the the option managing the extension of a move 
    * to the components involved in a FixTogether.
    * @param iLock
    *	the locking operation to be performed
    *	<b>Legal values</b>:
    *	<br><tt>1 :</tt>   to lock the parameter.
    * <br><tt>0 :</tt>   to unlock the parameter.
    * @return
    * <dl>
    * <dt><tt>S_OK</tt>   <dd>on success
    * <dt><tt>E_FAIL</tt> <dd>on failure
    * </dl>
    */
    virtual HRESULT SetMoveWithFixTExtendModeLock (unsigned char iLock)=0;

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
