#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATIAModelVisuUUID \
CATVisUUID \
InfInterfacesUUID \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = CSASOLID CSASCOPE
#
OS = COMMON

LINK_WITH=$(LINK_WITH_FOR_IID)  YP00IMPL YI00IMPL YN000MAT YP00TMP CO0LSTPV \
	    CO0RCDBL JS0CORBA JS0ERROR AC0XXLNK AD0XXBAS \
	    AC0CATPL AC0SPBAS JS0SCBAK CSAERROR \
	    CO0RCINT NS0S3STR JS03TRA \
            CATV4Procedural CATSolPrimUtilities CATGeometricObjectsCATIA YP00FACT\
	    V4SysB V4SysMEM V4SysENV V4SysALL\
	    CATV4epsilon BftierV5 CATV4Topology \
	    CATCdbEntity VE0MDL VI0GEVUE CATGviSubGeoLink V4ToV5 \
	    InfItf GN0GRAPH SI0BREPA SI0REPER CATVisualization CATViz \
            CSGUtilities CATCGMGeoMath CATMathStream GN0NAME
#
OS = AIX

#
OS = IRIX

#
OS = HP-UX

#
OS = SunOS

OS = Windows_NT

