#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

LINK_WITH = JS0CORBA JS0FM JS0SCBAK JS0STR JS03TRA JS0LIB0 JS0ERROR\
            AD0XXBAS AC0XXLNK VE0BASE NS0S3STR NS0S1MSG CD0WIN CD0FRAME\
            DI0STATE DI0PANV2 YN000MFL AC0SPBAS MK0LINK CATVisualization \
			CATNavigatorItf CATNavigator2Itf
