#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
LINK_WITH = JS0GROUP CORBAServerInfraUUID GW0EXIT GW0SecuMgrAccess PLMSecSSOCClientInterfaces PLMSecSSOBaseCpp


OS = Windows
LINK_WITH = JS0GROUP CORBAServerInfraUUID GW0EXIT GW0SecuMgrAccess PLMSecSSOCClientInterfaces PLMSecSSOBaseCpp

LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /GX /Od /Zi -DIT_EX_MACROS
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

OS = win_b64
LINK_WITH = JS0GROUP CORBAServerInfraUUID GW0EXIT GW0SecuMgrAccess PLMSecSSOCClientInterfaces PLMSecSSOBaseCpp

LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DWIN32 -DWIN32_LEAN_AND_MEAN \
                -MD /Od /Zi -DIT_EX_MACROS
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib 

