# Copyright Dassault Systemes Provence 1999-2012, all rights reserved
#======================================================================
# Imakefile for module DTKFauxGeoTopo.m
#======================================================================
#  Aug 2012 On ne build pas sur iOS (voir MOBILE)                   mmo
#  Jul 2004 Optimisation O2                                         amr
#  Oct 2002 plus de reference a la R9                               mmo
#  Fev 2002 Ajout des options pour le compilateur Fortran SUN en R9 mmo
#  Jan 2000 This module is in CATCurveBasedGeoOperatorsA.m          mmo
#  Nov 1999 BUILT_OBJECT_TYPE=NONE for the bigger module            mmo
#           CATCurveBasedGeoOperators.m
#  Oct 1999 Supression de link with de DTKSystem                    jfi
#  Oct 1999 Modification                                            mmo
#  Jun 1999 Creation: Code generated by the CAA wizard              jfi
#======================================================================
#

# SHARED LIBRARY sauf sur les mobiles ou on ne compile pas a cause du FORTRAN

#if os MOBILE           
BUILD=NO
#else
BUILT_OBJECT_TYPE=NONE
#endif

COMDYN_MODULE = DTKSystem

IMPACT_ON_IMPORT=YES

OS = COMMON


OS = AIX
SYS_LIBS = -lxlf -lxlf90 -lxlfpad

OS = IRIX
SYS_LIBS = -lftn

OS = Windows_NT
#if os win_b64
#else
OPTIMIZATION_CPP = /O2
#endif

OS = HP-UX
SYS_LIBS = -lf

OS = SunOS
SYS_LIBS = -lF77 -lM77

OPTIMIZATION_CPP = -xO4
OPTIMIZATION_FORTRAN = -xO4

OS = Darwin
LOCAL_LDFLAGS = -Xlinker -commons -Xlinker use_dylibs

