# COPYRIGHT DASSAULT SYSTEMES 1999
#======================================================================
# Imakefile for module SP0VVUTIL.m
#======================================================================
#
#  Feb 1999  Creation: Code generated by the CAA wizard  PMM
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP JS0FM CATApplicationFrame 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)                 \
			ApplicationFrame CATIAApplicationFrame \
			ObjectModeler                          \
			ProcessInterfaces ProcessModelerVisu   \
			ProcessModelerBase                     \
			VE0GROUP                               \
			SP0VVPPR AS0STARTUP                    \
			VE0GRPH2                               \
            DI0PANV2                               \
            CATFileMenu                            \
            YN000MFL                               \
            CATMathematics                         \
            CATProductStructureInterfaces          \
            AC0SPEXT                               \
			CATViz

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
