#ifndef _CATIASERVERSTATISTICSSETTINGATT
#define _CATIASERVERSTATISTICSSETTINGATT
/*IDLREP*/
// COPYRIGHT DASSAULT SYSTEMES 2003
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
#include "CATIABase.idl"
#include "CATVariant.idl"
#include "CATSafeArray.idl"
#include "CATIASettingController.idl"
#include "CATBSTR.idl"


/**
 * Interface for Server statistic Controler
 * <br><b>Role</b>: the server statistics controler manages the values of all or
 * only a part of the attributes available for the thematic.
 * <br>For the definitions of methods and variables common to every thematic, see the @href CATIAGeneralStatisticsSettingAtt
 */
interface  CATIAServerStatisticsSettingAtt : CATIAGeneralStatisticsSettingAtt
{


};

// Interface Name : CATIASysServerStatisticsSettingAtt
#pragma ID CATIAServerStatisticsSettingAtt "DCE:E7A22A29-82DB-43d4-A520AE3FBA7F3E32"
#pragma DUAL CATIAServerStatisticsSettingAtt

// VB Object Name : ServerStatisticsSettingAtt
#pragma ID ServerStatisticsSettingAtt "DCE:82B5EADF-ECF0-457f-8F0FDF01898AF513"
#pragma ALIAS CATIAServerStatisticsSettingAtt  ServerStatisticsSettingAtt
#endif



