#ifndef _CATIAACCESSLOGSTATISTICSSETTINGATT
#define _CATIAACCESSLOGSTATISTICSSETTINGATT
/*IDLREP*/
// COPYRIGHT DASSAULT SYSTEMES 2003
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

#include "CATIABase.idl"
#include "CATVariant.idl"
#include "CATSafeArray.idl"
#include "CATIASettingController.idl"
#include "CATBSTR.idl"


/**
 * Interface for Accesslog statistic Controler.
 * <br><b>Role</b>: the accesslog statistics controler manages the values of all or
 * only a part of the attributes available for the thematic.<b>
 * <br>For the definitions of methods and variables common to every thematic, see the @href CATIAGeneralStatisticsSettingAtt.
 */
interface  CATIAAccesslogStatisticsSettingAtt : CATIAGeneralStatisticsSettingAtt
{
};

// Interface Name : CATIASysAccesslogStatisticsSettingAtt
#pragma ID CATIAAccesslogStatisticsSettingAtt "DCE:5C5B89F2-D4AE-4e93-A128267ECA414934"
#pragma DUAL CATIAAccesslogStatisticsSettingAtt

// VB Object Name : AccesslogStatisticsSettingAtt
#pragma ID AccesslogStatisticsSettingAtt "DCE:3638411B-B20B-4464-92EAC33CA5864618"
#pragma ALIAS CATIAAccesslogStatisticsSettingAtt  AccesslogStatisticsSettingAtt
#endif



