#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ObjectModelerBaseUUID \
ObjectModelerCATSDMUUID \
ObjectModelerSDMUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = AC0CATSDM

LINK_WITH=$(LINK_WITH_FOR_IID)  CATCdbEntity AD0XXBAS AC0XXLNK AD0SDBAS AC0CATPL\
            KS0LATE KS0SIMPL KS0ROLL KS0BINA\
            JS0CORBA JS0SCBAK JS03TRA JS0SETT JS0STR\
            NS0S3STR CO0LSTPV CO0LSTST

#
OS = AIX

#
OS = HP-UX

#
OS = IRIX

#
OS = SunOS

#
OS = Windows_NT
