#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID \
CATIAApplicationFrameUUID \
CATVisUUID \
MarkerUUID \
NavigatorInterfacesUUID \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = MK0BASE

LINK_WITH=$(LINK_WITH_FOR_IID)  JS0CORBA JS0FM JS0SCBAK JS0STR JS03TRA JS0LIB0 JS0ERROR\
            AD0XXBAS AC0XXLNK VE0BASE NS0S3STR NS0S1MSG CD0WIN CD0FRAME TECHNLNK\
            DI0STATE DI0PANV2 YN000MFL AC0SPBAS CATGraphicProperties CATVisualization\
	    CATNavigatorItf CATNavigator2Itf SELECT  AS0STARTUP CATMMediaAudio CATInteractiveInterfaces\
	    CATInfInterfaces CATFileMenu MK0LINK CATMkrView XMLUtils  xmlxerces\
		CATTabletSupportBase KnowledgeItf CATLiteralFeatures CATViz CATMathStream\
		CAT3DXmlBaseServices CAT3DXmlLightBaseServices CAT3DXmlInterfaces CATLightXml CATPrt3DXmlFonts CATXMLParserItf

################
OS = HP-UX
CXX_EXCEPTION =
LOCAL_CCFLAGS = -DNATIVE_EXCEPTION


