# COPYRIGHT DASSAULT SYSTEMES 2006
#======================================================================
# Imakefile for module CATDataExchTypeLib.m
# Module for compilation of the typelib
#======================================================================
#
#  Feb 2006  Creation: Code generated by the CAA wizard  JFI
#======================================================================
#
# TYPELIB          
#

BUILT_OBJECT_TYPE=TYPELIB
BUILD_PRIORITY=4
 

LINK_WITH = InfTypeLib 
