# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module CATCCSServicesUI.m
#======================================================================
#
#  May 2001  Creation: Code generated by the CAA wizard  jcb
#  07/08/2001 : fdm; Become alone ans independant      
#  02/09/2001 : fdm; Use of CATToolingServices
#  25/10/2001 : fdm; Architecture, limitation des dependances
#  15/01/2002 : jcb; Suppression de CATGmoUtilities
#  15/05/2002 : jcb; Ajout de CATViz (mkmk-WARNING) 
#  21/06/2002 : jcb; Ajout de CK0FEAT
#  10/12/2002 : jcb; Suppression de CK0Param
#  04/02/2003 : jcb ; Diag LINK_WITH : Module [CATConstraintModeler.m], which is define as an alias, 
#                was automatically added in LINK_WITH.
#  12/11/2003 : jfi ; ajout de CK0PARAM et DI0PANV2
#  10/05/2004 : jcb ; Suppression de CATMmrAxisSystem
#======================================================================
#
# NONE
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 

LINK_WITH = \
            AC0SPBAS                \  # ObjectSpecsModeler
            AD0XXBAS                \  # ObjectModelerBase
            AdvTopoUtil					\  # Advanced Topological Operators
            AS0STARTUP              \  # ProductStructure
            BOHYBOPE                \  # TopologicalOperators
            CATAdvancedMathematics  \
            CATApplicationFrame     \  # ApplicationFrame
            CATCCSItf               \  # CATCoreCavityInterfaces 
            CATCGMGeoMath           \
            CATGitInterfaces        \  # GSMInterfaces 
            CATGmoUtilities         \  # GSMModel
            CATHealingAssistantAlgos\  # CATHealingAssistantAlgos pour CQG
            CATMathematics          \  # Mathematics
            CATMathStream           \  # Mathematics
            CATTlgServices          \  # CATToolingServices
            CATVisualization        \  # Visualization
            CATViz                  \  # Visualization
            CK0FEAT                 \  # LiteralFeatures
            KnowledgeItf            \  
            JS0FM                   \  # System
            JS0STR                  \  # System
            MecModItfCPP            \  # MecModInterfaces
            MF0STARTUP              \  # MechanicalModeler
            PrtEnv                  \  # MechanicalModelerUI
            TessAPI                 \  # Tesselation
            YI00IMPL                \  # NewTopologicalObjects
            YP00IMPL                \  # GeometricObjects
            Y30C3XGG                \  # GeometricOperators
            CK0PARAM                \
            DI0PANV2                \
            CATInteractiveInterfaces\

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
