#ifndef CATAxisSystemOriginType_IDL
#define CATAxisSystemOriginType_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1997
//=================================================================
//								   
// CATAxisSystemOriginType:						   
// The enumeration specifies if the origin point of the coordinate system 
// is defined by a geometric point or by coordinates
//								   
//=================================================================
// Fev2000 Creation                                    JMarc Gautier
//=================================================================
/**
 * Axis System Origin.
 * <br>
 * @param catAxisSystemOriginByPoint = 0
 * Specifies that the origin point is put at the position defined by a geometric point.
 * If no point si selected, the origin will be automatically put at the intersection 
 * of the lines or planes defining the axes. 
 * @param catAxisSystemOriginByCoordinates = 1
 * Specifies that the origin point must stay at the position defined by  three coordinates x,y,z. 
 */
enum CATAxisSystemOriginType	
{
	catAxisSystemOriginByPoint, 
	catAxisSystemOriginByCoordinates
};
#endif // CatAxisSystemOriginType_IDL 

