#ifndef CatConstraintRefAxis_IDL
#define CatConstraintRefAxis_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1998
//=================================================================
//								   
// CatConstraintRefAxis:						   
// enumeration specifying which axis to use as a reference for a 
// catCstTypeAxisParallel or catCstTypeAxisPerpendicular constraint
// type
//								   
//=================================================================
// Jan 98  Creation                                    JJ Auffret 
//=================================================================
/**
 * Constraint reference axis.
 * <br>
 * Constraints that specify parallelism or perpendicularity to an 
 * axis in 3D are mono-element constraints. The axis to which the 
 * constraint applies is determined by the constraint property 
 * <tt>ReferenceAxis</tt>. This enum lists appropriate values to 
 * set this property.  
 * @param catCstRefAxisX
 *    The constraint applies to the X axis.
 *
 * @param catCstRefAxisY
 *    The constraint applies to the Y axis.
 *
 * @param catCstRefAxisZ
 *    The constraint applies to the Z axis.
 *
 */
enum CatConstraintRefAxis	
{
	catCstRefAxisX, 
	catCstRefAxisY,
        catCstRefAxisZ
};

#endif // CatConstraintRefAxis_IDL 

