#ifndef CatConstraintDistDirection_IDL
#define CatConstraintDistDirection_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

//=================================================================
// COPYRIGHT DASSAULT SYSTEMES 1998
//=================================================================
//								   
// CatConstraintDistDirection			
//  
// enumeration used, for catCstTypeDistance constraints only,
// to specify along which direction the distance is measured.
//
// If no direction is specified, the distance is the usual 
// minimum distance.
//								   
//=================================================================
// Nov 98  Creation                                    JMarc Gautier 
//=================================================================
/**
 * Constraint distance direction.
 * <br>
 * <tt>DistanceDirection</tt>. This enum lists the appropriate values to 
 * set this property.
 *
 * @param catCstDistDirectionNone
 *    No direction has been specified.
 *    The constraint is measured as usual.
 *
 * @param catCstDistDirection1
 *    2D : The constraint is measured along the horizontal axis.   
 *    3D : The constraint is measured along the X axis.
 *    
 * @param catCstDistDirection2
 *    2D : The constraint is measured along the vertical axis.
 *    3D : The constraint is measured along the Y axis.
 *
 * @param catCstDistDirection3
 *    3D : The constraint is measured along the Z axis.
 *
 */
enum CatConstraintDistDirection	
{
	catCstDistDirectionNone,
	catCstDistDirection1, 
	catCstDistDirection2,
    catCstDistDirection3
};

#endif

