#include "CATIAV5Level.h"
//#ifdef CATIAV5R9
#ifndef CATIAZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex_IDL
#define CATIAZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
// COPYRIGHT DASSAULT SYSTEMES 2002
//--------------------------------------------------------------------------
// ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex Object
// bpt - 02/2002
//--------------------------------------------------------------------------

#include "CATIAVertex.idl"
#include "CATBSTR.idl"

/**
 * 0-D boundary beeing either an isolated point or the extremity of a feature whose topological result is one dimensional.
 * <b>Role</b>: 
 * This @href CATIABoundary object may be, for example, the extremity of a line segment.</br> 
 * You will create a ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex object using the @href CATIAShapes#GetBoundary , 
 * @href CATIAHybridShapes#GetBoundary , @href CATIASketches#GetBoundary or @href CATIASelection#SelectElement2 method. 
 * Then, you pass it to the operator.</br> 
 * The lifetime of a ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex object is limited, see @href CATIABoundary.</br> 
 */ 

interface CATIAZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex : CATIAVertex
{

};

// Interface Name : CATIAZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex

#pragma ID CATIAZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex "DCE:42e70ce0-2c61-11d6-80650010b5d44ab2"
#pragma DUAL CATIAZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex

// VB Object Name : ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex
#pragma ID ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex "DCE:17db4710-1be8-11d6-80600010b5d44ab2"
#pragma ALIAS CATIAZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex

#endif
//#endif

