// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CATIMmiBRepAttributeSynchronize.h
// Define the CATIMmiBRepAttributeSynchronize interface
//
//===================================================================
//
// Usage notes:
//   New interface: Interface used to synchronize BRep attributes and colors for a import
//
//===================================================================
//
//  May 2005  Creation: Code generated by the CAA wizard  gdp
//===================================================================
#ifndef CATIMmiBRepAttributeSynchronize_H
#define CATIMmiBRepAttributeSynchronize_H

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
#include "MecModItfCPP.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByMecModItfCPP IID IID_CATIMmiBRepAttributeSynchronize;
#else
extern "C" const IID IID_CATIMmiBRepAttributeSynchronize ;
#endif

/**
 * Interface to synchronize attributes that have been copied on the Import Feature.
 * <b>Role</b>: This interface allows to synchronize BRep attributes.
 * It is implemented by external references of a Part document (Features issued from a Copy As Result With Link).
 * See @href CATIPersistentSubElement interface for more informations about those attributes.
 *
*/
class ExportedByMecModItfCPP CATIMmiBRepAttributeSynchronize: public CATBaseUnknown
{
  CATDeclareInterface;

  public:
   /**
		* Returns the synchronized status of the BRep attributes.
		* @param oStatus
		*  integer.
		*   <br><b>legal values</b>: 
		*   <ul><li><b>0</b> the BRep attributes are not synchronized
		*   <li><b>1</b> the BRep attributes are synchronized.</ul>
		* @return
 *   The error code.
 *   <br><b>Legal values</b>: <ul>
 *   <li><tt>S_OK</tt>: The status is retrieved </li>
 *   <li><tt>E_FAIL</tt>: The status could not be accessed.</li></ul>
		*/
		virtual HRESULT GetBRepAttributeStatus(int* oStatus) const = 0 ;

	 /**
    * Synchronizes the BRep attributes.
    * @return
		*   The error code.
		*   <br><b>Legal values</b>: <ul>
		*   <li><tt>S_OK</tt>: The synchronization has been performed </li>
		*   <li><tt>E_FAIL</tt>: The synchronization could not be performed. The method can return a @href CATError class,
		*   that you retrieve thanks the @href CATError#CATGetLastError global function. The possible case of error are:
		* <ul>
		*   <li><tt>AttributesERR_1001</tt>: The imported feature is deactivated.</li></ul>
		* <ul>
		*   <li><tt>AttributesERR_1002</tt>: The referenced feature is deactivated.</li></ul>
		* <ul>
		*   <li><tt>AttributesERR_1003</tt>: The referenced feature has no domains.</li></ul>
		* </ul>
    */
		virtual HRESULT SynchronizeBRepAttributes() const = 0;
  
};

CATDeclareHandler(CATIMmiBRepAttributeSynchronize,CATBaseUnknown);
//------------------------------------------------------------------

#endif
