#include "CATIAV5Level.h"
//#ifdef CATIAV5R9
#ifndef CATIARectilinearTriDimFeatEdge_IDL
#define CATIARectilinearTriDimFeatEdge_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
// COPYRIGHT DASSAULT SYSTEMES 2002
//--------------------------------------------------------------------------
// RectilinearTriDimFeatEdge Object
// bpt - 02/2002
//--------------------------------------------------------------------------

#include "CATIATriDimFeatEdge.idl" 
#include "CATSafeArray.idl"
#include "CATBSTR.idl"

/**
 * 1-D boundary belonging to a feature whose topological result is three dimensional, the boundary having a rectilinear geometry.
 * <b>Role</b>: 
 * This @href CATIABoundary object may be, for example, the edge of a Pad resulting from the extrusion of a square.</br> 
 * You will create a RectilinearTriDimFeatEdge object using the @href CATIAShapes#GetBoundary , @href CATIAHybridShapes#GetBoundary , 
 * @href CATIASketches#GetBoundary or @href CATIASelection#SelectElement2 method. Then, you pass it
 * to the operator (such as @href CATIAHole#SetDirection ).</br> 
 * The lifetime of a RectilinearTriDimFeatEdge object is limited, see @href CATIABoundary.</br> 
 * <! @sample>
 * <dl>
 * <dt><b>Example:</b>
 * <dd>
 * This example asks the end user to select a face, a rectilinear edge, and creates a hole.
 * The rectilinear edge specifies the hole direction. It may be a RectilinearTriDimFeatEdge, a RectilinearBiDimFeatEdge
 * or a RectilinearMonoDimFeatEdge.
 * <pre>
 * Dim EnabledObjectSelection1(0)
 * Dim EnabledObjectSelection2(2)
 * Set Document = CATIA.ActiveDocument
 * Set Selection = Document.Selection
 * 'We propose to the user that he select a face
 * EnabledObjectSelection1(0)="Face"
 * Status=Selection.SelectElement2(EnabledObjectSelection1,"Select a face",true)
 * if (Status = "cancel") then Exit Sub
 * Set Face = Selection.Item(1).Value
 * Selection.Clear
 * 'We propose to the user that he select the hole direction
 * EnabledObjectSelection2(0)="RectilinearTriDimFeatEdge"
 * EnabledObjectSelection2(1)="RectilinearBiDimFeatEdge"
 * EnabledObjectSelection2(2)="RectilinearMonoDimFeatEdge"
 * Status=Selection.SelectElement2(EnabledObjectSelection2,"Select the hole direction",true)
 * if (Status = "cancel") then Exit Sub
 * Set Hole = ShapeFactory.AddNewHoleFromPoint(20.0,-5.5, 1.07,Face,10.0)
 * Hole.ThreadingMode = 1
 * Hole.ThreadSide = 0
 * Hole.SetDirection Selection.Item(1).Value
 * Document.Part.Update 
 * </pre>
 * </dl>
 */ 

interface CATIARectilinearTriDimFeatEdge : CATIATriDimFeatEdge
{
  /**
    * Returns the origin of the the rectilinear edge. 	
    *   @param oOrigin[0]
    *   The X Coordinate of the rectilinear edge origin
    *   @param oOrigin[1]
    *   The Y Coordinate of the rectilinear edge origin
    *   @param oOrigin[2]
    *   The Z Coordinate of the rectilinear edge origin
    */
  HRESULT GetOrigin (inout  CATSafeArrayVariant oOrigin);

  /**
    *  Returns the direction of the rectilinear edge
    *   @param oDirection[0]
    *   The X Coordinate of the direction
    *   @param oDirection[1]
    *   The Y Coordinate of the direction
    *   @param oDirection[2]
    *   The Z Coordinate of the direction
    */ 
  HRESULT GetDirection (inout  CATSafeArrayVariant oDirection);
};

// Interface Name : CATIARectilinearTriDimFeatEdge

#pragma ID CATIARectilinearTriDimFeatEdge "DCE:339f6470-31f1-11d6-80660010b5d44ab2"
#pragma DUAL CATIARectilinearTriDimFeatEdge

// VB Object Name : RectilinearTriDimFeatEdge
#pragma ID RectilinearTriDimFeatEdge "DCE:5f3e92b0-31f1-11d6-80660010b5d44ab2"
#pragma ALIAS CATIARectilinearTriDimFeatEdge RectilinearTriDimFeatEdge

#endif
//#endif

