#ifndef _CATIMmDecodeSubElem_h
#define _CATIMmDecodeSubElem_h

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

// COPYRIGHT DASSAULT SYSTEMES 2000

#include "IUnknown.h"
class CATIBRepAccess;
#include "CATLISTV_CATISpecObject.h"

extern "C" const IID IID_CATIMmDecodeSubElem;

/**
 * Interface to find the sub-elements that generate a given result.
 */
class CATIMmDecodeSubElem : public IUnknown
{
public:
  /**
   * Gets the list of sub-elements that specifically generates the give BRep.
   * @param iBRep
   * The CATIBRepAccess generated by the sub-element that is seeked.
   * @param oSpecs
   * The list of specifications that generate the given BRep.
   * <br>The list is allocated by the caller and filled by the callee.
   */
  virtual HRESULT GetSpecificFeatures(CATIBRepAccess *iBRep, CATLISTV(CATISpecObject_var) *oSpecs) = 0;

  /**
  * Gets the list of CATIBRepAccess corresponding to Sketch sub-elements.
  * @param iSpec  
  * The iSpec is a sub-element specification of sketch.
  * @param oBReps
  * The list of CATIBRepAccess corresponding to Sketch sub-elements.
  * <br>The list is allocated by the caller and filled by the callee.
  */
  virtual HRESULT GetSpecificBRepAccess(CATISpecObject *iSpec, CATListValCATBaseUnknown_var *oBReps) =0;
};

#endif
