// COPYRIGHT Dassault Systemes 2004
//===================================================================
//
// CATIMfIntersectApplicativeResolution.h
// Define the CATIMfIntersectApplicativeResolution interface
//
//===================================================================
//  Jan 2005  Creation: Code generated by the CAA wizard  PWE
//===================================================================
#ifndef CATIMfIntersectApplicativeResolution_H
#define CATIMfIntersectApplicativeResolution_H

/**
 * @CAA2Level L1
 * @CAA2Usage U5
 */

#include "MecModItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATLISTV_CATISpecObject.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByMecModItfCPP IID IID_CATIMfIntersectApplicativeResolution;
#else
extern "C" const IID IID_CATIMfIntersectApplicativeResolution ;
#endif

//------------------------------------------------------------------
/**
 * Interface to allow applicative CATCells computing related to an IntersectionEdge.
 * <b>Role</b>:This interface allows to manage specific ways to compute the list of edges
 * corresponding to the intersection of two lists of features.
 * This interface is in relationship with the @href CATIMfIntersectionEdge interface. It is invoked only when the 
 * <tt>CATMfResolutionMode</tt> attribute of the intersection edge BRep feature is set to
 * <tt>MfResolutionMode_Application</tt>.
 * <p>Together, the <tt>CATIMfIntersectionEdge</tt> feature has stored a provided feature
 * that implements <tt>CATIMfIntersectApplicativeResolution</tt> interface. This feature is then 
 * internally used when the @href CATIMfBRep#GetCells method is called to get the result edges 
 * of the intersection edge BRep feature.
 * <p>This interface should not be directly used by application. You have to implement it on
 * a startup feature and to provide an instance of this feature to the intersection edge with
 * the @href CATIMfIntersectionEdge#SetResolveMode method.
 */
class ExportedByMecModItfCPP CATIMfIntersectApplicativeResolution: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

  /**
   * Computes a list of intersection edges from the two lists of features. 
 * @param iFirstOperands
 * The first list of features.
 * @param iSecondOperands
 * The second list of features.
 * @param iResolveFeature
 * The feature owning the body ( @href CATBody ) on which the edges are searched.
 * @param oEdges
 * The edges (  @href CATCell ) corresponding to the applicative rules.
 */       
   virtual HRESULT GetResolutionEdges ( CATLISTV(CATISpecObject_var)& iFirstOperands, 
                            CATLISTV(CATISpecObject_var)& iSecondOperands, CATISpecObject_var& iResolveFeature,
                                                                         CATLISTV(CATBaseUnknown_var) & oEdges ) = 0 ;
};

CATDeclareHandler( CATIMfIntersectApplicativeResolution, CATBaseUnknown) ;
//------------------------------------------------------------------
#endif
