/**
 * @CAA2Level L0
 * @CAA2Usage U3
 */
// COPYRIGHT Dassault Systemes 2008
//===================================================================
//
// CATIMmiPartInfrastructureSettingAtt2.h
// Define the CATIMmiPartInfrastructureSettingAtt2 interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2008  Creation: Code generated by the CAA wizard  gdp
//===================================================================
#ifndef CATIMmiPartInfrastructureSettingAtt2_H
#define CATIMmiPartInfrastructureSettingAtt2_H

#include "MecModItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATIAV5Level.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByMecModItfCPP IID IID_CATIMmiPartInfrastructureSettingAtt2;
#else
extern "C" const IID IID_CATIMmiPartInfrastructureSettingAtt2 ;
#endif

class CATSettingInfo;

//------------------------------------------------------------------

/**
 * Interface to retrieve application parameters related to Part Infrastructure.
 * <b>Role:</b>This interface describes all the application parameters related 
 * to Part infrastructure, as displayed in Tools/Options.
 * <br/>Here under is an example on how to retrieve a pointer to this interface:
 * <code><pre>
 * #include "CATInstantiateComponent.h" //System
 * #include "CATIMmiPartInfrastructureSettingAtt.h"  //MecModInterfaces
 * { 
 *  ...
 *   CATIMmiPartInfrastructureSettingAtt *pIGetController=NULL;
 *   if(SUCCEEDED(::CATInstantiateComponent("CATMmuPartInfrastructureSettingCtrl", IID_CATIMmiPartInfrastructureSettingAtt,(void**)&pIGetController)))
 *     {
 *      <b>//insert your code here</b>
 *      pIGetController->Release(); pIGetController=NULL;
 *     }
 *   ...
 * }
 * </pre></code> 
*/
class ExportedByMecModItfCPP CATIMmiPartInfrastructureSettingAtt2: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
   * Retrieves the "ColorSynchronizationEditability" parameter's value.
   * <br/><b>Role:</b> This parameter determines whether Part editability for syanchornization is available or not for user.
   * <br/>Color synchronization editability defines whether the imported feature synchronization mode can be edited through Color Management
   * tab on Part Properties, or not.
   * If it is defined to 0, it will not be editable.
   * This option can be changed after a document has been opened.
   * @param oColorSynchronizationEditability
   *   Current "oColorSynchronizationEditability" parameter's value:
   *      <ul><li>TRUE or 1 if Color management tab for synchronization is editable</li>
   *      <li>FALSE or 0 otherwise.</li></ul>
   * @return
   *   S_OK if the parameter is correctly retrieved, E_FAIL otherwise.
   */
  virtual HRESULT GetColorSynchronizationEditability(CATBoolean& oColorSynchronizationEditability) = 0;
    
     
  /**
   * Retrieves the state of the "ColorSynchronizationEditability" parameter.
   * @param oInfo
   *	Address of an object CATSettingInfo.
   * @return
   *	<b>Legal values</b>:
   *	<br><tt>S_OK :</tt>   on success
   * 	<br><tt>E_FAIL:</tt>  on failure
   */
  virtual HRESULT GetColorSynchronizationEditabilityInfo( CATSettingInfo*    oInfo ) = 0;

#ifdef CATIAV5R25
  /**
   * Retrieves the "DefaultColorsEditability" parameter's value.
   * <br/><b>Role:</b> This parameter determines whether Part editability for syanchornization is available or not for user.
   * <br/>Color synchronization editability defines whether the imported feature synchronization mode can be edited through Color Management
   * tab on Part Properties, or not.
   * If it is defined to 0, it will not be editable.
   * This option can be changed after a document has been opened.
   * @param oDefaultColorsEditability
   *   Current "oDefaultColorsEditability" parameter's value:
   *      <ul><li>TRUE or 1 if Color management tab for synchronization is editable</li>
   *      <li>FALSE or 0 otherwise.</li></ul>
   * @return
   *   S_OK if the parameter is correctly retrieved, E_FAIL otherwise.
   */
  virtual HRESULT GetDefaultColorsEditability(CATBoolean& oDefaultColorsEditability) = 0;
    
     
  /**
   * Retrieves the state of the "DefaultColorsEditability" parameter.
   * @param oInfo
   *	Address of an object CATSettingInfo.
   * @return
   *	<b>Legal values</b>:
   *	<br><tt>S_OK :</tt>   on success
   * 	<br><tt>E_FAIL:</tt>  on failure
   */
  virtual HRESULT GetDefaultColorsEditabilityInfo( CATSettingInfo*    oInfo ) = 0;

  /**
   * Retrieves the "Colors3DExperienceManagement" parameter's value.
   * <br/><b>Role:</b> This parameter determines whether Part editability for syanchornization is available or not for user.
   * <br/>Color synchronization editability defines whether the imported feature synchronization mode can be edited through Color Management
   * tab on Part Properties, or not.
   * If it is defined to 0, it will not be editable.
   * This option can be changed after a document has been opened.
   * @param oColors3DExperienceManagement
   *   Current "oColors3DExperienceManagement" parameter's value:
   *      <ul><li>TRUE or 1 if Color management tab for synchronization is editable</li>
   *      <li>FALSE or 0 otherwise.</li></ul>
   * @return
   *   S_OK if the parameter is correctly retrieved, E_FAIL otherwise.
   */
  virtual HRESULT GetColors3DExperienceManagement(CATBoolean& oColors3DExperienceManagement) = 0;
    
     
  /**
   * Retrieves the state of the "Colors3DExperienceManagement" parameter.
   * @param oInfo
   *	Address of an object CATSettingInfo.
   * @return
   *	<b>Legal values</b>:
   *	<br><tt>S_OK :</tt>   on success
   * 	<br><tt>E_FAIL:</tt>  on failure
   */
  virtual HRESULT GetColors3DExperienceManagementInfo( CATSettingInfo*    oInfo ) = 0;
#endif
};

//------------------------------------------------------------------

#endif
