#include "CATIAV5Level.h"
//#ifdef CATIAV5R9
#ifndef CATIAMonoDimFeatEdge_IDL
#define CATIAMonoDimFeatEdge_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */
// COPYRIGHT DASSAULT SYSTEMES 2002
//--------------------------------------------------------------------------
// MonoDimFeatEdge Object
// bpt - 02/2002
//--------------------------------------------------------------------------

#include "CATIAEdge.idl"
#include "CATBSTR.idl"

/**
 * 1-D boundary belonging to a feature whose topological result is one dimensional.
 * <b>Role</b>:
 * This @href CATIABoundary object may be, for example, in a part containing a Sketch which is made up of a circle
 * arc and a spline, the circle arc.</br> 
 * You will create a MonoDimFeatEdge object using the @href CATIAShapes#GetBoundary , @href CATIAHybridShapes#GetBoundary , 
 * @href CATIASketches#GetBoundary or @href CATIASelection#SelectElement2 method. Then, you pass it
 * to the operator (such as @href CATIAHybridShapeFactory#AddNewPointTangent ).</br> 
 * The lifetime of a MonoDimFeatEdge object is limited, see @href CATIABoundary.</br> 
 */ 

interface CATIAMonoDimFeatEdge : CATIAEdge
{

};

// Interface Name : CATIAMonoDimFeatEdge

#pragma ID CATIAMonoDimFeatEdge "DCE:4092e5b0-1be1-11d6-80600010b5d44ab2"
#pragma DUAL CATIAMonoDimFeatEdge

// VB Object Name : MonoDimFeatEdge
#pragma ID MonoDimFeatEdge "DCE:e4a8f7e0-1be7-11d6-80600010b5d44ab2"
#pragma ALIAS CATIAMonoDimFeatEdge MonoDimFeatEdge

#endif
//#endif

