# 
BUILT_OBJECT_TYPE =NONE

LINK_WITH = CATVizBase VE0BASE JS0CORBA JS0SCBAK JS03TRA JS0INF InfItfCPP
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION

OS = SunOS
LOCAL_CFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS
