# COPYRIGHT Dassault Systemes 2004
#======================================================================
# Imakefile for module CATFLXCableInterfacesUUID.m
#======================================================================
#
#  May 2004  Creation: Code generated by the CAA wizard  ccc
#======================================================================
#
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE

