#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=NONE

OS = aix_a
LOCAL_CCFLAGS = -qfloat=hsflt  -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXt -lXi -lX11

OS = aix_a64
LOCAL_CCFLAGS = -qfloat=hsflt -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = HP-UX
LOCAL_CCFLAGS = -I/opt/graphics/OpenGL/include -DCATVIZ_SPECIFICATION
SYS_LIBS = -lXm -lXt -lXi -lX11

OS = IRIX
SYS_LIBS = -lXm -lXt -lX11 -lXext
LOCAL_CCFLAGS  = -float -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS   = -float

OS = SunOS
OPTIMIZATION_CPP = -xO4
SYS_LIBS = -lXm -lXt -lXi -lX11
LOCAL_CFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION #-DMOTIF12_HEADERS -xlibmil

## @linux mcf 2004-05-13.11:14:31 [Linux support] ##
OS = Linux
SYS_LIBS = -lXm -lXt -lXi -lX11
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION

OS = Windows
SYS_LIBS = vfw32.lib wsock32.lib winmm.lib
LOCAL_CCFLAGS = -D_WNT40I_SOURCE -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  = -D_WNT40I_SOURCE
# For official CATV5PrecompiledHeader.h to include afxwin.h :
MKMFC_DEPENDENCY = yes
