#
BUILT_OBJECT_TYPE=LOAD MODULE

LINK_WITH = WFTOCTools CXINSTUTIL CATDlgStandard  DI0PANV2 JS0SCBAK JS0CORBA JS0FM JS0STR JS0ERROR NS0S3STR NS0S1MSG

OS = SunOS
SYS_LIBS = -lXm


OS = Windows_NT
LOCAL_LDFLAGS=$(SUB_WIN)
MKMFC_DEPENDENCY=Yes 
SYS_LIBS =  winmm.lib
