#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID \
FileMenuUUID \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

INCLUDED_MODULES =	AC0DLNAME

					

LINK_WITH=$(LINK_WITH_FOR_IID) $(LINK_WITH_SPECIFICS) JS0CORBA JS0ERROR JS0SCBAK JS0FM JS0STR JS0SETT JS03TRA JS0LIB0\
	    JS0DSPA JS0LOGRP JS0CTYP InfItf JS0INF\
            AD0XXBAS AC0XXLNK CP0CLIP\
            NS0S3STR\
            CO0LSTPV CO0LSTST CO0RCINT\
            DI0PANV2 AC0DLNAME\
            CD0FRAME CD0WIN CD0SCCP\
            DI0STATE DI0GRAF DI0APPLI\
	    VE0MDL\
	    NS0S1MSG ON0FRAME CATPrint CATDlgStandard\
		CATInteractiveInterfaces\
		ApplicationFrame\
        CATPrt\
		CATFileMenu \
		CATSysFile CATViz



SH_LINK_WITH= $(LINK_WITH)

LINK_WITH_SPECIFICS=

OS = Windows_NT
LINK_WITH_SPECIFICS = JS0SMT
