#
BUILT_OBJECT_TYPE = SHARED LIBRARY
#

LINK_WITH = CATAfrLicensing GW0COMUN orbix JS0CATLM CATCsbCORBA
CATCsbCORBA = SERVER


OS = AIX
LOCAL_CCFLAGS = -D_AIX_SOURCE -DNATIVE_EXCEPTION
CXX_EXCEPTION = 
SYS_INCPATH =
SYS_LIBPATH = 
LOCAL_LDFLAGS = -brtl

OS = HP-UX
LOCAL_CCFLAGS = -D_HPUX_SOURCE -D_REENTRANT -DNATIVE_EXCEPTION
SYS_INCPATH = 
SYS_LIBPATH = 
CXX_EXCEPTION = 
# shared lib non multithreadee ORBIXS

OS = IRIX
LOCAL_CCFLAGS = -D_IRIX_SOURCE -DNATIVE_EXCEPTION
LOCAL_LDFLAGS = 
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
#shared lib non multithreadee ORBIXS
SYS_LIBS =  -lCsup


OS = SunOS
LOCAL_CCFLAGS = -D_SUNOS_SOURCE -DNATIVE_EXCEPTION
CXX_EXCEPTION = 
SYS_INCPATH = 
SYS_LIBPATH = 
#shared lib non multithreadee ORBIXS

OS = intel_a
#BUILD=NO
LINK_WITH = ITMi GW0COMUN LicensingFR JS0CATLM CATCsbCORBA
CATCsbCORBA = SERVER
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DWIN32 -DIT_EX_MACROS
CXX_EXCEPTION = 

OS = win_b
#BUILD=NO
LINK_WITH = ITMi GW0COMUN LicensingFR JS0CATLM CATCsbCORBA
CATCsbCORBA = SERVER
SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DWIN32 -DIT_EX_MACROS
CXX_EXCEPTION = 

OS = win_b64
#BUILD=NO
LINK_WITH = ITMi GW0COMUN LicensingFR JS0CATLM CATCsbCORBA
CATCsbCORBA = SERVER
#SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DIT_EX_MACROS
CXX_EXCEPTION = 

OS = alpha_a
BUILD=NO
BUILD = NO



OS = win_a
#BUILD=NO
LINK_WITH = ITMi GW0COMUN LicensingFR JS0CATLM CATCsbCORBA
CATCsbCORBA = SERVER

SYS_LIBS = Wsock32.LIB advapi32.lib user32.lib
LOCAL_CCFLAGS = -D_WINDOWS_SOURCE -DORBIX_DLL -DWIN32 -DIT_EX_MACROS
CXX_EXCEPTION = 


