#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATAfrUUID \
CATVisUUID \
NavigatorInterfacesUUID \
ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

ALIASES_ON_IMPORT=CATDMUModel CATDMUWind

LINK_WITH=$(LINK_WITH_FOR_IID)  JS0CORBA JS0FM JS0SCBAK JS0STR JS0ERROR\
            AD0XXBAS NS0S3STR NS0S1MSG CD0FRAME DI0PANV2\
            VE0BASE YN000MFL AC0SPBAS\
            ON0FRAME CD0STWIN CD0SHOW  ON0FRAME AS0STARTUP\
            CATNavigatorItf CATInfInterfaces\
            ON0GRAPH CATSimulationBase CATGraphicProperties \
            CATViz CATMathStream CATNavigator2Itf CATDMUBase CATDMUWind
