/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAPspStretchableData_h
#define CATIAPspStretchableData_h

#ifndef ExportedByCATPspPlantShipPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATPspPlantShipPubIDL
#define ExportedByCATPspPlantShipPubIDL __declspec(dllexport)
#else
#define ExportedByCATPspPlantShipPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATPspPlantShipPubIDL
#endif
#endif

#include "CATIABase.h"

class CATIAProduct;
class CATIAPspListOfDoubles;

extern ExportedByCATPspPlantShipPubIDL IID IID_CATIAPspStretchableData;

class ExportedByCATPspPlantShipPubIDL CATIAPspStretchableData : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall ListDefinitionPoints(CATIAProduct * iRelAxis, CATIAPspListOfDoubles *& oListPoints)=0;

    virtual HRESULT __stdcall ListBendData(CATIAPspListOfDoubles *& oListOfBendRadius)=0;


};

CATDeclareHandler(CATIAPspStretchableData, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIAAnalyze.h"
#include "CATIACollection.h"
#include "CATIAMove.h"
#include "CATIAParameters.h"
#include "CATIAPosition.h"
#include "CATIAProduct.h"
#include "CATIAPublications.h"
#include "CATSafeArray.h"
#include "CATVariant.h"
#include "CatFileType.h"
#include "CatProductSource.h"
#include "CatRepType.h"
#include "CatWorkModeType.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
