/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAPspPartConnector_h
#define CATIAPspPartConnector_h

#ifndef ExportedByCATPspPlantShipPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATPspPlantShipPubIDL
#define ExportedByCATPspPlantShipPubIDL __declspec(dllexport)
#else
#define ExportedByCATPspPlantShipPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATPspPlantShipPubIDL
#endif
#endif

#include "CATIABase.h"
#include "CatPspIDLPartConnectorType.h"

class CATIAProduct;
class CATIAPspListOfBSTRs;
class CATIAPspListOfDoubles;
class CATIAReference;

extern ExportedByCATPspPlantShipPubIDL IID IID_CATIAPspPartConnector;

class ExportedByCATPspPlantShipPubIDL CATIAPspPartConnector : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall GetFaceConnector(CATIAReference *& oCntr)=0;

    virtual HRESULT __stdcall SetFaceConnector(CATIAReference * iFaceCntr, CatPspIDLPartConnectorType ieFaceType)=0;

    virtual HRESULT __stdcall GetAlignmentConnector(CATIAReference *& oCntr)=0;

    virtual HRESULT __stdcall SetAlignmentConnector(CATIAReference * iAlignCntr, CatPspIDLPartConnectorType ieAlignType)=0;

    virtual HRESULT __stdcall GetOrientationConnector(CATIAReference *& oCntr)=0;

    virtual HRESULT __stdcall SetOrientationConnector(CATIAReference * iOrientCntr, CatPspIDLPartConnectorType ieOrientation)=0;

    virtual HRESULT __stdcall GetDatumConnector(CATIAReference *& oCntr)=0;

    virtual HRESULT __stdcall SetDatumConnector(CATIAReference * iDatumCntr)=0;

    virtual HRESULT __stdcall GetPosition(CATIAProduct * iRelAxis, CATIAPspListOfDoubles *& oPosition)=0;

    virtual HRESULT __stdcall GetAlignmentDirection(CATIAProduct * iRelAxis, CATIAPspListOfDoubles *& oAlignmentDirection)=0;

    virtual HRESULT __stdcall GetConnectorMathPlane(CATIAProduct * iRelAxis, CATIAPspListOfDoubles *& oMathPlane)=0;

    virtual HRESULT __stdcall GetUpDirection(CATIAProduct * iRelAxis, CATIAPspListOfDoubles *& oUpDirection)=0;

    virtual HRESULT __stdcall get_FaceType(CatPspIDLPartConnectorType & oFaceType)=0;

    virtual HRESULT __stdcall get_AlignType(CatPspIDLPartConnectorType & oAlignType)=0;

    virtual HRESULT __stdcall get_ClockType(CatPspIDLPartConnectorType & oClockType)=0;

    virtual HRESULT __stdcall get_AttributeNames(CATIAPspListOfBSTRs *& oLAttributeNames)=0;

    virtual HRESULT __stdcall put_AttributeNames(CATIAPspListOfBSTRs * iLAttributeNames)=0;


};

CATDeclareHandler(CATIAPspPartConnector, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIAAnalyze.h"
#include "CATIACollection.h"
#include "CATIAMove.h"
#include "CATIAParameters.h"
#include "CATIAPosition.h"
#include "CATIAProduct.h"
#include "CATIAPspListOfBSTRs.h"
#include "CATIAPublications.h"
#include "CATIAReference.h"
#include "CATSafeArray.h"
#include "CATVariant.h"
#include "CatFileType.h"
#include "CatProductSource.h"
#include "CatRepType.h"
#include "CatWorkModeType.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
