/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIAPspListOfDoubles_h
#define CATIAPspListOfDoubles_h

#ifndef ExportedByCATPspPlantShipPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATPspPlantShipPubIDL
#define ExportedByCATPspPlantShipPubIDL __declspec(dllexport)
#else
#define ExportedByCATPspPlantShipPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATPspPlantShipPubIDL
#endif
#endif

#include "CATIABase.h"

extern ExportedByCATPspPlantShipPubIDL IID IID_CATIAPspListOfDoubles;

class ExportedByCATPspPlantShipPubIDL CATIAPspListOfDoubles : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall get_Count(CATLONG & oNbItems)=0;

    virtual HRESULT __stdcall Item(CATLONG iIndex, double & oDouble)=0;

    virtual HRESULT __stdcall Append(double iDouble)=0;

    virtual HRESULT __stdcall RemoveByIndex(CATLONG iIndex)=0;


};

CATDeclareHandler(CATIAPspListOfDoubles, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
