# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CATJoystick3DDaemon.m
#======================================================================
#
#  Apr 2003  Creation: Code generated by the CAA wizard  aur
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP  \
CATVisVR \
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
VE0BASE \
JS0MT \
CATVizBaseUUID CATViz


# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
