/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CATIACompositesMaterial_h
#define CATIACompositesMaterial_h

#ifndef ExportedByCATCompositesPubIDL
#ifdef _WINDOWS_SOURCE
#ifdef __CATCompositesPubIDL
#define ExportedByCATCompositesPubIDL __declspec(dllexport)
#else
#define ExportedByCATCompositesPubIDL __declspec(dllimport)
#endif
#else
#define ExportedByCATCompositesPubIDL
#endif
#endif

#include "CATIABase.h"

extern ExportedByCATCompositesPubIDL IID IID_CATIACompositesMaterial;

class ExportedByCATCompositesPubIDL CATIACompositesMaterial : public CATIABase
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall ExistCompositesData(short & bAnswer)=0;

    virtual HRESULT __stdcall CreateCompositesData()=0;

    virtual HRESULT __stdcall get_MaterialType(short & oMaterialType)=0;

    virtual HRESULT __stdcall put_MaterialType(short iMaterialType)=0;

    virtual HRESULT __stdcall get_UncuredThickness(double & oUncuredThickness)=0;

    virtual HRESULT __stdcall put_UncuredThickness(double iUncuredThickness)=0;

    virtual HRESULT __stdcall get_CuredThickness(double & oCuredThickness)=0;

    virtual HRESULT __stdcall put_CuredThickness(double iCuredThickness)=0;

    virtual HRESULT __stdcall get_MaxDeformation(double & oMaxDeformation)=0;

    virtual HRESULT __stdcall put_MaxDeformation(double iMaxDeformation)=0;

    virtual HRESULT __stdcall get_LimitDeformation(double & oLimitDeformation)=0;

    virtual HRESULT __stdcall put_LimitDeformation(double iLimitDeformation)=0;

    virtual HRESULT __stdcall get_FabricWidth(double & oFabricWidth)=0;

    virtual HRESULT __stdcall put_FabricWidth(double iFabricWidth)=0;

    virtual HRESULT __stdcall get_SurfacicWeigth(double & oSurfacicWeigth)=0;

    virtual HRESULT __stdcall put_SurfacicWeigth(double iSurfacicWeigth)=0;

    virtual HRESULT __stdcall get_MassCost(double & oMassCost)=0;

    virtual HRESULT __stdcall put_MassCost(double iMassCost)=0;


};

CATDeclareHandler(CATIACompositesMaterial, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
