#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
ObjectSpecsModelerUUID ObjectModelerBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=$(LINK_WITH_FOR_IID)  CATObjectSpecsModeler CATClnSpecs AC0SPCHECK AC0SPBAS		\
            JS0FM JS0STR AD0XXBAS CATClnBase AC0BOXS CD0WIN DI0PANV2 DI0STATE
#

#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT


