#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
LiteralFeaturesUUID \
KnowledgeInterfacesUUID 
#else
LINK_WITH_FOR_IID =
#endif
# COPYRIGHT DASSAULT SYSTEMES 2000
#======================================================================
# Imakefile for module CATMatUtilities.m
#======================================================================
#
#  Oct 2000  Creation: Code generated by the CAA wizard  AST
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH = JS0GROUP \
            AC0SPBAS \
            AS0STARTUP \
            AC0XXLNK \
            CATMatItfCPP \
            CATRmaItfCPP \
            CATMaterialCAA2 \
            CATMatModel \
            CATLiteralFeatures \
            CATLifSpecs \
            CATKnowledgeModeler \
            CAT3DXmlInterfaces \
            CAT3DXmlLightBaseServices \
            CAT3DXmlBaseServices \
            CATMathematics \
            CATLightXml \
            CATViz

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
