#ifndef CATIASchAppModelInit_IDL 
#define CATIASchAppModelInit_IDL 
    
/*IDLREP*/
    
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

//	COPYRIGHT DASSAULT SYSTEMES 2004
    
interface  CATIADocument;
    
    
#include "CATIABase.idl"

 /** 
  * Manage the initialization of application model.
  */

interface CATIASchAppModelInit : CATIABase
{
  /**
  * Initialize application model.
  * @param iDoc
  *   Pointer to the document concerned.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchAppModelInit
  * Dim objArg1 As Document
  *  ...
  * objThisIntf.<font color="red">AppInit</font>objArg1
  * </pre>
  *    
  */
  HRESULT AppInit ( 
    in CATIADocument iDoc );
    
};
    
// Interface name : CATIASchAppModelInit
#pragma ID CATIASchAppModelInit "DCE:3f9eedbc-715f-44a8-a6f659ee400d8586"
#pragma DUAL CATIASchAppModelInit
    
// VB object name : SchAppModelInit
#pragma ID SchAppModelInit "DCE:51bc9bdd-fbb8-4841-ae90c0e00e9e019e"
#pragma ALIAS CATIASchAppModelInit SchAppModelInit
    
#endif 
    
