#ifndef CATIASchCntrConnect_IDL 
#define CATIASchCntrConnect_IDL 
    
/*IDLREP*/
    
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

//	COPYRIGHT DASSAULT SYSTEMES 2004
    
interface  CATIASchGRRCntr;
interface  CATIASchListOfDoubles;
    
    
#include "CATIABase.idl"

 /** 
  * Manage the a schematic connector.
  */

interface CATIASchCntrConnect : CATIABase
{
 /**
  * Query whether 'this' connector can be connected to the specified
  * connector, that is, whether their positions are coincident.
  * @param iGRRCntr
  *   Pointer to the image of the 'connect to' connector. 
  * @param oBYes
  *   If TRUE, then it is OK to connect.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchCntrConnect
  * Dim objArg1 As SchGRRCntr
  * Dim bVar2 As boolean
  *  ...
  * objThisIntf.<font color="red">OKToConnect</font>objArg1,bVar2
  * </pre>
  *    
  */
  HRESULT OKToConnect ( 
    in CATIASchGRRCntr iGRRCntr, 
    inout boolean oBYes );
    
 /**
  * Get the transformation matrix needed to transform 'this' connector to be 
  * coincident and aligned with the 'connect to' connector.
  * NOTE: "alignment" in this context means that the connectors' alignment
  *       vectors are facing opposite directions.
  * @param iGRRCntr
  *   Pointer to the image of the 'connect to' connector. 
  * @param oDb6Matrix
  *   Transformation matrix.
  *   for explanation of this argument.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchCntrConnect
  * Dim objArg1 As SchGRRCntr
  * Dim objArg2 As SchListOfDoubles
  *  ...
  * objThisIntf.<font color="red">GetTransformMatrix</font>objArg1,objArg2
  * </pre>
  *    
  */
  HRESULT GetTransformMatrix ( 
    in CATIASchGRRCntr iGRRCntr, 
    inout CATIASchListOfDoubles oDb6Matrix );
    
};
    
// Interface name : CATIASchCntrConnect
#pragma ID CATIASchCntrConnect "DCE:6c7ab5c3-d2f3-4d53-9f7e708e0349a672"
#pragma DUAL CATIASchCntrConnect
    
// VB object name : SchCntrConnect
#pragma ID SchCntrConnect "DCE:fbdaacfc-a8d7-406e-b45d63e17f14db47"
#pragma ALIAS CATIASchCntrConnect SchCntrConnect
    
#endif 
    
