#ifndef CATIASchZone_IDL 
#define CATIASchZone_IDL 
    
/*IDLREP*/
    
/**
 * @CAA2Level L1
 * @CAA2Usage U3
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004       
    
#include "CATIABase.idl"

 /** 
  * Manage zone boundaries.
  */

interface CATIASchZone : CATIABase
{
  /**
  * Update the zone members based on the current zone boundaries.
  * @param iGRRToAdd
  *   The graphical representation to be added to the zone.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchZone
  *  ...
  * objThisIntf.<font color="red">UpdateBoundedElements</font>
  * </pre>
  *    
  */
  HRESULT UpdateBoundedElements ( );
    
};
    
// Interface name : CATIASchZone
#pragma ID CATIASchZone "DCE:8a4991eb-2578-436f-a0a446c2f52af8df"
#pragma DUAL CATIASchZone
    
// VB object name : SchZone
#pragma ID SchZone "DCE:e86dde75-699c-4f42-a2797c83aafdd84b"
#pragma ALIAS CATIASchZone SchZone
    
#endif 
    
