#ifndef CATIASchAppEnvironment_IDL 
#define CATIASchAppEnvironment_IDL 
    
/*IDLREP*/
    
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

//	COPYRIGHT DASSAULT SYSTEMES 2004
    
#include "CATIABase.idl"

 /** 
  * Manage the application environment in a schematic session.
  */

interface CATIASchAppEnvironment : CATIABase
{
  /**
  * Initialize environment when schematic application starts.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchAppEnvironment
  *  ...
  * objThisIntf.<font color="red">AppInitWhenApplicationStarts</font>
  * </pre>
  *    
  */
  HRESULT AppInitWhenApplicationStarts ( );
    
  /**
  * Initialize environment when schematic application ends.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchAppEnvironment
  *  ...
  * objThisIntf.<font color="red">AppCleanUpWhenApplicationEnds</font>
  * </pre>
  *    
  */
  HRESULT AppCleanUpWhenApplicationEnds ( );
    
  /**
  * Load all the necessary feat files.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchAppEnvironment
  *  ...
  * objThisIntf.<font color="red">AppLoadFeatFiles</font>
  * </pre>
  *    
  */
  HRESULT AppLoadFeatFiles ( );
    
};
    
// Interface name : CATIASchAppEnvironment
#pragma ID CATIASchAppEnvironment "DCE:2c809dea-c5f7-4a6e-93a88e11951119ec"
#pragma DUAL CATIASchAppEnvironment
    
// VB object name : SchAppEnvironment
#pragma ID SchAppEnvironment "DCE:619187bd-42d0-42c9-928b91046c820c1e"
#pragma ALIAS CATIASchAppEnvironment SchAppEnvironment
    
#endif 
    
