#ifndef CATIASchAppCntrColor_IDL 
#define CATIASchAppCntrColor_IDL 
    
/*IDLREP*/
    
/**
* @CAA2Level L1
* @CAA2Usage U3
*/

//	COPYRIGHT DASSAULT SYSTEMES 2004  
    
#include "CATIABase.idl"


 /** 
  * Manage graphical representation of schematic connector.
  */

interface CATIASchAppCntrColor : CATIABase
{
  /**
  * Specify the connector color of this connector type.
  * @param oColor
  *   Application connector color for "this" connector type.
  *   Please refer to CATColorName.h of Visualization FW.
  *    
  * @sample
  * <pre>
  * Dim objThisIntf As SchAppCntrColor
  * Dim intVar1 As Integer
  *  ...
  * objThisIntf.<font color="red">AppGetConnectorColorByType</font>intVar1
  * </pre>
  *    
  */
  HRESULT AppGetConnectorColorByType ( 
    inout long oColor );
    
};
    
// Interface name : CATIASchAppCntrColor
#pragma ID CATIASchAppCntrColor "DCE:53471a28-57db-4a18-b4964db3795c7597"
#pragma DUAL CATIASchAppCntrColor
    
// VB object name : SchAppCntrColor
#pragma ID SchAppCntrColor "DCE:dfca9a74-c782-4b60-ba53c3d327c288fa"
#pragma ALIAS CATIASchAppCntrColor SchAppCntrColor
    
#endif 
    
