#ifndef CatSchIDLGapPriority_IDL
#define CatSchIDLGapPriority_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * Schematic route gap priority.
 * <b>Role</b>: Indicates which route to gap when 2 routes intersect.
 * @param catSchIDLGapThisRoute
 *   Put a gap on this route.
 * @param catSchIDLGapInputRoute
 *   Put a gap on the input route.
 * @param catSchIDLGapNoPriority
 *   Put a gap based on priority rule.
 * @param catSchIDLGapHorizontalSeg
 *   Put a gap on the horizontal segment.
 * @param catSchIDLGapVerticalSeg
 *   Put a gap on the vertical segment.
 */
enum CatSchIDLGapPriority
{
  catSchIDLGapThisRoute,
  catSchIDLGapInputRoute,
  catSchIDLGapNoPriority,
  catSchIDLGapHorizontalSeg,
  catSchIDLGapVerticalSeg
};


#endif
