#ifndef CatSchIDLApplicationID_IDL
#define CatSchIDLApplicationID_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * DS supported schematic application ID.
 * <b>Role</b>: Schematic application ID.
 * @param catSchIDLCATPID
 *   Piping and Instrumentation Diagram.
 * @param catSchIDLCATHVACDiagram
 *   HVAC Diagram.
 * @param catSchIDLCATWaveguideDiagram
 *   Wave Guide Diagram.
 * @param catSchIDLCATTubingDiagram
 *   Tubing Diagram.
 * @param catSchIDLCATElectricalDiagram
 *   Electrical Connectivity Diagram.
 */
enum CatSchIDLApplicationID
{
   catSchIDLCATPID,
   catSchIDLCATHVACDiagram,
   catSchIDLCATWaveguideDiagram,
   catSchIDLCATTubingDiagram,
   catSchIDLCATElectricalDiagram
};


#endif
