#ifndef CatSchIDLRouteMode_IDL
#define CatSchIDLRouteMode_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */
//	COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * Schematic routing modes. 
 * <b>Role</b>: For creation and modification of a route.
 * @param catSchIDLRouteMode_Undefined
 *   Undefined.
 * @param catSchIDLRouteMode_HorizontalVertical
 *   Horizontal-vertical.
 * @param catSchIDLRouteMode_HorizontalVertical45
 *   Horizontal-vertical and 45 degree.
 * @param catSchIDLRouteMode_PointToPoint
 *   Point-to-point.
 * @param catSchIDLRouteMode_AroundObject
 *   Around object.
 */

enum CatSchIDLRouteMode
{
  catSchIDLRouteMode_Undefined,
  catSchIDLRouteMode_HorizontalVertical,
  catSchIDLRouteMode_HorizontalVertical45,
  catSchIDLRouteMode_PointToPoint,
  catSchIDLRouteMode_AroundObject
};


#endif
