#ifndef CatSchIDLCntrFlowCapability_IDL
#define CatSchIDLCntrFlowCapability_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004


/**
 * Schematic connector flow directions. 
 * <b>Role</b>: Possible flow directions of a connector.
 * @param catSchIDLCntrFlowCapability_Undefined
 *   Undefined.
 * @param catSchIDLCntrFlowCapability_InDirection
 *   In.
 * @param catSchIDLCntrFlowCapability_OutDirection
 *   Out.
 * @param catSchIDLCntrFlowCapability_InOutDirection
 *   In-Out.

 */
enum CatSchIDLCntrFlowCapability
{
  catSchIDLCntrFlowCapability_Undefined,
  catSchIDLCntrFlowCapability_InDirection,
  catSchIDLCntrFlowCapability_OutDirection,
  catSchIDLCntrFlowCapability_InOutDirection
};


#endif
