#ifndef CatSchIDLInternalFlowStatus_IDL
#define CatSchIDLInternalFlowStatus_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004


/**
 * Schematic internal flow flow status. 
 * <b>Role</b>: For inserting a component into a route.
 * @param catSchIDLInternFlowStatus_Undefined
 *   Undefined.
 * @param catSchIDLInternFlowStatus_Open
 *   Open.
 * @param catSchIDLInternFlowStatus_Close
 *   Close.
 */
enum CatSchIDLInternalFlowStatus
{
  catSchIDLInternFlowStatus_Undefined,
  catSchIDLInternFlowStatus_Open,
  catSchIDLInternFlowStatus_Close
};


#endif
