#ifndef CatSchIDLExtensionType_IDL
#define CatSchIDLExtensionType_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * Schematic extension types. 
 * <b>Role</b>: For creation and modification of schematic base objects.
 * @param catSchIDLComponent_Extension
 *   Component extension.
 * @param catSchIDLRoute_Extension
 *   Route extension.
 * @param catSchIDLCompConnector_Extension
 *   Component connector extension.
 * @param catSchIDLRouteConnector_Extension
 *   Route connector extension.
 * @param catSchIDLZone_Extension
 *   Zone extension.
 */

enum CatSchIDLExtensionType
{
  catSchIDLComponent_Extension,
  catSchIDLRoute_Extension,
  catSchIDLCompConnector_Extension, 
  catSchIDLRouteConnector_Extension, 
  catSchIDLZone_Extension
};

#endif
