#ifndef CatSchIDLRouteUnsetGapsMode_IDL
#define CatSchIDLRouteUnsetGapsMode_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004

/**
 * Flag for whether or not to unset gaps when setting a route's path.
 * <b>Role</b>: Indicate whether or not to unset gaps in effected routes.
 * @param catSchIDLUnsetGapsOff
 *   Do not remove the gaps when the route's path is changed.
 * @param catSchIDLUnsetGapsOn
 *   Remove the gaps when the route's path is changed.
 */
enum CatSchIDLRouteUnsetGapsMode
{
  catSchIDLUnsetGapsOff,
  catSchIDLUnsetGapsOn
};


#endif
