#ifndef CatSchIDLCntrFlowReality_IDL
#define CatSchIDLCntrFlowReality_IDL
/*IDLREP*/

/**
 * @CAA2Level L1
 * @CAA2Usage U1
 */

//	COPYRIGHT DASSAULT SYSTEMES 2004


/**
 * Schematic connector flow directions. 
 * <b>Role</b>: Actual flow directions of a connector.
 * @param catSchIDLCntrFlowReality_Undefined
 *   Undefined.
 * @param catSchIDLCntrFlowReality_InDirection
 *   In.
 * @param catSchIDLCntrFlowReality_OutDirection
 *   Out.
 * @param catSchIDLCntrFlowReality_InOutDirection
 *   In-Out.
 */
enum CatSchIDLCntrFlowReality
{
  catSchIDLCntrFlowReality_Undefined,
  catSchIDLCntrFlowReality_InDirection,
  catSchIDLCntrFlowReality_OutDirection,
  catSchIDLCntrFlowReality_InOutDirection
};


#endif
