# COPYRIGHT Dassault Systemes 2002
#======================================================================
# Imakefile for module CATHealingAssistantUIUUID.m
#======================================================================
#
#  Jan 2002  Creation: Code generated by the CAA wizard  mlh
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
