# COPYRIGHT Dassault Systemes 2001
#======================================================================
# Imakefile for module CATOBMInterfacesUUID.m
#======================================================================
#
#  Jul 2001  Creation: Code generated by the CAA wizard  JPI
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
