#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_FOR_IID = \
CATVisUUID
CATVizBaseUUID
#else
LINK_WITH_FOR_IID =
#endif
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
OS = COMMON

LINK_WITH=$(LINK_WITH_FOR_IID)  CATVizBase CATViz JS0MT JS0SCBAK JS0FM DI0PANV2 CATSysMainThreadMQ

LOCAL_CCFLAGS =  -DCATVIZ_SPECIFICATION
LOCAL_CFLAGS  =  -DCATVIZ_SPECIFICATION

OS = AIX

OS = HP-UX

OS = IRIX
#with irix version 6.5 or more: LOCAL_CCFLAGS = 
#without irix version 6.5: LOCAL_CCFLAGS = -DNO_WAITING_POINT
LOCAL_CCFLAGS = -DCATVIZ_SPECIFICATION

OS = SunOS
SYS_LIBPATH = -L/usr/openwin/lib
LOCAL_CCFLAGS = -mt -DCATVIZ_SPECIFICATION

OS = Windows_NT
SYS_LIBS = vfw32.lib wsock32.lib

