BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH= AD0XXBAS AC0XXLNK AC0SPBAS \
	CO0LSTPV CO0LSTST CO0RCINT \
	JS03TRA JS0CORBA JS0ERROR JS0FM JS0LIB0 JS0SCBAK JS0STR \
        CD0WIN CD0FRAME DI0PANV2 DI0STATE DI0GRAF DI0APPLI\
	VE0BASE VE0MDL NS0S1MSG NS0S3STR \
	AS0STARTUP \
	PCBModeler PCBoard PCBServices \
	YP00IMPL PartItf \
	PCBModeler PartPubIDL PCBoard \
	CD0WIN MecModItfCPP PartItf \
	PCBModeler \
        CATGeometricObjects CATMathematics\
	CATPartDesignUI PCBoardUI CATVisualization VE0MDL \
	MF0GEOM CATInfInterfaces \
	CATProductStructureInterfaces PCBExt \
        AD0XXBAS AC0XXLNK AC0SPBAS \
	CO0LSTPV CO0LSTST CO0RCINT \
	JS03TRA JS0CORBA JS0ERROR JS0FM JS0LIB0 JS0SCBAK JS0STR \
        CD0WIN CD0FRAME DI0PANV2 DI0STATE DI0GRAF DI0APPLI\
	VE0BASE VE0MDL NS0S1MSG NS0S3STR \
	AS0STARTUP \
	PCBModeler PCBoard PCBServices \
	YP00IMPL PartItf \
	PCBModeler PartPubIDL PCBoard \
	CK0FEAT CD0WIN MecModItfCPP PartItf \
	PCBModeler \
    CATGeometricObjects CATMathematics\
	CATPartDesignUI PCBoardUI CATVisualization VE0MDL CATInfInterfaces CATPCBInterfaces CATProductStructureInterfaces \
	CATAssCouMdl MechFeatCom CATGitInterfaces CATFileMenu  CATInteractiveInterfaces

#------------
OS = HP-UX
#BUILD = NO
#
OS=IRIX
#BUILD=NO
#
OS = COMMON

