# COPYRIGHT DASSAULT SYSTEMES 2004
#======================================================================
# Imakefile for module CATLieKnowledgePattern.m
#======================================================================
#
#  Jul 2004  Creation: Code generated by the CAA wizard  TVQ
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP JS0GROUP JS0FM CATAfrUUID \
JS0GROUP JS0FM DI0PANV2 CATApplicationFrame 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATApplicationFrame KnowledgeItf CATObjectSpecsModeler CATObjectModelerBase CATLiteralsEditor DI0PANV2 CATDialogEngine CATVisualization CATVizBase CATLiteralFeatures CATKnowledgeModeler

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
