# COPYRIGHT DASSAULT SYSTEMES 2005
#======================================================================
# Imakefile for module CATKweDocument.m
#======================================================================
#
#  Feb 2005  Creation: Code generated by the CAA wizard  phb
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP KnowledgeItfCPP KnowledgeInterfacesUUID  \
ON0MAIN ObjectModelerBaseUUID 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
	CATObjectSpecsModeler \
	CATObjectModelerCATIA \
	CATObjectModelerBase \
	CATLiteralFeatures \
	CATApplicationFrame \
	CATViz \
	CATVisualization \
	CATFdeInterfaces

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
