#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

LINK_WITH = JS0CORBA JS0FM JS0SCBAK JS0STR JS03TRA JS0LIB0 JS0ERROR\
            DI0PANV2 AD0XXBAS NS0S3STR NS0S1MSG CO0LSTPV OM0EDPRO\
            LicensingFR CATWorkbenchUtil
