#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE= NONE

LINK_WITH=  MF0STARTUP CP0CLIP AS0STARTUP \
            JS0LOGRP JS0GROUP JS0DSPA JS0COL JS0INF \
            NS0SI18N AC0SPBAS CK0FEAT \
	    ON0PROP ObjectModeler MF0AUTO AS0SEL  \
            AC0SPBAS YP00IMPL CATAssCouMdl YN00MAT \
	    MecModItf ProductStructureItf CATScriptReplayInteractions


LOCAL_CCFLAGS= -DSPECDEBUG


OS = AIX

OS = HP-UX

OS = IRIX

OS = SunOS

OS = Windows_NT

