#
# AEC Analysis
#

BUILT_OBJECT_TYPE=SHARED LIBRARY
INCLUDED_MODULES = AECBAnalysis


LINK_WITH= AD0XXBAS AC0XXLNK \
CO0LSTPV CO0LSTST CO0RCINT \
JS03TRA JS0CORBA JS0ERROR JS0FM JS0LIB0 JS0SCBAK JS0STR \
CD0WIN DI0PANV2 DI0STATE DI0GRAF DI0APPLI \
VE0BASE VE0MDL NS0S1MSG NS0S3STR \
AECBUtilities CATEsuUtil \
AECReviewItfCPP CK0FEAT \
CCP_DragDrop AC0CATPL CATNavigatorItf \
AECRegistration  IAODependancies V4SysALL \
CATIAEntity AECReviewItf \
CATPrsRep


#ifdef LOCAL_DEFINITION_FOR_IID
LINK_WITH_IID= AECReviewInterfacesUUID
#else
LINK_WITH_IID=
#endif

#------------
OS = COMMON
# removed 110601 kny
# CATDMUBase  ON0GRAPH VE0GRPH2 OM0EDPRO CD0FRAME MK0BASE
# removed 032502 kny
# ON0FRAME 
